import { NextResponse } from "next/server";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { taxCodeCreateSchema } from "@/lib/enterprise/accounting/finance-domain-schemas";
import { authorizeFinanceRequest, financeErrorResponse } from "@/lib/enterprise/accounting/http";
import { createTaxCode } from "@/lib/enterprise/accounting/master-service";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ organizationId: string }> };
export async function GET(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_TAX", "view"); if (!auth.ok) return auth.response; const items = await prisma.enterpriseTaxCode.findMany({ where: { organizationId }, orderBy: { code: "asc" }, include: { rates: { orderBy: { effectiveFrom: "desc" } }, rules: true } }); await writeApiLog({ request: req, statusCode: 200, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "taxes" } }); return NextResponse.json({ items, disclaimer: "Operational configurable tax summaries; jurisdiction-specific legal filing is not automated." }); }
export async function POST(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_TAX", "manage", { mutation: true, limit: 40 }); if (!auth.ok) return auth.response; const parsed = taxCodeCreateSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message }, { status: 400 }); try { const taxCode = await createTaxCode(organizationId, auth.session.userId, parsed.data); await writeAuditLog({ userId: auth.session.userId, action: "ENTERPRISE_TAX_CODE_CREATED", entity: "EnterpriseTaxCode", entityId: taxCode.id, request: req, metadata: { organizationId, code: taxCode.code, category: taxCode.category, jurisdiction: taxCode.jurisdiction } }); await writeApiLog({ request: req, statusCode: 201, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "taxes" } }); return NextResponse.json({ ok: true, taxCode }, { status: 201 }); } catch (error) { return financeErrorResponse(error, "TAX_CODE_CREATE_FAILED"); } }
