-- DTSC ERP consolidation iteration 02: projects, milestones and deliverables.

CREATE TABLE "EnterpriseProject" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "projectType" TEXT NOT NULL DEFAULT 'CLIENT',
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "businessPartyId" TEXT,
  "contractId" TEXT,
  "ownerUserId" TEXT,
  "departmentId" TEXT,
  "siteId" TEXT,
  "budgetId" TEXT,
  "currency" TEXT,
  "indicativeBudget" DECIMAL(18,2),
  "startDate" TIMESTAMP(3),
  "targetEndDate" TIMESTAMP(3),
  "completedAt" TIMESTAMP(3),
  "closedAt" TIMESTAMP(3),
  "cancelledAt" TIMESTAMP(3),
  "cancellationReason" TEXT,
  "progressPercent" INTEGER NOT NULL DEFAULT 0,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseProject_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseProjectMember" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "projectId" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'MEMBER',
  "allocationPercent" INTEGER DEFAULT 100,
  "startsAt" TIMESTAMP(3),
  "endsAt" TIMESTAMP(3),
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "createdByUserId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseProjectMember_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseProjectMilestone" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "projectId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "dueDate" TIMESTAMP(3),
  "status" TEXT NOT NULL DEFAULT 'PLANNED',
  "ownerUserId" TEXT,
  "approvalRequired" BOOLEAN NOT NULL DEFAULT false,
  "completedAt" TIMESTAMP(3),
  "approvedAt" TIMESTAMP(3),
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdByUserId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseProjectMilestone_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseProjectDeliverable" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "projectId" TEXT NOT NULL,
  "milestoneId" TEXT,
  "reference" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "ownerUserId" TEXT,
  "dueDate" TIMESTAMP(3),
  "documentId" TEXT,
  "submittedAt" TIMESTAMP(3),
  "acceptedAt" TIMESTAMP(3),
  "changesRequestedAt" TIMESTAMP(3),
  "rejectedAt" TIMESTAMP(3),
  "reviewComment" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdByUserId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseProjectDeliverable_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseProjectRisk" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "projectId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "category" TEXT,
  "probability" TEXT NOT NULL DEFAULT 'MEDIUM',
  "impact" TEXT NOT NULL DEFAULT 'MEDIUM',
  "severity" TEXT NOT NULL DEFAULT 'MEDIUM',
  "status" TEXT NOT NULL DEFAULT 'OPEN',
  "ownerUserId" TEXT,
  "mitigationPlan" TEXT,
  "dueDate" TIMESTAMP(3),
  "closedAt" TIMESTAMP(3),
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdByUserId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseProjectRisk_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseProjectIssue" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "projectId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "issueType" TEXT,
  "priority" TEXT NOT NULL DEFAULT 'NORMAL',
  "status" TEXT NOT NULL DEFAULT 'OPEN',
  "ownerUserId" TEXT,
  "dueDate" TIMESTAMP(3),
  "resolution" TEXT,
  "resolvedAt" TIMESTAMP(3),
  "closedAt" TIMESTAMP(3),
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdByUserId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseProjectIssue_pkey" PRIMARY KEY ("id")
);
