export const TAILORING_BUSINESS_SUBTYPE_CODE = "TAILORING_APPAREL" as const;

export const TAILORING_MODULE_CODES = [
  "TAILORING_OVERVIEW",
  "TAILORING_MEASUREMENTS",
  "TAILORING_STYLES_PATTERNS",
  "TAILORING_SIZE_GRADING",
  "TAILORING_MATERIAL_PROFILES",
  "TAILORING_CUTTING_PLANS",
  "TAILORING_FITTINGS",
  "TAILORING_ALTERATIONS",
  "TAILORING_GARMENT_TRACKING",
  "TAILORING_FINISHING",
] as const;

export type TailoringModuleCode = (typeof TAILORING_MODULE_CODES)[number];

export const TAILORING_OPERATING_MODES = ["MADE_TO_MEASURE", "READY_TO_WEAR", "MIXED"] as const;
export const TAILORING_MEASUREMENT_UNITS = ["CM", "IN"] as const;
export const TAILORING_MEASUREMENT_CODES = [
  "NECK",
  "CHEST",
  "WAIST",
  "HIPS",
  "SHOULDER_WIDTH",
  "BACK_LENGTH",
  "GARMENT_LENGTH",
  "SLEEVE_LENGTH",
  "BICEP",
  "WRIST",
  "RISE",
  "INSEAM",
  "OUTSEAM",
  "THIGH",
  "KNEE",
  "ANKLE",
] as const;
export const TAILORING_DEFINITION_STATUSES = ["DRAFT", "ACTIVE", "RETIRED"] as const;
export const TAILORING_MATERIAL_PROFILE_TYPES = ["FABRIC", "TRIM"] as const;
export const TAILORING_CUTTING_PLAN_STATUSES = ["DRAFT", "READY", "IN_PROGRESS", "COMPLETED", "CANCELLED"] as const;
export const TAILORING_FITTING_STATUSES = ["SCHEDULED", "COMPLETED", "CANCELLED"] as const;
export const TAILORING_FITTING_RESULTS = ["PENDING", "PASS", "ADJUSTMENTS_REQUIRED"] as const;
export const TAILORING_ALTERATION_STATUSES = ["OPEN", "IN_PROGRESS", "COMPLETED", "CANCELLED"] as const;
export const TAILORING_ALTERATION_PRIORITIES = ["LOW", "NORMAL", "HIGH", "CRITICAL"] as const;
export const TAILORING_BUNDLE_STATUSES = ["CUT", "SEWING", "FITTING", "ALTERATION", "FINISHING", "READY_FOR_DELIVERY"] as const;
export const TAILORING_FINISHING_STATUSES = ["PENDING", "IN_PROGRESS", "READY", "HOLD"] as const;
