export const EMPLOYEE_STATUSES = ["ACTIVE", "ON_LEAVE", "SUSPENDED", "TERMINATED", "ARCHIVED"] as const;
export const EMPLOYMENT_CONTRACT_STATUSES = ["DRAFT", "PENDING_APPROVAL", "ACTIVE", "SUSPENDED", "ENDED"] as const;
export const LEAVE_REQUEST_STATUSES = ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED", "CANCELLED"] as const;
export const TIMESHEET_STATUSES = ["DRAFT", "SUBMITTED", "APPROVED", "CORRECTION_REQUESTED", "REJECTED"] as const;
export const PAYROLL_RUN_STATUSES = ["DRAFT", "PREPARED", "PENDING_APPROVAL", "APPROVED", "APPROVED_AWAITING_PAYMENT", "REJECTED", "CANCELLED"] as const;
