import { NextResponse } from "next/server";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { authorizeFinanceRequest, financeErrorResponse, financeListParams } from "@/lib/enterprise/accounting/http";
import { createJournalEntryDraft, listJournalEntries } from "@/lib/enterprise/accounting/journal-service";
import { journalEntryCreateSchema } from "@/lib/enterprise/accounting/schemas";

type Params = { params: Promise<{ organizationId: string }> };
export async function GET(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_ACCOUNTING", "view"); if (!auth.ok) return auth.response; const result = await listJournalEntries(organizationId, financeListParams(req)); await writeApiLog({ request: req, statusCode: 200, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "journal-entries" } }); return NextResponse.json(result); }
export async function POST(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_ACCOUNTING", "create", { mutation: true, limit: 100 }); if (!auth.ok) return auth.response; const parsed = journalEntryCreateSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message }, { status: 400 }); try { const entry = await createJournalEntryDraft(organizationId, auth.session.userId, parsed.data); await writeAuditLog({ userId: auth.session.userId, action: "ENTERPRISE_JOURNAL_ENTRY_CREATED", entity: "EnterpriseJournalEntry", entityId: entry.id, request: req, metadata: { organizationId, number: entry.number, totalDebit: entry.totalDebit.toFixed(), currency: entry.functionalCurrencyCode } }); await writeApiLog({ request: req, statusCode: 201, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "journal-entries" } }); return NextResponse.json({ ok: true, entry }, { status: 201 }); } catch (error) { return financeErrorResponse(error, "JOURNAL_ENTRY_CREATE_FAILED"); } }
