export type HistoricalImportLocale = "fr" | "en";

const COPY = {
  fr: {
    title: "Reprise de l'historique du Shop",
    description: "Restituez les opérations antérieures à DTSC sans les mélanger avec les caisses et opérations courantes. Prévisualisez d'abord, puis faites appliquer la reprise par une autre personne autorisée.",
    sourceLabel: "Source de l'historique",
    sourcePlaceholder: "Ex. Cahier Shop — août 2026",
    periodStart: "Début de la période",
    periodEnd: "Fin de la période",
    balancesTitle: "Soldes au début de la reprise",
    balancesDescription: "Ajoutez tous les comptes de caisse et floats utilisés. Le solde de départ doit être exactement le solde actuel du compte avant application de l'historique.",
    addBalance: "Ajouter un compte",
    account: "Compte",
    openingBalance: "Solde au départ",
    expectedClosingBalance: "Solde final vérifié (facultatif)",
    operationsTitle: "Opérations du cahier",
    operationsDescription: "Saisissez chaque opération avec sa date d'origine. Les recharges Télécom exigent le coût réellement débité par l'opérateur.",
    addMobileMoney: "Ajouter dépôt/retrait",
    addTelco: "Ajouter recharge",
    operationDate: "Date et heure",
    provider: "Opérateur",
    operationType: "Opération",
    deposit: "Dépôt client",
    withdrawal: "Retrait client",
    customerPhone: "Téléphone client",
    principal: "Montant principal",
    customerFee: "Frais client",
    providerCommission: "Commission opérateur",
    feeCollection: "Encaissement des frais",
    feeNone: "Aucun",
    feeCash: "En espèces",
    feeProvider: "Chez l'opérateur",
    operatorReference: "Référence opérateur (si disponible)",
    sourceLine: "Repère dans le cahier (facultatif)",
    cashAccount: "Caisse utilisée",
    tenderAccount: "Compte d'encaissement",
    offerLabel: "Offre / forfait",
    saleAmount: "Prix payé par le client",
    operatorCost: "Coût débité par l'opérateur",
    remove: "Retirer",
    preview: "Prévisualiser la reprise",
    previewing: "Vérification…",
    saveDraft: "Enregistrer pour validation",
    saving: "Enregistrement…",
    previewReady: "Prévisualisation cohérente. Aucun solde n'a encore été modifié.",
    previewAccounts: "Effets calculés par compte",
    effect: "Effet",
    computedClosing: "Solde calculé",
    expectedClosing: "Solde vérifié",
    lineCount: "opérations",
    mobileMoney: "Mobile Money",
    telco: "Télécom",
    historyTitle: "Reprises enregistrées",
    noHistory: "Aucune reprise historique enregistrée.",
    apply: "Appliquer la reprise",
    applying: "Application…",
    independentReview: "Une autre personne autorisée doit appliquer cette reprise.",
    applied: "Reprise appliquée",
    draftSaved: "Reprise enregistrée. Faites-la contrôler et appliquer par une autre personne autorisée.",
    statusDraft: "À valider",
    statusApplying: "Comptabilisation à terminer",
    statusApplied: "Appliquée",
    refresh: "Actualiser",
    selectAccount: "Choisir un compte",
    selectProvider: "Choisir un opérateur",
    validationRequired: "Prévisualisez une version cohérente avant de l'enregistrer.",
    genericError: "La reprise n'a pas pu être terminée. Vérifiez les soldes, les comptes, les opérateurs et les périodes comptables.",
    readOnly: "Vous pouvez consulter les reprises, mais votre poste ne permet pas d'en préparer ou d'en appliquer.",
  },
  en: {
    title: "Restore Shop history",
    description: "Restore operations that predate DTSC without mixing them with current tills and live operations. Preview first, then have another authorized person apply the historical batch.",
    sourceLabel: "History source",
    sourcePlaceholder: "E.g. Shop notebook — August 2026",
    periodStart: "Period start",
    periodEnd: "Period end",
    balancesTitle: "Balances at the start of the restore",
    balancesDescription: "Add every cash and operator-float account used by the historical operations. The opening balance must exactly match the account's current balance before the restore is applied.",
    addBalance: "Add account",
    account: "Account",
    openingBalance: "Opening balance",
    expectedClosingBalance: "Verified closing balance (optional)",
    operationsTitle: "Notebook operations",
    operationsDescription: "Enter each operation with its original date. Telco top-ups require the actual cost debited by the operator.",
    addMobileMoney: "Add deposit/withdrawal",
    addTelco: "Add top-up",
    operationDate: "Date and time",
    provider: "Operator",
    operationType: "Operation",
    deposit: "Customer deposit",
    withdrawal: "Customer withdrawal",
    customerPhone: "Customer phone",
    principal: "Principal amount",
    customerFee: "Customer fee",
    providerCommission: "Operator commission",
    feeCollection: "Fee collection",
    feeNone: "None",
    feeCash: "Cash",
    feeProvider: "At operator",
    operatorReference: "Operator reference (when available)",
    sourceLine: "Notebook reference (optional)",
    cashAccount: "Cash account used",
    tenderAccount: "Collection account",
    offerLabel: "Offer / bundle",
    saleAmount: "Price paid by customer",
    operatorCost: "Cost debited by operator",
    remove: "Remove",
    preview: "Preview restore",
    previewing: "Checking…",
    saveDraft: "Save for validation",
    saving: "Saving…",
    previewReady: "Preview is consistent. No account balance has been changed yet.",
    previewAccounts: "Calculated effects by account",
    effect: "Effect",
    computedClosing: "Calculated closing",
    expectedClosing: "Verified closing",
    lineCount: "operations",
    mobileMoney: "Mobile Money",
    telco: "Telco",
    historyTitle: "Saved historical restores",
    noHistory: "No historical restore has been saved yet.",
    apply: "Apply restore",
    applying: "Applying…",
    independentReview: "Another authorized person must apply this restore.",
    applied: "Restore applied",
    draftSaved: "Restore saved. Have another authorized person review and apply it.",
    statusDraft: "Awaiting validation",
    statusApplying: "Accounting to finish",
    statusApplied: "Applied",
    refresh: "Refresh",
    selectAccount: "Choose an account",
    selectProvider: "Choose an operator",
    validationRequired: "Preview a consistent version before saving it.",
    genericError: "The restore could not be completed. Check balances, accounts, operators and accounting periods.",
    readOnly: "You can review historical restores, but your role cannot prepare or apply them.",
  },
} as const;

export function historicalImportCopy(locale: HistoricalImportLocale) {
  return COPY[locale];
}

export function historicalImportErrorMessage(code: string | undefined, locale: HistoricalImportLocale) {
  const fr: Record<string, string> = {
    RETAIL_HISTORY_BASELINE_REQUIRED: "Ajoutez un solde de départ pour chaque caisse et chaque float réellement utilisé.",
    RETAIL_HISTORY_BASELINE_CHANGED: "Un solde a changé depuis la préparation. Actualisez les comptes et recommencez la prévisualisation.",
    RETAIL_HISTORY_ACCOUNT_INVALID: "Un compte sélectionné n'est plus disponible pour cette entreprise.",
    RETAIL_HISTORY_CLOSING_BALANCE_MISMATCH: "Le solde final saisi ne correspond pas au solde calculé à partir des opérations du cahier.",
    RETAIL_HISTORY_INSUFFICIENT_BALANCE: "Le solde de départ est insuffisant pour rejouer les opérations dans leur ordre historique.",
    RETAIL_HISTORY_TELCO_MARGIN_INVALID: "Le coût opérateur d'une recharge dépasse son prix de vente.",
    RETAIL_HISTORY_LIVE_CASH_SESSION: "Une caisse concernée est encore ouverte ou en validation. Terminez cette caisse avant d'appliquer l'historique.",
    RETAIL_HISTORY_OVERLAP: "Un compte possède déjà des mouvements DTSC dans la période choisie. Réduisez la période ou utilisez un cutover sans chevauchement.",
    RETAIL_HISTORY_SELF_APPROVAL_FORBIDDEN: "La personne qui prépare la reprise ne peut pas l'appliquer elle-même.",
    RETAIL_HISTORY_IMPORT_CONFLICT: "Cette reprise a changé d'état. Actualisez avant de continuer.",
    RETAIL_HISTORY_IMPORT_NOT_FOUND: "Cette reprise historique n'est plus disponible.",
    RETAIL_HISTORY_IDEMPOTENCY_CONFLICT: "Cette demande a déjà été utilisée avec un autre contenu. Actualisez puis recommencez.",
    RETAIL_EXTERNAL_REFERENCE_DUPLICATE: "Une référence opérateur existe déjà. Vérifiez que l'opération n'a pas déjà été enregistrée.",
    FINANCE_PERIOD_NOT_FOUND: "Aucune période comptable ouverte ne couvre une date de la reprise.",
    FINANCE_PERIOD_CLOSED: "Une période comptable de la reprise est fermée ou verrouillée.",
  };
  const en: Record<string, string> = {
    RETAIL_HISTORY_BASELINE_REQUIRED: "Add an opening balance for every cash and operator-float account actually used.",
    RETAIL_HISTORY_BASELINE_CHANGED: "An account balance changed after preparation. Refresh the accounts and preview again.",
    RETAIL_HISTORY_ACCOUNT_INVALID: "A selected account is no longer available for this company.",
    RETAIL_HISTORY_CLOSING_BALANCE_MISMATCH: "The verified closing balance does not match the balance calculated from the notebook operations.",
    RETAIL_HISTORY_INSUFFICIENT_BALANCE: "The opening balance is insufficient to replay the operations in historical order.",
    RETAIL_HISTORY_TELCO_MARGIN_INVALID: "A Telco operator cost is greater than the customer sale price.",
    RETAIL_HISTORY_LIVE_CASH_SESSION: "A related till is still open or under validation. Finish that till before applying history.",
    RETAIL_HISTORY_OVERLAP: "An account already has DTSC movements in the selected period. Use a non-overlapping cutover period.",
    RETAIL_HISTORY_SELF_APPROVAL_FORBIDDEN: "The person who prepared the restore cannot apply it themselves.",
    RETAIL_HISTORY_IMPORT_CONFLICT: "This restore changed state. Refresh before continuing.",
    RETAIL_HISTORY_IMPORT_NOT_FOUND: "This historical restore is no longer available.",
    RETAIL_HISTORY_IDEMPOTENCY_CONFLICT: "This request key was already used with different content. Refresh and try again.",
    RETAIL_EXTERNAL_REFERENCE_DUPLICATE: "An operator reference already exists. Check that the operation has not already been recorded.",
    FINANCE_PERIOD_NOT_FOUND: "No open accounting period covers one of the historical dates.",
    FINANCE_PERIOD_CLOSED: "An accounting period in the restore is closed or locked.",
  };
  return (locale === "en" ? en : fr)[code || ""] || COPY[locale].genericError;
}
