export const STOCK_MOVEMENT_TYPES = [
  "PURCHASE_RECEIPT",
  "SALE_FULFILLMENT",
  "TRANSFER_OUT",
  "TRANSFER_IN",
  "ADJUSTMENT_IN",
  "ADJUSTMENT_OUT",
  "RETURN_IN",
  "RETURN_OUT",
  "COUNT_CORRECTION",
  "OPENING_BALANCE",
] as const;

export const STOCK_DIRECTIONS = ["IN", "OUT"] as const;
export const STOCK_TRANSFER_STATUSES = ["DRAFT", "PENDING_APPROVAL", "APPROVED", "COMPLETED", "REJECTED", "CANCELLED"] as const;
export const INVENTORY_COUNT_STATUSES = ["DRAFT", "IN_PROGRESS", "SUBMITTED", "APPROVED", "COMPLETED", "REJECTED", "CANCELLED"] as const;
