import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeApiLog,writeAuditLog } from "@/lib/audit";
import { getHealthLaboratoryAccess } from "@/lib/health-laboratory-access";
import { healthLabActionSchema } from "@/lib/health-laboratory-validators";
import { actionHealthLabRequest } from "@/lib/health-laboratory";
import { getRateLimitKey,rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";

type Params={params:Promise<{organizationId:string;requestId:string}>};
export async function POST(req:Request,{params}:Params){const startedAt=Date.now();if(!isSameOriginRequest(req))return NextResponse.json({error:"Forbidden"},{status:403});const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const limited=await rateLimit(getRateLimitKey(req,`health-lab-action:${session.userId}`),140,3600000);if(!limited.ok)return NextResponse.json({error:"Too many requests"},{status:429});const {organizationId,requestId}=await params,access=await getHealthLaboratoryAccess({session,organizationId,action:"write"});if(!access)return NextResponse.json({error:"Forbidden"},{status:403});const parsed=healthLabActionSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid action",message:"Les informations de l’action laboratoire sont invalides."},{status:400});const action=parsed.data.action;const allowed=action==="collect_sample"||action==="reject_sample"?access.canCollect:action==="enter_result"||action==="start_analysis"?access.canEnterResult:action==="validate_result"?access.canValidate:action==="correct_result"?access.canCorrect:action==="transmit_result"?access.canTransmit:action==="cancel"||action==="reject_request"?access.canCancel:access.canUpdate;if(!allowed)return NextResponse.json({error:"Forbidden",message:action==="validate_result"?"Vous n’avez pas la permission de valider ce résultat.":"Vous n’avez pas la permission d’effectuer cette action laboratoire."},{status:403});try{const request=await actionHealthLabRequest(organizationId,requestId,session.userId,parsed.data);await writeAuditLog({userId:session.userId,action:`HEALTH_LAB_${action.toUpperCase()}`,entity:"HealthLabRequest",entityId:requestId,request:req,metadata:{organizationId,reason:parsed.data.reason}});await writeApiLog({request:req,statusCode:200,userId:session.userId,startedAt,metadata:{organizationId,moduleCode:"LABORATORY",action}});return NextResponse.json({ok:true,request,message:action==="validate_result"?"Résultat laboratoire validé avec succès.":"Action laboratoire enregistrée avec succès."})}catch(error){const code=error instanceof Error?error.message:"ACTION_FAILED";const messages:Record<string,string>={NOT_FOUND:"Demande laboratoire introuvable.",INVALID_TRANSITION:"Cette transition laboratoire n’est pas autorisée.",REASON_REQUIRED:"Un motif est obligatoire pour cette action sensible.",INVALID_SAMPLER:"Le préleveur n’appartient pas à cette entreprise.",RESULT_REQUIRED:"Saisissez le résultat avant de poursuivre."};return NextResponse.json({error:code,message:messages[code]||"Action laboratoire impossible."},{status:code==="NOT_FOUND"?404:409})}}
