import { NextResponse } from "next/server";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { createAssetAccountingProfile } from "@/lib/enterprise/accounting/asset-accounting-service";
import { authorizeFinanceRequest, financeErrorResponse } from "@/lib/enterprise/accounting/http";
import { assetProfileSchema } from "@/lib/enterprise/accounting/treasury-schemas";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ organizationId: string; assetId: string }> };
export async function GET(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId, assetId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_ASSETS", "view"); if (!auth.ok) return auth.response; const profile = await prisma.enterpriseAssetAccountingProfile.findFirst({ where: { organizationId, assetId }, include: { schedules: { orderBy: { scheduledDate: "asc" } }, disposals: true } }); await writeApiLog({ request: req, statusCode: 200, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "asset-accounting", assetId } }); return NextResponse.json({ profile }); }
export async function POST(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId, assetId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_ASSETS", "create", { mutation: true, limit: 40 }); if (!auth.ok) return auth.response; const parsed = assetProfileSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message }, { status: 400 }); try { const result = await createAssetAccountingProfile(organizationId, assetId, auth.session.userId, parsed.data); await writeAuditLog({ userId: auth.session.userId, action: "ENTERPRISE_ASSET_CAPITALIZED", entity: "EnterpriseAssetAccountingProfile", entityId: result.profile.id, request: req, metadata: { organizationId, assetId, journalEntryId: result.posting.entry.id, originalCost: parsed.data.originalCost, residualValue: parsed.data.residualValue, currency: parsed.data.currencyCode } }); await writeApiLog({ request: req, statusCode: 201, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "asset-accounting" } }); return NextResponse.json({ ok: true, ...result }, { status: 201 }); } catch (error) { return financeErrorResponse(error, "ASSET_ACCOUNTING_PROFILE_FAILED"); } }
