import { NextResponse } from "next/server";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { prepareFinancialClose } from "@/lib/enterprise/accounting/close-service";
import { authorizeFinanceRequest, financeErrorResponse, financeListParams } from "@/lib/enterprise/accounting/http";
import { closePrepareSchema } from "@/lib/enterprise/accounting/treasury-schemas";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ organizationId: string }> };
export async function GET(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_CLOSE", "view"); if (!auth.ok) return auth.response; const { page, pageSize, status } = financeListParams(req); const where = { organizationId, ...(status ? { status } : {}) }; const [items, total] = await Promise.all([prisma.enterpriseFinancialClose.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize, include: { fiscalPeriod: { include: { fiscalYear: true } } } }), prisma.enterpriseFinancialClose.count({ where })]); await writeApiLog({ request: req, statusCode: 200, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "financial-close" } }); return NextResponse.json({ items, pagination: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) } }); }
export async function POST(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_CLOSE", "create", { mutation: true, limit: 20 }); if (!auth.ok) return auth.response; const parsed = closePrepareSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message }, { status: 400 }); try { const close = await prepareFinancialClose(organizationId, parsed.data.fiscalPeriodId, auth.session.userId); await writeAuditLog({ userId: auth.session.userId, action: "ENTERPRISE_FINANCIAL_CLOSE_PREPARED", entity: "EnterpriseFinancialClose", entityId: close.id, request: req, metadata: { organizationId, fiscalPeriodId: close.fiscalPeriodId } }); await writeApiLog({ request: req, statusCode: 201, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "financial-close" } }); return NextResponse.json({ ok: true, close }, { status: 201 }); } catch (error) { return financeErrorResponse(error, "FINANCIAL_CLOSE_PREPARE_FAILED"); } }
