export type AccountingWorkspaceLocale = "fr" | "en";

const copy = {
  fr: {
    moduleEyebrow: "Comptabilité professionnelle",
    moduleDescription: "Pilotez la mise en service, le référentiel comptable, les exercices, les journaux, les écritures et les contrôles dans un même espace.",
    setup: "Mise en service comptable",
    overview: "Vue d’ensemble financière",
    charts: "Plans comptables",
    accounts: "Comptes",
    years: "Exercices",
    periods: "Périodes",
    journals: "Journaux",
    entries: "Écritures",
    ledger: "Grand livre",
    trial: "Balance générale",
    rules: "Règles de comptabilisation",
    anomalies: "Anomalies",
    setupDescription: "Préparez la comptabilité dans l’ordre : configuration financière, plan comptable, comptes, exercice, périodes, journaux et règles de comptabilisation.",
    overviewDescription: "Cette vue synthétise les écritures comptables réelles et les contrôles qui déterminent la santé opérationnelle de la comptabilité.",
    chartsDescription: "Un plan comptable organise l’ensemble des comptes utilisés par l’entreprise. Ouvrez un plan pour consulter sa version, sa structure et les comptes qu’il contient.",
    accountsDescription: "Un compte classe une nature d’opération dans le plan comptable. Ouvrez un compte pour comprendre son rôle, son niveau, son parent et ses règles d’utilisation.",
    yearsDescription: "Un exercice délimite la période annuelle de reporting. Il contient des périodes comptables et doit être ouvert avant la comptabilisation courante.",
    periodsDescription: "Une période découpe l’exercice en fenêtres de saisie et de clôture. Une période fermée ou verrouillée protège l’historique contre de nouvelles écritures.",
    journalsDescription: "Un journal regroupe les écritures par origine opérationnelle : ventes, achats, banque, caisse, paie, ajustements ou autres flux autorisés.",
    entriesDescription: "Les écritures matérialisent les opérations en partie double. Une écriture comptabilisée reste immuable et toute correction passe par une contrepassation contrôlée.",
    ledgerDescription: "Le grand livre détaille les mouvements comptabilisés compte par compte, avec la date, le journal, la pièce, le débit et le crédit.",
    trialDescription: "La balance générale agrège les débits, crédits et soldes de chaque compte afin de contrôler la cohérence globale du grand livre.",
    rulesDescription: "Les règles de comptabilisation relient un événement métier à son compte comptable. Elles garantissent que chaque opération est classée de manière cohérente.",
    anomaliesDescription: "Les anomalies signalent les comptabilisations qui n’ont pas pu aboutir et nécessitent une correction avant nouvelle tentative.",
    open: "Ouvrir",
    openDetails: "Ouvrir les détails",
    back: "Retour à la liste",
    refresh: "Actualiser",
    search: "Rechercher",
    reset: "Réinitialiser",
    status: "Statut",
    allStatuses: "Tous les statuts",
    newItem: "Nouvel élément",
    create: "Créer",
    edit: "Modifier",
    actions: "Actions",
    moreActions: "Plus d’actions",
    cancel: "Annuler",
    save: "Enregistrer",
    processing: "Traitement…",
    close: "Fermer",
    closeToast: "Fermer la notification",
    errorTitle: "Action impossible",
    successTitle: "Action terminée",
    loadFailed: "Les données comptables n’ont pas pu être chargées. Actualisez la page. Si le problème persiste, contactez le support DTSC.",
    saveFailed: "La configuration n’a pas pu être enregistrée. Vérifiez les champs et les prérequis indiqués, puis réessayez.",
    noData: "Aucune donnée pour cette vue.",
    noDataHelp: "Utilisez les filtres ou créez le premier élément si votre rôle vous y autorise.",
    configurationRequired: "Configuration à compléter",
    configurationReady: "Prêt pour la comptabilisation",
    required: "Obligatoire",
    recommended: "Recommandé",
    done: "Terminé",
    configure: "Configurer",
    configureFinance: "Configurer les paramètres financiers",
    configurationUnavailable: "Cette étape n’a pas de raccourci direct dans ce bloc. Ouvrez la configuration Finance avec un rôle autorisé ou contactez l’administrateur de votre entreprise.",
    currentChart: "Plan comptable sélectionné",
    noChart: "Aucun plan comptable n’est encore sélectionné.",
    template: "Référentiel / version",
    applyTemplate: "Appliquer la version",
    installJournals: "Installer les journaux recommandés",
    activateChart: "Activer le plan comptable",
    createChart: "Créer le plan de l’entreprise",
    chartCode: "Code interne du plan",
    chartNameFr: "Nom du plan en français",
    chartNameEn: "Nom du plan en anglais",
    chartCodeHelp: "Identifiant court propre à votre entreprise, par exemple PRINCIPAL.",
    chartNameHelp: "Nom métier affiché aux utilisateurs dans l’application.",
    chartAccounts: "Comptes du plan",
    accountMeaning: "Signification du compte",
    accountUsage: "Utilisation comptable",
    accountHierarchy: "Hiérarchie",
    parentAccount: "Compte parent",
    directPosting: "Saisie directe",
    controlAccount: "Compte collectif / de contrôle",
    systemAccount: "Compte système",
    currency: "Devise",
    type: "Type",
    subtype: "Sous-type",
    active: "Actif",
    inactive: "Inactif",
    yes: "Oui",
    no: "Non",
    fiscalYear: "Exercice",
    startDate: "Date de début",
    endDate: "Date de fin",
    periodsCount: "Périodes rattachées",
    openFiscalYear: "Ouvrir l’exercice",
    periodStateHelp: "Le statut détermine si de nouvelles écritures peuvent être enregistrées dans cette période.",
    journalType: "Type de journal",
    sequencePrefix: "Préfixe de numérotation",
    approvalRequired: "Validation indépendante requise",
    entriesCount: "Écritures",
    date: "Date",
    number: "N° écriture",
    journal: "Journal",
    period: "Période",
    reference: "Référence",
    description: "Description",
    debit: "Débit",
    credit: "Crédit",
    balance: "Solde",
    account: "Compte",
    amount: "Montant",
    mappingKey: "Usage métier",
    sourceModule: "Origine métier",
    mappedAccount: "Compte utilisé",
    effectiveFrom: "Valide à partir du",
    effectiveTo: "Valide jusqu’au",
    ruleExplanation: "Cette règle indique au moteur comptable quel compte utiliser lorsque l’événement métier correspondant est comptabilisé.",
    range: "Période d’analyse",
    range30: "30 derniers jours",
    range90: "90 derniers jours",
    range365: "12 derniers mois",
    rangeAll: "Tout l’historique",
    postedVolume: "Volume comptabilisé",
    workflow: "Cycle des écritures",
    activityByJournal: "Activité par journal",
    interpretation: "Interprétation",
    healthyInterpretation: "La comptabilité ne présente pas d’échec de comptabilisation dans la période analysée.",
    failedInterpretation: "Des comptabilisations ont échoué. Ouvrez Anomalies pour identifier la cause et corriger le prérequis avant de relancer.",
    pendingInterpretation: "Des écritures attendent une validation. Traitez-les pour éviter de retarder les états et clôtures.",
    noOpenPeriodInterpretation: "Aucune période ouverte n’est disponible. Les nouvelles comptabilisations seront bloquées tant qu’une période adaptée n’est pas ouverte.",
    compactTableHint: "Le tableau est volontairement compact. Sur mobile, faites défiler horizontalement uniquement le tableau pour conserver toutes les colonnes comptables.",
    formHelp: "Les champs de référence sont limités aux données de votre entreprise et revalidés côté serveur.",
    select: "Sélectionner",
    code: "Code",
    nameFr: "Libellé français",
    nameEn: "Libellé anglais",
    accountType: "Nature du compte",
    accountSubtype: "Sous-type du compte",
    allowDirectPosting: "Autoriser la saisie directe",
    createAccountHelp: "Pour un plan issu d’un référentiel, un nouveau compte personnalisé doit être rattaché à un compte parent autorisé.",
    journalHelp: "Choisissez un type qui correspond au flux réel. Le journal ne remplace ni l’exercice ni la période.",
    yearHelp: "L’exercice doit couvrir une plage cohérente et ne peut pas chevaucher un autre exercice de l’entreprise.",
    periodHelp: "La période doit rester à l’intérieur de l’exercice sélectionné et ne peut pas chevaucher une autre période.",
    details: "Détails",
    structure: "Structure",
    operationalControls: "Contrôles opérationnels",
    noAccountsInChart: "Aucun compte n’est encore rattaché à ce plan.",
    previous: "Précédent",
    next: "Suivant",
  },
  en: {
    moduleEyebrow: "Professional accounting",
    moduleDescription: "Manage accounting setup, the accounting reference, fiscal years, journals, entries and controls in one workspace.",
    setup: "Accounting setup",
    overview: "Financial overview",
    charts: "Charts of accounts",
    accounts: "Accounts",
    years: "Fiscal years",
    periods: "Periods",
    journals: "Journals",
    entries: "Entries",
    ledger: "General ledger",
    trial: "Trial balance",
    rules: "Posting rules",
    anomalies: "Anomalies",
    setupDescription: "Prepare accounting in order: financial configuration, chart of accounts, accounts, fiscal year, periods, journals and posting rules.",
    overviewDescription: "This view summarizes actual accounting entries and the controls that determine operational accounting health.",
    chartsDescription: "A chart of accounts organizes every account used by the company. Open a chart to review its version, structure and accounts.",
    accountsDescription: "An account classifies a type of transaction in the chart. Open an account to understand its purpose, level, parent and usage rules.",
    yearsDescription: "A fiscal year defines the annual reporting window. It contains accounting periods and must be opened before current posting.",
    periodsDescription: "A period divides the fiscal year into posting and closing windows. A closed or locked period protects history from new entries.",
    journalsDescription: "A journal groups entries by operational origin: sales, purchases, bank, cash, payroll, adjustments or other authorized flows.",
    entriesDescription: "Entries record operations using double-entry accounting. A posted entry is immutable and any correction uses a controlled reversal.",
    ledgerDescription: "The general ledger details posted movements account by account, including date, journal, reference, debit and credit.",
    trialDescription: "The trial balance aggregates debits, credits and balances for each account to control overall ledger consistency.",
    rulesDescription: "Posting rules connect a business event to its accounting account. They keep operational events classified consistently.",
    anomaliesDescription: "Anomalies identify postings that could not complete and require a correction before retrying.",
    open: "Open",
    openDetails: "Open details",
    back: "Back to list",
    refresh: "Refresh",
    search: "Search",
    reset: "Reset",
    status: "Status",
    allStatuses: "All statuses",
    newItem: "New item",
    create: "Create",
    edit: "Edit",
    actions: "Actions",
    moreActions: "More actions",
    cancel: "Cancel",
    save: "Save",
    processing: "Processing…",
    close: "Close",
    closeToast: "Close notification",
    errorTitle: "Action unavailable",
    successTitle: "Action completed",
    loadFailed: "Accounting data could not be loaded. Refresh the page. If the problem persists, contact DTSC support.",
    saveFailed: "The configuration could not be saved. Review the fields and listed prerequisites, then try again.",
    noData: "No data for this view.",
    noDataHelp: "Use the filters or create the first item if your role allows it.",
    configurationRequired: "Configuration to complete",
    configurationReady: "Ready for posting",
    required: "Required",
    recommended: "Recommended",
    done: "Done",
    configure: "Configure",
    configureFinance: "Configure financial settings",
    configurationUnavailable: "This step has no direct shortcut in this block. Open Finance configuration with an authorized role or contact your company administrator.",
    currentChart: "Selected chart of accounts",
    noChart: "No chart of accounts is selected yet.",
    template: "Reference / version",
    applyTemplate: "Apply version",
    installJournals: "Install recommended journals",
    activateChart: "Activate chart of accounts",
    createChart: "Create company chart",
    chartCode: "Internal chart code",
    chartNameFr: "Chart name in French",
    chartNameEn: "Chart name in English",
    chartCodeHelp: "Short identifier specific to your company, for example MAIN.",
    chartNameHelp: "Business name displayed to users in the application.",
    chartAccounts: "Chart accounts",
    accountMeaning: "Account meaning",
    accountUsage: "Accounting usage",
    accountHierarchy: "Hierarchy",
    parentAccount: "Parent account",
    directPosting: "Direct posting",
    controlAccount: "Control account",
    systemAccount: "System account",
    currency: "Currency",
    type: "Type",
    subtype: "Subtype",
    active: "Active",
    inactive: "Inactive",
    yes: "Yes",
    no: "No",
    fiscalYear: "Fiscal year",
    startDate: "Start date",
    endDate: "End date",
    periodsCount: "Linked periods",
    openFiscalYear: "Open fiscal year",
    periodStateHelp: "The status determines whether new entries may be recorded in this period.",
    journalType: "Journal type",
    sequencePrefix: "Numbering prefix",
    approvalRequired: "Independent approval required",
    entriesCount: "Entries",
    date: "Date",
    number: "Entry no.",
    journal: "Journal",
    period: "Period",
    reference: "Reference",
    description: "Description",
    debit: "Debit",
    credit: "Credit",
    balance: "Balance",
    account: "Account",
    amount: "Amount",
    mappingKey: "Business use",
    sourceModule: "Business source",
    mappedAccount: "Mapped account",
    effectiveFrom: "Valid from",
    effectiveTo: "Valid to",
    ruleExplanation: "This rule tells the accounting engine which account to use when the matching business event is posted.",
    range: "Analysis period",
    range30: "Last 30 days",
    range90: "Last 90 days",
    range365: "Last 12 months",
    rangeAll: "All history",
    postedVolume: "Posted volume",
    workflow: "Entry workflow",
    activityByJournal: "Activity by journal",
    interpretation: "Interpretation",
    healthyInterpretation: "Accounting has no posting failure in the selected period.",
    failedInterpretation: "Some postings failed. Open Anomalies to identify the cause and correct the prerequisite before retrying.",
    pendingInterpretation: "Some entries are waiting for approval. Process them to avoid delaying statements and closing.",
    noOpenPeriodInterpretation: "No open period is available. New postings will be blocked until a suitable period is open.",
    compactTableHint: "The table is intentionally compact. On mobile, scroll only the table horizontally to preserve all accounting columns.",
    formHelp: "Reference fields are limited to your company data and revalidated server-side.",
    select: "Select",
    code: "Code",
    nameFr: "French label",
    nameEn: "English label",
    accountType: "Account nature",
    accountSubtype: "Account subtype",
    allowDirectPosting: "Allow direct posting",
    createAccountHelp: "For a reference-based chart, a custom account must be linked to an authorized parent account.",
    journalHelp: "Choose a type matching the actual flow. A journal does not replace the fiscal year or period.",
    yearHelp: "The fiscal year must cover a consistent range and cannot overlap another company fiscal year.",
    periodHelp: "The period must remain inside the selected fiscal year and cannot overlap another period.",
    details: "Details",
    structure: "Structure",
    operationalControls: "Operational controls",
    noAccountsInChart: "No account is linked to this chart yet.",
    previous: "Previous",
    next: "Next",
  },
} as const;

export function getAccountingWorkspaceCopy(locale: string | null | undefined) {
  return copy[locale === "en" ? "en" : "fr"];
}
