export const EDUCATION_SECTOR_CODE = "EDUCATION" as const;

export const EDUCATION_MODULE_CODES = [
  "EDUCATION_SETTINGS",
  "ACADEMIC_STRUCTURE",
  "ACADEMIC_CALENDAR",
] as const;

export type EducationModuleCode = (typeof EDUCATION_MODULE_CODES)[number];

export const EDUCATION_RESOURCE_CODES = [
  "SETTINGS",
  "CAMPUS",
  "ACADEMIC_YEAR",
  "PERIOD",
  "LEVEL",
  "DEPARTMENT",
  "PROGRAM",
  "CLASS_GROUP",
  "SUBJECT",
  "COURSE_OFFERING",
  "CALENDAR_EVENT",
] as const;

export type EducationResourceCode = (typeof EDUCATION_RESOURCE_CODES)[number];

export const EDUCATION_RESOURCE_MODULE: Record<EducationResourceCode, EducationModuleCode> = {
  SETTINGS: "EDUCATION_SETTINGS",
  CAMPUS: "ACADEMIC_STRUCTURE",
  ACADEMIC_YEAR: "ACADEMIC_STRUCTURE",
  PERIOD: "ACADEMIC_STRUCTURE",
  LEVEL: "ACADEMIC_STRUCTURE",
  DEPARTMENT: "ACADEMIC_STRUCTURE",
  PROGRAM: "ACADEMIC_STRUCTURE",
  CLASS_GROUP: "ACADEMIC_STRUCTURE",
  SUBJECT: "ACADEMIC_STRUCTURE",
  COURSE_OFFERING: "ACADEMIC_STRUCTURE",
  CALENDAR_EVENT: "ACADEMIC_CALENDAR",
};

export const EDUCATION_YEAR_STATUSES = ["DRAFT", "ACTIVE", "CLOSED", "ARCHIVED"] as const;
export const EDUCATION_PERIOD_STATUSES = ["DRAFT", "ACTIVE", "CLOSED", "ARCHIVED"] as const;
export const EDUCATION_RECORD_STATUSES = ["ACTIVE", "INACTIVE", "ARCHIVED"] as const;
