"use client";

import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import { CalendarDays, Plus, Trophy, UserPlus } from "lucide-react";
import { Field, NativeSelect, formatEnterpriseAmount, formatEnterpriseDate } from "@/components/enterprise/core-v2/erp-v2-ui";
import { ProfessionalError, ProfessionalLoading, ProfessionalSearch, ProfessionalTabs, professionalMutation, useProfessionalCollection } from "@/components/enterprise/professional/professional-erp-ui";
import { useAppLocale } from "@/components/i18n/locale-provider";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useToastMessage } from "@/components/ui/use-toast-message";
import { BusinessList, BusinessListItem } from "@/components/workspace/business-list";
import { EmptyState } from "@/components/workspace/empty-state";
import { FullscreenEntityDetail } from "@/components/workspace/fullscreen-entity-detail";
import { ModuleMetric, ModuleMetrics } from "@/components/workspace/module-metrics";
import { ModuleContent, ModuleHeader, ModuleSection, ModuleToolbar, ModuleWorkspace } from "@/components/workspace/module-workspace";
import { StatusBadge, type StatusBadgeTone } from "@/components/workspace/status-badge";
import type { EnterpriseModuleDefinition } from "@/lib/enterprise/module-registry";

type TournamentStatus = "DRAFT" | "REGISTRATION_OPEN" | "REGISTRATION_CLOSED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
type TournamentFormat = "SINGLE_ELIMINATION" | "DOUBLE_ELIMINATION" | "ROUND_ROBIN" | "LEAGUE" | "CUSTOM";
type TournamentItem = { id: string; reference: string; title: string; description: string | null; siteId: string | null; entryCatalogItemId: string | null; tournamentFormat: TournamentFormat; status: TournamentStatus; registrationOpensAt: string | null; registrationClosesAt: string | null; startsAt: string; endsAt: string; maxParticipants: number | null; revision: number; _count: { registrations: number; stationAssignments: number } };
type Party = { id: string; code: string; legalName: string; displayName: string | null };
type Candidate = { userId: string; name: string; positionTitle: string | null; email: string };
type Site = { id: string; code: string; name: string };
type CatalogItem = { id: string; code: string; name: string; currency: string | null };
type StationOption = { id: string; stationCode: string; displayName: string | null; effectiveStatus: string; asset: { id: string; code: string; name: string } };
type Registration = { id: string; businessPartyId: string; salesInvoiceId: string | null; status: string; seedNumber: number | null; resultRank: number | null; resultLabel: string | null; revision: number; participant: Party | null; paymentStatus: string; invoice: { number: string; status: string; currencyCode: string; grandTotal: string; outstandingAmount: string } | null };
type Assignment = { id: string; stationId: string; slotStartAt: string; slotEndAt: string; label: string | null; status: string; revision: number; station: StationOption; asset: { id: string; code: string; name: string; status: string; condition: string } | null };
type Detail = { tournament: TournamentItem; site: Site | null; entryItem: CatalogItem | null; registrations: Registration[]; stations: Assignment[]; transitions: Array<{ id: string; action: string; fromStatus: string | null; toStatus: string; occurredAt: string }>; canWrite: boolean; canManage: boolean; canSeeFinance: boolean };
type Filter = "ALL" | TournamentStatus;
type DialogMode = "create" | "register" | "station" | "result" | "cancel" | null;
type Lookups = { sites: Site[]; services: CatalogItem[]; parties: Party[]; approvers: Candidate[]; stations: StationOption[] };

const formats: TournamentFormat[] = ["SINGLE_ELIMINATION", "DOUBLE_ELIMINATION", "ROUND_ROBIN", "LEAGUE", "CUSTOM"];

function tone(status: TournamentStatus): StatusBadgeTone { if (status === "COMPLETED") return "success"; if (status === "CANCELLED") return "danger"; if (status === "IN_PROGRESS" || status === "REGISTRATION_OPEN") return "info"; if (status === "REGISTRATION_CLOSED") return "warning"; return "neutral"; }
async function json<T>(url: string) { const response = await fetch(url, { cache: "no-store" }); const body = await response.json().catch(() => null) as (T & { message?: string; error?: string }) | null; if (!response.ok || !body) throw new Error(body?.message || body?.error || "LOAD_FAILED"); return body; }

export function EnterpriseGamingTournamentsWorkspace({ organizationId, organizationName, definition }: { organizationId: string; organizationName: string; definition: EnterpriseModuleDefinition }) {
  const locale = useAppLocale(); const en = locale === "en";
  const [filter, setFilter] = useState<Filter>("ALL"); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [refreshKey, setRefreshKey] = useState(0);
  const [detail, setDetail] = useState<Detail | null>(null); const [dialog, setDialog] = useState<DialogMode>(null); const [lookups, setLookups] = useState<Lookups | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(""); const [resultRegistration, setResultRegistration] = useState<Registration | null>(null);
  useToastMessage(message, "error"); useToastMessage(success, "success");
  const params = useMemo(() => { const value = new URLSearchParams({ page: String(page), pageSize: "20" }); if (filter !== "ALL") value.set("status", filter); if (search.trim()) value.set("search", search.trim()); return value; }, [filter, page, search]);
  const collection = useProfessionalCollection<TournamentItem>({ endpoint: `/api/enterprise/${organizationId}/gaming/tournaments`, params, refreshKey });
  const copy = {
    title: en ? "Tournaments & Gaming events" : "Tournois & événements Gaming",
    new: en ? "New tournament" : "Nouveau tournoi",
    all: en ? "All" : "Tous",
    participants: en ? "Participants" : "Participants",
    stations: en ? "Assigned stations" : "Postes affectés",
    register: en ? "Register participant" : "Inscrire un participant",
    assign: en ? "Assign station" : "Affecter un poste",
    empty: en ? "No tournament matches this scope." : "Aucun tournoi ne correspond à ce périmètre.",
    actionDone: en ? "Action completed." : "Action effectuée.",
  };
  const statusLabel = (status: TournamentStatus) => ({ DRAFT: en ? "Draft" : "Brouillon", REGISTRATION_OPEN: en ? "Registration open" : "Inscriptions ouvertes", REGISTRATION_CLOSED: en ? "Registration closed" : "Inscriptions closes", IN_PROGRESS: en ? "In progress" : "En cours", COMPLETED: en ? "Completed" : "Terminé", CANCELLED: en ? "Cancelled" : "Annulé" }[status]);
  const formatLabel = (format: TournamentFormat) => format.replaceAll("_", " ").toLowerCase().replace(/^./, (char) => char.toUpperCase());

  async function loadLookups() {
    if (lookups) return lookups;
    const [sites, services, parties, approvers, stations] = await Promise.allSettled([
      json<{ items: Site[] }>(`/api/enterprise/${organizationId}/sites?page=1&pageSize=50&status=ACTIVE`),
      json<{ items: CatalogItem[] }>(`/api/enterprise/${organizationId}/catalog?page=1&pageSize=50&itemType=SERVICE&status=ACTIVE`),
      json<{ items: Party[] }>(`/api/enterprise/${organizationId}/business-parties?page=1&pageSize=50&role=CUSTOMER&status=ACTIVE`),
      json<{ candidates: Candidate[] }>(`/api/enterprise/${organizationId}/approval-candidates?moduleCode=FINANCE_RECEIVABLES`),
      json<{ items: StationOption[] }>(`/api/enterprise/${organizationId}/gaming/stations?page=1&pageSize=100`),
    ]);
    const state: Lookups = {
      sites: sites.status === "fulfilled" ? sites.value.items : [], services: services.status === "fulfilled" ? services.value.items : [], parties: parties.status === "fulfilled" ? parties.value.items : [], approvers: approvers.status === "fulfilled" ? approvers.value.candidates : [], stations: stations.status === "fulfilled" ? stations.value.items : [],
    };
    setLookups(state); return state;
  }
  async function openDetail(item: TournamentItem) { setBusy(true); setMessage(""); try { const body = await json<Detail>(`/api/enterprise/${organizationId}/gaming/tournaments/${item.id}`); setDetail(body); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "LOAD_FAILED"); } finally { setBusy(false); } }
  async function refreshDetail() { if (!detail) return; const body = await json<Detail>(`/api/enterprise/${organizationId}/gaming/tournaments/${detail.tournament.id}`); setDetail(body); setRefreshKey((value) => value + 1); }
  async function openDialog(mode: Exclude<DialogMode, null>) { setMessage(""); if (["create", "register", "station"].includes(mode)) await loadLookups(); setDialog(mode); }

  async function createTournament(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setMessage(""); try { const body = await professionalMutation(`/api/enterprise/${organizationId}/gaming/tournaments`, { title: String(form.get("title") || ""), description: String(form.get("description") || "") || undefined, siteId: String(form.get("siteId") || "") || undefined, entryCatalogItemId: String(form.get("entryCatalogItemId") || "") || undefined, tournamentFormat: String(form.get("tournamentFormat") || "SINGLE_ELIMINATION"), registrationOpensAt: String(form.get("registrationOpensAt") || "") || undefined, registrationClosesAt: String(form.get("registrationClosesAt") || "") || undefined, startsAt: String(form.get("startsAt") || ""), endsAt: String(form.get("endsAt") || ""), maxParticipants: String(form.get("maxParticipants") || "") || undefined, notes: String(form.get("notes") || "") || undefined, idempotencyKey: `gaming-tournament:${crypto.randomUUID()}` }); const created = (body as { tournament?: TournamentItem }).tournament; setDialog(null); setSuccess(copy.actionDone); setRefreshKey((value) => value + 1); if (created) await openDetail(created); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "CREATE_FAILED"); } finally { setBusy(false); } }
  async function command(action: "OPEN_REGISTRATION" | "CLOSE_REGISTRATION" | "START" | "COMPLETE" | "CANCEL" | "ARCHIVE", reason?: string) { if (!detail) return; setBusy(true); setMessage(""); try { await professionalMutation(`/api/enterprise/${organizationId}/gaming/tournaments/${detail.tournament.id}`, { action, revision: detail.tournament.revision, reason }, "PATCH"); if (action === "ARCHIVE") { setDetail(null); setRefreshKey((value) => value + 1); } else await refreshDetail(); setDialog(null); setSuccess(copy.actionDone); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "ACTION_FAILED"); } finally { setBusy(false); } }
  async function register(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail) return; const form = new FormData(event.currentTarget); setBusy(true); setMessage(""); try { await professionalMutation(`/api/enterprise/${organizationId}/gaming/tournaments/${detail.tournament.id}/registrations`, { businessPartyId: String(form.get("businessPartyId") || ""), seedNumber: String(form.get("seedNumber") || "") || undefined, invoiceApproverUserId: String(form.get("invoiceApproverUserId") || "") || undefined, idempotencyKey: `gaming-tournament-registration:${crypto.randomUUID()}` }); await refreshDetail(); setDialog(null); setSuccess(copy.actionDone); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "REGISTER_FAILED"); } finally { setBusy(false); } }
  async function registrationAction(registration: Registration, action: "CHECK_IN" | "WITHDRAW" | "DISQUALIFY") { if (!detail) return; setBusy(true); setMessage(""); try { await professionalMutation(`/api/enterprise/${organizationId}/gaming/tournaments/${detail.tournament.id}/registrations/${registration.id}`, { action, revision: registration.revision, reason: action === "DISQUALIFY" ? (en ? "Disqualified by tournament manager" : "Disqualification par le responsable du tournoi") : undefined }, "PATCH"); await refreshDetail(); setSuccess(copy.actionDone); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "ACTION_FAILED"); } finally { setBusy(false); } }
  async function result(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail || !resultRegistration) return; const form = new FormData(event.currentTarget); setBusy(true); setMessage(""); try { await professionalMutation(`/api/enterprise/${organizationId}/gaming/tournaments/${detail.tournament.id}/registrations/${resultRegistration.id}`, { action: "SET_RESULT", revision: resultRegistration.revision, resultRank: String(form.get("resultRank") || "") || undefined, resultLabel: String(form.get("resultLabel") || "") || undefined }, "PATCH"); await refreshDetail(); setDialog(null); setResultRegistration(null); setSuccess(copy.actionDone); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "RESULT_FAILED"); } finally { setBusy(false); } }
  async function assignStation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail) return; const form = new FormData(event.currentTarget); setBusy(true); setMessage(""); try { await professionalMutation(`/api/enterprise/${organizationId}/gaming/tournaments/${detail.tournament.id}/stations`, { stationId: String(form.get("stationId") || ""), slotStartAt: String(form.get("slotStartAt") || ""), slotEndAt: String(form.get("slotEndAt") || ""), label: String(form.get("label") || "") || undefined }); await refreshDetail(); setDialog(null); setSuccess(copy.actionDone); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "ASSIGN_FAILED"); } finally { setBusy(false); } }
  async function releaseStation(assignment: Assignment) { if (!detail) return; setBusy(true); setMessage(""); try { await professionalMutation(`/api/enterprise/${organizationId}/gaming/tournaments/${detail.tournament.id}/stations/${assignment.id}`, { action: "RELEASE", revision: assignment.revision }, "PATCH"); await refreshDetail(); setSuccess(copy.actionDone); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "RELEASE_FAILED"); } finally { setBusy(false); } }

  const availableActions = detail ? ({ DRAFT: ["OPEN_REGISTRATION", "CANCEL"], REGISTRATION_OPEN: ["CLOSE_REGISTRATION", "START", "CANCEL"], REGISTRATION_CLOSED: ["START", "CANCEL"], IN_PROGRESS: ["COMPLETE", "CANCEL"], COMPLETED: ["ARCHIVE"], CANCELLED: ["ARCHIVE"] } as const)[detail.tournament.status] : [];
  return <ModuleWorkspace>
    <ModuleHeader eyebrow="Gaming Lounge" title={copy.title} description={`${en ? definition.descriptionEn : definition.descriptionFr} · ${organizationName}`} count={collection.pagination.total} primaryAction={collection.canWrite ? <Button onClick={() => void openDialog("create")}><Plus className="h-4 w-4" />{copy.new}</Button> : undefined} />
    <ModuleMetrics><ModuleMetric label={en ? "Draft" : "Brouillons"} value={collection.metrics.DRAFT || 0} /><ModuleMetric label={en ? "Registration" : "Inscriptions"} value={(collection.metrics.REGISTRATION_OPEN || 0) + (collection.metrics.REGISTRATION_CLOSED || 0)} /><ModuleMetric label={en ? "In progress" : "En cours"} value={collection.metrics.IN_PROGRESS || 0} /><ModuleMetric label={en ? "Completed" : "Terminés"} value={collection.metrics.COMPLETED || 0} icon={<Trophy className="h-4 w-4" />} /></ModuleMetrics>
    <ModuleToolbar controls={<div className="flex flex-wrap gap-3"><ProfessionalSearch value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder={en ? "Search a tournament…" : "Rechercher un tournoi…"} /><ProfessionalTabs value={filter} onChange={(value) => { setFilter(value); setPage(1); }} items={[{ id: "ALL", label: copy.all }, { id: "DRAFT", label: statusLabel("DRAFT") }, { id: "REGISTRATION_OPEN", label: statusLabel("REGISTRATION_OPEN") }, { id: "IN_PROGRESS", label: statusLabel("IN_PROGRESS") }, { id: "COMPLETED", label: statusLabel("COMPLETED") }]} /></div>} summary={`${en ? "Page" : "Page"} ${collection.pagination.page}/${collection.pagination.pageCount}`} />
    <ModuleContent><ModuleSection title={copy.title} description={en ? "Events use canonical CRM participants, Gaming stations and common Finance invoicing." : "Les événements utilisent les participants CRM, les postes Gaming et la facturation Finance canoniques."} defaultOpen>
      {collection.error ? <ProfessionalError message={collection.error} /> : collection.loading ? <ProfessionalLoading /> : collection.items.length === 0 ? <EmptyState icon={<CalendarDays className="h-5 w-5" />} title={copy.empty} /> : <BusinessList>{collection.items.map((item) => <BusinessListItem key={item.id} title={item.title} meta={`${item.reference} · ${formatEnterpriseDate(item.startsAt, locale)} → ${formatEnterpriseDate(item.endsAt, locale)}`} description={`${formatLabel(item.tournamentFormat)} · ${item._count.registrations} ${copy.participants.toLowerCase()} · ${item._count.stationAssignments} ${copy.stations.toLowerCase()}`} status={<StatusBadge tone={tone(item.status)}>{statusLabel(item.status)}</StatusBadge>} onOpen={() => void openDetail(item)} openLabel={`${en ? "Open" : "Ouvrir"} ${item.reference}`} />)}</BusinessList>}
      <div className="mt-4 flex justify-end gap-2"><Button variant="outline" disabled={page <= 1 || collection.loading} onClick={() => setPage((value) => Math.max(1, value - 1))}>{en ? "Previous" : "Précédent"}</Button><Button variant="outline" disabled={page >= collection.pagination.pageCount || collection.loading} onClick={() => setPage((value) => value + 1)}>{en ? "Next" : "Suivant"}</Button></div>
    </ModuleSection></ModuleContent>
    <FullscreenEntityDetail open={Boolean(detail)} onClose={() => setDetail(null)} title={detail?.tournament.title || copy.title} description={detail ? `${detail.tournament.reference} · ${statusLabel(detail.tournament.status)} · ${formatLabel(detail.tournament.tournamentFormat)}` : undefined}>
      {detail ? <div className="grid gap-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs font-black uppercase text-dtsc-muted">{en ? "Starts" : "Début"}</p><p className="font-black">{formatEnterpriseDate(detail.tournament.startsAt, locale)}</p></div><div><p className="text-xs font-black uppercase text-dtsc-muted">{en ? "Ends" : "Fin"}</p><p className="font-black">{formatEnterpriseDate(detail.tournament.endsAt, locale)}</p></div><div><p className="text-xs font-black uppercase text-dtsc-muted">{copy.participants}</p><p className="text-xl font-black">{detail.registrations.length}{detail.tournament.maxParticipants ? ` / ${detail.tournament.maxParticipants}` : ""}</p></div><div><p className="text-xs font-black uppercase text-dtsc-muted">{copy.stations}</p><p className="text-xl font-black">{detail.stations.length}</p></div></div>
        {detail.canWrite && availableActions.length ? <div className="flex flex-wrap gap-2">{availableActions.map((action) => action === "CANCEL" ? <Button key={action} variant="outline" onClick={() => setDialog("cancel")}>{en ? "Cancel tournament" : "Annuler le tournoi"}</Button> : <Button key={action} variant={action === "ARCHIVE" ? "outline" : "default"} onClick={() => void command(action)}>{({ OPEN_REGISTRATION: en ? "Open registration" : "Ouvrir les inscriptions", CLOSE_REGISTRATION: en ? "Close registration" : "Clore les inscriptions", START: en ? "Start" : "Démarrer", COMPLETE: en ? "Complete" : "Terminer", ARCHIVE: en ? "Archive" : "Archiver" } as Record<string, string>)[action]}</Button>)}</div> : null}
        <section className="grid gap-3"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">{copy.participants}</h3><p className="text-sm text-dtsc-muted">{en ? "CRM customers only. Paid entry fees are invoiced in the common Finance domain." : "Uniquement les clients CRM. Les droits d’entrée payants sont facturés dans le domaine Finance commun."}</p></div>{detail.canWrite && detail.tournament.status === "REGISTRATION_OPEN" ? <Button size="sm" onClick={() => void openDialog("register")}><UserPlus className="h-4 w-4" />{copy.register}</Button> : null}</div>
          {detail.registrations.length ? <div className="grid gap-2">{detail.registrations.map((registration) => <div key={registration.id} className="rounded-2xl border border-dtsc-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black">{registration.participant?.displayName || registration.participant?.legalName || registration.businessPartyId}</p><p className="text-xs text-dtsc-muted">{registration.status.replaceAll("_", " ")} · {en ? "Payment" : "Paiement"}: {registration.paymentStatus}</p>{registration.invoice ? <p className="mt-1 text-xs font-bold">{registration.invoice.number} · {formatEnterpriseAmount(registration.invoice.grandTotal, registration.invoice.currencyCode, locale)}</p> : null}{registration.resultRank || registration.resultLabel ? <p className="mt-1 text-sm font-black">#{registration.resultRank || "—"} · {registration.resultLabel || "—"}</p> : null}</div>{detail.canWrite ? <div className="flex flex-wrap gap-2">{registration.status === "REGISTERED" ? <><Button size="sm" onClick={() => void registrationAction(registration, "CHECK_IN")}>{en ? "Check in" : "Pointer"}</Button><Button size="sm" variant="outline" onClick={() => void registrationAction(registration, "WITHDRAW")}>{en ? "Withdraw" : "Retirer"}</Button></> : null}{registration.status === "CHECKED_IN" ? <><Button size="sm" onClick={() => { setResultRegistration(registration); setDialog("result"); }}>{en ? "Set result" : "Saisir résultat"}</Button>{detail.canManage ? <Button size="sm" variant="outline" onClick={() => void registrationAction(registration, "DISQUALIFY")}>{en ? "Disqualify" : "Disqualifier"}</Button> : null}</> : null}</div> : null}</div></div>)}</div> : <EmptyState title={en ? "No participant registered." : "Aucun participant inscrit."} />}
        </section>
        <section className="grid gap-3"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">{copy.stations}</h3><p className="text-sm text-dtsc-muted">{en ? "Availability is validated against bookings, live sessions, incidents and maintenance." : "La disponibilité est validée contre les réservations, sessions actives, incidents et maintenances."}</p></div>{detail.canWrite && !["COMPLETED", "CANCELLED"].includes(detail.tournament.status) ? <Button size="sm" onClick={() => void openDialog("station")}>{copy.assign}</Button> : null}</div>
          {detail.stations.length ? <div className="grid gap-2 md:grid-cols-2">{detail.stations.map((assignment) => <div key={assignment.id} className="rounded-2xl border border-dtsc-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{assignment.station.displayName || assignment.station.stationCode}</p><p className="text-xs text-dtsc-muted">{formatEnterpriseDate(assignment.slotStartAt, locale)} → {formatEnterpriseDate(assignment.slotEndAt, locale)}</p>{assignment.asset ? <Link className="mt-2 inline-flex text-xs font-black text-dtsc-primary" href={`/enterprise-modules/ASSETS_MAINTENANCE?assetId=${encodeURIComponent(assignment.asset.id)}`}>{en ? "Open asset / maintenance" : "Ouvrir actif / maintenance"}</Link> : null}</div>{detail.canWrite && assignment.status === "ASSIGNED" ? <Button size="sm" variant="outline" onClick={() => void releaseStation(assignment)}>{en ? "Release" : "Libérer"}</Button> : null}</div></div>)}</div> : <EmptyState title={en ? "No station assigned." : "Aucun poste affecté."} />}
        </section>
      </div> : busy ? <ProfessionalLoading /> : null}
    </FullscreenEntityDetail>

    <Dialog open={dialog === "create"} onClose={() => setDialog(null)} title={copy.new} className="h-[92dvh] max-w-4xl"><form className="grid gap-5" onSubmit={createTournament}><div className="grid gap-4 sm:grid-cols-2"><Field label={en ? "Title" : "Titre"} required><Input name="title" required /></Field><Field label={en ? "Format" : "Format"} required><NativeSelect name="tournamentFormat" defaultValue="SINGLE_ELIMINATION" items={formats.map((format) => ({ id: format, label: formatLabel(format) }))} /></Field><Field label={en ? "Starts at" : "Début"} required><Input type="datetime-local" name="startsAt" required /></Field><Field label={en ? "Ends at" : "Fin"} required><Input type="datetime-local" name="endsAt" required /></Field><Field label={en ? "Registration opens" : "Ouverture inscriptions"}><Input type="datetime-local" name="registrationOpensAt" /></Field><Field label={en ? "Registration closes" : "Clôture inscriptions"}><Input type="datetime-local" name="registrationClosesAt" /></Field><Field label={en ? "Site" : "Site"}><NativeSelect name="siteId" items={[{ id: "", label: en ? "No specific site" : "Aucun site spécifique" }, ...(lookups?.sites || []).map((site) => ({ id: site.id, label: `${site.code} · ${site.name}` }))]} /></Field><Field label={en ? "Entry fee service" : "Service droit d’entrée"}><NativeSelect name="entryCatalogItemId" items={[{ id: "", label: en ? "Free registration" : "Inscription gratuite" }, ...(lookups?.services || []).map((item) => ({ id: item.id, label: `${item.code} · ${item.name}${item.currency ? ` · ${item.currency}` : ""}` }))]} /></Field><Field label={en ? "Maximum participants" : "Participants maximum"}><Input type="number" min={2} name="maxParticipants" /></Field></div><Field label={en ? "Description" : "Description"}><textarea name="description" rows={4} className="w-full rounded-xl border border-dtsc-border bg-transparent p-3" /></Field><Field label={en ? "Notes" : "Notes"}><textarea name="notes" rows={3} className="w-full rounded-xl border border-dtsc-border bg-transparent p-3" /></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setDialog(null)}>{en ? "Cancel" : "Annuler"}</Button><Button type="submit" disabled={busy}>{en ? "Create" : "Créer"}</Button></div></form></Dialog>
    <Dialog open={dialog === "register"} onClose={() => setDialog(null)} title={copy.register} className="max-w-2xl"><form className="grid gap-5" onSubmit={register}><Field label={en ? "CRM customer" : "Client CRM"} required><NativeSelect name="businessPartyId" items={(lookups?.parties || []).map((party) => ({ id: party.id, label: `${party.code} · ${party.displayName || party.legalName}` }))} /></Field><Field label={en ? "Seed number" : "Numéro de tête de série"}><Input name="seedNumber" type="number" min={1} /></Field>{detail?.tournament.entryCatalogItemId ? <Field label={en ? "Invoice approver" : "Approbateur facture"} required><NativeSelect name="invoiceApproverUserId" items={(lookups?.approvers || []).map((candidate) => ({ id: candidate.userId, label: `${candidate.name}${candidate.positionTitle ? ` · ${candidate.positionTitle}` : ""}` }))} /></Field> : null}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setDialog(null)}>{en ? "Cancel" : "Annuler"}</Button><Button type="submit" disabled={busy}>{copy.register}</Button></div></form></Dialog>
    <Dialog open={dialog === "station"} onClose={() => setDialog(null)} title={copy.assign} className="max-w-2xl"><form className="grid gap-5" onSubmit={assignStation}><Field label={en ? "Gaming station" : "Poste Gaming"} required><NativeSelect name="stationId" items={(lookups?.stations || []).filter((station) => ["AVAILABLE", "RESERVED"].includes(station.effectiveStatus)).map((station) => ({ id: station.id, label: `${station.stationCode} · ${station.displayName || station.asset.name} · ${station.effectiveStatus}` }))} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label={en ? "Slot starts" : "Début créneau"} required><Input type="datetime-local" name="slotStartAt" required /></Field><Field label={en ? "Slot ends" : "Fin créneau"} required><Input type="datetime-local" name="slotEndAt" required /></Field></div><Field label={en ? "Label" : "Libellé"}><Input name="label" /></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setDialog(null)}>{en ? "Cancel" : "Annuler"}</Button><Button type="submit" disabled={busy}>{copy.assign}</Button></div></form></Dialog>
    <Dialog open={dialog === "result"} onClose={() => { setDialog(null); setResultRegistration(null); }} title={en ? "Tournament result" : "Résultat du tournoi"} className="max-w-xl"><form className="grid gap-5" onSubmit={result}><Field label={en ? "Rank" : "Classement"}><Input type="number" min={1} name="resultRank" /></Field><Field label={en ? "Result / score" : "Résultat / score"}><Input name="resultLabel" /></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setDialog(null)}>{en ? "Cancel" : "Annuler"}</Button><Button type="submit" disabled={busy}>{en ? "Save result" : "Enregistrer le résultat"}</Button></div></form></Dialog>
    <Dialog open={dialog === "cancel"} onClose={() => setDialog(null)} title={en ? "Cancel tournament" : "Annuler le tournoi"} className="max-w-xl"><form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void command("CANCEL", String(form.get("reason") || "")); }}><Field label={en ? "Reason" : "Motif"} required><textarea name="reason" required rows={4} className="w-full rounded-xl border border-dtsc-border bg-transparent p-3" /></Field><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setDialog(null)}>{en ? "Back" : "Retour"}</Button><Button type="submit" disabled={busy}>{en ? "Confirm cancellation" : "Confirmer l’annulation"}</Button></div></form></Dialog>
  </ModuleWorkspace>;
}
