-- DTSC ERP consolidation iteration 02: assets, assignments, incidents and maintenance.

CREATE TABLE "EnterpriseAssetCategory" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "createdByUserId" TEXT NOT NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseAssetCategory_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseAsset" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "categoryId" TEXT,
  "serialNumber" TEXT,
  "siteId" TEXT,
  "storageLocationId" TEXT,
  "responsibleEmployeeId" TEXT,
  "supplierId" TEXT,
  "purchaseId" TEXT,
  "acquisitionDate" TIMESTAMP(3),
  "indicativeValue" DECIMAL(18,2),
  "currency" TEXT,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "condition" TEXT NOT NULL DEFAULT 'GOOD',
  "warrantyEndsAt" TIMESTAMP(3),
  "notes" TEXT,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseAsset_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseAssetAssignment" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "assetId" TEXT NOT NULL,
  "employeeId" TEXT,
  "departmentId" TEXT,
  "assignedAt" TIMESTAMP(3) NOT NULL,
  "expectedReturnAt" TIMESTAMP(3),
  "returnedAt" TIMESTAMP(3),
  "initialCondition" TEXT NOT NULL,
  "returnCondition" TEXT,
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "assignedByUserId" TEXT NOT NULL,
  "returnedByUserId" TEXT,
  "notes" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseAssetAssignment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseAssetMaintenance" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "assetId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "maintenanceType" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PLANNED',
  "priority" TEXT NOT NULL DEFAULT 'NORMAL',
  "responsibleUserId" TEXT,
  "supplierId" TEXT,
  "plannedAt" TIMESTAMP(3),
  "dueAt" TIMESTAMP(3),
  "startedAt" TIMESTAMP(3),
  "completedAt" TIMESTAMP(3),
  "cancelledAt" TIMESTAMP(3),
  "cancellationReason" TEXT,
  "indicativeCost" DECIMAL(18,2),
  "currency" TEXT,
  "taskId" TEXT,
  "requestId" TEXT,
  "purchaseId" TEXT,
  "expenseId" TEXT,
  "documentId" TEXT,
  "notes" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdByUserId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseAssetMaintenance_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseAssetIncident" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "assetId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "incidentType" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "severity" TEXT NOT NULL DEFAULT 'MEDIUM',
  "status" TEXT NOT NULL DEFAULT 'OPEN',
  "reportedByUserId" TEXT NOT NULL,
  "responsibleUserId" TEXT,
  "occurredAt" TIMESTAMP(3),
  "reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "resolvedAt" TIMESTAMP(3),
  "resolution" TEXT,
  "maintenanceId" TEXT,
  "taskId" TEXT,
  "documentId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseAssetIncident_pkey" PRIMARY KEY ("id")
);
