import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { canAccessPharmacySettings } from "@/lib/pharmacy-setting-access";
import { pharmacySettingsActionSchema } from "@/lib/pharmacy-settings-validators";
import { getDefaultPharmacySettingsForOrganization, previewPharmacyEntityNumber, resetPharmacySettingsToDefaults, updatePharmacyNumberingSequence } from "@/lib/pharmacy-settings";
import { getRateLimitKey, rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";

type Params = { params: Promise<{ organizationId: string }> };
export async function POST(request: Request, { params }: Params) { const startedAt = Date.now(); if (!isSameOriginRequest(request)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const limited = await rateLimit(getRateLimitKey(request, `pharmacy-settings-action:${session.userId}`), 40, 3600000); if (!limited.ok) return NextResponse.json({ error: "Too many requests" }, { status: 429 }); const { organizationId } = await params; const parsed = pharmacySettingsActionSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid action", message: "Action de paramétrage invalide." }, { status: 400 }); if (!(await canAccessPharmacySettings(session.userId, organizationId, parsed.data.action === "preview-number" ? "view" : "reset"))) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  try { if (parsed.data.action === "preview-number") { if (!parsed.data.entityType) throw new Error("SEQUENCE_REQUIRED"); return NextResponse.json({ preview: await previewPharmacyEntityNumber(organizationId, parsed.data.entityType) }); } if (parsed.data.action === "apply-defaults") await getDefaultPharmacySettingsForOrganization(organizationId, session.userId); else if (parsed.data.action === "reset-section") { if (!parsed.data.section || !parsed.data.reason) throw new Error("REASON_REQUIRED"); await resetPharmacySettingsToDefaults(organizationId, parsed.data.section, session.userId, parsed.data.reason); } else if (parsed.data.action === "update-sequence") { if (!parsed.data.entityType || !parsed.data.reason) throw new Error("REASON_REQUIRED"); await updatePharmacyNumberingSequence(organizationId, parsed.data.entityType, session.userId, { prefix: parsed.data.prefix, format: parsed.data.format, resetFrequency: parsed.data.resetFrequency, counterLength: parsed.data.counterLength, allowManualOverride: parsed.data.allowManualOverride }, parsed.data.reason); } await writeAuditLog({ userId: session.userId, action: `PHARMACY_SETTINGS_${parsed.data.action.toUpperCase().replaceAll("-", "_")}`, entity: "PharmacySetting", request, metadata: { organizationId, section: parsed.data.section, entityType: parsed.data.entityType } }); await writeApiLog({ request, statusCode: 200, userId: session.userId, startedAt }); return NextResponse.json({ ok: true }); } catch (error) { const code = error instanceof Error ? error.message : "UNKNOWN"; return NextResponse.json({ error: code, message: code === "REASON_REQUIRED" ? "Un motif est obligatoire." : "Action de paramétrage impossible." }, { status: 400 }); } }
