import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { canAccessPharmacySettings, type PharmacySettingAction } from "@/lib/pharmacy-setting-access";
import { updatePharmacyCurrencyRate } from "@/lib/pharmacy-currencies";
import { pharmacySettingsActionSchema } from "@/lib/pharmacy-settings-validators";
import { getDefaultPharmacySettingsForOrganization, previewPharmacyEntityNumber, resetPharmacySettingsToDefaults, updatePharmacyNumberingSequence } from "@/lib/pharmacy-settings";
import { getRateLimitKey, rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";

type Params = { params: Promise<{ organizationId: string }> };
export async function POST(request: Request, { params }: Params) { const startedAt = Date.now(); if (!isSameOriginRequest(request)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const limited = await rateLimit(getRateLimitKey(request, `pharmacy-settings-action:${session.userId}`), 40, 3600000); if (!limited.ok) return NextResponse.json({ error: "Too many requests" }, { status: 429 }); const { organizationId } = await params; const parsed = pharmacySettingsActionSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid action", message: "Action de paramétrage invalide." }, { status: 400 }); const requiredPermission: PharmacySettingAction = parsed.data.action === "preview-number" ? "view" : parsed.data.action === "update-currency" ? parsed.data.isBase ? "update_critical" : "update" : "reset"; if (!(await canAccessPharmacySettings(session.userId, organizationId, requiredPermission))) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  try { if (parsed.data.action === "preview-number") { if (!parsed.data.entityType) throw new Error("SEQUENCE_REQUIRED"); return NextResponse.json({ preview: await previewPharmacyEntityNumber(organizationId, parsed.data.entityType) }); } if (parsed.data.action === "apply-defaults") await getDefaultPharmacySettingsForOrganization(organizationId, session.userId); else if (parsed.data.action === "reset-section") { if (!parsed.data.section || !parsed.data.reason) throw new Error("REASON_REQUIRED"); await resetPharmacySettingsToDefaults(organizationId, parsed.data.section, session.userId, parsed.data.reason); } else if (parsed.data.action === "update-sequence") { if (!parsed.data.entityType || !parsed.data.reason) throw new Error("REASON_REQUIRED"); await updatePharmacyNumberingSequence(organizationId, parsed.data.entityType, session.userId, { prefix: parsed.data.prefix, format: parsed.data.format, resetFrequency: parsed.data.resetFrequency, counterLength: parsed.data.counterLength, allowManualOverride: parsed.data.allowManualOverride }, parsed.data.reason); } else if (parsed.data.action === "update-currency") { if (!parsed.data.currencyCode || !parsed.data.rateToBase || (parsed.data.isBase && !parsed.data.reason)) throw new Error(parsed.data.isBase ? "REASON_REQUIRED" : "CURRENCY_REQUIRED"); await updatePharmacyCurrencyRate(organizationId, session.userId, { code: parsed.data.currencyCode, label: parsed.data.currencyLabel, symbol: parsed.data.currencySymbol, rateToBase: parsed.data.rateToBase, active: parsed.data.active, isBase: parsed.data.isBase, reason: parsed.data.reason }); } await writeAuditLog({ userId: session.userId, action: `PHARMACY_SETTINGS_${parsed.data.action.toUpperCase().replaceAll("-", "_")}`, entity: "PharmacySetting", request, metadata: { organizationId, section: parsed.data.section, entityType: parsed.data.entityType, currencyCode: parsed.data.currencyCode || null } }); await writeApiLog({ request, statusCode: 200, userId: session.userId, startedAt }); return NextResponse.json({ ok: true }); } catch (error) { const code = error instanceof Error ? error.message : "UNKNOWN"; const messages: Record<string, string> = { REASON_REQUIRED: "Un motif est obligatoire.", CURRENCY_REQUIRED: "La devise et son taux sont obligatoires.", UNKNOWN_CURRENCY: "Devise inconnue.", INVALID_RATE: "Le taux de conversion doit être strictement positif.", BASE_CURRENCY_REQUIRED: "Choisissez une autre devise principale avant de modifier celle-ci." }; return NextResponse.json({ error: code, message: messages[code] || "Action de paramétrage impossible." }, { status: 400 }); } }
