export const LEAD_STATUSES = ["NEW", "CONTACTED", "QUALIFIED", "CONVERTED", "LOST", "ARCHIVED"] as const;
export const OPPORTUNITY_STATUSES = ["OPEN", "QUALIFIED", "PROPOSAL", "NEGOTIATION", "WON", "LOST", "CLOSED"] as const;
export const QUOTE_STATUSES = ["DRAFT", "SENT", "ACCEPTED", "CONVERTED", "REJECTED", "EXPIRED", "CANCELLED"] as const;
export const CONTRACT_STATUSES = ["DRAFT", "PENDING_APPROVAL", "ACTIVE", "SUSPENDED", "EXPIRED", "TERMINATED", "CANCELLED"] as const;
export const SALES_ORDER_STATUSES = ["DRAFT", "PENDING_APPROVAL", "CONFIRMED", "IN_FULFILLMENT", "PARTIALLY_FULFILLED", "FULFILLED", "CLOSED", "CANCELLED"] as const;

export const LEAD_TRANSITIONS: Record<string, readonly string[]> = {
  NEW: ["CONTACTED", "QUALIFIED", "LOST", "ARCHIVED"],
  CONTACTED: ["QUALIFIED", "LOST", "ARCHIVED"],
  QUALIFIED: ["CONVERTED", "LOST", "ARCHIVED"],
};

export const QUOTE_TRANSITIONS: Record<string, readonly string[]> = {
  DRAFT: ["SENT", "CANCELLED"],
  SENT: ["ACCEPTED", "REJECTED", "EXPIRED", "CANCELLED"],
  ACCEPTED: ["CONVERTED"],
};
