"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Archive, CircleHelp, Eye, FilePenLine, Plus, RotateCcw, UserRoundX } from "lucide-react";
import { ActionMenu, type ActionMenuItem } from "@/components/ui/action-menu";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ListControls } from "@/components/ui/list-controls";
import { useSmartList } from "@/lib/hooks/use-smart-list";
import { useToastMessage } from "@/components/ui/use-toast-message";
import {
  healthClinicalDateTime,
  healthClinicalT,
  useHealthClinicalLocale,
  type HealthClinicalKey,
  type HealthClinicalLocale,
} from "@/components/enterprise/health-clinical-i18n";

type Named={id:string;labelFr?:string;labelEn?:string;name?:string;positionCode?:string;departmentCode?:string;permissionsJson?:unknown};
type Member={id:string;role:string;user:{id:string;name:string;email:string;phone:string|null}};
type Staff=Record<string,unknown>&{id:string;organizationMemberId:string;userId:string;enterprisePositionId:string;enterpriseDepartmentId:string;healthSpecialtyId:string|null;supervisorStaffId:string|null;professionalNumber:string|null;professionalOrder:string|null;experienceLevel:string|null;competenceArea:string|null;availabilityStatus:string;usualWorkDays:string[];usualStartTime:string|null;usualEndTime:string|null;dailyCapacity:number|null;status:string;permissionsJson:string[];notes:string|null;todayAppointments:number;todayConsultations:number;createdAt:string;updatedAt:string;organizationMember:{role:string;status:string;joinedAt:string|null;user:{id:string;name:string;email:string;phone:string|null}};enterprisePosition:Named;enterpriseDepartment:Named;healthSpecialty:Named|null;supervisorStaff:{user:{name:string}}|null;events?:Array<{id:string;eventType:string;summary:string;createdAt:string;actor:{name:string}}>};
type Permissions={canCreate:boolean;canUpdate:boolean;canSuspend:boolean;canArchive:boolean;canManageAvailability:boolean;canManagePermissions:boolean;canManageSpecialties:boolean;canViewPermissions:boolean;canViewActivity:boolean};
type Form=Record<string,string|boolean|string[]>;
type T=(key:HealthClinicalKey,values?:Record<string,string|number>)=>string;

const STAFF_STATUS_KEYS={ACTIVE:"staff.status.ACTIVE",INACTIVE:"staff.status.INACTIVE",SUSPENDED:"staff.status.SUSPENDED",PENDING_VALIDATION:"staff.status.PENDING_VALIDATION",ARCHIVED:"staff.status.ARCHIVED"} as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const AVAILABILITY_KEYS={AVAILABLE:"staff.availability.AVAILABLE",UNAVAILABLE:"staff.availability.UNAVAILABLE",ON_LEAVE:"staff.availability.ON_LEAVE",ON_CALL:"staff.availability.ON_CALL",IN_CONSULTATION:"staff.availability.IN_CONSULTATION",SUSPENDED:"staff.availability.SUSPENDED"} as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const DAY_KEYS={MONDAY:"staff.day.MONDAY",TUESDAY:"staff.day.TUESDAY",WEDNESDAY:"staff.day.WEDNESDAY",THURSDAY:"staff.day.THURSDAY",FRIDAY:"staff.day.FRIDAY",SATURDAY:"staff.day.SATURDAY",SUNDAY:"staff.day.SUNDAY"} as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const PROFESSIONAL_FIELDS=[
  ["professionalNumber","staff.field.professionalNumber"],
  ["professionalOrder","staff.field.professionalOrder"],
  ["experienceLevel","staff.field.experienceLevel"],
  ["competenceArea","staff.field.competenceArea"],
  ["notes","staff.field.notes"],
] as const satisfies ReadonlyArray<readonly [string,HealthClinicalKey]>;
const emptyForm=():Form=>({organizationMemberId:"",enterprisePositionId:"",enterpriseDepartmentId:"",healthSpecialtyId:"",supervisorStaffId:"",professionalNumber:"",professionalOrder:"",experienceLevel:"",competenceArea:"",availabilityStatus:"AVAILABLE",usualWorkDays:[],usualStartTime:"",usualEndTime:"",dailyCapacity:"",status:"ACTIVE",permissions:[],notes:""});

function controlledLabel(locale:HealthClinicalLocale,value:string,map:Readonly<Record<string,HealthClinicalKey>>){const key=map[value];return key?healthClinicalT(locale,key):value}
function catalogLabel(locale:HealthClinicalLocale,item:Named|null|undefined){if(!item)return "";return locale==="en"?(item.labelEn||item.labelFr||item.name||""):(item.labelFr||item.labelEn||item.name||"")}
function permissionLabel(locale:HealthClinicalLocale,id:string){const key=`staff.permission.${id}` as HealthClinicalKey;const localized=healthClinicalT(locale,key);return localized===key?id:localized}

export function HealthStaffWorkspace({organizationId}:{organizationId:string}){
 const locale=useHealthClinicalLocale();
 const intlLocale=locale==="en"?"en-US":"fr-FR";
 const t=useCallback<T>((key,values)=>healthClinicalT(locale,key,values),[locale]);
 const [staff,setStaff]=useState<Staff[]>([]),[members,setMembers]=useState<Member[]>([]),[positions,setPositions]=useState<Named[]>([]),[departments,setDepartments]=useState<Named[]>([]),[specialties,setSpecialties]=useState<Named[]>([]),[permissionOptions,setPermissionOptions]=useState<string[]>([]),[permissions,setPermissions]=useState<Permissions>({canCreate:false,canUpdate:false,canSuspend:false,canArchive:false,canManageAvailability:false,canManagePermissions:false,canManageSpecialties:false,canViewPermissions:false,canViewActivity:false});
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[position,setPosition]=useState(""),[department,setDepartment]=useState(""),[specialty,setSpecialty]=useState(""),[status,setStatus]=useState("");
 const [formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState<Staff|null>(null),[form,setForm]=useState<Form>(()=>emptyForm()),[detail,setDetail]=useState<Staff|null>(null),[activity,setActivity]=useState<{appointments:Record<string,unknown>[];consultations:Record<string,unknown>[]}>({appointments:[],consultations:[]}),[pending,setPending]=useState<{staff:Staff;action:"suspend"|"reactivate"|"archive"}|null>(null),[reason,setReason]=useState(""),[specialtyOpen,setSpecialtyOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const response=await fetch(`/api/enterprise/${organizationId}/healthcare/staff`,{cache:"no-store"});const body=await response.json().catch(()=>null) as {staff?:Staff[];members?:Member[];positions?:Named[];departments?:Named[];specialties?:Named[];permissionOptions?:string[];permissions?:Permissions;message?:string}|null;if(response.ok&&body?.staff&&body.members&&body.positions&&body.departments&&body.specialties&&body.permissionOptions&&body.permissions){setStaff(body.staff);setMembers(body.members);setPositions(body.positions);setDepartments(body.departments);setSpecialties(body.specialties);setPermissionOptions(body.permissionOptions);setPermissions(body.permissions)}else setMessage(body?.message||t("staff.loadFailed"));setLoading(false)},[organizationId,t]);
 useEffect(()=>{void load()},[load]);
 useToastMessage(message);
 const filtered=useMemo(()=>staff.filter(item=>{const text=`${item.organizationMember.user.name} ${item.organizationMember.user.email}`.toLocaleLowerCase(intlLocale);return(!query||text.includes(query.toLocaleLowerCase(intlLocale)))&&(!position||item.enterprisePositionId===position)&&(!department||item.enterpriseDepartmentId===department)&&(!specialty||item.healthSpecialtyId===specialty)&&(!status||item.status===status)}),[staff,query,position,department,specialty,status,intlLocale]);
 const list=useSmartList({items:filtered,pageSize:12,getSearchText:useCallback((item:Staff)=>`${item.organizationMember.user.name} ${item.organizationMember.user.email}`,[])});
 const dashboard={active:staff.filter(item=>item.status==="ACTIVE").length,doctors:staff.filter(item=>["DOCTOR","SPECIALIST_DOCTOR","MEDICAL_DIRECTOR"].includes(String(item.enterprisePosition.positionCode))).length,nurses:staff.filter(item=>["NURSE","HEAD_NURSE"].includes(String(item.enterprisePosition.positionCode))).length,suspended:staff.filter(item=>item.status==="SUSPENDED").length,available:staff.filter(item=>item.status==="ACTIVE"&&item.availabilityStatus==="AVAILABLE").length,noPermissions:staff.filter(item=>!item.permissionsJson?.length).length,appointments:staff.reduce((sum,item)=>sum+item.todayAppointments,0),consultations:staff.reduce((sum,item)=>sum+item.todayConsultations,0)};
 const dashboardKeys={active:"staff.dashboard.active",doctors:"staff.dashboard.doctors",nurses:"staff.dashboard.nurses",suspended:"staff.dashboard.suspended",available:"staff.dashboard.available",noPermissions:"staff.dashboard.noPermissions",appointments:"staff.dashboard.appointments",consultations:"staff.dashboard.consultations"} as const satisfies Record<keyof typeof dashboard,HealthClinicalKey>;
 function change(key:string,value:string|boolean|string[]){setForm(current=>({...current,[key]:value}))}
 function openCreate(){setEditing(null);setForm(emptyForm());setFormOpen(true)}
 function openEdit(item:Staff){setEditing(item);setForm({...emptyForm(),...Object.fromEntries(Object.keys(emptyForm()).map(key=>[key,item[key]===null||item[key]===undefined?"":item[key]])),permissions:item.permissionsJson||[]});setFormOpen(true)}
 async function save(event:FormEvent){event.preventDefault();const response=await fetch(editing?`/api/enterprise/${organizationId}/healthcare/staff/${editing.id}`:`/api/enterprise/${organizationId}/healthcare/staff`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json().catch(()=>null) as {message?:string}|null;setMessage(response.ok?(editing?t("staff.updated"):t("staff.created")):body?.message||t("staff.saveFailed"));if(response.ok){setFormOpen(false);setDetail(null);await load()}}
 async function openDetail(item:Staff){const response=await fetch(`/api/enterprise/${organizationId}/healthcare/staff/${item.id}`,{cache:"no-store"});const body=await response.json().catch(()=>null) as {assignment?:Staff;appointments?:Record<string,unknown>[];consultations?:Record<string,unknown>[];message?:string}|null;if(response.ok&&body?.assignment){setDetail(body.assignment);setActivity({appointments:body.appointments||[],consultations:body.consultations||[]})}else setMessage(body?.message||t("staff.detailUnavailable"))}
 async function runAction(){if(!pending)return;const response=await fetch(`/api/enterprise/${organizationId}/healthcare/staff/${pending.staff.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:pending.action,reason})});const body=await response.json().catch(()=>null) as {message?:string}|null;setMessage(response.ok?t("staff.actionSaved"):body?.message||t("staff.actionFailed"));setPending(null);setReason("");setDetail(null);if(response.ok)await load()}
 async function createSpecialty(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch(`/api/enterprise/${organizationId}/healthcare/staff`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,entity:"specialty"})});setMessage(response.ok?t("staff.specialtyCreated"):t("staff.specialtyCreateFailed"));if(response.ok){setSpecialtyOpen(false);await load()}}
 return <section className="min-w-0 space-y-4 overflow-hidden overflow-x-hidden rounded-2xl border border-dtsc-border bg-dtsc-surface p-3 sm:p-5">
  <div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="text-xl font-black">{t("staff.title")}</h3><p className="mt-1 max-w-3xl text-sm text-dtsc-muted">{t("staff.description")}</p></div><div className="flex w-full min-w-0 flex-wrap gap-2 sm:w-auto">{permissions.canManageSpecialties&&<Button variant="outline" onClick={()=>setSpecialtyOpen(true)}><Plus/>{t("staff.newSpecialty")}</Button>}{permissions.canCreate&&<Button className="bg-[#002b5b] text-white" onClick={openCreate}><Plus/>{t("staff.assignMember")}</Button>}</div></div>
  <div className="grid min-w-0 gap-2 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(dashboard).map(([key,value])=><article key={key} className="min-w-0 rounded-xl border border-dtsc-border bg-dtsc-page p-3"><p className="text-xs font-black uppercase text-dtsc-muted">{t(dashboardKeys[key as keyof typeof dashboard])}</p><p className="mt-1 text-2xl font-black text-cyan-600">{value}</p></article>)}</div>
  <div className="grid min-w-0 gap-2 sm:grid-cols-2 xl:grid-cols-4"><Filter label={t("staff.filter.position")}><Choice value={position} set={setPosition} items={positions} locale={locale} all={t("staff.filter.all")}/></Filter><Filter label={t("staff.filter.department")}><Choice value={department} set={setDepartment} items={departments} locale={locale} all={t("staff.filter.all")}/></Filter><Filter label={t("staff.filter.specialty")}><Choice value={specialty} set={setSpecialty} items={specialties} locale={locale} all={t("staff.filter.all")}/></Filter><Filter label={t("staff.filter.status")}><ChoiceMap value={status} set={setStatus} keys={STAFF_STATUS_KEYS} locale={locale} all={t("staff.filter.all")}/></Filter></div>
  <ListControls query={query} onQueryChange={setQuery} page={list.page} pageCount={list.pageCount} totalCount={staff.length} filteredCount={filtered.length} onPageChange={list.setPage} placeholder={t("staff.searchPlaceholder")}/>
  {loading?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(id=><div key={id} className="h-44 animate-pulse rounded-2xl bg-dtsc-page"/>)}</div>:<div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-3">{list.paginatedItems.map(item=><StaffCard key={item.id} item={item} permissions={permissions} locale={locale} t={t} detail={openDetail} edit={openEdit} action={action=>setPending({staff:item,action})}/>)}</div>}
  {!loading&&!filtered.length&&<Empty text={t("staff.empty")}/>} 
  <Dialog open={formOpen} onClose={()=>setFormOpen(false)} title={editing?t("staff.form.editTitle"):t("staff.form.createTitle")} description={t("staff.form.description")} className="h-[94dvh] max-w-6xl"><StaffForm form={form} change={change} save={save} editing={editing} staff={staff} members={members} positions={positions} departments={departments} specialties={specialties} permissionOptions={permissionOptions} canManagePermissions={permissions.canManagePermissions} locale={locale} t={t}/></Dialog>
  <Dialog open={Boolean(detail)} onClose={()=>setDetail(null)} title={detail?detail.organizationMember.user.name:t("staff.detail.fallbackTitle")} description={t("staff.detail.description")} className="h-[94dvh] max-w-6xl">{detail&&<StaffDetail item={detail} activity={activity} permissions={permissions} locale={locale} t={t} edit={openEdit}/>}</Dialog>
  <Dialog open={Boolean(pending)} onClose={()=>setPending(null)} title={t("staff.actionDialog.title")} description={t("staff.actionDialog.description")}><Field label={t("staff.actionDialog.reason")} help={t("staff.actionDialog.reasonHelp")}><textarea required value={reason} onChange={event=>setReason(event.target.value)} className="min-h-28 min-w-0 rounded-xl border border-dtsc-border bg-dtsc-surface p-3"/></Field><Button className="mt-4 bg-[#002b5b] text-white" onClick={()=>void runAction()}>{t("staff.actionDialog.confirm")}</Button></Dialog>
  <Dialog open={specialtyOpen} onClose={()=>setSpecialtyOpen(false)} title={t("staff.specialtyDialog.title")} description={t("staff.specialtyDialog.description")}><form onSubmit={createSpecialty} className="grid min-w-0 gap-3 overflow-x-hidden"><Field label={t("staff.specialtyDialog.code")} help={t("staff.specialtyDialog.codeHelp")}><Input name="code" required/></Field><Field label={t("staff.specialtyDialog.labelFr")} help={t("staff.specialtyDialog.labelFrHelp")}><Input name="labelFr" required/></Field><Field label={t("staff.specialtyDialog.labelEn")} help={t("staff.specialtyDialog.labelEnHelp")}><Input name="labelEn"/></Field><Button className="bg-[#002b5b] text-white">{t("staff.specialtyDialog.create")}</Button></form></Dialog>
 </section>
}

function StaffCard({item,permissions,locale,t,detail,edit,action}:{item:Staff;permissions:Permissions;locale:HealthClinicalLocale;t:T;detail:(item:Staff)=>Promise<void>;edit:(item:Staff)=>void;action:(action:"suspend"|"reactivate"|"archive")=>void}){
 const actions:ActionMenuItem[]=[{key:"detail",label:t("staff.action.detail"),icon:Eye,onSelect:()=>void detail(item)}];
 if(permissions.canUpdate&&item.status!=="ARCHIVED")actions.push({key:"edit",label:t("staff.action.edit"),icon:FilePenLine,onSelect:()=>edit(item)});
 if(permissions.canSuspend&&item.status==="ACTIVE")actions.push({key:"suspend",label:t("staff.action.suspend"),icon:UserRoundX,destructive:true,onSelect:()=>action("suspend")});
 if(permissions.canUpdate&&item.status==="SUSPENDED")actions.push({key:"reactivate",label:t("staff.action.reactivate"),icon:RotateCcw,onSelect:()=>action("reactivate")});
 if(permissions.canArchive&&item.status!=="ARCHIVED")actions.push({key:"archive",label:t("staff.action.archive"),icon:Archive,destructive:true,onSelect:()=>action("archive")});
 return <article className="relative min-w-0 rounded-2xl border border-dtsc-border bg-dtsc-page p-4 pr-14"><div className="absolute right-3 top-3"><ActionMenu items={actions}/></div><div className="flex flex-wrap gap-2"><Badge text={controlledLabel(locale,item.status,STAFF_STATUS_KEYS)}/><Badge text={controlledLabel(locale,item.availabilityStatus,AVAILABILITY_KEYS)}/></div><button type="button" onClick={()=>void detail(item)} className="mt-3 block min-w-0 text-left"><h4 className="break-words font-black">{item.organizationMember.user.name}</h4><p className="mt-1 break-words text-sm text-dtsc-muted">{item.organizationMember.user.email}</p><p className="mt-2 break-words text-sm font-bold">{catalogLabel(locale,item.enterprisePosition)} · {catalogLabel(locale,item.enterpriseDepartment)}</p><p className="mt-1 break-words text-xs text-dtsc-muted">{catalogLabel(locale,item.healthSpecialty)||t("staff.card.noSpecialty")} · {t("staff.card.appointments",{count:item.todayAppointments})} · {t("staff.card.consultations",{count:item.todayConsultations})}</p></button></article>
}

function StaffForm({form,change,save,editing,staff,members,positions,departments,specialties,permissionOptions,canManagePermissions,locale,t}:{form:Form;change:(key:string,value:string|boolean|string[])=>void;save:(event:FormEvent)=>Promise<void>;editing:Staff|null;staff:Staff[];members:Member[];positions:Named[];departments:Named[];specialties:Named[];permissionOptions:string[];canManagePermissions:boolean;locale:HealthClinicalLocale;t:T}){
 const selected=Array.isArray(form.permissions)?form.permissions:[];
 return <form onSubmit={save} className="grid min-w-0 gap-4 overflow-x-hidden">
  <Section title={t("staff.section.assignment")}><Grid><Field label={t("staff.field.activeMember")} help={t("staff.help.activeMember")}><select required disabled={Boolean(editing)} value={String(form.organizationMemberId)} onChange={e=>change("organizationMemberId",e.target.value)} className={selectClass}><option value="">{t("staff.select.member")}</option>{members.filter(member=>editing?.organizationMemberId===member.id||!staff.some(item=>item.organizationMemberId===member.id)).map(member=><option key={member.id} value={member.id}>{member.user.name} · {member.user.email}</option>)}</select></Field><SelectField label={t("staff.field.position")} help={t("staff.help.position")} value={String(form.enterprisePositionId)} set={v=>change("enterprisePositionId",v)} items={positions} locale={locale} t={t}/><SelectField label={t("staff.field.department")} help={t("staff.help.department")} value={String(form.enterpriseDepartmentId)} set={v=>change("enterpriseDepartmentId",v)} items={departments} locale={locale} t={t}/><SelectField label={t("staff.field.specialty")} help={t("staff.help.specialty")} value={String(form.healthSpecialtyId)} set={v=>change("healthSpecialtyId",v)} items={specialties} locale={locale} t={t} optional/><Field label={t("staff.field.supervisor")} help={t("staff.help.supervisor")}><select value={String(form.supervisorStaffId)} onChange={e=>change("supervisorStaffId",e.target.value)} className={selectClass}><option value="">{t("staff.select.noSupervisor")}</option>{staff.filter(item=>item.id!==editing?.id&&item.status==="ACTIVE").map(item=><option key={item.id} value={item.id}>{item.organizationMember.user.name}</option>)}</select></Field></Grid></Section>
  <Section title={t("staff.section.professional")}><Grid>{PROFESSIONAL_FIELDS.map(([key,labelKey])=>{const label=t(labelKey);return <Field key={key} label={label} help={t("staff.help.professionalValue",{label})}><Input value={String(form[key])} onChange={e=>change(key,e.target.value)}/></Field>})}</Grid></Section>
  <Section title={t("staff.section.availability")}><Grid><Field label={t("staff.field.currentAvailability")} help={t("staff.help.currentAvailability")}><ChoiceMap value={String(form.availabilityStatus)} set={v=>change("availabilityStatus",v)} keys={AVAILABILITY_KEYS} locale={locale}/></Field><Field label={t("staff.field.dailyCapacity")} help={t("staff.help.dailyCapacity")}><Input type="number" value={String(form.dailyCapacity)} onChange={e=>change("dailyCapacity",e.target.value)}/></Field><Field label={t("staff.field.usualStart")} help={t("staff.help.usualStart")}><Input type="time" value={String(form.usualStartTime)} onChange={e=>change("usualStartTime",e.target.value)}/></Field><Field label={t("staff.field.usualEnd")} help={t("staff.help.usualEnd")}><Input type="time" value={String(form.usualEndTime)} onChange={e=>change("usualEndTime",e.target.value)}/></Field></Grid><div className="grid min-w-0 gap-2 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(DAY_KEYS).map(([id,key])=><label key={id} className="flex min-w-0 items-center gap-2 rounded-xl border border-dtsc-border p-3"><input type="checkbox" checked={(form.usualWorkDays as string[]).includes(id)} onChange={e=>change("usualWorkDays",e.target.checked?[...(form.usualWorkDays as string[]),id]:(form.usualWorkDays as string[]).filter(day=>day!==id))}/>{t(key)}</label>)}</div></Section>
  {canManagePermissions&&<Section title={t("staff.section.permissions")}><div className="grid min-w-0 gap-2 md:grid-cols-2">{permissionOptions.map(id=><label key={id} className="flex min-w-0 items-start gap-2 rounded-xl border border-dtsc-border p-3 text-sm"><input type="checkbox" checked={selected.includes(id)} onChange={e=>change("permissions",e.target.checked?[...selected,id]:selected.filter(permission=>permission!==id))}/><span className="break-words">{permissionLabel(locale,id)}</span></label>)}</div></Section>}
  <Button className="bg-[#002b5b] text-white">{editing?t("staff.saveChanges"):t("staff.assignProfessional")}</Button>
 </form>
}

function StaffDetail({item,activity,permissions,locale,t,edit}:{item:Staff;activity:{appointments:Record<string,unknown>[];consultations:Record<string,unknown>[]};permissions:Permissions;locale:HealthClinicalLocale;t:T;edit:(item:Staff)=>void}){
 const details:[[string,string|null|undefined],...[string,string|null|undefined][]]=[
  [t("staff.field.name"),item.organizationMember.user.name],
  [t("staff.field.email"),item.organizationMember.user.email],
  [t("staff.field.phone"),item.organizationMember.user.phone],
  [t("staff.filter.position"),catalogLabel(locale,item.enterprisePosition)],
  [t("staff.filter.department"),catalogLabel(locale,item.enterpriseDepartment)],
  [t("staff.field.specialty"),catalogLabel(locale,item.healthSpecialty)],
  [t("staff.field.supervisor"),item.supervisorStaff?.user.name],
  [t("staff.field.status"),controlledLabel(locale,item.status,STAFF_STATUS_KEYS)],
  [t("staff.field.availability"),controlledLabel(locale,item.availabilityStatus,AVAILABILITY_KEYS)],
  [t("staff.field.professionalNumber"),item.professionalNumber],
 ];
 return <div className="grid min-w-0 gap-4 overflow-x-hidden">{permissions.canUpdate&&<Button className="w-fit" onClick={()=>edit(item)}><FilePenLine/>{t("staff.action.edit")}</Button>}<Section title={t("staff.section.infoAssignment")}><Grid>{details.map(([label,value])=><Info key={label} label={label} value={value?String(value):t("common.notProvided")}/>)}</Grid></Section>{permissions.canViewPermissions&&<Section title={t("staff.section.permissions")}><div className="grid min-w-0 gap-2 md:grid-cols-2">{item.permissionsJson.map(id=><Info key={id} label={permissionLabel(locale,id)} value={t("staff.field.allowed")}/>)}</div>{!item.permissionsJson.length&&<Empty text={t("staff.noPermissions")}/>}</Section>}{permissions.canViewActivity&&<Section title={t("staff.section.activity")}><Grid><Info label={t("staff.activity.appointments")} value={String(activity.appointments.length)}/><Info label={t("staff.activity.consultations")} value={String(activity.consultations.length)}/></Grid></Section>}<Section title={t("staff.section.history")}><div className="grid min-w-0 gap-2">{item.events?.map(event=><article key={event.id} className="min-w-0 rounded-xl bg-dtsc-surface p-3"><p className="break-words font-black">{event.eventType} · {event.actor.name}</p><p className="break-words text-sm text-dtsc-muted">{event.summary} · {healthClinicalDateTime(event.createdAt,locale)}</p></article>)}</div></Section></div>
}

function Filter({label,children}:{label:string;children:ReactNode}){return <label className="grid min-w-0 gap-1 text-xs font-black uppercase text-dtsc-muted"><span>{label}</span>{children}</label>}
function Field({label,help,children}:{label:string;help:string;children:ReactNode}){return <label className="grid min-w-0 gap-1"><span className="flex min-w-0 items-center gap-1 text-xs font-black uppercase text-dtsc-muted">{label}<span title={help} aria-label={`${label} : ${help}`}><CircleHelp className="h-3.5 w-3.5"/></span></span>{children}</label>}
function Choice({value,set,items,locale,all}:{value:string;set:(value:string)=>void;items:Named[];locale:HealthClinicalLocale;all:string}){return <select value={value} onChange={e=>set(e.target.value)} className={selectClass}><option value="">{all}</option>{items.map(item=><option key={item.id} value={item.id}>{catalogLabel(locale,item)}</option>)}</select>}
function ChoiceMap({value,set,keys,locale,all}:{value:string;set:(value:string)=>void;keys:Readonly<Record<string,HealthClinicalKey>>;locale:HealthClinicalLocale;all?:string}){return <select value={value} onChange={e=>set(e.target.value)} className={selectClass}>{all!==undefined&&<option value="">{all}</option>}{Object.entries(keys).map(([id,key])=><option key={id} value={id}>{healthClinicalT(locale,key)}</option>)}</select>}
function SelectField({label,help,value,set,items,locale,t,optional}:{label:string;help:string;value:string;set:(v:string)=>void;items:Named[];locale:HealthClinicalLocale;t:T;optional?:boolean}){return <Field label={label} help={help}><select required={!optional} value={value} onChange={e=>set(e.target.value)} className={selectClass}><option value="">{optional?t("staff.select.notProvided"):t("staff.select.select")}</option>{items.map(item=><option key={item.id} value={item.id}>{catalogLabel(locale,item)}</option>)}</select></Field>}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="min-w-0 space-y-3 rounded-2xl border border-dtsc-border bg-dtsc-page p-3 sm:p-4"><h4 className="break-words font-black text-cyan-600">{title}</h4>{children}</section>}
function Grid({children}:{children:ReactNode}){return <div className="grid min-w-0 gap-3 md:grid-cols-2">{children}</div>}
function Info({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl bg-dtsc-surface p-3"><p className="break-words text-xs font-black uppercase text-dtsc-muted">{label}</p><p className="mt-1 break-words text-sm font-bold">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-dtsc-border p-4 text-center text-sm text-dtsc-muted">{text}</p>}
function Badge({text}:{text:string}){return <span className="rounded-full bg-cyan-400/15 px-2 py-1 text-xs font-black text-cyan-700">{text}</span>}
const selectClass="h-11 min-w-0 rounded-xl border border-dtsc-border bg-dtsc-surface px-3 text-sm text-dtsc-ink";
