"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Beaker, CircleHelp, Eye, FilePenLine, FlaskConical, Plus, Send, ShieldCheck, XCircle } from "lucide-react";
import { ActionMenu, type ActionMenuItem } from "@/components/ui/action-menu";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ListControls } from "@/components/ui/list-controls";
import { useSmartList } from "@/lib/hooks/use-smart-list";
import { useToastMessage } from "@/components/ui/use-toast-message";
import {
  healthClinicalDateTime,
  healthClinicalT,
  useHealthClinicalLocale,
  type HealthClinicalKey,
  type HealthClinicalLocale,
} from "@/components/enterprise/health-clinical-i18n";

type Patient = { id:string; patientNumber:string; fullName:string; phonePrimary:string; sex:string; birthDate:string|null; knownAllergies?:string|null };
type Consultation = { id:string; consultationNumber:string; patientId:string; professionalId:string; chiefComplaint:string; provisionalDiagnosis:string|null; consultationDate:string };
type Staff = { id:string; name:string; positionCode:string; role:string; department:string };
type Test = { id:string; code:string; labelFr:string; labelEn:string|null; category:string; sampleType:string; defaultUnit:string|null; referenceRange:string|null };
type Permissions = { canCreate:boolean; canUpdate:boolean; canCancel:boolean; canCollect:boolean; canEnterResult:boolean; canValidate:boolean; canCorrect:boolean; canTransmit:boolean; canManageCatalog:boolean; canViewSensitive:boolean };
type Lab = Record<string, unknown> & {
  id:string; labRequestNumber:string; patientId:string; consultationId:string|null; requestedById:string; assignedLabStaffId:string|null; mainTestId:string|null;
  testLabel:string; clinicalIndication:string|null; medicalNotes:string|null; sampleType:string|null; priority:string; status:string; confidentialityLevel:string;
  requestedAt:string; expectedSampleAt:string|null; sampledAt:string|null; sampleQuality:string|null; sampleNotes:string|null; resultText:string|null; resultUnit:string|null;
  referenceRange:string|null; resultInterpretation:string|null; abnormalityLevel:string|null; validatedAt:string|null; transmittedToDoctorAt:string|null; cancellationReason:string|null;
  patient:Patient; consultation:{consultationNumber:string;patientId:string;professional:{name:string}}|null; requestedBy:{name:string}; assignedLabStaff:{name:string}|null;
  sampledBy?:{name:string}|null; resultEnteredBy?:{name:string}|null; validatedBy?:{name:string}|null; mainTest:{id:string;labelFr:string;category:string}|null;
  items:Array<{id:string;testCatalogId:string|null;testLabel:string;status:string;resultText:string|null;unit:string|null;referenceRange:string|null;interpretation:string|null;abnormalityLevel:string|null}>;
  events?:Array<{id:string;eventType:string;summary:string;fromStatus:string|null;toStatus:string|null;createdAt:string;actor:{name:string}}>;
};
type Form = Record<string, string|string[]>;
type T = (key:HealthClinicalKey, values?:Record<string,string|number>) => string;

const STATUS_KEYS = {
  DRAFT:"lab.status.DRAFT", REQUESTED:"lab.status.REQUESTED", PENDING_SAMPLE:"lab.status.PENDING_SAMPLE", SAMPLED:"lab.status.SAMPLED", ANALYZING:"lab.status.ANALYZING",
  RESULT_ENTERED:"lab.status.RESULT_ENTERED", PENDING_VALIDATION:"lab.status.PENDING_VALIDATION", VALIDATED:"lab.status.VALIDATED", TRANSMITTED:"lab.status.TRANSMITTED",
  CANCELLED:"lab.status.CANCELLED", REJECTED:"lab.status.REJECTED",
} as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const PRIORITY_KEYS = { ROUTINE:"lab.priority.ROUTINE", PRIORITY:"lab.priority.PRIORITY", URGENT:"lab.priority.URGENT", CRITICAL:"lab.priority.CRITICAL" } as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const SAMPLE_KEYS = { BLOOD:"lab.sample.BLOOD", URINE:"lab.sample.URINE", STOOL:"lab.sample.STOOL", SWAB:"lab.sample.SWAB", BIOLOGICAL_FLUID:"lab.sample.BIOLOGICAL_FLUID", SKIN_SAMPLE:"lab.sample.SKIN_SAMPLE", OTHER:"lab.sample.OTHER" } as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const QUALITY_KEYS = { COMPLIANT:"lab.quality.COMPLIANT", INSUFFICIENT:"lab.quality.INSUFFICIENT", HEMOLYZED:"lab.quality.HEMOLYZED", CONTAMINATED:"lab.quality.CONTAMINATED", REPEAT_REQUIRED:"lab.quality.REPEAT_REQUIRED", NOT_APPLICABLE:"lab.quality.NOT_APPLICABLE" } as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const ABNORMALITY_KEYS = { NORMAL:"lab.abnormality.NORMAL", MILD_ABNORMAL:"lab.abnormality.MILD_ABNORMAL", SIGNIFICANT_ABNORMAL:"lab.abnormality.SIGNIFICANT_ABNORMAL", CRITICAL:"lab.abnormality.CRITICAL", RECHECK:"lab.abnormality.RECHECK" } as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const CATEGORY_KEYS = { HEMATOLOGY:"lab.category.HEMATOLOGY", BIOCHEMISTRY:"lab.category.BIOCHEMISTRY", SEROLOGY:"lab.category.SEROLOGY", MICROBIOLOGY:"lab.category.MICROBIOLOGY", PARASITOLOGY:"lab.category.PARASITOLOGY", IMMUNOLOGY:"lab.category.IMMUNOLOGY", HORMONOLOGY:"lab.category.HORMONOLOGY", URINE:"lab.category.URINE", STOOL:"lab.category.STOOL", OTHER:"lab.category.OTHER" } as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const CONFIDENTIALITY_KEYS = { MEDICAL_STANDARD:"lab.confidentiality.MEDICAL_STANDARD", MEDICAL_RESTRICTED:"lab.confidentiality.MEDICAL_RESTRICTED", HIGHLY_CONFIDENTIAL:"lab.confidentiality.HIGHLY_CONFIDENTIAL" } as const satisfies Readonly<Record<string,HealthClinicalKey>>;
const ACTION_TITLE_KEYS = { collect_sample:"lab.actionTitle.collect_sample", reject_sample:"lab.actionTitle.reject_sample", start_analysis:"lab.actionTitle.start_analysis", enter_result:"lab.actionTitle.enter_result", validate_result:"lab.actionTitle.validate_result", correct_result:"lab.actionTitle.correct_result", transmit_result:"lab.actionTitle.transmit_result", cancel:"lab.actionTitle.cancel", reject_request:"lab.actionTitle.reject_request" } as const satisfies Readonly<Record<string,HealthClinicalKey>>;

const empty = ():Form => ({ patientId:"", consultationId:"", requestedById:"", assignedLabStaffId:"", mainTestId:"", testIds:[], clinicalIndication:"", medicalNotes:"", sampleType:"BLOOD", priority:"ROUTINE", confidentialityLevel:"MEDICAL_STANDARD", expectedSampleAt:"", internalNotes:"", laboratoryNotes:"" });
const emptyAction = ():Form => ({ action:"collect_sample", reason:"", sampledAt:"", sampledById:"", sampleType:"BLOOD", sampleQuality:"COMPLIANT", sampleNotes:"", resultText:"", resultUnit:"", referenceRange:"", resultInterpretation:"", abnormalityLevel:"NORMAL", laboratoryNotes:"" });

function controlledLabel(locale:HealthClinicalLocale, value:string, map:Readonly<Record<string,HealthClinicalKey>>) {
  const key = map[value];
  return key ? healthClinicalT(locale,key) : value;
}
function catalogLabel(locale:HealthClinicalLocale, item:Test) {
  return locale === "en" ? (item.labelEn || item.labelFr) : (item.labelFr || item.labelEn || item.code);
}
function actionTitle(locale:HealthClinicalLocale, action:string) {
  const key = (ACTION_TITLE_KEYS as Readonly<Record<string,HealthClinicalKey>>)[action];
  return key ? healthClinicalT(locale,key) : healthClinicalT(locale,"lab.actionTitle.fallback");
}

export function HealthLaboratoryWorkspace({organizationId}:{organizationId:string}) {
  const locale = useHealthClinicalLocale();
  const intlLocale = locale === "en" ? "en-US" : "fr-FR";
  const t = useCallback<T>((key,values)=>healthClinicalT(locale,key,values),[locale]);
  const [requests,setRequests] = useState<Lab[]>([]), [patients,setPatients] = useState<Patient[]>([]), [consultations,setConsultations] = useState<Consultation[]>([]), [staff,setStaff] = useState<Staff[]>([]), [catalog,setCatalog] = useState<Test[]>([]);
  const [permissions,setPermissions] = useState<Permissions>({canCreate:false,canUpdate:false,canCancel:false,canCollect:false,canEnterResult:false,canValidate:false,canCorrect:false,canTransmit:false,canManageCatalog:false,canViewSensitive:false});
  const [loading,setLoading] = useState(true), [message,setMessage] = useState(""), [query,setQuery] = useState(""), [status,setStatus] = useState(""), [priority,setPriority] = useState(""), [test,setTest] = useState(""), [requester,setRequester] = useState(""), [dateFrom,setDateFrom] = useState("");
  const [formOpen,setFormOpen] = useState(false), [editing,setEditing] = useState<Lab|null>(null), [form,setForm] = useState<Form>(()=>empty()), [detail,setDetail] = useState<Lab|null>(null), [actionTarget,setActionTarget] = useState<Lab|null>(null), [actionForm,setActionForm] = useState<Form>(()=>emptyAction()), [catalogOpen,setCatalogOpen] = useState(false);

  const load = useCallback(async()=>{
    setLoading(true);
    const response = await fetch(`/api/enterprise/${organizationId}/healthcare/laboratory`,{cache:"no-store"});
    const body = await response.json().catch(()=>null) as {requests?:Lab[];patients?:Patient[];consultations?:Consultation[];staff?:Staff[];catalog?:Test[];permissions?:Permissions;message?:string}|null;
    if(response.ok && body?.requests && body.patients && body.consultations && body.staff && body.catalog && body.permissions) {
      setRequests(body.requests); setPatients(body.patients); setConsultations(body.consultations); setStaff(body.staff); setCatalog(body.catalog); setPermissions(body.permissions);
    } else setMessage(body?.message || t("lab.loadFailed"));
    setLoading(false);
  },[organizationId,t]);
  useEffect(()=>{void load()},[load]);
  useToastMessage(message);

  const filtered = useMemo(()=>requests.filter(item=>{
    const text = `${item.labRequestNumber} ${item.patient.fullName} ${item.patient.patientNumber} ${item.testLabel}`.toLocaleLowerCase(intlLocale);
    return (!query || text.includes(query.toLocaleLowerCase(intlLocale))) && (!status || item.status===status) && (!priority || item.priority===priority) && (!test || item.items.some(row=>row.testCatalogId===test)) && (!requester || item.requestedById===requester) && (!dateFrom || item.requestedAt.slice(0,10)>=dateFrom);
  }),[requests,query,status,priority,test,requester,dateFrom,intlLocale]);
  const list = useSmartList({items:filtered,pageSize:12,getSearchText:useCallback((item:Lab)=>`${item.labRequestNumber} ${item.patient.fullName} ${item.patient.patientNumber} ${item.testLabel}`,[])});
  const today = new Date().toISOString().slice(0,10);
  const dashboard = {
    today:requests.filter(item=>item.requestedAt.slice(0,10)===today).length,
    pending:requests.filter(item=>["REQUESTED","PENDING_SAMPLE"].includes(item.status)).length,
    toSample:requests.filter(item=>item.status==="PENDING_SAMPLE"||item.status==="REQUESTED").length,
    sampled:requests.filter(item=>item.status==="SAMPLED").length,
    analysis:requests.filter(item=>item.status==="ANALYZING").length,
    toValidate:requests.filter(item=>item.status==="PENDING_VALIDATION").length,
    validated:requests.filter(item=>item.status==="VALIDATED").length,
    urgent:requests.filter(item=>["URGENT","CRITICAL"].includes(item.priority)&&!["VALIDATED","TRANSMITTED","CANCELLED"].includes(item.status)).length,
    critical:requests.filter(item=>item.abnormalityLevel==="CRITICAL").length,
  };
  const dashboardKeys = {today:"lab.dashboard.today",pending:"lab.dashboard.pending",toSample:"lab.dashboard.toSample",sampled:"lab.dashboard.sampled",analysis:"lab.dashboard.analysis",toValidate:"lab.dashboard.toValidate",validated:"lab.dashboard.validated",urgent:"lab.dashboard.urgent",critical:"lab.dashboard.critical"} as const satisfies Record<keyof typeof dashboard,HealthClinicalKey>;

  function change(key:string,value:string|string[]){setForm(current=>({...current,[key]:value}))}
  function openCreate(){setEditing(null);setForm(empty());setFormOpen(true)}
  function openEdit(item:Lab){setEditing(item);setForm({...empty(),...Object.fromEntries(Object.keys(empty()).map(key=>[key,key==="testIds"?item.items.map(row=>row.testCatalogId).filter(Boolean) as string[]:item[key]===null||item[key]===undefined?"":String(item[key])]))});setFormOpen(true)}
  async function save(event:FormEvent){event.preventDefault();const response=await fetch(editing?`/api/enterprise/${organizationId}/healthcare/laboratory/${editing.id}`:`/api/enterprise/${organizationId}/healthcare/laboratory`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json().catch(()=>null) as {message?:string}|null;setMessage(response.ok?(editing?t("lab.updated"):t("lab.created")):body?.message||t("lab.saveFailed"));if(response.ok){setFormOpen(false);setDetail(null);await load()}}
  async function openDetail(item:Lab){const response=await fetch(`/api/enterprise/${organizationId}/healthcare/laboratory/${item.id}`,{cache:"no-store"});const body=await response.json().catch(()=>null) as {request?:Lab;message?:string}|null;const savedRequest=body?.request;if(response.ok&&savedRequest)setDetail(savedRequest);else setMessage(body?.message||t("lab.detailUnavailable"))}
  function openAction(item:Lab,action:string){setActionTarget(item);setActionForm({...emptyAction(),action,sampleType:item.sampleType||"BLOOD",resultText:item.resultText||"",resultUnit:item.resultUnit||"",referenceRange:item.referenceRange||"",resultInterpretation:item.resultInterpretation||"",abnormalityLevel:item.abnormalityLevel||"NORMAL",laboratoryNotes:String(item.laboratoryNotes||"")})}
  async function runAction(event:FormEvent){event.preventDefault();if(!actionTarget)return;const response=await fetch(`/api/enterprise/${organizationId}/healthcare/laboratory/${actionTarget.id}/actions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(actionForm)});const body=await response.json().catch(()=>null) as {message?:string}|null;setMessage(response.ok?(body?.message||t("lab.actionSuccess")):body?.message||t("lab.actionFailed"));if(response.ok){setActionTarget(null);setDetail(null);await load()}}
  async function createCatalog(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch(`/api/enterprise/${organizationId}/healthcare/laboratory`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,entity:"catalog"})});setMessage(response.ok?t("lab.catalogCreated"):t("lab.catalogCreateFailed"));if(response.ok){setCatalogOpen(false);await load()}}

  return <section className="min-w-0 space-y-4 overflow-hidden overflow-x-hidden rounded-2xl border border-dtsc-border bg-dtsc-surface p-3 sm:p-5">
    <div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="text-xl font-black">{t("lab.title")}</h3><p className="mt-1 max-w-3xl text-sm text-dtsc-muted">{t("lab.description")}</p></div><div className="flex w-full min-w-0 flex-wrap gap-2 sm:w-auto">{permissions.canManageCatalog&&<Button variant="outline" onClick={()=>setCatalogOpen(true)}><FlaskConical/>{t("lab.newTest")}</Button>}{permissions.canCreate&&<Button className="bg-[#002b5b] text-white" onClick={openCreate}><Plus/>{t("lab.newRequest")}</Button>}</div></div>
    <div className="grid min-w-0 gap-2 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(dashboard).map(([key,value])=><article key={key} className="min-w-0 rounded-xl border border-dtsc-border bg-dtsc-page p-3"><p className="text-xs font-black uppercase text-dtsc-muted">{t(dashboardKeys[key as keyof typeof dashboard])}</p><p className="mt-1 text-2xl font-black text-cyan-600">{value}</p></article>)}</div>
    <div className="grid min-w-0 gap-2 sm:grid-cols-2 xl:grid-cols-5"><Filter label={t("lab.filter.status")}><Choice value={status} set={setStatus} options={STATUS_KEYS} locale={locale} all={t("lab.filter.all")}/></Filter><Filter label={t("lab.filter.priority")}><Choice value={priority} set={setPriority} options={PRIORITY_KEYS} locale={locale} all={t("lab.filter.all")}/></Filter><Filter label={t("lab.filter.test")}><Select value={test} set={setTest} items={catalog} locale={locale} all={t("lab.filter.all")}/></Filter><Filter label={t("lab.filter.requester")}><select value={requester} onChange={e=>setRequester(e.target.value)} className={selectClass}><option value="">{t("lab.filter.all")}</option>{staff.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Filter><Filter label={t("lab.filter.from")}><Input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></Filter></div>
    <ListControls query={query} onQueryChange={setQuery} page={list.page} pageCount={list.pageCount} totalCount={requests.length} filteredCount={filtered.length} onPageChange={list.setPage} placeholder={t("lab.searchPlaceholder")}/>
    {loading?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(id=><div key={id} className="h-44 animate-pulse rounded-2xl bg-dtsc-page"/>)}</div>:<div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-3">{list.paginatedItems.map(item=><LabCard key={item.id} item={item} permissions={permissions} locale={locale} t={t} detail={openDetail} edit={openEdit} action={openAction}/>)}</div>}
    {!loading&&!filtered.length&&<Empty text={t("lab.empty")}/>}
    <Dialog open={formOpen} onClose={()=>setFormOpen(false)} title={editing?t("lab.dialog.requestEdit"):t("lab.dialog.requestCreate")} description={t("lab.dialog.requestDescription")} className="h-[94dvh] max-w-6xl"><RequestForm form={form} change={change} save={save} editing={editing} patients={patients} consultations={consultations} staff={staff} catalog={catalog} locale={locale} t={t}/></Dialog>
    <Dialog open={Boolean(detail)} onClose={()=>setDetail(null)} title={detail?`${detail.labRequestNumber} · ${detail.patient.fullName}`:t("lab.dialog.detailFallback")} description={t("lab.dialog.detailDescription")} className="h-[94dvh] max-w-7xl">{detail&&<LabDetail item={detail} permissions={permissions} locale={locale} t={t} edit={openEdit} action={openAction}/>}</Dialog>
    <Dialog open={Boolean(actionTarget)} onClose={()=>setActionTarget(null)} title={actionTitle(locale,String(actionForm.action))} description={t("lab.dialog.actionDescription")} className="h-[90dvh] max-w-4xl"><ActionForm form={actionForm} set={(key,value)=>setActionForm(current=>({...current,[key]:value}))} save={runAction} staff={staff} locale={locale} t={t}/></Dialog>
    <Dialog open={catalogOpen} onClose={()=>setCatalogOpen(false)} title={t("lab.dialog.catalogTitle")} description={t("lab.dialog.catalogDescription")} className="h-[90dvh] max-w-3xl"><CatalogForm save={createCatalog} locale={locale} t={t}/></Dialog>
  </section>;
}

function LabCard({item,permissions,locale,t,detail,edit,action}:{item:Lab;permissions:Permissions;locale:HealthClinicalLocale;t:T;detail:(item:Lab)=>Promise<void>;edit:(item:Lab)=>void;action:(item:Lab,action:string)=>void}) {
  const actions:ActionMenuItem[]=[{key:"detail",label:t("lab.action.detail"),icon:Eye,onSelect:()=>void detail(item)}];
  if(permissions.canUpdate&&!["VALIDATED","TRANSMITTED","CANCELLED","REJECTED"].includes(item.status))actions.push({key:"edit",label:t("lab.action.edit"),icon:FilePenLine,onSelect:()=>edit(item)});
  if(permissions.canCollect&&["REQUESTED","PENDING_SAMPLE"].includes(item.status))actions.push({key:"sample",label:t("lab.action.collect"),icon:Beaker,onSelect:()=>action(item,"collect_sample")});
  if(permissions.canEnterResult&&["SAMPLED","ANALYZING","RESULT_ENTERED","PENDING_VALIDATION"].includes(item.status))actions.push({key:"result",label:t("lab.action.enterResult"),icon:FlaskConical,onSelect:()=>action(item,"enter_result")});
  if(permissions.canValidate&&item.status==="PENDING_VALIDATION")actions.push({key:"validate",label:t("lab.action.validate"),icon:ShieldCheck,onSelect:()=>action(item,"validate_result")});
  if(permissions.canTransmit&&item.status==="VALIDATED")actions.push({key:"transmit",label:t("lab.action.transmit"),icon:Send,onSelect:()=>action(item,"transmit_result")});
  if(permissions.canCancel&&!["VALIDATED","TRANSMITTED","CANCELLED","REJECTED"].includes(item.status))actions.push({key:"cancel",label:t("lab.action.cancel"),icon:XCircle,destructive:true,onSelect:()=>action(item,"cancel")});
  return <article className="relative min-w-0 rounded-2xl border border-dtsc-border bg-dtsc-page p-4 pr-14"><div className="absolute right-3 top-3"><ActionMenu items={actions}/></div><div className="flex flex-wrap gap-2"><Badge text={controlledLabel(locale,item.status,STATUS_KEYS)}/><Badge text={controlledLabel(locale,item.priority,PRIORITY_KEYS)} critical={item.priority==="CRITICAL"}/>{item.abnormalityLevel==="CRITICAL"&&<Badge text={t("lab.badge.criticalResult")} critical/>}</div><button type="button" onClick={()=>void detail(item)} className="mt-3 block min-w-0 text-left"><p className="text-xs font-black uppercase text-cyan-600">{item.labRequestNumber}</p><h4 className="mt-1 break-words font-black">{item.patient.fullName}</h4><p className="mt-1 break-words text-sm text-dtsc-muted">{item.patient.patientNumber} · {item.items.map(row=>row.testLabel).join(", ")}</p><p className="mt-2 break-words text-xs font-bold text-dtsc-muted">{t("lab.card.requestedBy",{name:item.requestedBy.name})} · {healthClinicalDateTime(item.requestedAt,locale)}</p></button></article>;
}

function RequestForm({form,change,save,editing,patients,consultations,staff,catalog,locale,t}:{form:Form;change:(key:string,value:string|string[])=>void;save:(event:FormEvent)=>Promise<void>;editing:Lab|null;patients:Patient[];consultations:Consultation[];staff:Staff[];catalog:Test[];locale:HealthClinicalLocale;t:T}) {
  const selected=Array.isArray(form.testIds)?form.testIds:[]; const patientId=String(form.patientId);
  return <form onSubmit={save} className="grid min-w-0 gap-4 overflow-x-hidden">
    <Section title={t("lab.section.patientConsultation")}><Grid><F label={t("lab.field.patient")} help={t("lab.help.patient")}><select required disabled={Boolean(editing?.sampledAt)} value={patientId} onChange={e=>change("patientId",e.target.value)} className={selectClass}><option value="">{t("lab.select.patient")}</option>{patients.map(item=><option key={item.id} value={item.id}>{item.patientNumber} · {item.fullName}</option>)}</select></F><F label={t("lab.field.consultation")} help={t("lab.help.consultation")}><select disabled={Boolean(editing?.sampledAt)} value={String(form.consultationId)} onChange={e=>change("consultationId",e.target.value)} className={selectClass}><option value="">{t("lab.select.noConsultation")}</option>{consultations.filter(item=>!patientId||item.patientId===patientId).map(item=><option key={item.id} value={item.id}>{item.consultationNumber} · {item.chiefComplaint}</option>)}</select></F></Grid></Section>
    <Section title={t("lab.section.medicalRequest")}><Grid><F label={t("lab.field.requester")} help={t("lab.help.requester")}><StaffSelect required value={String(form.requestedById)} set={value=>change("requestedById",value)} staff={staff} t={t}/></F><F label={t("lab.field.assignedLab")} help={t("lab.help.assignedLab")}><StaffSelect value={String(form.assignedLabStaffId)} set={value=>change("assignedLabStaffId",value)} staff={staff.filter(item=>["LAB_TECHNICIAN","LAB_MANAGER","MEDICAL_DIRECTOR"].includes(item.positionCode))} t={t}/></F><F label={t("lab.field.clinicalIndication")} help={t("lab.help.clinicalIndication")}><Area value={String(form.clinicalIndication)} set={value=>change("clinicalIndication",value)} required/></F><F label={t("lab.field.medicalNotes")} help={t("lab.help.medicalNotes")}><Area value={String(form.medicalNotes)} set={value=>change("medicalNotes",value)}/></F></Grid></Section>
    <Section title={t("lab.section.requestedTests")}><Grid><F label={t("lab.field.mainTest")} help={t("lab.help.mainTest")}><Select required value={String(form.mainTestId)} set={value=>change("mainTestId",value)} items={catalog} locale={locale} select={t("lab.select.select")}/></F><F label={t("lab.field.sampleType")} help={t("lab.help.sampleType")}><Choice value={String(form.sampleType)} set={value=>change("sampleType",value)} options={SAMPLE_KEYS} locale={locale}/></F></Grid><div className="grid min-w-0 gap-2 md:grid-cols-2">{catalog.map(item=><label key={item.id} className="flex min-w-0 items-start gap-2 rounded-xl border border-dtsc-border p-3 text-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>change("testIds",e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/><span className="min-w-0"><strong className="break-words">{catalogLabel(locale,item)}</strong><span className="block break-words text-xs text-dtsc-muted">{controlledLabel(locale,item.category,CATEGORY_KEYS)} · {controlledLabel(locale,item.sampleType,SAMPLE_KEYS)}</span></span></label>)}</div></Section>
    <Section title={t("lab.section.prioritySamplingConfidentiality")}><Grid><F label={t("lab.field.priority")} help={t("lab.help.priority")}><Choice value={String(form.priority)} set={value=>change("priority",value)} options={PRIORITY_KEYS} locale={locale}/></F><F label={t("lab.field.expectedSample")} help={t("lab.help.expectedSample")}><Input type="datetime-local" value={String(form.expectedSampleAt)} onChange={e=>change("expectedSampleAt",e.target.value)}/></F><F label={t("lab.field.confidentiality")} help={t("lab.help.confidentiality")}><Choice value={String(form.confidentialityLevel)} set={value=>change("confidentialityLevel",value)} options={CONFIDENTIALITY_KEYS} locale={locale}/></F><F label={t("lab.field.laboratoryInstructions")} help={t("lab.help.laboratoryInstructions")}><Area value={String(form.laboratoryNotes)} set={value=>change("laboratoryNotes",value)}/></F><F label={t("lab.field.internalNotes")} help={t("lab.help.internalNotes")}><Area value={String(form.internalNotes)} set={value=>change("internalNotes",value)}/></F>{editing&&<F label={t("lab.field.modificationReason")} help={t("lab.help.modificationReason")}><Area value={String(form.reason||"")} set={value=>change("reason",value)}/></F>}</Grid></Section>
    <Button className="bg-[#002b5b] text-white">{editing?t("lab.button.saveChanges"):t("lab.button.createRequest")}</Button>
  </form>;
}

function LabDetail({item,permissions,locale,t,edit,action}:{item:Lab;permissions:Permissions;locale:HealthClinicalLocale;t:T;edit:(item:Lab)=>void;action:(item:Lab,action:string)=>void}) {
  const notProvided=t("lab.common.notProvided");
  return <div className="grid min-w-0 gap-4 overflow-x-hidden"><div className="flex min-w-0 flex-wrap gap-2">{permissions.canUpdate&&!["VALIDATED","TRANSMITTED","CANCELLED","REJECTED"].includes(item.status)&&<Button onClick={()=>edit(item)}><FilePenLine/>{t("lab.action.edit")}</Button>}{permissions.canCollect&&["REQUESTED","PENDING_SAMPLE"].includes(item.status)&&<Button variant="outline" onClick={()=>action(item,"collect_sample")}><Beaker/>{t("lab.action.collect")}</Button>}{permissions.canEnterResult&&["SAMPLED","ANALYZING","RESULT_ENTERED","PENDING_VALIDATION"].includes(item.status)&&<Button variant="outline" onClick={()=>action(item,"enter_result")}><FlaskConical/>{t("lab.action.enterResult")}</Button>}{permissions.canValidate&&item.status==="PENDING_VALIDATION"&&<Button onClick={()=>action(item,"validate_result")}><ShieldCheck/>{t("lab.action.validate")}</Button>}{permissions.canTransmit&&item.status==="VALIDATED"&&<Button variant="outline" onClick={()=>action(item,"transmit_result")}><Send/>{t("lab.action.transmit")}</Button>}</div>
    <Section title={t("lab.section.requestSummary")}><Grid>{[[t("lab.field.requestNumber"),item.labRequestNumber],[t("lab.field.patient"),`${item.patient.patientNumber} · ${item.patient.fullName}`],[t("lab.field.consultation"),item.consultation?.consultationNumber],[t("lab.field.requester"),item.requestedBy.name],[t("lab.field.assignedLab"),item.assignedLabStaff?.name],[t("lab.field.priority"),controlledLabel(locale,item.priority,PRIORITY_KEYS)],[t("lab.field.status"),controlledLabel(locale,item.status,STATUS_KEYS)],[t("lab.field.requestDate"),healthClinicalDateTime(item.requestedAt,locale)]].map(([label,value])=><Info key={String(label)} label={String(label)} value={value?String(value):notProvided}/>)}</Grid></Section>
    {permissions.canViewSensitive?<><Section title={t("lab.section.clinicalInfo")}><Grid><Info label={t("lab.field.clinicalIndication")} value={item.clinicalIndication||notProvided}/><Info label={t("lab.field.medicalNotes")} value={item.medicalNotes||notProvided}/></Grid></Section><Section title={t("lab.section.sampling")}><Grid>{[[t("lab.field.sampleType"),item.sampleType?controlledLabel(locale,item.sampleType,SAMPLE_KEYS):null],[t("lab.field.actualDate"),item.sampledAt?healthClinicalDateTime(item.sampledAt,locale):null],[t("lab.field.sampler"),item.sampledBy?.name],[t("lab.field.sampleQuality"),item.sampleQuality?controlledLabel(locale,item.sampleQuality,QUALITY_KEYS):null],[t("lab.field.sampleComment"),item.sampleNotes]].map(([label,value])=><Info key={String(label)} label={String(label)} value={value?String(value):notProvided}/>)}</Grid></Section><Section title={t("lab.section.results")}><Grid>{[[t("lab.field.result"),item.resultText],[t("lab.field.unit"),item.resultUnit],[t("lab.field.referenceValues"),item.referenceRange],[t("lab.field.interpretation"),item.resultInterpretation],[t("lab.field.abnormality"),item.abnormalityLevel?controlledLabel(locale,item.abnormalityLevel,ABNORMALITY_KEYS):null],[t("lab.field.enteredBy"),item.resultEnteredBy?.name],[t("lab.field.validatedBy"),item.validatedBy?.name],[t("lab.field.validationDate"),item.validatedAt?healthClinicalDateTime(item.validatedAt,locale):null]].map(([label,value])=><Info key={String(label)} label={String(label)} value={value?String(value):notProvided}/>)}</Grid><div className="mt-3 grid min-w-0 gap-2">{item.items.map(row=><article key={row.id} className="min-w-0 rounded-xl bg-dtsc-surface p-3"><p className="break-words font-black">{row.testLabel}</p><p className="break-words text-sm text-dtsc-muted">{row.resultText||t("lab.common.resultNotEntered")}{row.unit?` · ${row.unit}`:""}{row.referenceRange?` · ${t("lab.common.referencePrefix",{value:row.referenceRange})}`:""}</p></article>)}</div></Section></>:<Empty text={t("lab.common.sensitiveProtected")}/>}
    <Section title={t("lab.section.businessLinks")}><Grid><Info label={t("lab.field.patient")} value={item.patient.fullName}/><Info label={t("lab.field.consultation")} value={item.consultation?.consultationNumber||t("lab.common.notLinked")}/><Info label={t("lab.field.medicalRecord")} value={String(item.medicalRecordId||t("lab.common.notLinked"))}/><Info label={t("lab.field.transmission")} value={item.transmittedToDoctorAt?healthClinicalDateTime(item.transmittedToDoctorAt,locale):t("lab.common.notTransmitted")}/></Grid></Section>
    <Section title={t("lab.section.history")}><div className="grid min-w-0 gap-2">{item.events?.map(event=><article key={event.id} className="min-w-0 rounded-xl bg-dtsc-surface p-3"><p className="break-words font-black">{event.eventType} · {event.actor.name}</p><p className="break-words text-sm text-dtsc-muted">{event.summary} · {healthClinicalDateTime(event.createdAt,locale)}</p></article>)}</div></Section>
  </div>;
}

function ActionForm({form,set,save,staff,locale,t}:{form:Form;set:(key:string,value:string)=>void;save:(event:FormEvent)=>Promise<void>;staff:Staff[];locale:HealthClinicalLocale;t:T}) {
  const action=String(form.action), sample=action==="collect_sample"||action==="reject_sample", result=action==="enter_result"||action==="correct_result", reason=["cancel","reject_request","reject_sample","correct_result"].includes(action);
  return <form onSubmit={save} className="grid min-w-0 gap-4 overflow-x-hidden">{sample&&<Section title={t("lab.section.sampleInfo")}><Grid><F label={t("lab.field.sampleDateTime")} help={t("lab.help.sampleDateTime")}><Input type="datetime-local" value={String(form.sampledAt)} onChange={e=>set("sampledAt",e.target.value)}/></F><F label={t("lab.field.sampler")} help={t("lab.help.sampler")}><StaffSelect value={String(form.sampledById)} set={value=>set("sampledById",value)} staff={staff} t={t}/></F><F label={t("lab.field.sampleType")} help={t("lab.help.sampleType")}><Choice value={String(form.sampleType)} set={value=>set("sampleType",value)} options={SAMPLE_KEYS} locale={locale}/></F><F label={t("lab.field.sampleQuality")} help={t("lab.help.sampleQuality")}><Choice value={String(form.sampleQuality)} set={value=>set("sampleQuality",value)} options={QUALITY_KEYS} locale={locale}/></F><F label={t("lab.field.sampleNotes")} help={t("lab.help.sampleNotes")}><Area value={String(form.sampleNotes)} set={value=>set("sampleNotes",value)}/></F></Grid></Section>}{result&&<Section title={t("lab.section.labResult")}><Grid><F label={t("lab.field.result")} help={t("lab.help.result")}><Area required value={String(form.resultText)} set={value=>set("resultText",value)}/></F><F label={t("lab.field.interpretation")} help={t("lab.help.interpretation")}><Area value={String(form.resultInterpretation)} set={value=>set("resultInterpretation",value)}/></F><F label={t("lab.field.unit")} help={t("lab.help.unit")}><Input value={String(form.resultUnit)} onChange={e=>set("resultUnit",e.target.value)}/></F><F label={t("lab.field.referenceValues")} help={t("lab.help.referenceValues")}><Input value={String(form.referenceRange)} onChange={e=>set("referenceRange",e.target.value)}/></F><F label={t("lab.field.abnormality")} help={t("lab.help.abnormality")}><Choice value={String(form.abnormalityLevel)} set={value=>set("abnormalityLevel",value)} options={ABNORMALITY_KEYS} locale={locale}/></F><F label={t("lab.field.laboratoryComment")} help={t("lab.help.laboratoryComment")}><Area value={String(form.laboratoryNotes)} set={value=>set("laboratoryNotes",value)}/></F></Grid></Section>}{reason&&<F label={t("lab.field.requiredReason")} help={t("lab.help.requiredReason")}><Area required value={String(form.reason)} set={value=>set("reason",value)}/></F>}<Button className="bg-[#002b5b] text-white">{t("lab.button.confirmAction")}</Button></form>;
}

function CatalogForm({save,locale,t}:{save:(event:FormEvent<HTMLFormElement>)=>Promise<void>;locale:HealthClinicalLocale;t:T}) {
  return <form onSubmit={save} className="grid min-w-0 gap-3 overflow-x-hidden"><Grid><NamedInput name="code" label={t("lab.catalog.code")} help={t("lab.catalog.codeHelp")}/><NamedInput name="labelFr" label={t("lab.catalog.labelFr")} help={t("lab.catalog.labelFrHelp")}/><NamedInput name="labelEn" label={t("lab.catalog.labelEn")} help={t("lab.catalog.labelEnHelp")} optional/><F label={t("lab.catalog.category")} help={t("lab.catalog.categoryHelp")}><select name="category" className={selectClass}>{Object.entries(CATEGORY_KEYS).map(([id,key])=><option key={id} value={id}>{healthClinicalT(locale,key)}</option>)}</select></F><F label={t("lab.catalog.sampleType")} help={t("lab.catalog.sampleTypeHelp")}><select name="sampleType" className={selectClass}>{Object.entries(SAMPLE_KEYS).map(([id,key])=><option key={id} value={id}>{healthClinicalT(locale,key)}</option>)}</select></F><NamedInput name="defaultUnit" label={t("lab.catalog.defaultUnit")} help={t("lab.catalog.defaultUnitHelp")} optional/><NamedInput name="referenceRange" label={t("lab.catalog.referenceRange")} help={t("lab.catalog.referenceRangeHelp")} optional/><NamedInput name="description" label={t("lab.catalog.description")} help={t("lab.catalog.descriptionHelp")} optional/></Grid><Button className="bg-[#002b5b] text-white">{t("lab.button.addCatalog")}</Button></form>;
}

function F({label,help,children}:{label:string;help:string;children:ReactNode}){return <label className="grid min-w-0 gap-1"><span className="flex min-w-0 items-center gap-1 text-xs font-black uppercase text-dtsc-muted">{label}<span title={help} aria-label={`${label} : ${help}`}><CircleHelp className="h-3.5 w-3.5"/></span></span>{children}</label>}
function Filter({label,children}:{label:string;children:ReactNode}){return <label className="grid min-w-0 gap-1 text-xs font-black uppercase text-dtsc-muted"><span>{label}</span>{children}</label>}
function Choice({value,set,options,locale,all}:{value:string;set:(value:string)=>void;options:Readonly<Record<string,HealthClinicalKey>>;locale:HealthClinicalLocale;all?:string}){return <select value={value} onChange={e=>set(e.target.value)} className={selectClass}>{all!==undefined&&<option value="">{all}</option>}{Object.entries(options).map(([id,key])=><option key={id} value={id}>{healthClinicalT(locale,key)}</option>)}</select>}
function Select({value,set,items,locale,required,all,select}:{value:string;set:(value:string)=>void;items:Test[];locale:HealthClinicalLocale;required?:boolean;all?:string;select?:string}){return <select required={required} value={value} onChange={e=>set(e.target.value)} className={selectClass}><option value="">{required?(select||""):(all||"")}</option>{items.map(item=><option key={item.id} value={item.id}>{catalogLabel(locale,item)}</option>)}</select>}
function StaffSelect({value,set,staff,t,required}:{value:string;set:(value:string)=>void;staff:Staff[];t:T;required?:boolean}){return <select required={required} value={value} onChange={e=>set(e.target.value)} className={selectClass}><option value="">{required?t("lab.select.select"):t("lab.select.unassigned")}</option>{staff.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="min-w-0 space-y-3 rounded-2xl border border-dtsc-border bg-dtsc-page p-3 sm:p-4"><h4 className="break-words font-black text-cyan-600">{title}</h4>{children}</section>}
function Grid({children}:{children:ReactNode}){return <div className="grid min-w-0 gap-3 md:grid-cols-2">{children}</div>}
function Area({value,set,required}:{value:string;set:(value:string)=>void;required?:boolean}){return <textarea required={required} value={value} onChange={e=>set(e.target.value)} className="min-h-24 min-w-0 rounded-xl border border-dtsc-border bg-dtsc-surface p-3 text-sm"/>}
function NamedInput({name,label,help,optional}:{name:string;label:string;help:string;optional?:boolean}){return <F label={label} help={help}><Input name={name} required={!optional}/></F>}
function Info({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl bg-dtsc-surface p-3"><p className="break-words text-xs font-black uppercase text-dtsc-muted">{label}</p><p className="mt-1 break-words text-sm font-bold">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-dtsc-border p-4 text-center text-sm text-dtsc-muted">{text}</p>}
function Badge({text,critical}:{text:string;critical?:boolean}){return <span className={`rounded-full px-2 py-1 text-xs font-black ${critical?"bg-red-500/15 text-red-600":"bg-cyan-400/15 text-cyan-700"}`}>{text}</span>}
const selectClass="h-11 min-w-0 rounded-xl border border-dtsc-border bg-dtsc-surface px-3 text-sm text-dtsc-ink";
