"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { CircleHelp, Download, RefreshCw, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ListControls } from "@/components/ui/list-controls";
import { useSmartList } from "@/lib/hooks/use-smart-list";

type Row = Record<string, string | number | boolean | null>;
type Section = { title: string; description: string; metrics: Array<{ label: string; value: string | number; sensitive?: boolean }>; rows: Row[] };
type Option = { id: string; label: string };
type Data = { filters: Filters; permissions: { financial: boolean; sensitive: boolean }; sections: Record<string, Section>; options: Record<"products" | "batches" | "suppliers" | "members" | "departments", Option[]>; savedViews: Array<{ id: string; name: string; reportType: string; filtersJson: Filters; visibility: string }>; exports: Array<{ id: string; reportName: string; format: string; status: string; exportedAt: string }>; snapshots: Array<{ id: string; snapshotName: string; reportType: string; generatedAt: string }> };
type Filters = { start?: string; end?: string; productId?: string; batchId?: string; supplierId?: string; userId?: string; departmentId?: string; status?: string; category?: string; criticality?: string; paymentMethod?: string };
const tabs = [
  ["overview", "Tableau de bord rapports", "PHARMACY_OVERVIEW"], ["sales", "Rapports ventes", "SALES"], ["stock", "Rapports stock", "STOCK"], ["batches", "Rapports lots & péremptions", "BATCH_EXPIRY"], ["purchases", "Rapports achats & fournisseurs", "PURCHASES"], ["receipts", "Rapports réceptions", "RECEIPTS"], ["cash", "Rapports caisse & paiements", "CASH_PAYMENTS"], ["prescriptions", "Rapports ordonnances", "PRESCRIPTIONS"], ["returns", "Rapports retours, pertes & destructions", "RETURNS_LOSSES"], ["quality", "Rapports qualité & pharmacovigilance", "QUALITY_INCIDENTS"], ["alerts", "Rapports alertes", "ALERTS"], ["documents", "Rapports documents & conformité", "DOCUMENTS_COMPLIANCE"], ["collaborators", "Rapports collaborateurs / activité", "COLLABORATOR_ACTIVITY"], ["custom", "Rapports personnalisés simples", "CUSTOM_SIMPLE"], ["exports", "Exports & historiques", "CUSTOM_SIMPLE"],
] as const;
const emptyFilters: Filters = {};
const help: Record<string, string> = { start: "Début de la période analysée.", end: "Fin de la période analysée.", productId: "Limiter les indicateurs au produit sélectionné.", batchId: "Limiter aux données du lot sélectionné.", supplierId: "Limiter au fournisseur sélectionné.", userId: "Limiter à l'activité du collaborateur.", departmentId: "Limiter au département.", status: "Filtrer selon un statut métier exact.", criticality: "Limiter à une criticité.", paymentMethod: "Limiter au mode de paiement." };
const date = (value: string) => value ? new Date(value).toLocaleDateString("fr-FR") : "";

export function PharmacyReportsWorkspace({ organizationId }: { organizationId: string }) {
  const [active, setActive] = useState("overview"); const [filters, setFilters] = useState<Filters>(emptyFilters); const [data, setData] = useState<Data | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [saveOpen, setSaveOpen] = useState(false); const [viewName, setViewName] = useState(""); const [snapshotName, setSnapshotName] = useState("");
  const load = useCallback(async (nextFilters: Filters = filters) => { setBusy(true); const query = new URLSearchParams(Object.entries(nextFilters).filter((entry): entry is [string, string] => Boolean(entry[1]))); const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/reports?${query}`, { cache: "no-store" }); const body = await response.json().catch(() => null) as Data | { message?: string } | null; if (response.ok && body && "sections" in body) setData(body); else setMessage(body && "message" in body ? body.message || "Chargement impossible." : "Chargement impossible."); setBusy(false); }, [filters, organizationId]);
  useEffect(() => { void load(); }, [load]);
  const current = data?.sections[active]; const reportType = tabs.find((item) => item[0] === active)?.[2] || "PHARMACY_OVERVIEW";
  async function saveView() { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/reports`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: viewName, reportType, filters, visibility: "PRIVATE" }) }); setMessage(response.ok ? "Vue sauvegardée." : "Sauvegarde impossible."); if (response.ok) { setSaveOpen(false); setViewName(""); await load(); } }
  async function snapshot() { if (!snapshotName.trim()) return setMessage("Saisissez un nom de snapshot."); const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/reports/actions/snapshot/new`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create-snapshot", reportType, filters, snapshotName }) }); setMessage(response.ok ? "Snapshot créé." : "Création du snapshot impossible."); if (response.ok) { setSnapshotName(""); await load(); } }
  async function exportCsv() { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/reports/export`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reportType, format: "CSV", filters }) }); if (!response.ok) { const body = await response.json().catch(() => null) as { message?: string } | null; return setMessage(body?.message || "Export impossible."); } const blob = await response.blob(); const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = `rapport-pharmacie-${reportType.toLowerCase()}.csv`; anchor.click(); URL.revokeObjectURL(href); setMessage("Export CSV généré et audité."); await load(); }
  function applyView(view: Data["savedViews"][number]) { setFilters(view.filtersJson || {}); const target = tabs.find((item) => item[2] === view.reportType)?.[0]; if (target) setActive(target); void load(view.filtersJson || {}); }
  return <div className="min-w-0 space-y-4 overflow-x-hidden">
    <div className="flex max-w-full gap-2 overflow-x-auto pb-2">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setActive(key)} className={`shrink-0 rounded-2xl border px-4 py-3 text-sm font-black ${active === key ? "border-emerald-300 bg-emerald-400/15 text-emerald-700" : "border-dtsc-border bg-dtsc-surface text-dtsc-ink"}`}>{label}</button>)}</div>
    <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-black text-dtsc-ink">{current?.title || "Rapports pharmacie"}</h3><p className="text-sm text-dtsc-muted">{current?.description || "Agrégations métier réelles."}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void load()} disabled={busy}><RefreshCw className="h-4 w-4" />Actualiser</Button><Button variant="outline" onClick={() => setSaveOpen(true)}><Save className="h-4 w-4" />Sauvegarder la vue</Button><Button variant="outline" onClick={() => void exportCsv()}><Download className="h-4 w-4" />Exporter CSV</Button></div></div>
      <div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Filter title="Début" help={help.start}><Input type="date" value={filters.start || data?.filters.start || ""} onChange={(event) => setFilters((old) => ({ ...old, start: event.target.value }))} /></Filter><Filter title="Fin" help={help.end}><Input type="date" value={filters.end || data?.filters.end || ""} onChange={(event) => setFilters((old) => ({ ...old, end: event.target.value }))} /></Filter><SelectFilter title="Produit" help={help.productId} value={filters.productId} options={data?.options.products || []} onChange={(value) => setFilters((old) => ({ ...old, productId: value }))} /><SelectFilter title="Lot" help={help.batchId} value={filters.batchId} options={data?.options.batches || []} onChange={(value) => setFilters((old) => ({ ...old, batchId: value }))} /><SelectFilter title="Fournisseur" help={help.supplierId} value={filters.supplierId} options={data?.options.suppliers || []} onChange={(value) => setFilters((old) => ({ ...old, supplierId: value }))} /><SelectFilter title="Collaborateur" help={help.userId} value={filters.userId} options={data?.options.members || []} onChange={(value) => setFilters((old) => ({ ...old, userId: value }))} /><SelectFilter title="Département" help={help.departmentId} value={filters.departmentId} options={data?.options.departments || []} onChange={(value) => setFilters((old) => ({ ...old, departmentId: value }))} /><Filter title="Statut" help={help.status}><Input value={filters.status || ""} onChange={(event) => setFilters((old) => ({ ...old, status: event.target.value }))} placeholder="Ex. VALIDATED" /></Filter></div>
      <div className="mt-3 flex flex-wrap gap-2"><Button onClick={() => void load(filters)}>Appliquer les filtres</Button><Button variant="outline" onClick={() => { setFilters({}); void load({}); }}>Réinitialiser</Button>{!data?.permissions.financial && <Tag>Montants financiers protégés</Tag>}{!data?.permissions.sensitive && <Tag>Données sensibles protégées</Tag>}</div>
    </section>
    {busy ? <p className="rounded-2xl border border-dtsc-border bg-dtsc-page p-5 text-sm font-bold text-dtsc-muted">Calcul des indicateurs réels en cours...</p> : current && <ReportSection section={current} />}
    {active === "custom" && <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><h4 className="font-black text-dtsc-ink">Vues sauvegardées</h4><div className="mt-3 grid gap-2 md:grid-cols-2">{data?.savedViews.map((view) => <button key={view.id} type="button" onClick={() => applyView(view)} className="rounded-xl border border-dtsc-border p-3 text-left"><b>{view.name}</b><span className="block text-xs text-dtsc-muted">{view.reportType} · {view.visibility}</span></button>)}{!data?.savedViews.length && <Empty />}</div></section>}
    {active === "exports" && <section className="grid gap-4 lg:grid-cols-2"><History title="Historique des exports" rows={(data?.exports || []).map((item) => [item.reportName, `${item.format} · ${item.status} · ${date(item.exportedAt)}`])} /><History title="Snapshots décisionnels" rows={(data?.snapshots || []).map((item) => [item.snapshotName, `${item.reportType} · ${date(item.generatedAt)}`])} /><div className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><h4 className="font-black">Créer un snapshot du rapport actif</h4><Input className="mt-3" value={snapshotName} onChange={(event) => setSnapshotName(event.target.value)} placeholder="Nom du snapshot" /><Button className="mt-3" onClick={() => void snapshot()}>Créer le snapshot</Button></div></section>}
    {message && <p className="rounded-2xl border border-dtsc-border bg-dtsc-page p-3 text-sm font-bold text-dtsc-blue">{message}</p>}
    <Dialog open={saveOpen} title="Sauvegarder cette vue" description="La vue conserve le domaine et les filtres dans l'organisation active." onClose={() => setSaveOpen(false)}><Filter title="Nom facilement identifiable" help="Exemple : ventes mensuelles par produit."><Input value={viewName} onChange={(event) => setViewName(event.target.value)} /></Filter><Button className="mt-4" disabled={viewName.trim().length < 2} onClick={() => void saveView()}>Enregistrer la vue</Button></Dialog>
  </div>;
}

function ReportSection({ section }: { section: Section }) { const list = useSmartList({ items: section.rows, pageSize: 12, getSearchText: useCallback((row: Row) => Object.values(row).join(" "), []) }); const columns = useMemo(() => Array.from(new Set(section.rows.flatMap((row) => Object.keys(row)))).slice(0, 10), [section.rows]); return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{section.metrics.map((item) => <article key={item.label} className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><p className="text-xs font-black uppercase text-emerald-600">{item.label}</p><p className="mt-2 break-words text-2xl font-black text-dtsc-ink">{String(item.value)}</p></article>)}</div><section className="min-w-0 overflow-hidden rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><ListControls query={list.query} onQueryChange={list.setQuery} page={list.page} pageCount={list.pageCount} totalCount={list.totalCount} filteredCount={list.filteredCount} placeholder="Rechercher dans le rapport..." onPageChange={list.setPage} /><div className="mt-3 hidden max-w-full overflow-x-auto md:block"><table className="min-w-full text-left text-sm"><thead><tr>{columns.map((column) => <th key={column} className="whitespace-nowrap border-b border-dtsc-border p-2 font-black">{column}</th>)}</tr></thead><tbody>{list.paginatedItems.map((row, index) => <tr key={index}>{columns.map((column) => <td key={column} className="max-w-64 border-b border-dtsc-border p-2 text-dtsc-muted">{String(row[column] ?? "")}</td>)}</tr>)}</tbody></table></div><div className="mt-3 grid gap-2 md:hidden">{list.paginatedItems.map((row, index) => <article key={index} className="rounded-xl border border-dtsc-border p-3">{columns.map((column) => <p key={column} className="break-words text-xs"><b>{column} :</b> {String(row[column] ?? "")}</p>)}</article>)}</div>{!list.filteredCount && <Empty />}</section></div>; }
function Filter({ title, help: helpText, children }: { title: string; help: string; children: ReactNode }) { return <label className="grid min-w-0 gap-1 text-xs font-black uppercase text-dtsc-muted"><span className="flex items-center gap-1">{title}<span title={helpText} aria-label={helpText}><CircleHelp className="h-3.5 w-3.5" /></span></span>{children}</label>; }
function SelectFilter({ title, help: helpText, value, options, onChange }: { title: string; help: string; value?: string; options: Option[]; onChange: (value: string) => void }) { return <Filter title={title} help={helpText}><select value={value || ""} onChange={(event) => onChange(event.target.value)} className="min-w-0 rounded-xl border border-dtsc-border bg-dtsc-surface px-3 py-2 text-sm text-dtsc-ink"><option value="">Tous</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></Filter>; }
function Tag({ children }: { children: ReactNode }) { return <span className="rounded-full bg-amber-400/15 px-3 py-2 text-xs font-black text-amber-700">{children}</span>; }
function Empty() { return <p className="rounded-xl border border-dashed border-dtsc-border p-4 text-sm text-dtsc-muted">Aucune donnée réelle ne correspond aux filtres sélectionnés.</p>; }
function History({ title, rows }: { title: string; rows: Array<[string, string]> }) { return <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><h4 className="font-black text-dtsc-ink">{title}</h4><div className="mt-3 grid gap-2">{rows.map(([name, detail], index) => <article key={`${name}-${index}`} className="rounded-xl border border-dtsc-border p-3"><b>{name}</b><span className="block text-xs text-dtsc-muted">{detail}</span></article>)}{!rows.length && <Empty />}</div></section>; }
