"use client";

import { useCallback, useEffect, useState, type Dispatch, type FormEvent, type ReactNode, type SetStateAction } from "react";
import { BadgeCheck, CircleHelp, Download, Eye, Plus, RefreshCw, ShieldAlert } from "lucide-react";
import { ActionMenu, type ActionMenuItem } from "@/components/ui/action-menu";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ListControls } from "@/components/ui/list-controls";
import { useSmartList } from "@/lib/hooks/use-smart-list";

import { useToastMessage } from "@/components/ui/use-toast-message";
type Opt = { id: string; name?: string; title?: string; productId?: string; batchNumber?: string; orderNumber?: string; receiptNumber?: string; saleNumber?: string; paymentNumber?: string; invoiceNumber?: string; prescriptionNumber?: string; eventNumber?: string; incidentNumber?: string; alertNumber?: string; cashSessionNumber?: string };
type Link = { id: string; entityType: string; entityId: string; linkRole: string };
type Version = { id: string; versionNumber: number; filename: string | null; mimeType: string | null; fileSize: number | null; uploadedAt: string; changeReason: string | null; isCurrent: boolean };
type AccessLog = { id: string; documentId: string; actorId: string; action: string; createdAt: string };
type DocumentItem = { id: string; documentNumber: string; title: string; description: string | null; documentType: string; category: string; moduleSource: string | null; reference: string | null; documentDate: string | null; issuer: string | null; fileUrl: string | null; filename: string | null; mimeType: string | null; fileSize: number | null; versionNumber: number; importance: string; confidentialityLevel: string; complianceRequired: boolean; complianceStatus: string; expiryDate: string | null; renewalRequired: boolean; renewalDueDate: string | null; verificationRequired: boolean; status: string; notes: string | null; createdById: string; createdAt: string; updatedAt: string; links: Link[]; versions: Version[]; accessLogs: AccessLog[] };
type Missing = { id: string; entityType: string; entityId: string; expectedDocumentType: string; criticality: string; status: string; assignedToId: string | null; resolvedByDocumentId: string | null; createdAt: string };
type Rule = { id: string; ruleCode: string; label: string; description: string | null; entityType: string; documentType: string; required: boolean; expiryRequired: boolean; verificationRequired: boolean; defaultConfidentialityLevel: string; enabled: boolean };
type Data = { metrics: Record<string, number>; documents: DocumentItem[]; rules: Rule[]; missing: Missing[]; accessLogs: AccessLog[]; storageConfigured: boolean; products: Opt[]; batches: Opt[]; suppliers: Opt[]; orders: Opt[]; receipts: Opt[]; sales: Opt[]; payments: Opt[]; invoices: Opt[]; prescriptions: Opt[]; inventories: Opt[]; returns: Opt[]; qualityIncidents: Opt[]; alerts: Opt[]; cashSessions: Opt[]; members: Opt[]; legacyCounts: number[] };
type Tab = "dashboard" | "library" | "modules" | "products" | "suppliers" | "receipts" | "sales" | "prescriptions" | "returns" | "quality" | "administrative" | "expired" | "missing" | "access" | "history";
type FormState = Record<string, string | boolean>;

const TABS: Array<[Tab, string]> = [["dashboard", "Tableau de bord documentaire"], ["library", "Bibliothèque documents"], ["modules", "Documents par module"], ["products", "Documents produits & lots"], ["suppliers", "Documents fournisseurs & achats"], ["receipts", "Documents réceptions"], ["sales", "Documents ventes, reçus & factures"], ["prescriptions", "Documents ordonnances"], ["returns", "Documents retours, pertes & destructions"], ["quality", "Documents incidents qualité"], ["administrative", "Documents administratifs & conformité"], ["expired", "Documents expirés / à renouveler"], ["missing", "Documents manquants"], ["access", "Accès & confidentialité"], ["history", "Historique documentaire"]];
const TYPES = ["SCANNED_PRESCRIPTION", "PRESCRIPTION_PHOTO", "RECEIPT", "CUSTOMER_INVOICE", "SUPPLIER_INVOICE", "DELIVERY_NOTE", "PURCHASE_ORDER", "PROFORMA", "PAYMENT_PROOF", "QUALITY_CERTIFICATE", "SUPPLIER_CERTIFICATE", "BATCH_CERTIFICATE", "COMPLIANCE_DOCUMENT", "ADMIN_AUTHORIZATION", "SUPPLIER_CONTRACT", "INVENTORY_REPORT", "LOSS_REPORT", "DESTRUCTION_MINUTES", "QUALITY_INCIDENT_REPORT", "PHARMACOVIGILANCE_REPORT", "CUSTOMER_RETURN_DOCUMENT", "SUPPLIER_RETURN_DOCUMENT", "INTERNAL_PROCEDURE", "INTERNAL_POLICY", "AUDIT_DOCUMENT", "RECALL_DOCUMENT", "OTHER"];
const CATEGORIES = ["PRESCRIPTION", "SALE_INVOICE_RECEIPT", "PAYMENT", "SUPPLIER", "PURCHASE", "RECEIPT", "PRODUCT", "BATCH", "STOCK_INVENTORY", "RETURN_LOSS_DESTRUCTION", "QUALITY", "PHARMACOVIGILANCE", "ADMINISTRATIVE", "COMPLIANCE", "PROCEDURE", "AUDIT", "OTHER"];
const MODULES = ["PRODUCTS", "BATCHES", "STOCK", "RECEIPTS", "SALES", "PRESCRIPTIONS", "SUPPLIERS", "PURCHASES", "CASH", "RETURNS_LOSSES", "ALERTS", "QUALITY", "ADMINISTRATION", "COMPLIANCE", "OTHER"];
const LABELS: Record<string, string> = { INTERNAL: "Public interne", DEPARTMENT_ONLY: "Département uniquement", MANAGERS_ONLY: "Managers uniquement", RESPONSIBLE_PHARMACIST: "Pharmacien responsable", ADMIN_ENTERPRISE: "Admin entreprise", QUALITY_ONLY: "Qualité uniquement", FINANCIAL: "Financier", VERY_CONFIDENTIAL: "Très confidentiel", DRAFT: "Brouillon", ACTIVE: "Actif", TO_VERIFY: "À vérifier", VALIDATED: "Validé", EXPIRED: "Expiré", TO_RENEW: "À renouveler", ARCHIVED: "Archivé", REJECTED: "Rejeté", DELETED: "Supprimé logiquement", NOT_REQUIRED: "Non requis", COMPLIANT: "Conforme", NON_COMPLIANT: "Non conforme", NORMAL: "Normale", IMPORTANT: "Importante", CRITICAL: "Critique", PRIMARY: "Principal", SUPPORTING: "Justificatif", PROOF: "Preuve", ANNEX: "Annexe", RENEWAL: "Renouvellement", HISTORY: "Historique", PRODUCTS: "Produits & médicaments", BATCHES: "Lots & péremptions", STOCK: "Stock & inventaire", RECEIPTS: "Entrées stock / réceptions", SALES: "Ventes", PRESCRIPTIONS: "Ordonnances", SUPPLIERS: "Fournisseurs", PURCHASES: "Achats", CASH: "Caisse", RETURNS_LOSSES: "Retours, pertes & destructions", ALERTS: "Alertes", QUALITY: "Incidents qualité", ADMINISTRATION: "Administratif", COMPLIANCE: "Conformité", OTHER: "Autre", PharmacyProduct: "Produit", PharmacyBatch: "Lot", PharmacySupplier: "Fournisseur", PharmacyPurchaseOrder: "Commande fournisseur", PharmacyReceipt: "Réception", PharmacySale: "Vente", PharmacyPayment: "Paiement", PharmacyInvoice: "Facture", PharmacyPrescription: "Ordonnance", PharmacyInventorySession: "Inventaire", PharmacyReturnLossEvent: "Retour, perte ou destruction", PharmacyQualityIncident: "Incident qualité", PharmacyAlert: "Alerte", PharmacyCashSession: "Session de caisse", DOWNLOAD: "Téléchargement sensible" };
for (const [code, text] of [["SCANNED_PRESCRIPTION", "Ordonnance scannée"], ["PRESCRIPTION_PHOTO", "Photo ordonnance"], ["RECEIPT", "Reçu"], ["CUSTOMER_INVOICE", "Facture client"], ["SUPPLIER_INVOICE", "Facture fournisseur"], ["DELIVERY_NOTE", "Bon de livraison"], ["PURCHASE_ORDER", "Bon de commande"], ["PROFORMA", "Proforma"], ["PAYMENT_PROOF", "Preuve de paiement"], ["QUALITY_CERTIFICATE", "Certificat qualité"], ["SUPPLIER_CERTIFICATE", "Certificat fournisseur"], ["BATCH_CERTIFICATE", "Certificat lot"], ["COMPLIANCE_DOCUMENT", "Document conformité"], ["ADMIN_AUTHORIZATION", "Autorisation administrative"], ["SUPPLIER_CONTRACT", "Contrat fournisseur"], ["INVENTORY_REPORT", "Rapport inventaire"], ["LOSS_REPORT", "Rapport perte"], ["DESTRUCTION_MINUTES", "Procès-verbal de destruction"], ["QUALITY_INCIDENT_REPORT", "Rapport incident qualité"], ["PHARMACOVIGILANCE_REPORT", "Rapport pharmacovigilance"], ["CUSTOMER_RETURN_DOCUMENT", "Document retour client"], ["SUPPLIER_RETURN_DOCUMENT", "Document retour fournisseur"], ["INTERNAL_PROCEDURE", "Procédure interne"], ["INTERNAL_POLICY", "Politique interne"], ["AUDIT_DOCUMENT", "Document audit"], ["RECALL_DOCUMENT", "Document de rappel"], ["PRESCRIPTION", "Ordonnance"], ["SALE_INVOICE_RECEIPT", "Vente / facture / reçu"], ["PAYMENT", "Paiement"], ["SUPPLIER", "Fournisseur"], ["PURCHASE", "Achat"], ["PRODUCT", "Produit"], ["BATCH", "Lot"], ["STOCK_INVENTORY", "Stock / inventaire"], ["RETURN_LOSS_DESTRUCTION", "Retour / perte / destruction"], ["PHARMACOVIGILANCE", "Pharmacovigilance"], ["ADMINISTRATIVE", "Administratif"], ["PROCEDURE", "Procédure"], ["AUDIT", "Audit"]]) LABELS[code] = text;

function initial(): FormState { return { documentNumber: "", title: "", description: "", documentType: "COMPLIANCE_DOCUMENT", category: "COMPLIANCE", subcategory: "", moduleSource: "COMPLIANCE", sourceEntityType: "", sourceEntityId: "", reference: "", documentDate: "", issuer: "", language: "fr", tags: "", importance: "NORMAL", confidentialityLevel: "INTERNAL", downloadRequiresPermission: true, sensitiveDownloadAudit: false, visibleInActivities: false, complianceRequired: false, complianceStatus: "NOT_REQUIRED", expiryDate: "", renewalRequired: false, renewalDueDate: "", verificationRequired: false, notes: "", linkEntityType: "", linkEntityId: "", linkRole: "PRIMARY" }; }

export function PharmacyDocumentsWorkspace({ organizationId }: { organizationId: string }) {
  const [data, setData] = useState<Data | null>(null), [tab, setTab] = useState<Tab>("dashboard"), [detail, setDetail] = useState<DocumentItem | null>(null), [formOpen, setFormOpen] = useState(false), [form, setForm] = useState<FormState>(initial), [file, setFile] = useState<File | null>(null), [message, setMessage] = useState("");
  useToastMessage(message);
  const load = useCallback(async () => { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/documents`, { cache: "no-store" }); const body = await response.json().catch(() => null) as Data | null; if (response.ok && body) setData(body); else setMessage("Chargement du référentiel documentaire impossible."); }, [organizationId]);
  useEffect(() => { void load(); }, [load]);
  const documents = data?.documents || []; const list = useSmartList({ items: documents, pageSize: 12, getSearchText: useCallback((item: DocumentItem) => `${item.documentNumber} ${item.title} ${item.description || ""} ${item.documentType} ${item.category} ${item.moduleSource || ""} ${item.confidentialityLevel} ${item.status}`, []) });
  async function save(submitEvent: FormEvent) { submitEvent.preventDefault(); const body = new FormData(); body.set("metadata", JSON.stringify(form)); if (file) body.set("file", file); const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/documents`, { method: "POST", body }); const result = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Document enregistré dans le référentiel." : result?.message || "Enregistrement impossible."); if (response.ok) { setFormOpen(false); setFile(null); await load(); } }
  async function action(entity: string, id: string, actionName: string, extra: Record<string, unknown> = {}) { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/documents/actions/${entity}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, ...extra }) }); const result = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Action documentaire enregistrée." : result?.message || "Action impossible."); if (response.ok) { setDetail(null); await load(); } }
  const shown = filtered(tab, documents); return <section className="w-full min-w-0 overflow-hidden rounded-2xl border bg-dtsc-page p-3 sm:p-4">
    <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-black">Documents & conformité</h3><p className="text-sm text-dtsc-muted">Référentiel privé, classification, liens métier, conformité, expiration, versioning et audit.</p></div><div className="grid w-full gap-2 sm:flex sm:w-auto"><Button variant="outline" onClick={() => void action("system", "detect", "detect-compliance")}><RefreshCw />Détecter expirés et manquants</Button><Button className="bg-[#002b5b] text-white" onClick={() => { setForm(initial()); setFile(null); setFormOpen(true); }}><Plus />Nouveau document</Button></div></div>
    <div className="mt-4 flex max-w-full gap-2 overflow-x-auto pb-2">{TABS.map(([code, title]) => <button key={code} type="button" onClick={() => setTab(code)} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-black ${tab === code ? "border-emerald-400 text-emerald-700" : "border-dtsc-border text-dtsc-muted"}`}>{title}</button>)}</div>
    {tab === "dashboard" ? <Dashboard values={data?.metrics || {}} /> : tab === "modules" ? <ModuleGroups documents={documents} /> : tab === "missing" ? <MissingView items={data?.missing || []} documents={documents} action={action} /> : tab === "access" ? <AccessView data={data} action={action} /> : tab === "history" ? <History logs={data?.accessLogs || []} documents={documents} /> : <>
      {tab === "library" && <ListControls query={list.query} onQueryChange={list.setQuery} page={list.page} pageCount={list.pageCount} totalCount={list.totalCount} filteredCount={list.filteredCount} onPageChange={list.setPage} placeholder="Titre, numéro, type, catégorie, module, confidentialité..." />}
      <Grid>{(tab === "library" ? list.paginatedItems : shown).map((item) => <DocumentCard key={item.id} item={item} actions={documentActions(item, setDetail, action)} />)}</Grid>{!(tab === "library" ? list.paginatedItems : shown).length && <Empty />}
    </>}

    <DocumentForm open={formOpen} close={() => setFormOpen(false)} form={form} setForm={setForm} file={file} setFile={setFile} data={data} save={save} />
    <Dialog open={Boolean(detail)} title={detail?.title || "Détail document"} description="Fichier privé, liens métier, conformité, versions et audit." onClose={() => setDetail(null)} className="h-[96dvh] max-w-6xl">{detail && <DocumentDetail item={detail} organizationId={organizationId} action={action} />}</Dialog>
  </section>;
}

function filtered(tab: Tab, documents: DocumentItem[]) { if (tab === "products") return documents.filter((item) => ["PRODUCTS", "BATCHES"].includes(item.moduleSource || "")); if (tab === "suppliers") return documents.filter((item) => ["SUPPLIERS", "PURCHASES"].includes(item.moduleSource || "")); if (tab === "receipts") return documents.filter((item) => item.moduleSource === "RECEIPTS"); if (tab === "sales") return documents.filter((item) => ["SALES", "CASH"].includes(item.moduleSource || "")); if (tab === "prescriptions") return documents.filter((item) => item.moduleSource === "PRESCRIPTIONS"); if (tab === "returns") return documents.filter((item) => item.moduleSource === "RETURNS_LOSSES"); if (tab === "quality") return documents.filter((item) => item.moduleSource === "QUALITY"); if (tab === "administrative") return documents.filter((item) => ["ADMINISTRATION", "COMPLIANCE"].includes(item.moduleSource || "")); if (tab === "expired") return documents.filter((item) => ["EXPIRED", "TO_RENEW"].includes(item.complianceStatus)); return documents; }
function Dashboard({ values }: { values: Record<string, number> }) { return <Grid>{[["Total documents", values.total], ["Ajoutés aujourd'hui", values.addedToday], ["Ajoutés ce mois", values.addedMonth], ["Documents sensibles", values.sensitive], ["Très confidentiels", values.veryConfidential], ["Documents expirés", values.expired], ["Expirant bientôt", values.expiringSoon], ["Documents manquants", values.missing], ["Documents fournisseurs", values.suppliers], ["Documents ordonnances", values.prescriptions], ["Documents ventes / factures", values.sales], ["Documents qualité", values.quality], ["Documents de lots", values.batches], ["Documents de destruction", values.destruction], ["Documents administratifs", values.administrative], ["Téléchargements sensibles", values.sensitiveDownloads]].map(([title, value]) => <Card key={String(title)} title={String(title)} text={String(value ?? 0)} />)}</Grid>; }
function ModuleGroups({ documents }: { documents: DocumentItem[] }) { return <Grid>{MODULES.map((code) => <Card key={code} title={label(code)} text={`${documents.filter((item) => item.moduleSource === code).length} document(s)`} />)}</Grid>; }
function DocumentCard({ item, actions }: { item: DocumentItem; actions: ActionMenuItem[] }) { return <article className="dtsc-glass-list-item min-w-0 rounded-2xl p-4"><div className="flex justify-between gap-2"><div className="min-w-0"><div className="flex flex-wrap gap-1"><Badge value={item.status} /><Badge value={item.confidentialityLevel} /><Badge value={item.complianceStatus} /></div><h4 className="mt-2 break-words font-black">{item.title}</h4><p className="text-xs text-dtsc-muted">{item.documentNumber} · {label(item.documentType)} · {label(item.moduleSource || "OTHER")}</p></div><ActionMenu items={actions} /></div><p className="mt-2 line-clamp-2 text-sm text-dtsc-muted">{item.description || "Aucune description."}</p><p className="mt-2 text-xs font-bold text-dtsc-muted">{item.filename ? `Fichier privé : ${item.filename}` : "Métadonnées seules"} · version {item.versionNumber}</p></article>; }
function documentActions(item: DocumentItem, detail: (item: DocumentItem) => void, action: (entity: string, id: string, name: string, extra?: Record<string, unknown>) => Promise<void>): ActionMenuItem[] { const items: ActionMenuItem[] = [{ key: "view", label: "Voir le détail", icon: Eye, onSelect: () => detail(item) }]; const downloadUrl = typeof item.fileUrl === "string" ? item.fileUrl : undefined; if (downloadUrl) items.push({ key: "download", label: "Télécharger", icon: Download, onSelect: () => window.open(downloadUrl, "_blank", "noopener,noreferrer") }); if (["DRAFT", "TO_VERIFY"].includes(item.status)) items.push({ key: "validate", label: "Valider", icon: BadgeCheck, onSelect: () => void action("document", item.id, "validate", { reason: "Document contrôlé et validé." }) }); if (["EXPIRED", "TO_RENEW"].includes(item.complianceStatus)) items.push({ key: "renew", label: "Préparer le renouvellement", icon: RefreshCw, onSelect: () => void action("document", item.id, "renew", { reason: "Renouvellement initié depuis le document expiré." }) }); return items; }

function DocumentForm({ open, close, form, setForm, file, setFile, data, save }: { open: boolean; close: () => void; form: FormState; setForm: Dispatch<SetStateAction<FormState>>; file: File | null; setFile: (file: File | null) => void; data: Data | null; save: (event: FormEvent) => Promise<void> }) {
  const change = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value })); const entityType = String(form.linkEntityType); const options = entityOptions(entityType, data);
  return <Dialog open={open} title="Nouveau document" description="Référentiel documentaire privé et liens métier contrôlés." onClose={close} className="h-[96dvh] max-w-7xl"><form onSubmit={save} className="grid min-w-0 gap-4 overflow-x-hidden">
    <Section title="Identification document"><Fields><Field name="title" title="Titre du document"><Input required value={String(form.title)} onChange={(event) => change("title", event.target.value)} /></Field><Choice name="documentType" title="Type de document" value={String(form.documentType)} setValue={(value) => change("documentType", value)} options={TYPES.map(option)} /><Choice name="category" title="Catégorie documentaire" value={String(form.category)} setValue={(value) => change("category", value)} options={CATEGORIES.map(option)} /><Field name="reference" title="Référence du document"><Input value={String(form.reference)} onChange={(event) => change("reference", event.target.value)} /></Field><Field name="documentDate" title="Date du document"><Input type="date" value={String(form.documentDate)} onChange={(event) => change("documentDate", event.target.value)} /></Field><Field name="issuer" title="Auteur ou organisme émetteur"><Input value={String(form.issuer)} onChange={(event) => change("issuer", event.target.value)} /></Field></Fields><Field name="description" title="Description"><textarea value={String(form.description)} onChange={(event) => change("description", event.target.value)} className="min-h-24 w-full min-w-0 rounded-xl border bg-dtsc-surface p-3" /></Field></Section>
    <Section title="Fichier privé">{data?.storageConfigured ? <Field name="file" title="Fichier à stocker"><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx" onChange={(event) => setFile(event.target.files?.[0] || null)} className="w-full min-w-0 rounded-xl border p-3" />{file && <span className="text-xs text-dtsc-muted">{file.name} · {Math.ceil(file.size / 1024)} Ko</span>}</Field> : <p className="rounded-xl border p-3 text-sm text-dtsc-muted">Le stockage privé Supabase n&apos;est pas configuré. Le document sera enregistré avec ses métadonnées uniquement, sans faux téléversement.</p>}</Section>
    <Section title="Classification et liaison métier"><Fields><Choice name="moduleSource" title="Module métier source" value={String(form.moduleSource)} setValue={(value) => change("moduleSource", value)} options={MODULES.map(option)} /><Choice name="linkEntityType" title="Type d'objet métier lié" value={entityType} setValue={(value) => { change("linkEntityType", value); change("linkEntityId", ""); }} options={["PharmacyProduct", "PharmacyBatch", "PharmacySupplier", "PharmacyPurchaseOrder", "PharmacyReceipt", "PharmacySale", "PharmacyPayment", "PharmacyInvoice", "PharmacyPrescription", "PharmacyInventorySession", "PharmacyReturnLossEvent", "PharmacyQualityIncident", "PharmacyAlert", "PharmacyCashSession"].map(option)} /><Choice name="linkEntityId" title="Objet métier lié" value={String(form.linkEntityId)} setValue={(value) => change("linkEntityId", value)} options={options} /><Choice name="linkRole" title="Rôle du lien" value={String(form.linkRole)} setValue={(value) => change("linkRole", value)} options={["PRIMARY", "SUPPORTING", "PROOF", "ANNEX", "RENEWAL", "HISTORY", "OTHER"].map(option)} /><Field name="tags" title="Mots-clés séparés par virgule"><Input value={String(form.tags)} onChange={(event) => change("tags", event.target.value)} /></Field><Choice name="importance" title="Importance documentaire" value={String(form.importance)} setValue={(value) => change("importance", value)} options={["NORMAL", "IMPORTANT", "CRITICAL"].map(option)} /></Fields></Section>
    <Section title="Confidentialité & accès"><Fields><Choice name="confidentialityLevel" title="Niveau de confidentialité" value={String(form.confidentialityLevel)} setValue={(value) => change("confidentialityLevel", value)} options={["INTERNAL", "DEPARTMENT_ONLY", "MANAGERS_ONLY", "RESPONSIBLE_PHARMACIST", "ADMIN_ENTERPRISE", "QUALITY_ONLY", "FINANCIAL", "VERY_CONFIDENTIAL"].map(option)} /><Check title="Permission obligatoire pour télécharger" checked={Boolean(form.downloadRequiresPermission)} setChecked={(value) => change("downloadRequiresPermission", value)} /><Check title="Auditer les téléchargements sensibles" checked={Boolean(form.sensitiveDownloadAudit)} setChecked={(value) => change("sensitiveDownloadAudit", value)} /><Check title="Visible dans les activités autorisées" checked={Boolean(form.visibleInActivities)} setChecked={(value) => change("visibleInActivities", value)} /></Fields></Section>
    <Section title="Conformité & expiration"><Fields><Check title="Document obligatoire pour la conformité" checked={Boolean(form.complianceRequired)} setChecked={(value) => change("complianceRequired", value)} /><Choice name="complianceStatus" title="Statut de conformité" value={String(form.complianceStatus)} setValue={(value) => change("complianceStatus", value)} options={["NOT_REQUIRED", "TO_VERIFY", "COMPLIANT", "NON_COMPLIANT", "EXPIRED", "TO_RENEW", "REJECTED"].map(option)} /><Field name="expiryDate" title="Date d'expiration"><Input type="date" value={String(form.expiryDate)} onChange={(event) => change("expiryDate", event.target.value)} /></Field><Check title="Renouvellement requis" checked={Boolean(form.renewalRequired)} setChecked={(value) => change("renewalRequired", value)} /><Field name="renewalDueDate" title="Échéance de renouvellement"><Input type="date" value={String(form.renewalDueDate)} onChange={(event) => change("renewalDueDate", event.target.value)} /></Field><Check title="Vérification obligatoire" checked={Boolean(form.verificationRequired)} setChecked={(value) => change("verificationRequired", value)} /></Fields></Section>
    <Section title="Notes & historique"><Field name="notes" title="Notes internes"><textarea value={String(form.notes)} onChange={(event) => change("notes", event.target.value)} className="min-h-24 w-full min-w-0 rounded-xl border bg-dtsc-surface p-3" /></Field></Section><div className="grid gap-2 sm:flex"><Button className="bg-[#002b5b] text-white">Enregistrer</Button><Button type="button" variant="outline" onClick={close}>Retour</Button></div>
  </form></Dialog>;
}

function DocumentDetail({ item, organizationId, action }: { item: DocumentItem; organizationId: string; action: (entity: string, id: string, name: string, extra?: Record<string, unknown>) => Promise<void> }) { const [reason, setReason] = useState(""); return <div className="grid min-w-0 gap-4 overflow-x-hidden"><Grid><Card title="Type" text={label(item.documentType)} /><Card title="Catégorie" text={label(item.category)} /><Card title="Confidentialité" text={label(item.confidentialityLevel)} /><Card title="Conformité" text={label(item.complianceStatus)} /></Grid><Section title="Fichier">{item.fileUrl ? <a href={`/api/enterprise/${organizationId}/pharmacy/documents/${item.id}/download`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 font-bold"><Download />Télécharger le fichier privé</a> : <p className="text-sm text-dtsc-muted">Aucun fichier n&apos;est associé; seules les métadonnées sont disponibles.</p>}</Section><Section title="Liens métier"><Grid>{item.links.map((link) => <Card key={link.id} title={label(link.entityType)} text={`${label(link.linkRole)} · ${link.entityId}`} />)}</Grid></Section><Section title="Versions"><Grid>{item.versions.map((version) => <Card key={version.id} title={`Version ${version.versionNumber}${version.isCurrent ? " · active" : ""}`} text={`${version.filename || "Métadonnées"} · ${date(version.uploadedAt)}`} />)}</Grid></Section><Section title="Validation et archivage"><Field name="reason" title="Commentaire ou motif"><Input value={reason} onChange={(event) => setReason(event.target.value)} /></Field><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void action("document", item.id, "validate", { reason })}><BadgeCheck />Valider</Button><Button variant="outline" disabled={!reason} onClick={() => void action("document", item.id, "reject", { reason })}><ShieldAlert />Rejeter</Button><Button variant="outline" disabled={!reason} onClick={() => void action("document", item.id, "archive", { reason })}>Archiver</Button><Button variant="outline" onClick={() => void action("document", item.id, "mark-not-applicable", { reason })}>Marquer non applicable</Button></div></Section></div>; }
function MissingView({ items, documents, action }: { items: Missing[]; documents: DocumentItem[]; action: (entity: string, id: string, name: string, extra?: Record<string, unknown>) => Promise<void> }) { return <Grid>{items.filter((item) => item.status === "OPEN").map((item) => <article key={item.id} className="rounded-2xl border p-4"><Badge value={item.criticality} /><h4 className="mt-2 font-black">{label(item.expectedDocumentType)}</h4><p className="text-sm text-dtsc-muted">{label(item.entityType)} · objet réel {item.entityId}</p><select className="mt-3 h-11 w-full min-w-0 rounded-xl border bg-dtsc-surface px-3" defaultValue="" onChange={(event) => { if (event.target.value) void action("missing", item.id, "resolve-missing", { documentId: event.target.value }); }}><option value="">Résoudre avec un document...</option>{documents.filter((document) => document.documentType === item.expectedDocumentType).map((document) => <option key={document.id} value={document.id}>{document.title}</option>)}</select></article>)}</Grid>; }
function AccessView({ data, action }: { data: Data | null; action: (entity: string, id: string, name: string, extra?: Record<string, unknown>) => Promise<void> }) { return <div className="grid gap-4 lg:grid-cols-2"><Section title="Règles de conformité">{(data?.rules || []).map((rule) => <div key={rule.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-black">{rule.label}</p><p className="text-xs text-dtsc-muted">{label(rule.entityType)} · {label(rule.documentType)}</p></div><Button variant="outline" onClick={() => void action("rule", rule.id, "validate", { enabled: !rule.enabled })}>{rule.enabled ? "Désactiver" : "Activer"}</Button></div>)}</Section><Section title="Confidentialité active"><Grid>{["INTERNAL", "DEPARTMENT_ONLY", "MANAGERS_ONLY", "RESPONSIBLE_PHARMACIST", "ADMIN_ENTERPRISE", "QUALITY_ONLY", "FINANCIAL", "VERY_CONFIDENTIAL"].map((level) => <Card key={level} title={label(level)} text={`${(data?.documents || []).filter((item) => item.confidentialityLevel === level).length} document(s)`} />)}</Grid></Section></div>; }
function History({ logs, documents }: { logs: AccessLog[]; documents: DocumentItem[] }) { return logs.length ? <Grid>{logs.map((log) => <Card key={log.id} title={label(log.action)} text={`${documents.find((item) => item.id === log.documentId)?.title || "Document sensible"} · ${date(log.createdAt)}`} />)}</Grid> : <p className="rounded-2xl border p-4 text-sm text-dtsc-muted">Aucun accès sensible audité n&apos;est visible avec vos permissions.</p>; }
function entityOptions(entityType: string, data: Data | null): string[][] { const map: Record<string, Opt[]> = { PharmacyProduct: data?.products || [], PharmacyBatch: data?.batches || [], PharmacySupplier: data?.suppliers || [], PharmacyPurchaseOrder: data?.orders || [], PharmacyReceipt: data?.receipts || [], PharmacySale: data?.sales || [], PharmacyPayment: data?.payments || [], PharmacyInvoice: data?.invoices || [], PharmacyPrescription: data?.prescriptions || [], PharmacyInventorySession: data?.inventories || [], PharmacyReturnLossEvent: data?.returns || [], PharmacyQualityIncident: data?.qualityIncidents || [], PharmacyAlert: data?.alerts || [], PharmacyCashSession: data?.cashSessions || [] }; return (map[entityType] || []).map((item) => [item.id, item.name || item.title || item.batchNumber || item.orderNumber || item.receiptNumber || item.saleNumber || item.paymentNumber || item.invoiceNumber || item.prescriptionNumber || item.eventNumber || item.incidentNumber || item.alertNumber || item.cashSessionNumber || "Élément"]); }
function Empty() { return <p className="rounded-2xl border p-4 text-sm text-dtsc-muted">Aucun document n&apos;est encore enregistré. Ajoutez des documents pour centraliser les ordonnances, factures, certificats, preuves de réception, documents qualité et pièces de conformité.</p>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="min-w-0 space-y-3 overflow-hidden rounded-2xl border p-3"><h4 className="font-black text-emerald-600">{title}</h4>{children}</section>; }
function Fields({ children }: { children: ReactNode }) { return <div className="grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-3">{children}</div>; }
function Grid({ children }: { children: ReactNode }) { return <div className="mt-3 grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4">{children}</div>; }
function Card({ title, text }: { title: string; text: string }) { return <article className="min-w-0 rounded-2xl border bg-dtsc-surface p-4"><p className="break-words font-black">{title}</p><p className="mt-1 break-words text-sm text-dtsc-muted">{text}</p></article>; }
function Field({ name, title, children }: { name: string; title: string; children: ReactNode }) { const help = `Renseignez ${title.toLocaleLowerCase("fr")} avec une information vérifiable.`; return <label className="grid min-w-0 gap-1"><span className="flex items-center gap-1 text-xs font-black uppercase text-dtsc-muted">{title}<span title={help} aria-label={help}><CircleHelp className="h-3.5 w-3.5" /></span></span>{children}<span className="sr-only">{name}</span></label>; }
function Choice({ name, title, value, setValue, options }: { name: string; title: string; value: string; setValue: (value: string) => void; options: string[][] }) { return <Field name={name} title={title}><select value={value} onChange={(event) => setValue(event.target.value)} className="h-11 w-full min-w-0 truncate rounded-xl border bg-dtsc-surface px-3"><option value="">Sélectionner...</option>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></Field>; }
function Check({ title, checked, setChecked }: { title: string; checked: boolean; setChecked: (value: boolean) => void }) { return <label className="flex min-w-0 items-center gap-2 text-sm font-bold"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)} />{title}<span title={`Activez uniquement si ${title.toLocaleLowerCase("fr")} est confirmé.`} aria-label={`Aide : ${title}`}><CircleHelp className="h-3.5 w-3.5" /></span></label>; }
function Badge({ value }: { value: string }) { return <span className="rounded-full bg-emerald-400/15 px-2 py-1 text-xs font-black text-emerald-700">{label(value)}</span>; }
function option(value: string) { return [value, label(value)]; }
function label(value: string) { return LABELS[value] || value.replaceAll("_", " ").toLocaleLowerCase("fr"); }
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
