"use client";

import type * as React from "react";
import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { BadgeCheck, CircleHelp, Eye, Plus, Send, ShieldAlert, Trash2 } from "lucide-react";
import { ActionMenu, type ActionMenuItem } from "@/components/ui/action-menu";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ListControls } from "@/components/ui/list-controls";
import { useSmartList } from "@/lib/hooks/use-smart-list";

import { useToastMessage } from "@/components/ui/use-toast-message";
type Opt = { id: string; name?: string; title?: string; stockUnit?: string; productId?: string; batchNumber?: string; availableQuantity?: string; purchasePrice?: string | null; orderNumber?: string; receiptNumber?: string; supplierId?: string; saleId?: string; saleNumber?: string; refundNumber?: string };
type EventItem = { id: string; eventNumber: string; eventType: string; saleId: string | null; supplierId: string | null; productId: string; batchId: string | null; quantity: string; unit: string; direction: string; itemCondition: string | null; stockDecision: string | null; reason: string; estimatedValue: string | null; criticality: string; refundRequested: boolean; status: string; stockImpactApplied: boolean; createdAt: string };
type AlertItem = { id: string; alertType: string; criticality: string; status: string; message: string; recommendedAction: string | null };
type Movement = { id: string; movementType: string; direction: string; quantity: string; reason: string; createdAt: string };
type Data = { metrics: Record<string, number>; events: EventItem[]; products: Opt[]; batches: Opt[]; sales: Opt[]; suppliers: Opt[]; orders: Opt[]; receipts: Opt[]; refunds: Opt[]; members: Opt[]; documents: Array<{ id: string; title: string; documentType: string; fileUrl: string }>; alerts: AlertItem[]; movements: Movement[] };
type Tab = "dashboard" | "customer" | "supplier" | "adjustments" | "losses" | "expired" | "recalls" | "destructions" | "validation" | "documents" | "history" | "alerts";
type FormState = Record<string, string | boolean>;

const LABELS: Record<string, string> = { CUSTOMER_RETURN: "Retour client", SUPPLIER_RETURN: "Retour fournisseur", STOCK_ADJUSTMENT: "Ajustement stock", LOSS: "Perte", DAMAGE: "Casse / dommage", EXPIRED_WITHDRAWAL: "Produit expiré retiré", RECALL_WITHDRAWAL: "Rappel / retrait de lot", DESTRUCTION: "Destruction / mise au rebut", EXCEPTIONAL_TRANSFER: "Transfert exceptionnel", DRAFT: "Brouillon", SUBMITTED: "En validation", VALIDATED: "Validé", REJECTED: "Rejeté", CANCELLED: "Annulé", IN: "Entrée stock", OUT: "Sortie stock", INTACT: "Intact / revendable", DAMAGED_PACKAGING: "Emballage endommagé", DAMAGED: "Produit endommagé", OPENED: "Produit ouvert", EXPIRED: "Produit expiré", SUSPECT: "Produit suspect", RECALLED: "Produit rappelé", NON_COMPLIANT: "Produit non conforme", RESTOCK: "Remettre en stock vendable", QUARANTINE: "Mettre en quarantaine", RETURN_SUPPLIER: "Retourner au fournisseur", DESTROY: "Détruire", ADJUST_POSITIVE: "Ajustement positif", ADJUST_NEGATIVE: "Ajustement négatif", WITHDRAW: "Retirer du stock", RECALL: "Rappeler le lot", TRANSFER: "Transférer", LOW: "Faible", MEDIUM: "Moyenne", HIGH: "Élevée", CRITICAL: "Critique", OPEN: "Ouverte", RESOLVED: "Résolue" };
const HELP: Record<string, string> = { eventType: "Nature métier de la déclaration.", saleId: "Vente réelle liée au retour client.", supplierId: "Fournisseur réel lié au retour.", productId: "Produit actif concerné.", batchId: "Lot précis dont le stock sera impacté.", quantity: "Quantité positive contrôlée côté serveur.", direction: "Sens réel du mouvement de stock.", stockDecision: "Décision appliquée lors de la validation.", reason: "Justification conservée dans les mouvements et l'audit.", criticality: "Niveau de risque utilisé pour les alertes." };
const TABS: Array<[Tab, string]> = [["dashboard", "Tableau de bord retours & pertes"], ["customer", "Retours clients"], ["supplier", "Retours fournisseurs"], ["adjustments", "Ajustements stock"], ["losses", "Pertes & casses"], ["expired", "Produits expirés retirés"], ["recalls", "Produits rappelés / retraits de lots"], ["destructions", "Destructions / mises au rebut"], ["validation", "Validations en attente"], ["documents", "Documents justificatifs"], ["history", "Historique des mouvements"], ["alerts", "Alertes retours & pertes"]];

function initial(data: Data | null): FormState { return { eventNumber: "", eventType: "CUSTOMER_RETURN", saleId: "", saleLineId: "", refundId: "", supplierId: "", purchaseOrderId: "", receiptId: "", inventorySessionId: "", inventoryLineId: "", productId: data?.products[0]?.id || "", batchId: "", targetLocationId: "", quantity: "1", unit: data?.products[0]?.stockUnit || "unité", direction: "IN", itemCondition: "INTACT", stockDecision: "RESTOCK", reason: "", estimatedValue: "", criticality: "MEDIUM", refundRequested: false, responsibleUserId: data?.members[0]?.id || "", witnessUserId: "", destructionMethod: "", destructionDate: "", notes: "" }; }

export function PharmacyReturnLossWorkspace({ organizationId }: { organizationId: string }) {
  const [data, setData] = useState<Data | null>(null), [tab, setTab] = useState<Tab>("dashboard"), [formOpen, setFormOpen] = useState(false), [form, setForm] = useState<FormState>(() => initial(null)), [detail, setDetail] = useState<EventItem | null>(null), [reason, setReason] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/returns-losses`, { cache: "no-store" }); const body = await response.json().catch(() => null) as Data | null; if (response.ok && body) setData(body); else setMessage("Chargement des retours et pertes impossible."); }, [organizationId]);
  useEffect(() => { void load(); }, [load]);
  const productMap = useMemo(() => new Map((data?.products || []).map((item) => [item.id, item.name || "Produit"])), [data]);
  const events = data?.events || [];
  const list = useSmartList({ items: events, pageSize: 12, getSearchText: useCallback((item: EventItem) => `${item.eventNumber} ${item.eventType} ${item.status} ${item.reason} ${item.criticality}`, []) });
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/returns-losses`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Déclaration enregistrée." : body?.message || "Enregistrement impossible."); if (response.ok) { setFormOpen(false); await load(); } }
  async function action(entity: string, id: string, actionName: string, actionReason = "") { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/returns-losses/${entity}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, reason: actionReason }) }); const body = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Action enregistrée." : body?.message || "Action impossible."); if (response.ok) { setDetail(null); setReason(""); await load(); } }
  const filter: Partial<Record<Tab, string[]>> = { customer: ["CUSTOMER_RETURN"], supplier: ["SUPPLIER_RETURN"], adjustments: ["STOCK_ADJUSTMENT"], losses: ["LOSS", "DAMAGE"], expired: ["EXPIRED_WITHDRAWAL"], recalls: ["RECALL_WITHDRAWAL"], destructions: ["DESTRUCTION"], validation: [] };
  const shown = tab === "validation" ? events.filter((item) => item.status === "SUBMITTED") : filter[tab] ? events.filter((item) => filter[tab]?.includes(item.eventType)) : list.paginatedItems;
  return <section className="w-full min-w-0 overflow-hidden rounded-2xl border border-dtsc-border bg-dtsc-page p-3 sm:p-4">
    <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-black">Retours, ajustements & pertes</h3><p className="text-sm text-dtsc-muted">Déclarations anormales, validation, impact stock, alertes et mouvements inverses.</p></div><Button className="w-full bg-[#002b5b] text-white sm:w-auto" onClick={() => { setForm(initial(data)); setFormOpen(true); }}><Plus />Nouvelle déclaration</Button></div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-2">{TABS.map(([code, title]) => <button key={code} type="button" onClick={() => setTab(code)} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-black ${tab === code ? "border-emerald-400 text-emerald-700" : "border-dtsc-border text-dtsc-muted"}`}>{title}</button>)}</div>
    {tab === "dashboard" ? <Metrics values={data?.metrics || {}} /> : tab === "documents" ? <Grid>{(data?.documents || []).map((item) => <a key={item.id} href={item.fileUrl} target="_blank" rel="noreferrer" className="rounded-2xl border p-4"><p className="font-black">{item.title}</p><p className="text-sm text-dtsc-muted">{label(item.documentType)}</p></a>)}</Grid> : tab === "history" ? <Grid>{(data?.movements || []).map((item) => <Card key={item.id} title={label(item.movementType)} text={`${label(item.direction)} · ${item.quantity} · ${item.reason} · ${date(item.createdAt)}`} />)}</Grid> : tab === "alerts" ? <Grid>{(data?.alerts || []).map((item) => <article key={item.id} className="rounded-2xl border p-4"><Badge value={item.criticality} /><p className="mt-2 font-black">{label(item.alertType)}</p><p className="text-sm text-dtsc-muted">{item.message}</p>{item.status !== "RESOLVED" && <Button className="mt-2" variant="outline" onClick={() => void action("alert", item.id, "resolve-alert")}><BadgeCheck />Résoudre</Button>}</article>)}</Grid> : <><ListControls query={list.query} onQueryChange={list.setQuery} page={list.page} pageCount={list.pageCount} totalCount={list.totalCount} filteredCount={list.filteredCount} onPageChange={list.setPage} placeholder="Numéro, type, motif, statut ou criticité..." /><Grid>{shown.map((item) => <EventCard key={item.id} item={item} product={productMap.get(item.productId)} actions={eventActions(item, setDetail, action)} />)}</Grid></>}

    <ReturnLossForm open={formOpen} close={() => setFormOpen(false)} form={form} setForm={setForm} data={data} save={save} />
    <Dialog open={Boolean(detail)} title={detail?.eventNumber || "Détail déclaration"} description="Validation, rejet et annulation avec audit." onClose={() => setDetail(null)} className="h-[94dvh] max-w-4xl">{detail && <Detail item={detail} product={productMap.get(detail.productId)} reason={reason} setReason={setReason} action={action} />}</Dialog>
  </section>;
}

function Metrics({ values }: { values: Record<string, number> }) { return <Grid>{[["Retours clients du jour", values.customerReturnsToday], ["Retours clients du mois", values.customerReturnsMonth], ["Retours fournisseurs ouverts", values.supplierReturnsOpen], ["Ajustements en attente", values.pendingAdjustments], ["Ajustements validés", values.validatedAdjustments], ["Pertes & casses", values.losses], ["Produits expirés retirés", values.expired], ["Lots rappelés retirés", values.recalled], ["Destructions en attente", values.destructionsPending], ["Valeur estimée des pertes", values.estimatedLossValue], ["Mouvements stock créés", values.movements], ["Alertes critiques", values.criticalAlerts], ["Validations en attente", values.pendingValidations]].map(([title, value]) => <Card key={String(title)} title={String(title)} text={String(value ?? 0)} />)}</Grid>; }
function EventCard({ item, product, actions }: { item: EventItem; product?: string; actions: ActionMenuItem[] }) { return <article className="dtsc-glass-list-item min-w-0 rounded-2xl p-4"><div className="flex justify-between gap-2"><div className="min-w-0"><Badge value={item.eventType} /><h4 className="mt-2 truncate font-black">{item.eventNumber}</h4><p className="text-xs text-dtsc-muted">{product || "Produit"} · {item.quantity} {item.unit} · {label(item.status)}</p></div><ActionMenu items={actions} /></div><p className="mt-2 text-sm text-dtsc-muted">{item.reason} · {item.stockImpactApplied ? "Stock impacté" : "Stock non impacté"}</p></article>; }
function eventActions(item: EventItem, detail: (item: EventItem) => void, action: (entity: string, id: string, name: string, reason?: string) => Promise<void>): ActionMenuItem[] { const items: ActionMenuItem[] = [{ key: "view", label: "Voir le détail", icon: Eye, onSelect: () => detail(item) }]; if (item.status === "DRAFT") items.push({ key: "submit", label: "Soumettre", icon: Send, onSelect: () => void action("event", item.id, "submit") }); if (item.status === "SUBMITTED") items.push({ key: "validate", label: "Valider et appliquer", icon: BadgeCheck, onSelect: () => void action("event", item.id, "validate") }); return items; }
function Detail({ item, product, reason, setReason, action }: { item: EventItem; product?: string; reason: string; setReason: (value: string) => void; action: (entity: string, id: string, name: string, reason?: string) => Promise<void> }) { return <div className="grid gap-4"><Grid><Card title="Produit" text={product || "Produit"} /><Card title="Type" text={label(item.eventType)} /><Card title="Quantité" text={`${item.quantity} ${item.unit}`} /><Card title="Décision stock" text={label(item.stockDecision || "OTHER")} /></Grid><Section title="Motif contrôlé"><Field name="reason" labelText="Motif de rejet ou annulation"><Input value={reason} onChange={(event) => setReason(event.target.value)} /></Field><div className="flex flex-wrap gap-2">{item.status === "SUBMITTED" && <Button variant="outline" disabled={!reason} onClick={() => void action("event", item.id, "reject", reason)}><ShieldAlert />Rejeter</Button>}{!["CANCELLED", "REJECTED"].includes(item.status) && <Button variant="outline" disabled={!reason} onClick={() => void action("event", item.id, "cancel", reason)}><Trash2 />Annuler avec mouvement inverse</Button>}</div></Section></div>; }

function ReturnLossForm({ open, close, form, setForm, data, save }: { open: boolean; close: () => void; form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>>; data: Data | null; save: (event: FormEvent) => Promise<void> }) {
  const change = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const productId = String(form.productId); const supplierId = String(form.supplierId); const saleId = String(form.saleId);
  return <Dialog open={open} title="Nouvelle déclaration retours, ajustements ou pertes" description="Formulaire plein écran avec références réelles de la pharmacie." onClose={close} className="h-[96dvh] max-w-6xl"><form onSubmit={save} className="grid min-w-0 gap-4 overflow-x-hidden">
    <Section title="Nature et références"><Fields><Choice name="eventType" labelText="Type de déclaration" value={String(form.eventType)} setValue={(value) => change("eventType", value)} options={["CUSTOMER_RETURN", "SUPPLIER_RETURN", "STOCK_ADJUSTMENT", "LOSS", "DAMAGE", "EXPIRED_WITHDRAWAL", "RECALL_WITHDRAWAL", "DESTRUCTION", "EXCEPTIONAL_TRANSFER"].map((value) => [value, label(value)])} /><Choice name="saleId" labelText="Vente liée" value={saleId} setValue={(value) => change("saleId", value)} options={(data?.sales || []).map((item) => [item.id, item.saleNumber || "Vente"])} /><Choice name="supplierId" labelText="Fournisseur lié" value={supplierId} setValue={(value) => change("supplierId", value)} options={(data?.suppliers || []).map((item) => [item.id, item.name || "Fournisseur"])} /><Choice name="purchaseOrderId" labelText="Commande fournisseur" value={String(form.purchaseOrderId)} setValue={(value) => change("purchaseOrderId", value)} options={(data?.orders || []).filter((item) => !supplierId || item.supplierId === supplierId).map((item) => [item.id, item.orderNumber || "Commande"])} /><Choice name="receiptId" labelText="Réception fournisseur" value={String(form.receiptId)} setValue={(value) => change("receiptId", value)} options={(data?.receipts || []).filter((item) => !supplierId || item.supplierId === supplierId).map((item) => [item.id, item.receiptNumber || "Réception"])} /><Choice name="refundId" labelText="Remboursement lié" value={String(form.refundId)} setValue={(value) => change("refundId", value)} options={(data?.refunds || []).filter((item) => !saleId || item.saleId === saleId).map((item) => [item.id, item.refundNumber || "Remboursement"])} /></Fields></Section>
    <Section title="Produit, lot et quantité"><Fields><Choice name="productId" labelText="Produit" value={productId} setValue={(value) => { const product = data?.products.find((item) => item.id === value); change("productId", value); change("batchId", ""); if (product) change("unit", product.stockUnit || "unité"); }} options={(data?.products || []).map((item) => [item.id, item.name || "Produit"])} /><Choice name="batchId" labelText="Lot concerné" value={String(form.batchId)} setValue={(value) => { const batch = data?.batches.find((item) => item.id === value); change("batchId", value); if (batch?.purchasePrice) change("estimatedValue", String(Number(batch.purchasePrice) * Number(form.quantity))); }} options={(data?.batches || []).filter((item) => item.productId === productId).map((item) => [item.id, `${item.batchNumber} · stock ${item.availableQuantity}`])} /><Field name="quantity" labelText="Quantité concernée"><Input required type="number" min="0.001" step="any" value={String(form.quantity)} onChange={(event) => change("quantity", event.target.value)} /></Field><Choice name="direction" labelText="Sens du mouvement" value={String(form.direction)} setValue={(value) => change("direction", value)} options={["IN", "OUT"].map((value) => [value, label(value)])} /><Choice name="itemCondition" labelText="État du produit" value={String(form.itemCondition)} setValue={(value) => change("itemCondition", value)} options={["INTACT", "DAMAGED_PACKAGING", "DAMAGED", "OPENED", "EXPIRED", "SUSPECT", "RECALLED", "NON_COMPLIANT", "OTHER"].map((value) => [value, label(value)])} /><Choice name="stockDecision" labelText="Décision stock" value={String(form.stockDecision)} setValue={(value) => change("stockDecision", value)} options={["RESTOCK", "QUARANTINE", "RETURN_SUPPLIER", "DESTROY", "ADJUST_POSITIVE", "ADJUST_NEGATIVE", "WITHDRAW", "RECALL", "TRANSFER"].map((value) => [value, label(value)])} /></Fields></Section>
    <Section title="Justification et validation"><Fields><Field name="reason" labelText="Motif détaillé"><Input required value={String(form.reason)} onChange={(event) => change("reason", event.target.value)} /></Field><Choice name="criticality" labelText="Criticité" value={String(form.criticality)} setValue={(value) => change("criticality", value)} options={["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((value) => [value, label(value)])} /><Choice name="responsibleUserId" labelText="Responsable" value={String(form.responsibleUserId)} setValue={(value) => change("responsibleUserId", value)} options={(data?.members || []).map((item) => [item.id, item.name || "Collaborateur"])} /><Choice name="witnessUserId" labelText="Témoin" value={String(form.witnessUserId)} setValue={(value) => change("witnessUserId", value)} options={(data?.members || []).map((item) => [item.id, item.name || "Collaborateur"])} /><Field name="estimatedValue" labelText="Valeur estimée"><Input type="number" min="0" value={String(form.estimatedValue)} onChange={(event) => change("estimatedValue", event.target.value)} /></Field><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={Boolean(form.refundRequested)} onChange={(event) => change("refundRequested", event.target.checked)} />Demander un remboursement via le module Caisse</label></Fields></Section>
    <Section title="Notes et documents"><Field name="notes" labelText="Notes internes"><textarea value={String(form.notes)} onChange={(event) => change("notes", event.target.value)} className="min-h-24 w-full rounded-xl border bg-dtsc-surface p-3" /></Field><p className="text-sm text-dtsc-muted">Les justificatifs passent par le stockage documentaire privé; aucun faux téléversement n&apos;est proposé.</p></Section><div className="grid gap-2 sm:flex"><Button className="bg-[#002b5b] text-white">Enregistrer en brouillon</Button><Button type="button" variant="outline" onClick={close}>Retour</Button></div>
  </form></Dialog>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="min-w-0 space-y-3 overflow-hidden rounded-2xl border p-3"><h4 className="font-black text-emerald-600">{title}</h4>{children}</section>; }
function Fields({ children }: { children: ReactNode }) { return <div className="grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-3">{children}</div>; }
function Grid({ children }: { children: ReactNode }) { return <div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4">{children}</div>; }
function Card({ title, text }: { title: string; text: string }) { return <article className="min-w-0 rounded-2xl border bg-dtsc-surface p-4"><p className="break-words font-black">{title}</p><p className="mt-1 break-words text-sm text-dtsc-muted">{text}</p></article>; }
function Help({ text }: { text: string }) { return <span title={text} aria-label={text}><CircleHelp className="h-3.5 w-3.5" /></span>; }
function Field({ name, labelText, children }: { name: string; labelText: string; children: ReactNode }) { return <label className="grid min-w-0 gap-1"><span className="flex items-center gap-1 text-xs font-black uppercase text-dtsc-muted">{labelText}<Help text={HELP[name] || `Renseignez ${labelText.toLocaleLowerCase("fr")} pour compléter la déclaration.`} /></span>{children}</label>; }
function Choice({ name, labelText, value, setValue, options }: { name: string; labelText: string; value: string; setValue: (value: string) => void; options: string[][] }) { return <Field name={name} labelText={labelText}><select value={value} onChange={(event) => setValue(event.target.value)} className="h-11 w-full min-w-0 truncate rounded-xl border bg-dtsc-surface px-3"><option value="">Sélectionner...</option>{options.map(([id, title]) => <option key={id} value={id}>{title}</option>)}</select></Field>; }
function Badge({ value }: { value: string }) { return <span className="rounded-full bg-emerald-400/15 px-2 py-1 text-xs font-black text-emerald-700">{label(value)}</span>; }
function label(value: string) { return LABELS[value] || value.replaceAll("_", " ").toLocaleLowerCase("fr"); }
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(value)); }
