"use client";

import type * as React from "react";
import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { BadgeCheck, CircleHelp, Eye, FileText, Plus, ReceiptText, Send, ShieldAlert, WalletCards } from "lucide-react";
import { ActionMenu, type ActionMenuItem } from "@/components/ui/action-menu";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ListControls } from "@/components/ui/list-controls";
import { useSmartList } from "@/lib/hooks/use-smart-list";

import { useToastMessage } from "@/components/ui/use-toast-message";
type Option = { id: string; name?: string; labelFr?: string };
type CashSession = { id: string; cashSessionNumber: string; cashPointName: string | null; cashPointType: string | null; cashierId: string; openedAt: string; closedAt: string | null; openingAmount: string; currency: string; theoreticalCashAmount: string | null; countedCashAmount: string | null; totalPayments: string | null; totalRefunds: string | null; varianceAmount: string | null; varianceCriticity: string | null; varianceJustification: string | null; status: string; discrepancies: Discrepancy[] };
type Payment = { id: string; paymentNumber: string; saleId: string | null; invoiceId: string | null; cashSessionId: string | null; cashierId: string; paymentMethod: string; amount: string; currency: string; paymentReference: string | null; paymentDate: string; status: string };
type Invoice = { id: string; invoiceNumber: string; saleId: string | null; customerName: string | null; invoiceDate: string; totalAmount: string; paidAmount: string; remainingAmount: string; currency: string; status: string };
type ReceiptDocument = { id: string; receiptNumber: string; saleId: string | null; paymentId: string | null; amount: string; paymentMethod: string | null; generatedAt: string; status: string };
type Refund = { id: string; refundNumber: string; saleId: string; paymentId: string | null; cashSessionId: string | null; refundType: string; amount: string; currency: string; reason: string; restockItems: boolean; status: string; createdAt: string };
type Discrepancy = { id: string; cashSessionId: string; cashierId: string; discrepancyType: string; theoreticalAmount: string; countedAmount: string; varianceAmount: string; criticity: string; justification: string | null; status: string };
type Sale = { id: string; saleNumber: string; customerName: string | null; totalAmount: string; paidAmount: string; remainingAmount: string; paymentStatus: string; cashierId: string; cashSessionId: string | null; saleDate: string };
type Dataset = { metrics: Record<string, number>; sessions: CashSession[]; payments: Payment[]; invoices: Invoice[]; receipts: ReceiptDocument[]; refunds: Refund[]; discrepancies: Discrepancy[]; sales: Sale[]; members: Option[]; departments: Option[] };
type Tab = "dashboard" | "sessions" | "open" | "collections" | "payments" | "invoices" | "receipts" | "refunds" | "close" | "discrepancies" | "validation" | "history" | "reports";
type FormKind = "session" | "payment" | "refund";
type CashForm = Record<string, string | boolean> & { entityType: FormKind };

const LABELS: Record<string, string> = { OPEN: "Ouverte", CLOSING: "En clôture", CLOSED: "Clôturée", PENDING_VALIDATION: "En validation", VALIDATED: "Validée", REJECTED: "Rejetée", CANCELLED: "Annulée", ARCHIVED: "Archivée", PAID: "Payé", PARTIALLY_PAID: "Partiellement payé", UNPAID: "Non payé", GENERATED: "Généré", SUBMITTED: "Soumis", CASH: "Espèces", MOBILE_MONEY: "Mobile Money", CARD: "Carte", TRANSFER: "Virement", CREDIT: "Crédit client", INSURANCE: "Assurance / prise en charge", VOUCHER: "Bon / coupon", OTHER: "Autre", MAIN_COUNTER: "Comptoir principal", SECONDARY_COUNTER: "Comptoir secondaire", INTERNAL_PHARMACY: "Pharmacie interne", MOBILE_CASH: "Caisse mobile", EMERGENCY_CASH: "Caisse urgence", TOTAL: "Remboursement total", PARTIAL: "Remboursement partiel", CASH_ERROR: "Erreur caisse", RETURN_RESTOCK: "Retour avec remise en stock", RETURN_NO_RESTOCK: "Retour sans remise en stock", SALE_CANCELLATION: "Annulation vente", COMMERCIAL_GESTURE: "Geste commercial", CASH_SHORTAGE: "Manquant cash", CASH_SURPLUS: "Surplus cash", LOW: "Faible", MEDIUM: "Moyenne", HIGH: "Élevée", CRITICAL: "Critique", RESOLVED: "Résolu" };
const HELP: Record<string, string> = { cashierId: "Collaborateur actif responsable de la caisse ou du paiement.", cashSessionId: "Session ouverte qui reçoit cet encaissement.", openingAmount: "Montant cash physiquement présent lors de l'ouverture.", countedCashAmount: "Montant cash réellement compté lors de la clôture.", saleId: "Vente de la pharmacie à encaisser ou rembourser.", paymentMethod: "Moyen réellement utilisé par le payeur.", amount: "Montant positif contrôlé côté serveur.", reason: "Motif obligatoire et conservé dans l'audit." };
const TABS: Array<[Tab, string]> = [["dashboard", "Tableau de bord caisse"], ["sessions", "Sessions de caisse"], ["open", "Ouverture de caisse"], ["collections", "Encaissements"], ["payments", "Paiements"], ["invoices", "Factures"], ["receipts", "Reçus"], ["refunds", "Remboursements"], ["close", "Clôture de caisse"], ["discrepancies", "Écarts de caisse"], ["validation", "Validation de clôture"], ["history", "Historique caisse"], ["reports", "Rapports caisse"]];

function initialForm(kind: FormKind, data: Dataset | null): CashForm {
  const today = new Date().toISOString().slice(0, 10);
  return { entityType: kind, cashSessionNumber: "", cashPointName: "", cashPointType: "MAIN_COUNTER", cashierId: data?.members[0]?.id || "", departmentId: "", financialAccountId: "", openedAt: today, openingAmount: "0", currency: "USD", notes: "", saleId: "", invoiceId: "", cashSessionId: data?.sessions.find((item) => item.status === "OPEN")?.id || "", paymentMethod: "CASH", amount: "", paymentReference: "", payerName: "", payerPhone: "", paymentDate: today, paymentId: "", refundType: "PARTIAL", reason: "", restockItems: false };
}

export function PharmacyCashWorkspace({ organizationId }: { organizationId: string }) {
  const [data, setData] = useState<Dataset | null>(null), [tab, setTab] = useState<Tab>("dashboard"), [formOpen, setFormOpen] = useState(false), [kind, setKind] = useState<FormKind>("session"), [form, setForm] = useState<CashForm>(() => initialForm("session", null)), [detail, setDetail] = useState<CashSession | Payment | null>(null), [counted, setCounted] = useState("0"), [reason, setReason] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/cash`, { cache: "no-store" }); const body = await response.json().catch(() => null) as Dataset | null; if (response.ok && body) setData(body); else setMessage("Chargement de la caisse impossible."); }, [organizationId]);
  useEffect(() => { void load(); }, [load]);
  const memberMap = useMemo(() => new Map((data?.members || []).map((item) => [item.id, item.name || "Collaborateur"])), [data]);
  const saleMap = useMemo(() => new Map((data?.sales || []).map((item) => [item.id, item.saleNumber])), [data]);
  const sessionList = useSmartList({ items: data?.sessions || [], pageSize: 12, getSearchText: useCallback((item: CashSession) => `${item.cashSessionNumber} ${item.cashPointName || ""} ${item.status}`, []) });
  const paymentList = useSmartList({ items: data?.payments || [], pageSize: 12, getSearchText: useCallback((item: Payment) => `${item.paymentNumber} ${item.paymentMethod} ${item.status} ${item.paymentReference || ""}`, []) });
  function open(next: FormKind) { setKind(next); setForm(initialForm(next, data)); setFormOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/cash`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Opération de caisse enregistrée." : body?.message || "Enregistrement impossible."); if (response.ok) { setFormOpen(false); await load(); } }
  async function action(entity: string, id: string, actionName: string, extra: Record<string, unknown> = {}) { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/cash/${entity}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, ...extra }) }); const body = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Action de caisse enregistrée." : body?.message || "Action impossible."); if (response.ok) { setDetail(null); setReason(""); await load(); } }
  const sessions = data?.sessions || [], payments = data?.payments || [];
  return <section className="w-full min-w-0 overflow-hidden rounded-2xl border border-dtsc-border bg-dtsc-page p-3 sm:p-4">
    <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-black text-dtsc-ink">Caisse, factures & paiements</h3><p className="text-sm text-dtsc-muted">Encaissements, clôtures, écarts, factures, reçus et remboursements auditables.</p></div><div className="grid w-full gap-2 sm:flex sm:w-auto"><Button variant="outline" onClick={() => open("session")}><Plus />Ouvrir une caisse</Button><Button className="bg-[#002b5b] text-white" onClick={() => open("payment")}><WalletCards />Nouveau paiement</Button></div></div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-2">{TABS.map(([code, title]) => <button key={code} type="button" onClick={() => code === "open" ? open("session") : setTab(code)} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-black ${tab === code ? "border-emerald-400 text-emerald-700" : "border-dtsc-border text-dtsc-muted"}`}>{title}</button>)}</div>
    {tab === "dashboard" ? <Metrics values={data?.metrics || {}} /> : tab === "sessions" || tab === "close" || tab === "validation" ? <><ListControls query={sessionList.query} onQueryChange={sessionList.setQuery} page={sessionList.page} pageCount={sessionList.pageCount} totalCount={sessionList.totalCount} filteredCount={sessionList.filteredCount} onPageChange={sessionList.setPage} placeholder="Numéro, point de vente ou statut..." /><Grid>{sessionList.paginatedItems.filter((item) => tab === "close" ? item.status === "OPEN" : tab === "validation" ? item.status === "PENDING_VALIDATION" : true).map((item) => <SessionCard key={item.id} item={item} cashier={memberMap.get(item.cashierId)} actions={sessionActions(item, setDetail, action)} />)}</Grid></> : tab === "payments" || tab === "collections" ? <><div className="mb-3 flex flex-wrap gap-2"><Button variant="outline" onClick={() => open("payment")}><Plus />Enregistrer un paiement</Button></div><ListControls query={paymentList.query} onQueryChange={paymentList.setQuery} page={paymentList.page} pageCount={paymentList.pageCount} totalCount={paymentList.totalCount} filteredCount={paymentList.filteredCount} onPageChange={paymentList.setPage} placeholder="Numéro, mode ou référence..." /><Grid>{paymentList.paginatedItems.map((item) => <PaymentCard key={item.id} item={item} sale={item.saleId ? saleMap.get(item.saleId) : undefined} actions={paymentActions(item, setDetail, action)} />)}</Grid></> : tab === "invoices" ? <Grid>{(data?.invoices || []).map((item) => <Card key={item.id} title={item.invoiceNumber} text={`${item.customerName || "Client non renseigné"} · ${item.totalAmount} ${item.currency} · ${label(item.status)} · reste ${item.remainingAmount}`} />)}</Grid> : tab === "receipts" ? <Grid>{(data?.receipts || []).map((item) => <Card key={item.id} title={item.receiptNumber} text={`${item.amount} · ${label(item.paymentMethod || "OTHER")} · ${label(item.status)} · ${date(item.generatedAt)}`} />)}</Grid> : tab === "refunds" ? <><Button className="mb-3" variant="outline" onClick={() => open("refund")}><Plus />Demander un remboursement</Button><Grid>{(data?.refunds || []).map((item) => <RefundCard key={item.id} item={item} sale={saleMap.get(item.saleId)} actions={refundActions(item, action)} />)}</Grid></> : tab === "discrepancies" ? <Grid>{(data?.discrepancies || []).map((item) => <DiscrepancyCard key={item.id} item={item} action={action} />)}</Grid> : tab === "reports" ? <ReportView data={data} /> : <Grid>{[...sessions.map((item) => ({ id: `s-${item.id}`, title: item.cashSessionNumber, text: `${label(item.status)} · ${date(item.openedAt)}` })), ...payments.map((item) => ({ id: `p-${item.id}`, title: item.paymentNumber, text: `${label(item.paymentMethod)} · ${item.amount} ${item.currency}` }))].map((item) => <Card key={item.id} title={item.title} text={item.text} />)}</Grid>}

    <CashFormDialog open={formOpen} close={() => setFormOpen(false)} kind={kind} form={form} setForm={setForm} data={data} save={save} />
    <Dialog open={Boolean(detail)} title={detail && "cashSessionNumber" in detail ? detail.cashSessionNumber : detail && "paymentNumber" in detail ? detail.paymentNumber : "Détail caisse"} description="Actions contrôlées et historisées." onClose={() => setDetail(null)} className="h-[94dvh] max-w-4xl">{detail && "cashSessionNumber" in detail ? <SessionDetail item={detail} counted={counted} setCounted={setCounted} reason={reason} setReason={setReason} action={action} /> : detail && <PaymentDetail item={detail} reason={reason} setReason={setReason} action={action} />}</Dialog>
  </section>;
}

function Metrics({ values }: { values: Record<string, number> }) { const cards = [["Caisse ouverte", values.cashOpen ? "Oui" : "Non"], ["Sessions ouvertes", values.openSessions], ["Ventes encaissées aujourd'hui", values.paidSalesToday], ["Total encaissé aujourd'hui", values.paidToday], ["Espèces", values.cash], ["Mobile Money", values.mobileMoney], ["Carte", values.card], ["Crédit", values.credit], ["Assurance", values.insurance], ["Ventes partielles", values.partialSales], ["Ventes non payées", values.unpaidSales], ["Remboursements du jour", values.refundsToday], ["Factures générées", values.invoices], ["Reçus générés", values.receipts], ["Écarts ouverts", values.openDiscrepancies], ["Clôtures à valider", values.pendingClosures]]; return <Grid>{cards.map(([title, value]) => <Card key={String(title)} title={String(title)} text={String(value ?? 0)} />)}</Grid>; }
function SessionCard({ item, cashier, actions }: { item: CashSession; cashier?: string; actions: ActionMenuItem[] }) { return <article className="dtsc-glass-list-item min-w-0 rounded-2xl p-4"><div className="flex justify-between gap-2"><div className="min-w-0"><Badge value={item.status} /><h4 className="mt-2 truncate font-black">{item.cashSessionNumber}</h4><p className="text-xs text-dtsc-muted">{cashier || "Caissier"} · {item.cashPointName || label(item.cashPointType || "OTHER")}</p></div><ActionMenu items={actions} /></div><p className="mt-2 text-xs text-dtsc-muted">Ouverture {item.openingAmount} {item.currency} · paiements {item.totalPayments || "0"} · écart {item.varianceAmount || "0"}</p></article>; }
function PaymentCard({ item, sale, actions }: { item: Payment; sale?: string; actions: ActionMenuItem[] }) { return <article className="dtsc-glass-list-item min-w-0 rounded-2xl p-4"><div className="flex justify-between gap-2"><div><Badge value={item.paymentMethod} /><h4 className="mt-2 font-black">{item.paymentNumber}</h4><p className="text-xs text-dtsc-muted">{sale || "Paiement sans vente"} · {date(item.paymentDate)}</p></div><ActionMenu items={actions} /></div><p className="mt-2 font-black">{item.amount} {item.currency} · {label(item.status)}</p></article>; }
function RefundCard({ item, sale, actions }: { item: Refund; sale?: string; actions: ActionMenuItem[] }) { return <article className="rounded-2xl border p-4"><div className="flex justify-between gap-2"><div><Badge value={item.status} /><h4 className="mt-2 font-black">{item.refundNumber}</h4><p className="text-xs text-dtsc-muted">{sale || "Vente"} · {label(item.refundType)}</p></div><ActionMenu items={actions} /></div><p className="mt-2 text-sm">{item.amount} {item.currency} · {item.reason}</p></article>; }
function DiscrepancyCard({ item, action }: { item: Discrepancy; action: (entity: string, id: string, name: string, extra?: Record<string, unknown>) => Promise<void> }) { return <article className="rounded-2xl border p-4"><Badge value={item.criticity} /><h4 className="mt-2 font-black">{label(item.discrepancyType)}</h4><p className="text-sm text-dtsc-muted">Théorique {item.theoreticalAmount} · compté {item.countedAmount} · écart {item.varianceAmount}</p>{item.status !== "RESOLVED" && <Button className="mt-2" variant="outline" onClick={() => void action("discrepancy", item.id, "resolve-discrepancy")}><BadgeCheck />Résoudre</Button>}</article>; }
function ReportView({ data }: { data: Dataset | null }) { return <Grid><Card title="Rapport paiements" text={`${data?.payments.length || 0} paiement(s) enregistrés`} /><Card title="Rapport clôtures" text={`${data?.sessions.filter((item) => item.status === "VALIDATED").length || 0} clôture(s) validée(s)`} /><Card title="Rapport remboursements" text={`${data?.refunds.length || 0} remboursement(s)`} /><Card title="Rapport écarts" text={`${data?.discrepancies.length || 0} écart(s) auditable(s)`} /></Grid>; }

function sessionActions(item: CashSession, detail: (item: CashSession) => void, action: (entity: string, id: string, name: string) => Promise<void>): ActionMenuItem[] { const items: ActionMenuItem[] = [{ key: "view", label: "Voir le détail", icon: Eye, onSelect: () => detail(item) }]; if (item.status === "CLOSED") items.push({ key: "submit", label: "Soumettre à validation", icon: Send, onSelect: () => void action("session", item.id, "submit-validation") }); if (item.status === "PENDING_VALIDATION") items.push({ key: "validate", label: "Valider la clôture", icon: BadgeCheck, onSelect: () => void action("session", item.id, "validate") }); return items; }
function paymentActions(item: Payment, detail: (item: Payment) => void, action: (entity: string, id: string, name: string) => Promise<void>): ActionMenuItem[] { const saleId = typeof item.saleId === "string" ? item.saleId : undefined; return [{ key: "view", label: "Voir le détail", icon: Eye, onSelect: () => detail(item) }, { key: "receipt", label: "Générer le reçu", icon: ReceiptText, onSelect: () => void action("payment", item.id, "generate-receipt") }, ...(saleId ? [{ key: "invoice", label: "Générer la facture", icon: FileText, onSelect: () => void action("sale", saleId, "generate-invoice") }] : [])]; }
function refundActions(item: Refund, action: (entity: string, id: string, name: string) => Promise<void>): ActionMenuItem[] { const items: ActionMenuItem[] = []; if (item.status === "SUBMITTED") items.push({ key: "validate", label: "Valider", icon: BadgeCheck, onSelect: () => void action("refund", item.id, "validate-refund") }); if (item.status === "VALIDATED") items.push({ key: "paid", label: "Marquer remboursé", icon: WalletCards, onSelect: () => void action("refund", item.id, "mark-refund-paid") }); return items; }

function SessionDetail({ item, counted, setCounted, reason, setReason, action }: { item: CashSession; counted: string; setCounted: (value: string) => void; reason: string; setReason: (value: string) => void; action: (entity: string, id: string, name: string, extra?: Record<string, unknown>) => Promise<void> }) { return <div className="grid min-w-0 gap-4"><Grid><Card title="Solde initial" text={`${item.openingAmount} ${item.currency}`} /><Card title="Solde théorique" text={`${item.theoreticalCashAmount || "Calculé à la clôture"} ${item.currency}`} /><Card title="Solde compté" text={`${item.countedCashAmount || "Non compté"} ${item.currency}`} /><Card title="Écart" text={`${item.varianceAmount || "0"} · ${label(item.varianceCriticity || "LOW")}`} /></Grid>{item.status === "OPEN" && <Section title="Clôture de caisse"><Fields><Field name="countedCashAmount" labelText="Cash compté"><Input type="number" min="0" value={counted} onChange={(event) => setCounted(event.target.value)} /></Field><Field name="reason" labelText="Justification d'écart"><Input value={reason} onChange={(event) => setReason(event.target.value)} /></Field></Fields><Button onClick={() => void action("session", item.id, "close", { countedCashAmount: Number(counted), varianceJustification: reason })}>Clôturer la caisse</Button></Section>}{item.status === "PENDING_VALIDATION" && <Section title="Validation responsable"><Field name="reason" labelText="Motif de rejet"><Input value={reason} onChange={(event) => setReason(event.target.value)} /></Field><div className="flex flex-wrap gap-2"><Button onClick={() => void action("session", item.id, "validate")}><BadgeCheck />Valider</Button><Button variant="outline" disabled={!reason} onClick={() => void action("session", item.id, "reject", { reason })}><ShieldAlert />Rejeter</Button></div></Section>}</div>; }
function PaymentDetail({ item, reason, setReason, action }: { item: Payment; reason: string; setReason: (value: string) => void; action: (entity: string, id: string, name: string, extra?: Record<string, unknown>) => Promise<void> }) { return <div className="grid gap-4"><Grid><Card title="Montant" text={`${item.amount} ${item.currency}`} /><Card title="Mode" text={label(item.paymentMethod)} /><Card title="Statut" text={label(item.status)} /><Card title="Référence" text={item.paymentReference || "Non renseignée"} /></Grid>{item.status === "PAID" && <Section title="Annulation contrôlée"><Field name="reason" labelText="Motif obligatoire"><Input value={reason} onChange={(event) => setReason(event.target.value)} /></Field><Button variant="outline" disabled={!reason} onClick={() => void action("payment", item.id, "cancel-payment", { reason })}>Annuler le paiement</Button></Section>}</div>; }

function CashFormDialog({ open, close, kind, form, setForm, data, save }: { open: boolean; close: () => void; kind: FormKind; form: CashForm; setForm: React.Dispatch<React.SetStateAction<CashForm>>; data: Dataset | null; save: (event: FormEvent) => Promise<void> }) {
  const change = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  return <Dialog open={open} title={kind === "session" ? "Ouverture de caisse" : kind === "payment" ? "Nouvel encaissement" : "Demande de remboursement"} description="Formulaire plein écran isolé dans la pharmacie active." onClose={close} className="h-[96dvh] max-w-6xl"><form onSubmit={save} className="grid min-w-0 gap-4 overflow-x-hidden">
    {kind === "session" && <><Section title="Informations caisse"><Fields><Field name="cashSessionNumber" labelText="Numéro de session"><Input value={String(form.cashSessionNumber)} onChange={(event) => change("cashSessionNumber", event.target.value)} placeholder="Généré automatiquement si vide" /></Field><Field name="cashPointName" labelText="Nom du point de vente"><Input value={String(form.cashPointName)} onChange={(event) => change("cashPointName", event.target.value)} /></Field><Choice name="cashPointType" labelText="Type de point de vente" value={String(form.cashPointType)} setValue={(value) => change("cashPointType", value)} options={["MAIN_COUNTER", "SECONDARY_COUNTER", "INTERNAL_PHARMACY", "MOBILE_CASH", "EMERGENCY_CASH", "OTHER"].map((value) => [value, label(value)])} /><Choice name="cashierId" labelText="Caissier" value={String(form.cashierId)} setValue={(value) => change("cashierId", value)} options={(data?.members || []).map((item) => [item.id, item.name || "Collaborateur"])} /><Choice name="departmentId" labelText="Département ou service" value={String(form.departmentId)} setValue={(value) => change("departmentId", value)} options={(data?.departments || []).map((item) => [item.id, item.labelFr || "Département"])} /><Field name="openingAmount" labelText="Solde initial"><Input required type="number" min="0" value={String(form.openingAmount)} onChange={(event) => change("openingAmount", event.target.value)} /></Field><Choice name="currency" labelText="Devise" value={String(form.currency)} setValue={(value) => change("currency", value)} options={["USD", "CDF", "EUR"].map((value) => [value, value])} /></Fields></Section></>}
    {kind === "payment" && <><Section title="Vente et session liées"><Fields><Choice name="saleId" labelText="Vente à encaisser" value={String(form.saleId)} setValue={(value) => change("saleId", value)} options={(data?.sales || []).filter((item) => Number(item.remainingAmount) > 0).map((item) => [item.id, `${item.saleNumber} · reste ${item.remainingAmount}`])} /><Choice name="cashSessionId" labelText="Session de caisse ouverte" value={String(form.cashSessionId)} setValue={(value) => change("cashSessionId", value)} options={(data?.sessions || []).filter((item) => item.status === "OPEN").map((item) => [item.id, item.cashSessionNumber])} /><Choice name="cashierId" labelText="Caissier" value={String(form.cashierId)} setValue={(value) => change("cashierId", value)} options={(data?.members || []).map((item) => [item.id, item.name || "Collaborateur"])} /></Fields></Section><Section title="Paiement"><Fields><Choice name="paymentMethod" labelText="Mode de paiement" value={String(form.paymentMethod)} setValue={(value) => change("paymentMethod", value)} options={["CASH", "MOBILE_MONEY", "CARD", "TRANSFER", "CREDIT", "INSURANCE", "VOUCHER", "OTHER"].map((value) => [value, label(value)])} /><Field name="amount" labelText="Montant encaissé"><Input required type="number" min="0.01" step="any" value={String(form.amount)} onChange={(event) => change("amount", event.target.value)} /></Field><Choice name="currency" labelText="Devise" value={String(form.currency)} setValue={(value) => change("currency", value)} options={["USD", "CDF", "EUR"].map((value) => [value, value])} /><Field name="paymentReference" labelText="Référence du paiement"><Input value={String(form.paymentReference)} onChange={(event) => change("paymentReference", event.target.value)} /></Field></Fields></Section></>}
    {kind === "refund" && <Section title="Remboursement contrôlé"><Fields><Choice name="saleId" labelText="Vente concernée" value={String(form.saleId)} setValue={(value) => change("saleId", value)} options={(data?.sales || []).filter((item) => Number(item.paidAmount) > 0).map((item) => [item.id, `${item.saleNumber} · payé ${item.paidAmount}`])} /><Choice name="paymentId" labelText="Paiement concerné" value={String(form.paymentId)} setValue={(value) => change("paymentId", value)} options={(data?.payments || []).filter((item) => !form.saleId || item.saleId === form.saleId).map((item) => [item.id, `${item.paymentNumber} · ${item.amount}`])} /><Choice name="cashSessionId" labelText="Session de remboursement" value={String(form.cashSessionId)} setValue={(value) => change("cashSessionId", value)} options={(data?.sessions || []).filter((item) => item.status === "OPEN").map((item) => [item.id, item.cashSessionNumber])} /><Choice name="refundType" labelText="Type de remboursement" value={String(form.refundType)} setValue={(value) => change("refundType", value)} options={["TOTAL", "PARTIAL", "CASH_ERROR", "RETURN_RESTOCK", "RETURN_NO_RESTOCK", "SALE_CANCELLATION", "COMMERCIAL_GESTURE", "OTHER"].map((value) => [value, label(value)])} /><Field name="amount" labelText="Montant à rembourser"><Input required type="number" min="0.01" value={String(form.amount)} onChange={(event) => change("amount", event.target.value)} /></Field><Field name="reason" labelText="Motif obligatoire"><Input required value={String(form.reason)} onChange={(event) => change("reason", event.target.value)} /></Field><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={Boolean(form.restockItems)} onChange={(event) => change("restockItems", event.target.checked)} />Remettre les produits en stock via le workflow ventes</label></Fields></Section>}
    <Section title="Notes"><Field name="notes" labelText="Notes internes"><textarea value={String(form.notes)} onChange={(event) => change("notes", event.target.value)} className="min-h-24 w-full rounded-xl border bg-dtsc-surface p-3" /></Field></Section><div className="grid gap-2 sm:flex"><Button className="bg-[#002b5b] text-white">Enregistrer</Button><Button type="button" variant="outline" onClick={close}>Retour</Button></div>
  </form></Dialog>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="min-w-0 space-y-3 overflow-hidden rounded-2xl border p-3"><h4 className="font-black text-emerald-600">{title}</h4>{children}</section>; }
function Fields({ children }: { children: ReactNode }) { return <div className="grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-3">{children}</div>; }
function Grid({ children }: { children: ReactNode }) { return <div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4">{children}</div>; }
function Card({ title, text }: { title: string; text: string }) { return <article className="min-w-0 rounded-2xl border bg-dtsc-surface p-4"><p className="break-words font-black">{title}</p><p className="mt-1 break-words text-sm text-dtsc-muted">{text}</p></article>; }
function Help({ text }: { text: string }) { return <span title={text} aria-label={text}><CircleHelp className="h-3.5 w-3.5" /></span>; }
function Field({ name, labelText, children }: { name: string; labelText: string; children: ReactNode }) { return <label className="grid min-w-0 gap-1"><span className="flex items-center gap-1 text-xs font-black uppercase text-dtsc-muted">{labelText}<Help text={HELP[name] || `Renseignez ${labelText.toLocaleLowerCase("fr")} pour compléter le suivi de caisse.`} /></span>{children}</label>; }
function Choice({ name, labelText, value, setValue, options }: { name: string; labelText: string; value: string; setValue: (value: string) => void; options: string[][] }) { return <Field name={name} labelText={labelText}><select value={value} onChange={(event) => setValue(event.target.value)} className="h-11 w-full min-w-0 truncate rounded-xl border bg-dtsc-surface px-3"><option value="">Sélectionner...</option>{options.map(([id, title]) => <option key={id} value={id}>{title}</option>)}</select></Field>; }
function Badge({ value }: { value: string }) { return <span className="rounded-full bg-emerald-400/15 px-2 py-1 text-xs font-black text-emerald-700">{label(value)}</span>; }
function label(value: string) { return LABELS[value] || value.replaceAll("_", " ").toLocaleLowerCase("fr"); }
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
