"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CircleHelp, RefreshCw, Save, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ListControls } from "@/components/ui/list-controls";
import { useSmartList } from "@/lib/hooks/use-smart-list";
import { pharmacyNumberingEntityLabels, pharmacySettingLabels } from "@/lib/pharmacy-settings-labels";
import { pharmacySettingSections, type PharmacySettingSection, type SettingValue } from "@/lib/pharmacy-settings-config";

import { useToastMessage } from "@/components/ui/use-toast-message";
type Sequence = { id: string; entityType: string; prefix: string; format: string; counterValue: number; counterLength: number; resetFrequency: string; allowManualOverride: boolean };
type History = { id: string; section: string; settingKey: string; oldValueJson: unknown; newValueJson: unknown; changeReason: string | null; criticality: string; actorId: string; createdAt: string };
type CurrencyRate = { id: string; code: string; label: string; symbol: string | null; isBase: boolean; rateToBase: string | number; active: boolean; updatedAt: string };
type Data = { sections: Record<PharmacySettingSection, Record<string, SettingValue>>; sequences: Sequence[]; history: History[]; currencies: CurrencyRate[]; locations: Array<{ id: string; name: string }>; members: Array<{ id: string; name: string }>; positions: Array<{ id: string; labelFr: string }>; criticalKeys: string[]; permissions: { canUpdate: boolean; canUpdateCritical: boolean; canReset: boolean; canViewHistory: boolean } };
type SettingsTab = PharmacySettingSection | "currencies" | "history";
const sectionLabels: Record<SettingsTab, string> = { general: "Général", numbering: "Numérotation & préfixes", "products-batches": "Produits & lots", "stock-inventory": "Stock & inventaire", "expiry-fefo": "Péremptions & FEFO", sales: "Ventes & dispensation", prescriptions: "Ordonnances", "receipts-purchases": "Réceptions & achats", "cash-payments": "Caisse, factures & paiements", "returns-losses": "Retours, ajustements & pertes", "alerts-notifications": "Alertes & notifications", "documents-compliance": "Documents & conformité", quality: "Qualité & pharmacovigilance", "reports-exports": "Rapports & exports", "privacy-security": "Confidentialité & sécurité", "erp-integrations": "Intégrations ERP", currencies: "Devises & conversions", history: "Historique des paramètres" };
const labels: Record<string, string> = { pharmacyName: "Nom opérationnel de la pharmacie", pharmacyType: "Type de pharmacie", currency: "Devise principale", timezone: "Fuseau horaire", language: "Langue principale", country: "Pays", city: "Ville", address: "Adresse", phone: "Téléphone", email: "Adresse e-mail", receiptFooterMessage: "Message par défaut sur les reçus", configurationStatus: "Statut de configuration", defaultFormat: "Format de numérotation par défaut", defaultResetFrequency: "Fréquence de remise à zéro", defaultCounterLength: "Longueur du compteur", allowManualOverride: "Autoriser une modification manuelle", allowNegativeStock: "Autoriser un stock négatif", blockSaleWhenStockUnavailable: "Bloquer la vente si le stock est insuffisant", defaultMinStock: "Seuil minimal par défaut", defaultMaxStock: "Seuil maximal par défaut", lowStockThresholdMode: "Méthode de seuil de stock faible", stockValueCalculationMethod: "Méthode de valorisation du stock", inventoryRequiresValidation: "Exiger la validation des inventaires", inventoryVarianceRequiresReason: "Exiger un motif pour les écarts d'inventaire", adjustmentRequiresValidation: "Exiger la validation des ajustements", defaultStockLocationId: "Emplacement de stock par défaut", nearExpiryThresholdDays: "Délai de péremption proche en jours", criticalExpiryThresholdDays: "Délai de péremption critique en jours", minimumAcceptableExpiryDaysOnReceipt: "Durée minimale restante à la réception", blockExpiredBatchSale: "Bloquer la vente des lots expirés", blockRecalledBatchSale: "Bloquer la vente des lots rappelés", blockQuarantinedBatchSale: "Bloquer la vente des lots en quarantaine", blockBlockedBatchSale: "Bloquer la vente des lots bloqués", enableFefoSuggestion: "Suggérer le lot expirant en premier", enforceFefoSale: "Imposer la règle FEFO", allowAnonymousSales: "Autoriser les ventes anonymes", allowPriceEditAtSale: "Autoriser la modification du prix en vente", allowDiscountAtSale: "Autoriser les remises", maxGlobalDiscountRate: "Remise globale maximale (%)", maxLineDiscountRate: "Remise maximale par ligne (%)", refundRequiresValidation: "Exiger la validation des remboursements", criticalCashVarianceThreshold: "Seuil critique d'écart de caisse", maxCashSessionHours: "Durée maximale d'une session caisse", documentExpiryAlertDays: "Délai d'alerte avant expiration documentaire", sensitiveDownloadAuditEnabled: "Auditer les téléchargements sensibles", criticalIncidentRequiresCapa: "Exiger une action corrective pour un incident critique", allowSensitiveReportExports: "Autoriser les exports de rapports sensibles", defaultReportPeriodDays: "Période de rapport par défaut en jours", protectPatientData: "Protéger les données patient", useEnterpriseDepartments: "Utiliser les départements de l'entreprise", useEnterpriseAuditLogs: "Utiliser l'audit du socle commun", useEnterpriseNotifications: "Utiliser les notifications du socle commun" };
const selectOptions: Record<string, Array<[string, string]>> = { pharmacyType: [["OFFICINE", "Officine"], ["CLINIC_INTERNAL", "Pharmacie interne clinique"], ["HOSPITAL", "Pharmacie hospitalière"], ["DEPOT", "Dépôt pharmaceutique"], ["WHOLESALE", "Grossiste / distribution"], ["MOBILE", "Pharmacie mobile"], ["OTHER", "Autre"]], currency: [["USD", "Dollar américain (USD)"], ["CDF", "Franc congolais (CDF)"], ["EUR", "Euro (EUR)"]], language: [["fr", "Français"], ["en", "Anglais"]], timezone: [["Africa/Kinshasa", "Kinshasa"], ["Africa/Lubumbashi", "Lubumbashi"], ["UTC", "UTC"]], defaultPaymentMethod: [["CASH", "Espèces"], ["MOBILE_MONEY", "Mobile Money"], ["CARD", "Carte"], ["TRANSFER", "Virement"], ["CREDIT", "Crédit"]], defaultDocumentConfidentiality: [["INTERNAL", "Interne"], ["CONFIDENTIAL", "Confidentiel"], ["VERY_CONFIDENTIAL", "Très confidentiel"]], prescriptionDocumentConfidentialityDefault: [["CONFIDENTIAL", "Confidentiel"], ["VERY_CONFIDENTIAL", "Très confidentiel"]], lowStockThresholdMode: [["PRODUCT", "Par produit"], ["GLOBAL", "Seuil global"], ["CATEGORY", "Par catégorie"], ["DISABLED", "Désactivé"]], stockValueCalculationMethod: [["AVERAGE_PURCHASE_PRICE", "Prix d'achat moyen"], ["LAST_PURCHASE_PRICE", "Dernier prix d'achat"], ["BATCH_PRICE", "Prix du lot"], ["MANUAL", "Prix manuel"], ["DISABLED", "Non calculé"]] };
function humanize(key: string) { return pharmacySettingLabels[key] || labels[key] || "Paramètre métier"; }
function help(key: string, critical: boolean) { return `${critical ? "Paramètre critique audité. " : ""}Cette valeur influence réellement les règles métier des modules Pharmacie concernés.`; }

export function PharmacySettingsWorkspace({ organizationId }: { organizationId: string }) {
  const [data, setData] = useState<Data | null>(null); const [active, setActive] = useState<SettingsTab>("general"); const [draft, setDraft] = useState<Record<string, SettingValue>>({}); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  useToastMessage(message); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState<Record<string, string>>({});
  const load = useCallback(async () => { setBusy(true); const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/settings`, { cache: "no-store" }); const body = await response.json().catch(() => null) as Data | null; if (response.ok && body) setData(body); else setMessage("Chargement des paramètres impossible."); setBusy(false); }, [organizationId]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (active !== "history" && active !== "currencies" && data) setDraft({ ...data.sections[active] }); }, [active, data]);
  const criticalChanged = useMemo(() => data && active !== "history" && active !== "currencies" ? Object.keys(draft).some((key) => data.criticalKeys.includes(key) && draft[key] !== data.sections[active][key]) : false, [active, data, draft]);
  async function save() { if (active === "history" || active === "currencies") return; const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/settings`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ section: active, values: draft, reason }) }); const body = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Paramètres enregistrés et appliqués." : body?.message || "Enregistrement impossible."); if (response.ok) { setReason(""); await load(); } }
  async function action(payload: Record<string, unknown>) { const response = await fetch(`/api/enterprise/${organizationId}/pharmacy/settings/actions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null) as { message?: string; preview?: string } | null; if (body?.preview && typeof payload.entityType === "string") setPreview((old) => ({ ...old, [payload.entityType as string]: body.preview || "" })); setMessage(response.ok ? "Action de paramétrage exécutée." : body?.message || "Action impossible."); if (response.ok && !body?.preview) await load(); }
  return <div className="min-w-0 space-y-4 overflow-x-hidden"><div className="flex max-w-full gap-2 overflow-x-auto pb-2">{[...pharmacySettingSections, "currencies" as const, "history" as const].map((section) => <button key={section} type="button" onClick={() => setActive(section)} className={`shrink-0 rounded-2xl border px-4 py-3 text-sm font-black ${active === section ? "border-emerald-300 bg-emerald-400/15 text-emerald-700" : "border-dtsc-border bg-dtsc-surface text-dtsc-ink"}`}>{sectionLabels[section]}</button>)}</div>
    <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-black text-dtsc-ink">{sectionLabels[active]}</h3><p className="text-sm text-dtsc-muted">Configuration persistée pour la pharmacie active, appliquée côté serveur et auditée.</p></div><Button variant="outline" onClick={() => void load()} disabled={busy}><RefreshCw className="h-4 w-4" />Actualiser</Button></div></section>
    {active === "history" ? <SettingsHistory items={data?.history || []} /> : active === "currencies" ? <CurrencyRates currencies={data?.currencies || []} permissions={data?.permissions} action={action} /> : active === "numbering" ? <Numbering sequences={data?.sequences || []} preview={preview} reason={reason} setReason={setReason} action={action} canUpdate={Boolean(data?.permissions.canReset)} /> : <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Object.entries(draft).map(([key, value]) => <SettingField key={key} settingKey={key} value={value} critical={Boolean(data?.criticalKeys.includes(key))} locations={data?.locations || []} onChange={(next) => setDraft((old) => ({ ...old, [key]: next }))} />)}</div><div className="mt-4 grid gap-3"><label className="grid gap-1 text-xs font-black uppercase text-dtsc-muted">Motif du changement {criticalChanged ? "(obligatoire)" : "(optionnel)"}<textarea value={reason} onChange={(event) => setReason(event.target.value)} className="min-h-20 rounded-xl border border-dtsc-border bg-dtsc-surface p-3 text-sm normal-case" /></label><div className="flex flex-wrap gap-2"><Button onClick={() => void save()} disabled={!data?.permissions.canUpdate || (criticalChanged && !data.permissions.canUpdateCritical)}><Save className="h-4 w-4" />Enregistrer</Button><Button variant="outline" onClick={() => data && setDraft({ ...data.sections[active] })}>Annuler les modifications</Button><Button variant="outline" disabled={!data?.permissions.canReset || !reason.trim()} onClick={() => void action({ action: "reset-section", section: active, reason })}>Réinitialiser la section</Button></div></div></section>}
    </div>;
}
function SettingField({ settingKey, value, critical, locations, onChange }: { settingKey: string; value: SettingValue; critical: boolean; locations: Array<{ id: string; name: string }>; onChange: (value: SettingValue) => void }) { const choices = settingKey === "defaultStockLocationId" ? locations.map((item) => [item.id, item.name] as [string, string]) : selectOptions[settingKey]; return <label className="grid min-w-0 gap-1 rounded-xl border border-dtsc-border p-3 text-xs font-black uppercase text-dtsc-muted"><span className="flex items-center gap-1">{humanize(settingKey)}<span title={help(settingKey, critical)} aria-label={help(settingKey, critical)}><CircleHelp className="h-3.5 w-3.5" /></span>{critical && <ShieldAlert className="h-3.5 w-3.5 text-amber-600" />}</span>{typeof value === "boolean" ? <button type="button" onClick={() => onChange(!value)} className={`rounded-xl border px-3 py-2 text-left normal-case ${value ? "border-emerald-400 bg-emerald-400/15 text-emerald-700" : "border-dtsc-border bg-dtsc-surface text-dtsc-muted"}`}>{value ? "Activé" : "Désactivé"}</button> : choices ? <select value={String(value || "")} onChange={(event) => onChange(event.target.value || null)} className="min-w-0 rounded-xl border border-dtsc-border bg-dtsc-surface px-3 py-2 text-sm normal-case text-dtsc-ink"><option value="">Non configuré</option>{choices.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select> : <Input type={typeof value === "number" ? "number" : "text"} value={value === null ? "" : String(value)} onChange={(event) => onChange(typeof value === "number" ? Number(event.target.value) : event.target.value)} />}</label>; }
function CurrencyRates({ currencies, permissions, action }: { currencies: CurrencyRate[]; permissions?: Data["permissions"]; action: (payload: Record<string, unknown>) => Promise<void> }) { return <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{currencies.map((currency) => <CurrencyCard key={currency.code} currency={currency} canUpdate={Boolean(permissions?.canUpdate)} canUpdateCritical={Boolean(permissions?.canUpdateCritical)} action={action} />)}{!currencies.length && <p className="text-sm text-dtsc-muted">Aucune devise configurée.</p>}</div></section>; }
function CurrencyCard({ currency, canUpdate, canUpdateCritical, action }: { currency: CurrencyRate; canUpdate: boolean; canUpdateCritical: boolean; action: (payload: Record<string, unknown>) => Promise<void> }) {
  const [rate, setRate] = useState(String(currency.rateToBase)); const [active, setActive] = useState(currency.active); const [isBase, setIsBase] = useState(currency.isBase); const [reason, setReason] = useState("");
  useEffect(() => { setRate(String(currency.rateToBase)); setActive(currency.active); setIsBase(currency.isBase); setReason(""); }, [currency.active, currency.isBase, currency.rateToBase]);
  const critical = isBase && !currency.isBase; const protectedBase = currency.isBase;
  return <article className="grid gap-3 rounded-xl border border-dtsc-border bg-dtsc-surface p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-black text-dtsc-ink">{currency.label} ({currency.code})</p><p className="text-xs text-dtsc-muted">{currency.isBase ? "Devise principale actuelle" : `1 ${currency.code} = ${currency.rateToBase} devise principale`}</p></div><span className={`rounded-full px-2 py-1 text-xs font-black ${currency.active ? "bg-emerald-400/15 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{currency.active ? "Active" : "Inactive"}</span></div><label className="grid gap-1 text-xs font-black uppercase text-dtsc-muted">Taux vers la devise principale<Input type="number" min="0.000001" step="0.000001" value={rate} disabled={isBase} onChange={(event) => setRate(event.target.value)} /></label><div className="grid gap-2 text-sm"><button type="button" disabled={protectedBase} onClick={() => setActive((value) => !value)} className={`rounded-xl border px-3 py-2 text-left font-black disabled:cursor-not-allowed disabled:opacity-70 ${active ? "border-emerald-400 bg-emerald-400/15 text-emerald-700" : "border-dtsc-border text-dtsc-muted"}`}>{protectedBase ? "Devise principale active" : active ? "Devise utilisable" : "Devise désactivée"}</button><button type="button" onClick={() => { if (!protectedBase) setIsBase((value) => !value); }} className={`rounded-xl border px-3 py-2 text-left font-black ${isBase ? "border-amber-400 bg-amber-400/15 text-amber-700" : "border-dtsc-border text-dtsc-muted"}`}>{isBase ? "Devise principale" : "Définir comme principale"}</button></div>{critical && <label className="grid gap-1 text-xs font-black uppercase text-dtsc-muted">Motif obligatoire<Input value={reason} onChange={(event) => setReason(event.target.value)} /></label>}<Button variant="outline" disabled={!canUpdate || (critical && (!canUpdateCritical || !reason.trim()))} onClick={() => void action({ action: "update-currency", currencyCode: currency.code, currencyLabel: currency.label, currencySymbol: currency.symbol || "", rateToBase: isBase ? 1 : Number(rate), active: protectedBase ? true : active, isBase, reason })}>Enregistrer la devise</Button></article>;
}
function Numbering({ sequences, preview, reason, setReason, action, canUpdate }: { sequences: Sequence[]; preview: Record<string, string>; reason: string; setReason: (value: string) => void; action: (payload: Record<string, unknown>) => Promise<void>; canUpdate: boolean }) { return <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><label className="grid gap-1 text-xs font-black uppercase text-dtsc-muted">Motif obligatoire pour modifier un préfixe<Input value={reason} onChange={(event) => setReason(event.target.value)} /></label><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{sequences.map((sequence) => <SequenceCard key={sequence.id} sequence={sequence} preview={preview[sequence.entityType]} canUpdate={canUpdate && Boolean(reason.trim())} action={action} reason={reason} />)}</div></section>; }
function SequenceCard({ sequence, preview, canUpdate, action, reason }: { sequence: Sequence; preview?: string; canUpdate: boolean; action: (payload: Record<string, unknown>) => Promise<void>; reason: string }) { const [prefix, setPrefix] = useState(sequence.prefix); return <article className="rounded-xl border border-dtsc-border p-3"><p className="font-black text-dtsc-ink">{pharmacyNumberingEntityLabels[sequence.entityType] || "Objet métier"}</p><p className="text-xs text-dtsc-muted">{preview || `${sequence.prefix} · compteur ${sequence.counterValue}`}</p><Input className="mt-2" value={prefix} onChange={(event) => setPrefix(event.target.value)} /><div className="mt-2 flex flex-wrap gap-2"><Button variant="outline" onClick={() => void action({ action: "preview-number", entityType: sequence.entityType })}>Prévisualiser</Button><Button variant="outline" disabled={!canUpdate} onClick={() => void action({ action: "update-sequence", entityType: sequence.entityType, prefix, format: sequence.format, resetFrequency: sequence.resetFrequency, counterLength: sequence.counterLength, allowManualOverride: sequence.allowManualOverride, reason })}>Enregistrer</Button></div></article>; }
function SettingsHistory({ items }: { items: History[] }) { const list = useSmartList({ items, pageSize: 12, getSearchText: useCallback((item: History) => `${item.section} ${item.settingKey} ${item.criticality} ${item.changeReason || ""}`, []) }); return <section className="rounded-2xl border border-dtsc-border bg-dtsc-page p-4"><ListControls query={list.query} onQueryChange={list.setQuery} page={list.page} pageCount={list.pageCount} totalCount={list.totalCount} filteredCount={list.filteredCount} placeholder="Rechercher dans l'historique..." onPageChange={list.setPage} /><div className="mt-3 grid gap-2">{list.paginatedItems.map((item) => <article key={item.id} className="rounded-xl border border-dtsc-border p-3"><div className="flex flex-wrap justify-between gap-2"><b>{sectionLabels[item.section as PharmacySettingSection] || item.section} · {humanize(item.settingKey)}</b><span className="text-xs font-black text-amber-600">{item.criticality}</span></div><p className="text-xs text-dtsc-muted">{new Date(item.createdAt).toLocaleString("fr-FR")} · {item.changeReason || "Sans motif"}</p></article>)}{!list.filteredCount && <p className="text-sm text-dtsc-muted">Aucun changement enregistré.</p>}</div></section>; }
