import type { ContextualUserGuide } from "@/lib/user-guides/iteration04-guides";

const FR: ContextualUserGuide = {
  code: "FINANCE_ACCOUNTING_ONBOARDING",
  title: "Guide de mise en service et d’exploitation comptable",
  summary: "Démarrer avec le plan SYSCOHADA par défaut de DTSC, terminer la mise en service, puis utiliser les espaces Accueil, Comptabiliser, Consulter et Configurer du workspace Comptabilité.",
  audience: "Administrateurs d’entreprise, responsables Finance et comptables autorisés",
  updatedAt: "2026-09-07",
  capabilities: [
    "SYSCOHADA révisé 2017 v0.1.0 comme plan par défaut DTSC",
    "Assistant Finance calculé par les diagnostics serveur",
    "Cases automatiquement validées après configuration réelle",
    "Permissions Finance dérivées des capacités serveur et des rôles/postes autorisés",
    "Filiation version → plan entreprise traçable",
    "Sous-comptes personnalisés contrôlés",
    "Mappings métier vers comptes actifs",
    "Journaux recommandés et personnalisables",
    "Distinction entre blocages obligatoires et recommandations contextuelles",
    "Activation explicite et auditée",
    "Journal Workbench multi-lignes avec totaux débit/crédit et dimensions analytiques",
    "Grand livre et balance compacts, paginés et filtrés côté serveur",
    "Traçabilité vers la source uniquement lorsque le module source est autorisé",
    "États financiers versionnés",
    "Diff de version sans mutation silencieuse",
  ],
  steps: [
    { title: "Ouvrir la mise en service", description: "Dans Comptabilité > Configurer > Mise en service, l’assistant affiche les prérequis calculés par le serveur. Une étape devient terminée automatiquement dès que la configuration correspondante est réellement valide." },
    { title: "Configurer les devises", description: "Définissez la devise fonctionnelle. La devise de présentation utilise la devise fonctionnelle si aucune devise distincte n’est nécessaire." },
    { title: "Créer l’exercice et la période", description: "Créez l’exercice financier puis au moins une période comptable ouverte correspondant au calendrier réel de l’entreprise." },
    { title: "Confirmer la version du plan", description: "DTSC sélectionne SYSCOHADA révisé 2017 v0.1.0 par défaut. Vérifiez la juridiction, la date d’effet, la provenance et la version affichée avant de l’appliquer au plan de l’entreprise.", cautions: ["Une nouvelle version n’est jamais appliquée automatiquement à un plan déjà utilisé.", "Le plan par défaut DTSC ne constitue pas à lui seul une certification réglementaire ou fiscale nationale."] },
    { title: "Créer et appliquer le plan entreprise", description: "Créez le plan propre à votre entreprise puis appliquez la version. Les comptes, mappings métier et journaux sont copiés dans le contexte isolé de l’entreprise avec une filiation code@version." },
    { title: "Personnaliser", description: "Ajoutez des sous-comptes autorisés sous un compte parent. Les comptes système et les comptes déjà utilisés restent protégés." },
    { title: "Vérifier les mappings et journaux", description: "Chaque opération ERP doit trouver le compte actif approprié à sa date comptable et le journal requis. DTSC n’utilise pas de fallback silencieux." },
    { title: "Traiter les recommandations", description: "Configurez les comptes financiers, la fiscalité applicable et la tolérance de rapprochement selon le contexte réel. Une recommandation non applicable ne bloque pas automatiquement la comptabilisation." },
    { title: "Corriger les blocages", description: "Traitez chaque point marqué Requis. Les messages et liens d’action sont fournis par le même contrat serveur que celui utilisé par le posting." },
    { title: "Vérifier les autorisations", description: "Les actions visibles dépendent des capacités serveur du module et des permissions de rôle ou de poste. Le rôle MANAGER ne donne pas automatiquement les privilèges d’administration Finance, d’approbation ou d’accès sensible." },
    { title: "Activer", description: "Lorsque les contrôles bloquants sont satisfaits, activez explicitement le plan. L’action est auditée et protégée par les permissions serveur." },
    { title: "Comptabiliser une écriture manuelle", description: "Dans Comptabiliser, ouvrez Nouvelle écriture. Sélectionnez journal, période, devise et comptes via les références proposées. Ajoutez autant de lignes que nécessaire, renseignez les dimensions utiles et vérifiez que Débit = Crédit avant d’enregistrer.", cautions: ["Une ligne utilise soit un débit positif, soit un crédit positif, jamais les deux.", "Les tiers, projets, départements, sites, actifs et articles de stock sont revalidés côté serveur dans l’entreprise active."] },
    { title: "Soumettre et valider", description: "Une écriture nécessitant une validation suit les capacités serveur : soumission à un validateur éligible, approbation/rejet, puis comptabilisation. Les règles d’indépendance restent appliquées." },
    { title: "Consulter le grand livre", description: "Dans Consulter > Grand livre, utilisez la recherche et les dates. Seules les écritures comptabilisées sont prises en compte. Les tableaux sont compacts et restent navigables au clavier et sur mobile." },
    { title: "Lire la balance", description: "La balance présente le solde d’ouverture, les débits et crédits de période et le solde de clôture par compte dans la devise fonctionnelle." },
    { title: "Ouvrir la trace d’une écriture", description: "Ouvrez une ligne du grand livre pour consulter l’écriture et ses lignes. Un lien vers le document métier source n’est proposé que si vous êtes aussi autorisé à lire le module source." },
    { title: "Consulter les états", description: "Utilisez la balance, le grand livre, le bilan et le compte de résultat. Chaque montant reste traçable vers les comptes et écritures comptabilisées." },
    { title: "Importer une nouvelle version", description: "Une nouvelle version est enregistrée séparément. Prévisualisez toujours le diff, la provenance et l’impact avant toute migration. Les écritures historiques ne sont jamais réécrites." },
  ],
  limitations: [
    "Les règles fiscales nationales variables ne sont pas intégrées au plan SYSCOHADA commun ; elles appartiennent à la configuration fiscale ou à un overlay pays sourcé.",
    "Une migration complexe d’un plan déjà utilisé exige une analyse d’impact et une validation contrôlée ; DTSC bloque l’application automatique plutôt que de modifier l’historique.",
    "La stabilisation technique de l’onboarding, du workbench et du posting ne vaut pas certification réglementaire du plan ou des déclarations d’un pays.",
    "Les écritures récurrentes, accruals/deferrals, réévaluation FX de clôture, year-end et consolidation sont suivis dans les itérations comptables suivantes et ne sont pas ajoutés par ce guide.",
  ],
};

const EN: ContextualUserGuide = {
  code: "FINANCE_ACCOUNTING_ONBOARDING",
  title: "Accounting setup and operations guide",
  summary: "Start with DTSC’s default SYSCOHADA chart, follow the server-driven setup, then use the Home, Post, Review and Configure areas of the Accounting workspace.",
  audience: "Enterprise administrators, Finance owners and authorized accountants",
  updatedAt: "2026-09-07",
  capabilities: [
    "Revised SYSCOHADA 2017 v0.1.0 as the DTSC default chart",
    "Finance assistant calculated from server diagnostics",
    "Automatically checked steps after real configuration",
    "Finance permissions derived from server capabilities and authorized roles/positions",
    "Traceable version → company chart lineage",
    "Controlled custom child accounts",
    "Business semantic mappings to active accounts",
    "Recommended and customizable journals",
    "Explicit distinction between blocking prerequisites and contextual recommendations",
    "Explicit audited activation",
    "Multi-line Journal Workbench with debit/credit totals and analytical dimensions",
    "Compact general ledger and trial balance with server-side pagination and filtering",
    "Source traceability only when the source module is authorized",
    "Versioned financial statements",
    "Version diff without silent mutation",
  ],
  steps: [
    { title: "Open setup", description: "In Accounting > Configure > Setup, the assistant displays prerequisites calculated by the server. A step becomes complete automatically as soon as the corresponding configuration is truly valid." },
    { title: "Configure currencies", description: "Set the functional currency. Presentation currency uses the functional currency when a separate presentation currency is not needed." },
    { title: "Create fiscal year and period", description: "Create the fiscal year and at least one open accounting period matching the company’s real accounting calendar." },
    { title: "Confirm the chart version", description: "DTSC selects Revised SYSCOHADA 2017 v0.1.0 by default. Review jurisdiction, effective date, provenance and displayed version before applying it to the company chart.", cautions: ["A new version is never applied automatically to a chart that is already in use.", "The DTSC default chart does not by itself constitute national regulatory or tax certification."] },
    { title: "Create and apply the company chart", description: "Create the company chart, then apply the version. Accounts, business mappings and journals are copied into the isolated company context while retaining code@version lineage." },
    { title: "Customize", description: "Add authorized child accounts below a parent account. System and already-used accounts remain protected." },
    { title: "Review mappings and journals", description: "Every ERP operation must resolve to the appropriate active account at its accounting date and to the required journal. DTSC does not silently fall back." },
    { title: "Handle recommendations", description: "Configure financial accounts, applicable tax setup and reconciliation tolerance for the real company context. A recommendation that does not apply does not automatically block posting." },
    { title: "Resolve blockers", description: "Address each item marked Required. Action messages and links come from the same server contract used by posting." },
    { title: "Review permissions", description: "Visible actions follow server module capabilities and role/position permissions. The MANAGER role does not automatically grant Finance administration, approval or sensitive-data privileges." },
    { title: "Activate", description: "When blocking controls are satisfied, explicitly activate the chart. The action is audited and protected by server permissions." },
    { title: "Post a manual journal entry", description: "In Post, open New journal entry. Select the journal, period, currency and accounts from the proposed references. Add as many lines as needed, enter useful dimensions and make sure Debit = Credit before saving.", cautions: ["A line uses either a positive debit or a positive credit, never both.", "Parties, projects, departments, sites, assets and inventory items are revalidated server-side in the active company."] },
    { title: "Submit and approve", description: "An entry requiring approval follows server capabilities: assignment to an eligible approver, approval/rejection, then posting. Independence rules remain enforced." },
    { title: "Review the general ledger", description: "In Review > General ledger, use search and dates. Only posted entries are included. Tables stay compact, keyboard-accessible and usable on mobile." },
    { title: "Read the trial balance", description: "The trial balance shows opening balance, period debits and credits, and closing balance by account in the functional currency." },
    { title: "Open an entry trace", description: "Open a general-ledger row to review the journal entry and its lines. A link to the business source document is offered only when you are also allowed to read the source module." },
    { title: "Read statements", description: "Use trial balance, general ledger, balance sheet and income statement. Each amount remains traceable to accounts and posted entries." },
    { title: "Import a new version", description: "A new version is registered separately. Always preview provenance, diff and impact before migration. Historical entries are never rewritten." },
  ],
  limitations: [
    "Variable national tax rules are not embedded in the common SYSCOHADA chart; they belong in tax configuration or a sourced country overlay.",
    "A complex migration of an already-used chart requires impact analysis and controlled approval; DTSC blocks automatic application rather than rewriting history.",
    "Technical stabilization of onboarding, the workbench and posting is not a regulatory certification of a country chart or filing regime.",
    "Recurring entries, accruals/deferrals, closing FX revaluation, year-end and consolidation are tracked by the following Accounting iterations and are not added by this guide.",
  ],
};

export function getAccountingOnboardingGuide(locale?: string | null) {
  return locale === "en" ? EN : FR;
}