import type { ContextualUserGuide } from "@/lib/user-guides/iteration04-guides";

export type Iteration07GuideCode =
  | "CONSOLE_OVERVIEW"
  | "CONSOLE_USERS"
  | "CONSOLE_CLIENT_ENTERPRISES"
  | "CONSOLE_SUBSCRIPTIONS"
  | "CONSOLE_SUPPORT"
  | "CONSOLE_CONTENT"
  | "CONSOLE_VISITS"
  | "CONSOLE_PLATFORM_SETTINGS"
  | "CONSOLE_SECURITY_AUDIT"
  | "CONSOLE_RBAC"
  | "DTSC_INTERNAL_ADMIN"
  | "DTSC_HR_CFO"
  | "DTSC_SCO"
  | "DTSC_COO"
  | "DTSC_CEO"
  | "DTSC_MPO"
  | "DTSC_CTO"
  | "DTSC_LEGAL";

type Seed = {
  fr: { title: string; summary: string; audience: string; capabilities: string[]; steps: Array<[string, string]>; limitations?: string[] };
  en: { title: string; summary: string; audience: string; capabilities: string[]; steps: Array<[string, string]>; limitations?: string[] };
};

const commonLimitFr = "Les actions disponibles dépendent du contexte DTSC interne, du poste, des permissions individuelles et de la capacité vérifiée côté serveur.";
const commonLimitEn = "Available actions depend on the DTSC internal context, official position, individual permissions and server-verified capability.";

const seeds: Record<Iteration07GuideCode, Seed> = {
  CONSOLE_OVERVIEW: {
    fr: { title: "Guide Vue générale Console", summary: "Lire les KPIs SaaS, leur source, leur période, leur fraîcheur et ouvrir les files d’actions réelles.", audience: "Administrateurs DTSC et décideurs autorisés", capabilities: ["KPIs sourcés", "Périodes cohérentes", "Santé plateforme", "Centre d’actions", "Drill-down"], steps: [["Choisir une période", "Utilisez aujourd’hui, 7, 30, 90 jours, année ou une période personnalisée."], ["Vérifier la définition", "Chaque carte précise source, unité, période et dernière actualisation."], ["Traiter une action", "Ouvrez la file d’actions puis suivez le lien profond vers l’objet canonique."], ["Lire la santé", "Un statut UNKNOWN signifie qu’aucun signal fournisseur fiable n’est persisté ; la Console ne l’invente pas."]], limitations: [commonLimitFr] },
    en: { title: "Console overview guide", summary: "Read SaaS KPIs, sources, periods, freshness and open real action queues.", audience: "DTSC administrators and authorized decision makers", capabilities: ["Sourced KPIs", "Consistent periods", "Platform health", "Action center", "Drill-down"], steps: [["Choose a period", "Use today, 7, 30, 90 days, year or a custom range."], ["Check the definition", "Every card states source, unit, period and last refresh."], ["Process an action", "Open the action queue and follow the deep link to the canonical object."], ["Read health", "UNKNOWN means no reliable provider signal is persisted; the Console does not invent one."]], limitations: [commonLimitEn] },
  },
  CONSOLE_USERS: {
    fr: { title: "Guide Utilisateurs globaux", summary: "Rechercher, filtrer, paginer et administrer les comptes sans supprimer leur historique métier.", audience: "Administrateurs DTSC habilités", capabilities: ["Pagination serveur", "Recherche et filtres", "Statut, rôle et limites", "Protection du dernier admin", "Audit"], steps: [["Trouver un compte", "Filtrez par rôle, statut, organisation, inscription ou recherche."], ["Lire le détail", "Vérifiez organisations, abonnement, usage, tickets et audits autorisés."], ["Modifier", "Toute suspension, réactivation, limite ou rôle exige la capacité correspondante."], ["Protéger", "Le serveur bloque l’auto-rétrogradation et la suppression du dernier administrateur critique."]], limitations: ["La suppression physique abusive n’est pas un parcours Console.", commonLimitFr] },
    en: { title: "Global users guide", summary: "Search, filter, paginate and manage accounts without deleting business history.", audience: "Authorized DTSC administrators", capabilities: ["Server pagination", "Search and filters", "Status, role and limits", "Last-admin protection", "Audit"], steps: [["Find an account", "Filter by role, status, organization, registration or search."], ["Read details", "Review authorized organizations, subscription, usage, tickets and audits."], ["Change", "Suspension, reactivation, limits and roles require the matching capability."], ["Protect", "The server blocks self-demotion and removal of the last critical administrator."]], limitations: ["Physical deletion is not a standard Console workflow.", commonLimitEn] },
  },
  CONSOLE_CLIENT_ENTERPRISES: {
    fr: { title: "Guide Entreprises clientes", summary: "Administrer le cycle de vie d’une organisation cliente sans ouvrir arbitrairement ses données privées.", audience: "Administrateurs DTSC autorisés", capabilities: ["Liste paginée", "Création atomique", "Plan et modules", "Suspension réversible", "Isolation tenant"], steps: [["Créer", "Vérifiez les doublons, choisissez secteur, plan et administrateur explicite."], ["Examiner", "Consultez les métadonnées globales, la santé, le support et l’audit autorisés."], ["Suspendre", "Renseignez le motif, l’impact et notifiez les administrateurs avant l’application."], ["Archiver", "L’archivage conserve les données et l’historique."]], limitations: ["La Console ne donne pas un accès automatique aux dossiers métiers privés de l’organisation.", commonLimitFr] },
    en: { title: "Client organizations guide", summary: "Manage a client organization lifecycle without arbitrarily opening private business data.", audience: "Authorized DTSC administrators", capabilities: ["Paginated list", "Atomic creation", "Plan and modules", "Reversible suspension", "Tenant isolation"], steps: [["Create", "Check duplicates and choose sector, plan and an explicit administrator."], ["Review", "Inspect authorized global metadata, health, support and audit."], ["Suspend", "Enter reason and impact, then notify administrators before enforcement."], ["Archive", "Archiving preserves data and history."]], limitations: ["Console access does not automatically grant access to private business records.", commonLimitEn] },
  },
  CONSOLE_SUBSCRIPTIONS: {
    fr: { title: "Guide Abonnements et facturation", summary: "Piloter plans, abonnements, paiements, factures et revenus validés sans réconciliation cachée.", audience: "Administrateurs commerciaux et financiers autorisés", capabilities: ["Catalogue versionné", "Abonnements utilisateurs et organisations", "Paiements traçables", "Revenus validés", "Réconciliation explicite"], steps: [["Lire le catalogue", "Vérifiez la version, la date d’effet, les limites et les modules du plan."], ["Filtrer", "Recherchez par organisation, statut, plan, paiement ou échéance."], ["Réconcilier", "Lancez l’action dédiée avec motif ; elle est idempotente et auditée."], ["Exporter", "Conservez période, devise, filtres, locale et classification."]], limitations: ["L’ouverture de la page ne synchronise ni paiement ni comptabilité.", commonLimitFr] },
    en: { title: "Subscriptions and billing guide", summary: "Manage plans, subscriptions, payments, invoices and validated revenue without hidden reconciliation.", audience: "Authorized commercial and finance administrators", capabilities: ["Versioned catalog", "User and organization subscriptions", "Traceable payments", "Validated revenue", "Explicit reconciliation"], steps: [["Read catalog", "Check version, effective date, limits and modules."], ["Filter", "Search by organization, status, plan, payment or due date."], ["Reconcile", "Run the dedicated action with a reason; it is idempotent and audited."], ["Export", "Preserve period, currency, filters, locale and classification."]], limitations: ["Opening the page never synchronizes payments or accounting.", commonLimitEn] },
  },
  CONSOLE_SUPPORT: {
    fr: { title: "Guide Support Console", summary: "Traiter la file globale de tickets avec assignation, priorité, SLA, escalade et historique.", audience: "Équipe Support DTSC et administrateurs autorisés", capabilities: ["Pagination et filtres", "Assignation", "SLA réel", "Escalade", "Résolution et réouverture"], steps: [["Prioriser", "Filtrez les tickets urgents, en retard, non assignés ou par organisation."], ["Assigner", "Choisissez un agent DTSC actif et conservez l’horodatage d’assignation."], ["Répondre", "Les messages restent liés au ticket ; une conversation générale n’est pas un ticket."], ["Résoudre", "Renseignez la résolution, vérifiez le SLA puis clôturez ou rouvrez selon le workflow."]], limitations: ["La satisfaction n’est affichée que lorsqu’une source réelle existe.", commonLimitFr] },
    en: { title: "Support Console guide", summary: "Process the global ticket queue with assignment, priority, SLA, escalation and history.", audience: "DTSC Support team and authorized administrators", capabilities: ["Pagination and filters", "Assignment", "Real SLA", "Escalation", "Resolution and reopening"], steps: [["Prioritize", "Filter urgent, overdue, unassigned or organization tickets."], ["Assign", "Choose an active DTSC agent and retain assignment time."], ["Reply", "Messages remain linked to the ticket; a general conversation is not a ticket."], ["Resolve", "Record resolution, check SLA, then close or reopen through the workflow."]], limitations: ["Satisfaction is shown only when a real source exists.", commonLimitEn] },
  },
  CONSOLE_CONTENT: {
    fr: { title: "Guide Contenus publics", summary: "Créer, prévisualiser, versionner, publier et archiver les contenus et promotions existants.", audience: "Équipe éditoriale et administrateurs autorisés", capabilities: ["Brouillon et publication", "Versionnement", "Prévisualisation protégée", "Bannières ciblées", "Consentements newsletter"], steps: [["Créer un brouillon", "Renseignez titre, slug, catégorie, résumé, contenu et locale."], ["Prévisualiser", "La prévisualisation utilise le rendu réel sans publier."], ["Publier", "La publication conserve une version et l’audit de l’auteur."], ["Archiver", "Archivez sans effacer l’historique ni les statistiques réelles."]], limitations: ["La programmation n’est proposée que si un worker fiable est actif.", commonLimitFr] },
    en: { title: "Public content guide", summary: "Create, preview, version, publish and archive existing content and promotions.", audience: "Editorial team and authorized administrators", capabilities: ["Draft and publish", "Versioning", "Protected preview", "Targeted banners", "Newsletter consent"], steps: [["Create a draft", "Enter title, slug, category, excerpt, content and locale."], ["Preview", "Preview uses the real renderer without publishing."], ["Publish", "Publishing preserves a version and author audit."], ["Archive", "Archive without deleting history or real statistics."]], limitations: ["Scheduling is offered only when a reliable worker is active.", commonLimitEn] },
  },
  CONSOLE_VISITS: {
    fr: { title: "Guide Visites et acquisition", summary: "Lire uniquement les dimensions réellement collectées et comprendre la définition des conversions.", audience: "Marketing et direction autorisés", capabilities: ["Périodes cohérentes", "Pages et référents collectés", "Confidentialité", "Conversions définies", "Exports filtrés"], steps: [["Choisir une période", "Utilisez les mêmes bornes pour cartes, graphiques et export."], ["Lire les dimensions", "N’interprétez que path, referrer, user-agent ou autres champs réellement collectés."], ["Protéger", "Évitez l’exposition d’IP et de parcours individuels."], ["Définir une conversion", "Documentez explicitement l’événement avant de l’utiliser comme KPI."]], limitations: ["Pays, campagne ou appareil restent indisponibles tant qu’ils ne sont pas collectés de façon fiable.", commonLimitFr] },
    en: { title: "Visits and acquisition guide", summary: "Read only collected dimensions and understand conversion definitions.", audience: "Authorized marketing and leadership users", capabilities: ["Consistent periods", "Collected pages and referrers", "Privacy", "Defined conversions", "Filtered exports"], steps: [["Choose a period", "Use the same boundaries for cards, charts and exports."], ["Read dimensions", "Interpret only path, referrer, user-agent and fields actually collected."], ["Protect", "Avoid exposing IP addresses and individual journeys."], ["Define a conversion", "Document the event explicitly before using it as a KPI."]], limitations: ["Country, campaign or device remain unavailable until reliably collected.", commonLimitEn] },
  },
  CONSOLE_PLATFORM_SETTINGS: {
    fr: { title: "Guide Paramètres plateforme", summary: "Modifier des paramètres schématisés et des feature flags sans exposer les secrets.", audience: "Administrateurs plateforme fortement autorisés", capabilities: ["Schéma et validation", "Historique", "Secrets masqués", "Feature flags", "Confirmation sensible"], steps: [["Identifier le paramètre", "Vérifiez code, catégorie, type, environnement, effet et besoin de redémarrage."], ["Modifier", "Renseignez un motif et confirmez toute valeur sensible."], ["Lire un secret", "La Console n’affiche que CONFIGURÉ, NON CONFIGURÉ, INVALIDE ou EXPIRANT."], ["Piloter une flag", "Définissez audience, environnement, pourcentage, période et propriétaire."]], limitations: ["Un secret complet n’est jamais retourné par l’API Console.", commonLimitFr] },
    en: { title: "Platform settings guide", summary: "Change schema-backed settings and feature flags without exposing secrets.", audience: "Strongly authorized platform administrators", capabilities: ["Schema and validation", "History", "Masked secrets", "Feature flags", "Sensitive confirmation"], steps: [["Identify setting", "Check code, category, type, environment, effect and restart requirement."], ["Change", "Provide a reason and confirm sensitive values."], ["Read a secret", "Console only shows CONFIGURED, NOT_CONFIGURED, INVALID or EXPIRING."], ["Manage a flag", "Define audience, environment, percentage, period and owner."]], limitations: ["A complete secret is never returned by the Console API.", commonLimitEn] },
  },
  CONSOLE_SECURITY_AUDIT: {
    fr: { title: "Guide Sécurité, API et webhooks", summary: "Rechercher les audits, logs API et webhooks avec redaction, corrélation et retry contrôlé.", audience: "Sécurité, support technique et administrateurs autorisés", capabilities: ["Pagination serveur", "Filtres et request ID", "Payload redacted", "Retry idempotent", "Rétention documentée"], steps: [["Choisir la source", "Sélectionnez Audit, API ou Webhook avant d’appliquer les filtres."], ["Ouvrir le détail", "Vérifiez acteur, contexte, objet, résultat, reason code et request ID."], ["Relancer", "Un webhook déjà appliqué ou sans dispatcher fiable ne peut pas être relancé."], ["Exporter", "L’export est borné, privé, expirant et audité."]], limitations: ["Tokens, OTP, mots de passe, cartes et données médicales détaillées sont redacted.", commonLimitFr] },
    en: { title: "Security, API and webhooks guide", summary: "Search audits, API logs and webhooks with redaction, correlation and controlled retry.", audience: "Security, technical support and authorized administrators", capabilities: ["Server pagination", "Filters and request ID", "Redacted payload", "Idempotent retry", "Documented retention"], steps: [["Choose source", "Select Audit, API or Webhook before applying filters."], ["Open details", "Review actor, context, object, result, reason code and request ID."], ["Retry", "An already applied webhook or one without a reliable dispatcher cannot be retried."], ["Export", "Exports are bounded, private, expiring and audited."]], limitations: ["Tokens, OTPs, passwords, cards and detailed medical data are redacted.", commonLimitEn] },
  },
  CONSOLE_RBAC: {
    fr: { title: "Guide RBAC Console", summary: "Comprendre la décision d’accès fondée sur rôle global, bloc, poste, permission individuelle et capacité.", audience: "Administrateurs des accès DTSC", capabilities: ["Capacités explicites", "Reason codes", "Permissions individuelles", "Lecture distincte de mutation", "Simulation"], steps: [["Choisir une capacité", "Une section peut exiger une capacité de lecture différente de sa capacité de gestion."], ["Simuler", "Vérifiez décision, origine et reason code sans modifier l’utilisateur."], ["Accorder", "Utilisez le catalogue individuel existant, sans seconde table parallèle."], ["Retirer", "La navigation et l’API doivent refuser immédiatement après retrait."]], limitations: [commonLimitFr] },
    en: { title: "Console RBAC guide", summary: "Understand access decisions based on global role, block, position, individual permission and capability.", audience: "DTSC access administrators", capabilities: ["Explicit capabilities", "Reason codes", "Individual permissions", "Read separated from manage", "Simulation"], steps: [["Choose a capability", "A section may require a read capability distinct from its manage capability."], ["Simulate", "Check decision, origin and reason code without changing the user."], ["Grant", "Use the existing individual catalog, not a parallel table."], ["Revoke", "Navigation and API must deny immediately after revocation."]], limitations: [commonLimitEn] },
  },
  DTSC_INTERNAL_ADMIN: {
    fr: { title: "Guide Administration interne DTSC", summary: "Accéder aux tableaux internes séparés selon le poste officiel et les permissions individuelles.", audience: "Collaborateurs internes DTSC", capabilities: ["Routes séparées", "Sources canoniques", "Liens profonds", "Guides par poste", "Chargement ciblé"], steps: [["Choisir son tableau", "Ouvrez uniquement la section liée à votre poste ou permission individuelle."], ["Lire les indicateurs", "Chaque chiffre doit provenir d’un moteur métier existant."], ["Ouvrir la source", "Utilisez le lien profond vers la tâche, le budget, le dossier ou le projet canonique."], ["Escalader", "Créez une action ou décision liée à l’objet source, sans le dupliquer."]], limitations: [commonLimitFr] },
    en: { title: "DTSC internal administration guide", summary: "Access separate internal dashboards according to official position and individual permissions.", audience: "Internal DTSC collaborators", capabilities: ["Separate routes", "Canonical sources", "Deep links", "Role guides", "Targeted loading"], steps: [["Choose dashboard", "Open only the section linked to your position or individual permission."], ["Read indicators", "Every value must come from an existing business engine."], ["Open source", "Use deep links to canonical tasks, budgets, cases or projects."], ["Escalate", "Create an action or decision linked to the source object without duplicating it."]], limitations: [commonLimitEn] },
  },
  DTSC_HR_CFO: roleSeed("HR & CFO", "RH, paie, budgets, dépenses, comptes et validations financières", "HR, payroll, budgets, expenses, accounts and financial approvals"),
  DTSC_SCO: roleSeed("SCO", "fournisseurs, achats, stocks, actifs et logistique", "suppliers, procurement, inventory, assets and logistics"),
  DTSC_COO: roleSeed("COO", "opérations, tâches, demandes, blocages, réunions et rapports", "operations, tasks, requests, blockers, meetings and reports"),
  DTSC_CEO: roleSeed("CEO", "objectifs, indicateurs, décisions, arbitrages, risques et maturité", "objectives, indicators, decisions, arbitration, risks and maturity"),
  DTSC_MPO: roleSeed("MPO", "projets, livrables, risques, jalons, dépendances et ressources", "projects, deliverables, risks, milestones, dependencies and resources"),
  DTSC_CTO: roleSeed("CTO", "projets techniques, incidents, qualité, sécurité, API et coûts", "technical projects, incidents, quality, security, APIs and costs"),
  DTSC_LEGAL: roleSeed("Legal Advisor", "dossiers, contrats, risques, litiges, documents et échéances", "cases, contracts, risks, disputes, documents and deadlines"),
};

function roleSeed(role: string, frDomain: string, enDomain: string): Seed {
  return {
    fr: { title: `Guide Tableau ${role}`, summary: `Piloter ${frDomain} depuis les sources métier canoniques.`, audience: `${role} et personnes autorisées`, capabilities: ["Indicateurs réels", "Filtres", "Actions liées", "Audit", "Responsive"], steps: [["Filtrer", "Choisissez la période, le statut ou le responsable sans charger les autres tableaux."], ["Analyser", "Vérifiez la définition et la source de chaque indicateur."], ["Agir", "Ouvrez l’objet canonique pour réaliser la mutation autorisée."], ["Rapporter", "Conservez décisions, commentaires et preuves dans le workflow existant."]], limitations: ["Le tableau ne recrée aucun moteur métier.", commonLimitFr] },
    en: { title: `${role} dashboard guide`, summary: `Manage ${enDomain} from canonical business sources.`, audience: `${role} and authorized users`, capabilities: ["Real indicators", "Filters", "Linked actions", "Audit", "Responsive"], steps: [["Filter", "Choose period, status or owner without loading other dashboards."], ["Analyze", "Check the definition and source of each indicator."], ["Act", "Open the canonical object to perform the authorized mutation."], ["Report", "Keep decisions, comments and evidence in the existing workflow."]], limitations: ["The dashboard does not recreate any business engine.", commonLimitEn] },
  };
}

export const ITERATION07_USER_GUIDE_CODES = Object.keys(seeds) as Iteration07GuideCode[];

export function getIteration07UserGuide(code: Iteration07GuideCode, locale?: string | null): ContextualUserGuide {
  const seed = seeds[code][locale === "en" ? "en" : "fr"];
  return {
    code,
    title: seed.title,
    summary: seed.summary,
    audience: seed.audience,
    capabilities: seed.capabilities,
    steps: seed.steps.map(([title, description]) => ({ title, description })),
    limitations: seed.limitations,
    updatedAt: "2026-08-05",
  };
}
