import type { ContextualUserGuide } from "@/lib/user-guides/iteration04-guides";

type RetailGuideCode = "RETAIL_POS" | "MOBILE_MONEY_AGENCY" | "TELCO_TOPUPS" | "RETAIL_DAILY_CLOSE";

const fr: Record<RetailGuideCode, ContextualUserGuide> = {
  RETAIL_POS: {
    code: "RETAIL_POS",
    title: "Guide d’onboarding Shop & Point de vente",
    summary: "Mettre en service un Shop Retail Core de façon contrôlée : structure, catalogue, stock, Finance, comptabilité POS, taux de change, caisse, vente, reporting et clôture. Mobile Money et Télécom sont des extensions optionnelles.",
    audience: "Administrateur entreprise, gérant, responsable ventes, vendeur, caissier et contrôleur",
    updatedAt: "2026-08-08",
    capabilities: [
      "Onboarding STARTER / BUSINESS / ENTERPRISE",
      "Profil RETAIL_CORE par défaut",
      "Checklist Mise en service du Shop",
      "Panier multi-articles",
      "Recherche catalogue/SKU",
      "Recherche POS serveur paginée",
      "Prix catalogue protégés côté serveur",
      "Dérogation de prix/remise réservée aux responsables avec motif",
      "Paiements cash, Mobile Money, banque ou carte selon configuration",
      "Paiement fractionné",
      "Sortie de stock atomique",
      "Comptabilité POS en partie double",
      "Valorisation COGS / INVENTORY",
      "Taux de change Finance datés et auditables",
      "Consolidation multi-devise au taux historique",
      "Ticket imprimable/partageable",
      "Annulation complète auditée et comptabilisée",
    ],
    steps: [
      { title: "Choisir l’offre", description: "STARTER prépare catalogue, clients et documents. BUSINESS est le minimum opérationnel recommandé pour le POS, le stock, Finance et la clôture. ENTERPRISE ajoute l’échelle et la gouvernance.", cautions: ["Ne vendez pas STARTER comme un POS opérationnel complet."] },
      { title: "Créer l’entreprise et appliquer le template Shop", description: "Depuis la Console DTSC, créez l’organisation CLIENT, choisissez COMMERCE_RETAIL, le plan et l’administrateur, puis appliquez le template sectoriel.", actions: ["Faire accepter l’invitation administrateur", "Vérifier le profil RETAIL_CORE pour un nouveau tenant", "Contrôler les modules autorisés par le plan"], cautions: ["Un tenant historique RETAIL_TELCO_MOBILE_MONEY conserve son profil pour éviter toute régression."] },
      { title: "Structurer l’équipe", description: "Affectez les postes du cœur Retail avant l’exploitation et ajoutez les rôles opérateurs seulement si les extensions correspondantes sont activées.", actions: ["Nommer le gérant", "Affecter vendeurs et caissiers", "Nommer le responsable achats", "Prévoir un contrôleur indépendant"] },
      { title: "Créer site, dépôt, catalogue et stock", description: "Le POS réutilise les référentiels ERP communs. Créez le site réel, le dépôt, les articles avec prix/devise puis chargez le stock initial avec sa valorisation.", actions: ["Créer site et dépôt", "Renseigner prix/SKU/devise", "Créer les articles d’inventaire", "Contrôler disponibilité et coût"] },
      { title: "Préparer Finance pour le POS", description: "Finance doit être READY avec devise fonctionnelle, comptes réels, journaux SALES/INVENTORY, période de posting et mappings SALES_REVENUE, TAX_PAYABLE, COST_OF_SALES et INVENTORY.", actions: ["Vérifier Finance READY", "Vérifier les quatre mappings", "Vérifier les journaux", "Vérifier la période comptable"], cautions: ["La checklist première vente reste incomplète si la comptabilité POS ne peut pas poster."] },
      { title: "Configurer les taux de change", description: "Dans Finance > Trésorerie > Taux de change et consolidation multi-devise, saisissez les paires sous la forme 1 SOURCE = RATE TARGET avec date d’effet et source.", actions: ["Créer les paires nécessaires", "Vérifier la devise de présentation/fonctionnelle", "Ouvrir le rapport consolidé Shop"], cautions: ["Un taux publié n’est pas réécrit : désactivez-le avec motif puis créez une nouvelle version.", "Si un taux historique manque, DTSC refuse d’afficher un total consolidé partiel."] },
      { title: "Vérifier la mise en service", description: "Le bloc Mise en service du Shop contrôle profil, dépôt, catalogue, caisse, comptabilité POS, FX et rôles de contrôle.", actions: ["Résoudre tous les prérequis du cœur Retail avant la première vente"] },
      { title: "Ouvrir sa caisse", description: "Avant un paiement cash, ouvrez votre session de caisse. Le POS réutilise ensuite automatiquement cette caisse.", actions: ["Choisir la caisse physique", "Compter le fonds d’ouverture", "Confirmer l’ouverture"] },
      { title: "Construire et encaisser le premier panier", description: "Recherchez les produits par nom, code ou SKU, ajoutez plusieurs lignes et validez les paiements. Le serveur revalide prix, stock, comptes et permissions.", actions: ["Choisir le dépôt", "Rechercher les articles", "Ajouter au panier", "Tester un paiement fractionné si utilisé", "Encaisser"] },
      { title: "Contrôler les écritures", description: "Après succès, vérifiez le débit des tenders, les crédits revenu/taxe et la valorisation Dr COST_OF_SALES / Cr INVENTORY.", actions: ["Vérifier que débits = crédits", "Rejouer la même clé d’idempotence et vérifier qu’aucune écriture n’est dupliquée"] },
      { title: "Tester l’annulation complète", description: "L’annulation réintègre le stock et inverse tenders, revenu, taxe et coût au coût original.", actions: ["Annuler avec motif", "Contrôler le stock", "Contrôler les écritures miroir"] },
      { title: "Activer les extensions seulement si vendues", description: "Mobile Money et Télécom ne sont pas des prérequis Retail Core. Mappez wallets et réseaux uniquement si le client exploite ces services.", cautions: ["M-Pesa est un wallet Mobile Money ; Vodacom est un réseau Télécom. Ne mélangez pas ces concepts."] },
      { title: "Contrôler le reporting et clôturer", description: "Vérifiez les agrégats natifs, la Consolidation multi-devise, puis comptez la caisse et faites valider la clôture par une autre personne autorisée.", actions: ["Contrôler les taux utilisés", "Justifier les écarts", "Soumettre", "Faire approuver indépendamment"] },
    ],
    limitations: [
      "Le moteur complet de pricing, fiscalité automatique, promotions et retours partiels appartient à Shop 2.0 itération 2.",
      "L’exécution chez les opérateurs Mobile Money/Télécom reste externe tant qu’un adaptateur partenaire n’est pas connecté.",
      "Le raccordement complet de la recherche POS serveur au workspace actif est un critère de clôture de l’itération 1.",
      "Les scénarios de valorisation COGS multi-devise ambiguë doivent être validés avant toute certification globale.",
    ],
  },
  MOBILE_MONEY_AGENCY: {
    code: "MOBILE_MONEY_AGENCY",
    title: "Guide Agence Mobile Money — extension Shop",
    summary: "Activer et exploiter l’extension Mobile Money d’un Shop avec une caisse ouverte, des wallets explicitement configurés et des références opérateur uniques.",
    audience: "Gérant, agent Mobile Money, caissier et contrôleur",
    updatedAt: "2026-08-08",
    capabilities: ["Extension Retail optionnelle", "M-Pesa, Orange Money, Airtel Money et Afrimoney configurables", "Float résolu depuis le provider", "Numéro normalisé côté serveur", "Confirmation avant validation", "Référence opérateur unique", "Dépôts et retraits", "Frais et commissions séparés", "Annulation contrôlée"],
    steps: [
      { title: "Activer uniquement les wallets utilisés", description: "Un Retail Core standard n’impose aucun wallet. Le responsable active/configure les wallets vendus au client et les relie aux vrais comptes de float.", actions: ["Ouvrir Configuration", "Choisir le compte MOBILE_MONEY correspondant", "Enregistrer"], cautions: ["DTSC ne crée ni faux compte ni faux solde."] },
      { title: "Ouvrir la caisse", description: "La session cash ouverte de l’agent est utilisée automatiquement lorsque l’opération exige du cash." },
      { title: "Préparer l’opération", description: "Choisissez Dépôt ou Retrait, le wallet, le téléphone, le montant, les frais/commissions et la référence opérateur." },
      { title: "Vérifier puis confirmer", description: "L’écran de confirmation affiche le téléphone et le montant avant écriture. Le backend applique la normalisation selon le pays de l’entreprise.", cautions: ["Une référence opérateur déjà utilisée est refusée."] },
      { title: "Rapprocher et annuler avec preuve", description: "Contrôlez cash et float. N’annulez dans DTSC qu’après inversion réelle chez le fournisseur lorsque cela est requis." },
    ],
    limitations: ["DTSC enregistre et rapproche actuellement l’opération ; la state machine provider asynchrone, les webhooks et retries opérateur appartiennent à l’itération 3."],
  },
  TELCO_TOPUPS: {
    code: "TELCO_TOPUPS",
    title: "Guide Télécom & forfaits — extension Shop",
    summary: "Activer et exploiter les recharges Télécom en distinguant strictement le réseau opérateur du wallet Mobile Money.",
    audience: "Gérant, responsable ventes, vendeur et agent Télécom",
    updatedAt: "2026-08-08",
    capabilities: ["Extension Retail optionnelle", "Vodacom, Orange, Airtel et Africell configurables", "Séparation Vodacom / M-Pesa et réseau / wallet", "Float Télécom résolu depuis le provider", "Numéro normalisé côté serveur", "Confirmation avant exécution", "Référence opérateur obligatoire si SUCCESS", "Protection anti-doublon", "Coût et marge", "SUCCESS/FAILED", "Annulation auditée"],
    steps: [
      { title: "Activer les réseaux réellement utilisés", description: "Un Retail Core standard n’impose aucun opérateur. Configurez uniquement les réseaux inclus dans l’offre du client.", actions: ["Ouvrir Configuration", "Relier chaque réseau à son vrai compte de float/clearing", "Vérifier la devise"] },
      { title: "Préparer les forfaits", description: "Les offres fréquentes peuvent être enregistrées comme services du catalogue avec prix et coût indicatifs." },
      { title: "Préparer la recharge", description: "Choisissez le réseau, saisissez le numéro, l’offre, le prix, le coût, la référence et le statut d’exécution." },
      { title: "Vérifier puis rapprocher", description: "Contrôlez numéro, encaissement, coût, marge et float. Une opération SUCCESS exige une référence fournisseur unique." },
    ],
    limitations: ["La recharge est actuellement exécutée sur le canal opérateur externe ; les adaptateurs asynchrones et webhooks appartiennent à l’itération 3."],
  },
  RETAIL_DAILY_CLOSE: {
    code: "RETAIL_DAILY_CLOSE",
    title: "Guide Clôture magasin",
    summary: "Clôturer le Retail Core avec comptage de caisse, écarts justifiés et validation indépendante ; ajouter les floats uniquement lorsque les extensions sont actives.",
    audience: "Caissier, gérant et contrôleur ; agent Mobile Money si l’extension est active",
    updatedAt: "2026-08-08",
    capabilities: ["Clôture Retail Core sans Mobile Money obligatoire", "Clôture multi-comptes", "Comptage des coupures", "Solde théorique de la session", "Floats optionnels par devise", "Écart motivé", "Validation indépendante", "Posting Finance des écarts approuvés", "Historique"],
    steps: [
      { title: "Terminer les opérations", description: "Vérifiez qu’aucune opération de caisse n’est en cours. Relevez les floats uniquement pour les extensions utilisées." },
      { title: "Déclarer", description: "Pour CASH, les coupures doivent totaliser exactement le montant déclaré. Les devises restent séparées." },
      { title: "Soumettre", description: "La session passe en attente de validation et ne doit plus recevoir de nouveaux mouvements." },
      { title: "Faire valider", description: "Le validateur doit être une autre personne autorisée ; il approuve ou refuse avec motif. Les écarts approuvés sont postés dans Finance." },
    ],
  },
};

const en: Record<RetailGuideCode, ContextualUserGuide> = {
  RETAIL_POS: {
    code: "RETAIL_POS",
    title: "Shop onboarding & Point of Sale guide",
    summary: "Bring a Retail Core Shop into controlled operation: organization, catalog, inventory, Finance, POS accounting, exchange rates, till, sales, reporting and closing. Mobile Money and Telco are optional extensions.",
    audience: "Company administrator, store manager, sales manager, seller, cashier and controller",
    updatedAt: "2026-08-08",
    capabilities: ["STARTER / BUSINESS / ENTERPRISE onboarding", "RETAIL_CORE default profile", "Shop readiness checklist", "Multi-item basket", "Catalog/SKU search", "Paginated server-side POS search", "Server-protected catalog prices", "Manager-only override with reason", "Configured cash, Mobile Money, bank or card tenders", "Split payment", "Atomic stock issue", "POS double-entry accounting", "COGS / INVENTORY valuation", "Dated auditable Finance exchange rates", "Historical FX multi-currency consolidation", "Printable/shareable receipt", "Audited full reversal"],
    steps: [
      { title: "Choose the offer", description: "STARTER prepares data. BUSINESS is the recommended operational minimum for POS, inventory, Finance and closing. ENTERPRISE adds plan-level scale and governance.", cautions: ["Do not sell STARTER as a full operational POS."] },
      { title: "Create the company and apply the Shop template", description: "Create the CLIENT organization, choose COMMERCE_RETAIL, plan and administrator, then apply the sector template.", actions: ["Have the administrator accept the invitation", "Verify RETAIL_CORE for a new tenant", "Check plan entitlements"], cautions: ["Existing RETAIL_TELCO_MOBILE_MONEY tenants retain their recognized profile for compatibility."] },
      { title: "Set up people, locations, catalog and inventory", description: "Assign core Retail roles, create the physical site/warehouse, build the catalog and load valued opening stock through common ERP domains." },
      { title: "Make Finance POS-ready", description: "Finance must be READY with functional currency, real tender accounts, SALES/INVENTORY journals, an available period and SALES_REVENUE, TAX_PAYABLE, COST_OF_SALES and INVENTORY mappings." },
      { title: "Configure exchange rates", description: "Save each required pair as 1 SOURCE = RATE TARGET with its effective date and source. Missing historical rates must keep consolidation incomplete rather than inventing a total." },
      { title: "Open the till and run the first sale", description: "Count opening cash, open the session, build a multi-item basket and collect configured tenders. Server checks price, stock, accounts and permissions." },
      { title: "Verify accounting", description: "Check tender debits, revenue/tax credits and Dr COST_OF_SALES / Cr INVENTORY. Retry the same idempotency key and confirm no duplicate sale or posting is created." },
      { title: "Test full reversal", description: "Reverse with a reason and verify stock return plus mirrored tender, revenue, tax and original-cost postings." },
      { title: "Enable optional operator extensions only when sold", description: "Mobile Money and Telco are not Retail Core prerequisites. Map wallets and telecom networks only for clients that use them.", cautions: ["M-Pesa is a Mobile Money wallet; Vodacom is a telecom network."] },
      { title: "Validate reporting and close", description: "Check native currency aggregates, historical FX consolidation, count the till, explain variances and require independent validation." },
    ],
    limitations: ["Full pricing/tax/promotion and partial-return engines belong to Shop 2.0 iteration 2.", "Operator-side Mobile Money/Telco execution remains external until provider adapters are delivered in iteration 3.", "The active POS workspace still needs final wiring to the server-side product search before iteration 1 can close.", "Ambiguous multi-currency COGS valuation still requires behavioral certification."],
  },
  MOBILE_MONEY_AGENCY: {
    code: "MOBILE_MONEY_AGENCY",
    title: "Mobile Money Agency — Shop extension guide",
    summary: "Enable and run the optional Mobile Money extension with an open till, explicitly configured wallets and unique provider references.",
    audience: "Store manager, Mobile Money agent, cashier and controller",
    updatedAt: "2026-08-08",
    capabilities: ["Optional Retail extension", "Configurable M-Pesa, Orange Money, Airtel Money and Afrimoney wallets", "Provider-resolved float", "Country-aware server phone normalization", "Confirmation before submission", "Unique provider reference", "Deposits and withdrawals", "Separate fees and commissions", "Controlled reversal"],
    steps: [
      { title: "Enable only the wallets in use", description: "Retail Core does not force wallets. Map each enabled wallet to a real MOBILE_MONEY float account.", cautions: ["DTSC never invents financial accounts or balances."] },
      { title: "Open the till", description: "The active cash session is reused when the operation requires cash." },
      { title: "Prepare and confirm", description: "Choose Deposit or Withdrawal, wallet, phone, principal, fees/commission and provider reference, then verify the confirmation screen." },
      { title: "Reconcile and reverse with evidence", description: "Verify cash/float effects and only reverse in DTSC after any required provider-side reversal." },
    ],
    limitations: ["DTSC currently records and reconciles the operation; asynchronous provider states, signed webhooks and retries belong to iteration 3."],
  },
  TELCO_TOPUPS: {
    code: "TELCO_TOPUPS",
    title: "Telco & top-ups — Shop extension guide",
    summary: "Enable and run optional telecom top-ups while keeping telecom networks distinct from Mobile Money wallets.",
    audience: "Store manager, sales manager, seller and telecom agent",
    updatedAt: "2026-08-08",
    capabilities: ["Optional Retail extension", "Configurable Vodacom, Orange, Airtel and Africell networks", "Network/wallet separation", "Provider-resolved telecom float", "Country-aware server phone normalization", "Confirmation", "Unique provider reference for SUCCESS", "Cost and margin", "SUCCESS/FAILED", "Audited reversal"],
    steps: [
      { title: "Enable networks actually used", description: "Retail Core does not force telecom providers. Map enabled networks to real float/clearing accounts." },
      { title: "Prepare offers", description: "Frequent bundles may be represented by catalog services with reference price and cost." },
      { title: "Prepare and verify the top-up", description: "Choose network, phone, offer, selling price, provider cost, reference and execution status; verify settlement, margin and float." },
    ],
    limitations: ["Provider-side execution remains external; asynchronous provider adapters and webhooks belong to iteration 3."],
  },
  RETAIL_DAILY_CLOSE: {
    code: "RETAIL_DAILY_CLOSE",
    title: "Store daily close guide",
    summary: "Close Retail Core with till counts, explained variances and independent validation; include operator floats only when extensions are enabled.",
    audience: "Cashier, store manager and controller; Mobile Money agent when that extension is enabled",
    updatedAt: "2026-08-08",
    capabilities: ["Retail Core close without mandatory Mobile Money", "Multi-account close", "Denomination counting", "Expected till balance", "Optional floats by currency", "Explained variance", "Independent validation", "Approved variance Finance posting", "History"],
    steps: [
      { title: "Finish operations", description: "Confirm no till operation is still running. Read operator floats only for enabled extensions." },
      { title: "Declare balances", description: "For CASH, denominations must exactly match the declared balance. Keep currencies separate." },
      { title: "Submit", description: "The till moves to pending validation and must not accept new movements." },
      { title: "Validate independently", description: "A different authorized person approves or rejects with a reason. Approved variances are posted to Finance." },
    ],
  },
};

export function getRetailUserGuide(code: string, locale: string): ContextualUserGuide {
  const resolved = (code in fr ? code : "RETAIL_POS") as RetailGuideCode;
  return locale === "en" ? en[resolved] : fr[resolved];
}
