import type { ContextualUserGuide } from "@/lib/user-guides/iteration04-guides";

type RetailGuideCode = "RETAIL_POS" | "MOBILE_MONEY_AGENCY" | "TELCO_TOPUPS" | "RETAIL_DAILY_CLOSE";

const fr: Record<RetailGuideCode, ContextualUserGuide> = {
  RETAIL_POS: {
    code: "RETAIL_POS",
    title: "Guide Shop & Point de vente — Retail Core",
    summary: "Mettre en service et exploiter un Shop Retail Core : catalogue, stock, Finance, tarification, retours, clienteling CRM, fidélité, cartes-cadeaux/avoirs, paiements, reçus et périphériques POS.",
    audience: "Administrateur entreprise, gérant, responsable ventes, vendeur, caissier et contrôleur",
    updatedAt: "2026-08-08",
    capabilities: [
      "Guide d’onboarding Shop",
      "Onboarding STARTER / BUSINESS / ENTERPRISE",
      "Profil RETAIL_CORE par défaut avec extensions optionnelles Mobile Money et Télécom",
      "Recherche catalogue/SKU paginée côté serveur",
      "Panier multi-articles et paiement fractionné",
      "Prix catalogue et fiscalité protégés côté serveur",
      "Promotions, coupons et dérogations auditables",
      "Retours partiels, échanges et remboursements contrôlés",
      "Client CRM canonique au POS",
      "Historique achats/retours sans second référentiel client",
      "Fidélité transactionnelle avec ledger et idempotence",
      "Cartes-cadeaux et avoirs avec protection anti-double-spend",
      "Paiements provider-neutral avec états explicites",
      "Reçu digital JSON ou HTML imprimable selon consentement",
      "Périphériques POS avec dégradation propre",
      "Sortie de stock atomique et valorisation COGS / INVENTORY",
      "Comptabilité POS en partie double",
      "Taux de change Finance datés et consolidation historique",
      "Consolidation multi-devise",
      "Annulation complète auditée et comptabilisée",
    ],
    steps: [
      { title: "Préparer le tenant Retail", description: "Créez l’organisation COMMERCE_RETAIL, appliquez le template RETAIL_CORE, affectez les postes et activez uniquement les modules autorisés par le plan. Mobile Money et Télécom restent des extensions optionnelles et ne font pas partie du noyau obligatoire.", cautions: ["BUSINESS reste le minimum opérationnel recommandé pour POS + stock + Finance + clôture."] },
      { title: "Créer site, dépôt, catalogue et stock", description: "Le POS réutilise les référentiels ERP communs. Créez les articles, SKU, prix, dépôts et stock valorisé avant la première vente." },
      { title: "Rendre Finance READY", description: "Configurez devise fonctionnelle, comptes réels, journaux SALES/INVENTORY, période de posting et mappings SALES_REVENUE, TAX_PAYABLE, COST_OF_SALES et INVENTORY." },
      { title: "Configurer tarification, taxes et promotions", description: "Les règles commerciales utilisent le Catalogue et les références fiscales communes. Une dérogation de prix/remise/taxe exige permission et motif." },
      { title: "Reconnaître le client", description: "Recherchez le client CRM par nom, code, email ou téléphone. Sélectionnez-le avant la vente si nécessaire ; une vente de passage reste possible.", cautions: ["La création rapide n’est visible qu’avec une vraie permission CRM d’écriture."] },
      { title: "Utiliser la fidélité", description: "Les programmes ACTIVE tiennent les points dans un ledger. Le gain automatique exige settings.autoEarn=true ; la dépense verrouille le compte et refuse un solde insuffisant." },
      { title: "Utiliser cartes-cadeaux et avoirs", description: "À l’émission, le code porteur est affiché une seule fois ; DTSC ne stocke que son hash. Débit et remboursement sont transactionnels et idempotents." },
      { title: "Encaisser", description: "Construisez le panier puis utilisez cash, Mobile Money, banque, carte ou valeur stockée selon la configuration. Le serveur revalide prix, stock, comptes, client et permissions." },
      { title: "Contrôler le reçu", description: "Le reçu peut être obtenu en JSON ou HTML imprimable. Le nom/code client peut identifier la transaction ; email/téléphone ne sont divulgués qu’avec un consentement actif RETAIL_RECEIPT_CONTACT." },
      { title: "Vérifier les périphériques", description: "Les scanners, imprimantes, tiroirs, terminaux, afficheurs et balances configurés indiquent leur disponibilité. WebUSB/WebBluetooth/WebSerial indisponible ne doit jamais bloquer la caisse." },
      { title: "Traiter retours et échanges", description: "Les quantités retournables tiennent compte des retours déjà terminés et en attente. Le demandeur ne valide pas son propre remboursement." },
      { title: "Contrôler Finance et clôturer", description: "Vérifiez écritures, valorisation, agrégats par devise et taux historiques, puis faites valider la clôture par une personne indépendante." },
    ],
    limitations: [
      "Un adaptateur PSP/opérateur n’est considéré connecté que s’il est réellement enregistré et configuré ; DTSC ne simule aucun fournisseur externe.",
      "Les scénarios de valorisation COGS multi-devise ambiguë doivent être validés avant certification globale.",
      "Offline, omnicanal avancé, multi-store global et country packs relèvent de Shop 2.0 itération 4.",
    ],
  },
  MOBILE_MONEY_AGENCY: {
    code: "MOBILE_MONEY_AGENCY",
    title: "Guide Agence Mobile Money — extension Shop",
    summary: "Exploiter Mobile Money en mode manuel contrôlé ou via un provider connecté, avec cash/float séparés, états asynchrones, webhooks signés et rapprochement.",
    audience: "Gérant, agent Mobile Money, caissier et contrôleur",
    updatedAt: "2026-08-08",
    capabilities: ["Extension Retail optionnelle", "Wallets configurables", "Cash et float séparés", "Dépôts/retraits", "Frais et commissions", "Mode MANUAL ou CONNECTED", "INITIATED/PENDING_PROVIDER/CONFIRMED/FAILED/UNKNOWN/RECONCILED", "Webhooks signés idempotents", "Timeout et rapprochement", "Annulation contrôlée"],
    steps: [
      { title: "Configurer wallet et comptes", description: "Reliez chaque provider au vrai compte de float et gardez une caisse ouverte pour les effets cash. Un wallet Mobile Money comme M-Pesa est distinct du réseau Télécom Vodacom : ne mélangez jamais leurs références, comptes ou opérations." },
      { title: "Choisir le mode d’intégration", description: "MANUAL conserve la confirmation opérateur contrôlée. CONNECTED exige un adaptateur réel et une intégration active.", cautions: ["Le navigateur ne déclare jamais lui-même CONFIRMED en mode connecté."] },
      { title: "Préparer l’opération", description: "Choisissez dépôt/retrait, wallet, téléphone, montant, frais et référence. Le numéro est normalisé côté serveur." },
      { title: "Suivre le provider", description: "Une opération CONNECTED peut rester PENDING_PROVIDER ou devenir UNKNOWN. Aucun effet définitif cash/float n’est créé avant confirmation provider." },
      { title: "Rapprocher", description: "Les contrôleurs autorisés relancent ou rapprochent une opération. Un webhook dupliqué ne doit jamais dupliquer l’effet métier ou Finance." },
    ],
    limitations: ["Sans adaptateur partenaire réel, utilisez MANUAL. UNKNOWN n’est jamais assimilé à un succès."],
  },
  TELCO_TOPUPS: {
    code: "TELCO_TOPUPS",
    title: "Guide Télécom & forfaits — extension Shop",
    summary: "Exploiter les recharges Télécom multi-devise en séparant réseau, comptes opérateur et encaissement, avec coût/marge, mode manuel ou connecté et rapprochement.",
    audience: "Gérant, responsable ventes, vendeur, agent Télécom et contrôleur",
    updatedAt: "2026-08-14",
    capabilities: ["Extension Retail optionnelle", "Réseaux configurables", "Comptes opérateur CDF/USD par réseau", "Plusieurs caisses CDF/USD simultanées", "Encaissement non-cash multi-devise", "Coût et marge", "Mode MANUAL ou CONNECTED", "États provider asynchrones", "Webhooks signés idempotents", "Timeout/UNKNOWN/RECONCILED", "Annulation auditée"],
    steps: [
      { title: "Configurer les comptes du réseau", description: "Associez chaque réseau à un compte opérateur distinct pour chaque devise exploitée. En RDC, configurez CDF et USD. Le réseau Télécom Vodacom reste distinct du wallet Mobile Money M-Pesa, même lorsqu’ils appartiennent au même écosystème commercial." },
      { title: "Préparer les offres", description: "Les offres fréquentes peuvent être des services du Catalogue avec prix et coût indicatifs." },
      { title: "Choisir MANUAL ou CONNECTED", description: "CONNECTED exige un adaptateur réel. Le statut SUCCESS métier n’est matérialisé qu’après confirmation provider." },
      { title: "Exécuter et suivre", description: "Pour les espèces, sélectionnez la caisse CDF ou USD à utiliser ; pour un autre paiement, choisissez le compte d’encaissement. La devise de ce compte sélectionne automatiquement le compte opérateur correspondant. Saisissez ensuite numéro, offre, prix et coût." },
      { title: "Rapprocher", description: "Les callbacks et retries sont idempotents. Les contrôleurs disposent d’une action de rapprochement pour les cas timeout/unknown." },
    ],
    limitations: ["Sans adaptateur opérateur réel, le mode MANUAL reste la voie explicite. Aucun provider fictif n’est livré en production."],
  },
  RETAIL_DAILY_CLOSE: {
    code: "RETAIL_DAILY_CLOSE",
    title: "Guide Clôture magasin",
    summary: "Clôturer Retail Core avec comptage de caisse, écarts justifiés, validation indépendante et floats seulement pour les extensions réellement actives.",
    audience: "Caissier, gérant et contrôleur ; agent Mobile Money si l’extension est active",
    updatedAt: "2026-08-08",
    capabilities: ["Clôture Retail Core", "Clôture multi-comptes", "Comptage des coupures", "Solde théorique", "Floats optionnels par devise", "Écart motivé", "Validation indépendante", "Posting Finance des écarts approuvés", "Historique"],
    steps: [
      { title: "Terminer les opérations", description: "Vérifiez qu’aucune opération de caisse n’est en cours et rapprochez les opérations provider UNKNOWN importantes avant clôture." },
      { title: "Déclarer", description: "Pour CASH, les coupures doivent totaliser le montant déclaré. Les devises restent séparées." },
      { title: "Soumettre", description: "La session passe en attente de validation et ne reçoit plus de nouveaux mouvements." },
      { title: "Faire valider", description: "Une autre personne autorisée approuve ou refuse avec motif. Les écarts approuvés sont postés dans Finance." },
    ],
  },
};

const en: Record<RetailGuideCode, ContextualUserGuide> = {
  RETAIL_POS: {
    code: "RETAIL_POS",
    title: "Shop & Point of Sale guide — Retail Core",
    summary: "Bring a Retail Core Shop into operation with catalog, inventory, Finance, pricing, returns, canonical CRM clienteling, loyalty, gift cards/store credit, payments, receipts and POS devices.",
    audience: "Company administrator, store manager, sales manager, seller, cashier and controller",
    updatedAt: "2026-08-08",
    capabilities: ["STARTER / BUSINESS / ENTERPRISE onboarding", "RETAIL_CORE default profile with optional Mobile Money and Telco extensions", "Paginated server-side catalog/SKU search", "Multi-item basket and split payment", "Server-protected pricing and taxes", "Audited promotions/coupons/overrides", "Partial returns, exchanges and controlled refunds", "Canonical CRM customer at POS", "Purchase/return history without a second customer master", "Transactional loyalty ledger", "Double-spend protected gift cards/store credit", "Provider-neutral payment states", "Consent-aware JSON/printable receipt", "Graceful POS device readiness", "Atomic inventory issue", "POS double-entry accounting", "COGS / INVENTORY valuation", "Historical FX consolidation", "Audited full reversal"],
    steps: [
      { title: "Prepare the Retail tenant", description: "Create the COMMERCE_RETAIL organization, apply the RETAIL_CORE template, assign roles and enable only plan-entitled modules. Mobile Money and Telco remain optional extensions rather than Retail Core requirements.", cautions: ["BUSINESS remains the recommended operational minimum for POS + inventory + Finance + close."] },
      { title: "Create site, warehouse, catalog and stock", description: "Use the common ERP sources for products, SKU, prices, warehouses and valued opening stock." },
      { title: "Make Finance READY", description: "Configure functional currency, real tender accounts, SALES/INVENTORY journals, an open period and the required accounting mappings." },
      { title: "Configure pricing, tax and promotions", description: "Commercial rules reuse the common Catalog and tax references. Price/discount/tax overrides require permission and a reason." },
      { title: "Recognize the customer", description: "Search canonical CRM by name, code, email or phone. Select a customer when needed; walk-in sales remain supported.", cautions: ["Quick create is visible only with real CRM write permission."] },
      { title: "Use loyalty", description: "ACTIVE programmes keep points in a transactional ledger. Automatic earning requires settings.autoEarn=true; redemption locks the account and checks balance/idempotency." },
      { title: "Use gift cards and store credit", description: "The bearer code is shown at issue time but only its hash is stored. Redeem/refund operations are transactional and idempotent." },
      { title: "Checkout", description: "Use cash, Mobile Money, bank, card or stored value according to configuration. The server rechecks pricing, inventory, accounts, customer and permissions." },
      { title: "Use the receipt", description: "Receipts are available as structured JSON or print-friendly HTML. Email/phone are disclosed only with an active RETAIL_RECEIPT_CONTACT consent." },
      { title: "Check devices", description: "Configured scanners, printers, drawers, terminals, displays and scales report browser readiness. Missing WebUSB/WebBluetooth/WebSerial support degrades without blocking POS." },
      { title: "Process returns and exchanges", description: "Returnable quantities account for completed and pending returns. Requesters cannot approve their own refund." },
      { title: "Verify Finance and close", description: "Check entries, valuation, currency-native reporting and historical rates, then have the close validated independently." },
    ],
    limitations: ["A PSP/operator is connected only when a real adapter is registered/configured; DTSC ships no fake external provider.", "Ambiguous multi-currency COGS scenarios require validation before global certification.", "Offline, advanced omnichannel, global multi-store and country packs belong to Shop 2.0 iteration 4."],
  },
  MOBILE_MONEY_AGENCY: {
    code: "MOBILE_MONEY_AGENCY",
    title: "Mobile Money Agency guide — Shop extension",
    summary: "Operate Mobile Money in controlled manual mode or through a connected provider with separated cash/float, asynchronous states, signed webhooks and reconciliation.",
    audience: "Store manager, Mobile Money agent, cashier and controller",
    updatedAt: "2026-08-08",
    capabilities: ["Optional Retail extension", "Configurable wallets", "Separated cash and float", "Deposits/withdrawals", "Fees/commissions", "MANUAL or CONNECTED mode", "INITIATED/PENDING_PROVIDER/CONFIRMED/FAILED/UNKNOWN/RECONCILED", "Signed idempotent webhooks", "Timeout and reconciliation", "Controlled reversal"],
    steps: [
      { title: "Configure wallet and accounts", description: "Link each provider to the real float account and keep a cash session open when the operation has a cash effect. A Mobile Money wallet such as M-Pesa is distinct from the Vodacom Telco network and must keep separate references and accounts." },
      { title: "Choose integration mode", description: "MANUAL keeps controlled operator entry. CONNECTED requires a real registered adapter and active integration.", cautions: ["The browser never declares CONFIRMED by itself in connected mode."] },
      { title: "Prepare the operation", description: "Choose deposit/withdrawal, wallet, phone, amount and fees. Phone normalization remains server-side." },
      { title: "Follow provider state", description: "A connected operation may stay PENDING_PROVIDER or become UNKNOWN. No definitive cash/float business effect is created before provider confirmation." },
      { title: "Reconcile", description: "Authorized controllers retry/reconcile. Duplicate webhooks must not duplicate the business or Finance effect." },
    ],
    limitations: ["Without a real partner adapter, use MANUAL. UNKNOWN is never treated as success."],
  },
  TELCO_TOPUPS: {
    code: "TELCO_TOPUPS",
    title: "Telco top-ups & bundles guide — Shop extension",
    summary: "Operate multi-currency Telco top-ups with separated network, operator and tender accounts, cost/margin, manual or connected provider mode and reconciliation.",
    audience: "Store manager, sales manager, seller, Telco agent and controller",
    updatedAt: "2026-08-14",
    capabilities: ["Optional Retail extension", "Configurable networks", "CDF/USD operator accounts per network", "Concurrent CDF/USD cash tills", "Multi-currency non-cash tender accounts", "Cost and margin", "MANUAL or CONNECTED mode", "Asynchronous provider states", "Signed idempotent webhooks", "Timeout/UNKNOWN/RECONCILED", "Audited reversal"],
    steps: [
      { title: "Configure network accounts", description: "Link each network to a distinct operator account for every operating currency. In DR Congo configure CDF and USD. The Vodacom Telco network remains distinct from the M-Pesa Mobile Money wallet." },
      { title: "Prepare offers", description: "Recurring bundles can be stored as Catalog services with indicative price and cost." },
      { title: "Choose MANUAL or CONNECTED", description: "CONNECTED requires a real adapter. Business SUCCESS is materialized only after provider confirmation." },
      { title: "Execute and follow", description: "For cash, select the CDF or USD till; for other payments, select the tender account. That account currency automatically selects the matching operator account. Then enter destination, offer, price and cost." },
      { title: "Reconcile", description: "Callbacks and retries are idempotent. Controllers can reconcile timeout/unknown cases." },
    ],
    limitations: ["Without a real operator adapter, MANUAL remains the explicit path. No fake provider is shipped to production."],
  },
  RETAIL_DAILY_CLOSE: {
    code: "RETAIL_DAILY_CLOSE",
    title: "Store daily close guide",
    summary: "Close Retail Core with till counts, explained variances, independent validation and operator floats only for enabled extensions.",
    audience: "Cashier, store manager and controller; Mobile Money agent when enabled",
    updatedAt: "2026-08-08",
    capabilities: ["Retail Core close", "Multi-account close", "Denomination counting", "Expected till balance", "Optional floats per currency", "Explained variance", "Independent validation", "Approved variance Finance posting", "History"],
    steps: [
      { title: "Finish operations", description: "Confirm no till operation is running and reconcile important UNKNOWN provider operations before close." },
      { title: "Declare balances", description: "For CASH, denominations must exactly match the declared balance. Keep currencies separate." },
      { title: "Submit", description: "The till moves to pending validation and no longer accepts new movements." },
      { title: "Validate independently", description: "A different authorized person approves or rejects with a reason. Approved variances are posted to Finance." },
    ],
  },
};

export function getRetailUserGuide(code: string, locale: string): ContextualUserGuide {
  const resolved = (code in fr ? code : "RETAIL_POS") as RetailGuideCode;
  return locale === "en" ? en[resolved] : fr[resolved];
}
