import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { normalizeEnterpriseCoreV2Error } from "@/lib/enterprise/core-v2/errors";
import { enterpriseExpenseVisibilityWhere, getEnterpriseFinanceAccess } from "@/lib/enterprise/finance/access";
import { createEnterpriseExpense } from "@/lib/enterprise/finance/expense-service";
import { enterpriseExpenseCreateSchema } from "@/lib/enterprise/finance/validators";
import { prisma } from "@/lib/prisma";
import { getRateLimitKey, rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";

type Params = { params: Promise<{ organizationId: string }> };

export async function GET(req: Request, { params }: Params) {
  const startedAt = Date.now(); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { organizationId } = await params; const access = await getEnterpriseFinanceAccess({ session, organizationId, moduleCode: "FINANCE_BUDGETS", action: "read" }); if (!access) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const url = new URL(req.url); const page = Math.max(1, Number(url.searchParams.get("page") || 1) || 1); const pageSize = Math.min(50, Math.max(5, Number(url.searchParams.get("pageSize") || 20) || 20)); const status = url.searchParams.get("status")?.trim(); const category = url.searchParams.get("category")?.trim(); const supplierId = url.searchParams.get("supplierId")?.trim(); const departmentId = url.searchParams.get("departmentId")?.trim(); const budgetId = url.searchParams.get("budgetId")?.trim(); const purchaseId = url.searchParams.get("purchaseId")?.trim(); const currency = url.searchParams.get("currency")?.trim().toUpperCase(); const search = url.searchParams.get("search")?.trim(); const from = url.searchParams.get("from"); const to = url.searchParams.get("to");
  const filters: Prisma.EnterpriseExpenseWhereInput[] = [enterpriseExpenseVisibilityWhere({ organizationId, userId: session.userId, canSeeAll: access.canSeeAll })]; if (status) filters.push({ status }); if (category) filters.push({ category }); if (supplierId) filters.push({ supplierId }); if (departmentId) filters.push({ departmentId }); if (budgetId) filters.push({ budgetLine: { budgetId } }); if (purchaseId) filters.push({ purchaseId }); if (currency) filters.push({ currency }); if (search) filters.push({ OR: [{ reference: { contains: search, mode: "insensitive" } }, { title: { contains: search, mode: "insensitive" } }, { description: { contains: search, mode: "insensitive" } }] }); if (from || to) filters.push({ expenseDate: { ...(from ? { gte: new Date(from) } : {}), ...(to ? { lte: new Date(to) } : {}) } });
  const where: Prisma.EnterpriseExpenseWhereInput = { AND: filters }; const [items, total] = await Promise.all([prisma.enterpriseExpense.findMany({ where, include: { supplier: { select: { id: true, legalName: true, displayName: true } }, purchase: { select: { id: true, reference: true, title: true, totalAmount: true } }, budgetLine: { select: { id: true, name: true, budget: { select: { id: true, reference: true, title: true, currency: true, status: true } } } } }, orderBy: [{ expenseDate: "desc" }, { createdAt: "desc" }], skip: (page - 1) * pageSize, take: pageSize }), prisma.enterpriseExpense.count({ where })]);
  await writeApiLog({ request: req, statusCode: 200, userId: session.userId, startedAt, metadata: { organizationId, domain: "expenses", page, pageSize } }); return NextResponse.json({ items: items.map((item) => ({ ...item, budgetStatus: item.budgetLineId ? "BUDGETED" : "UNBUDGETED" })), pagination: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) }, canManage: access.canManage, canCreate: access.canCreate });
}

export async function POST(req: Request, { params }: Params) {
  const startedAt = Date.now(); if (!isSameOriginRequest(req)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const limited = await rateLimit(getRateLimitKey(req, `enterprise-expenses:${session.userId}`), 100, 60 * 60 * 1000); if (!limited.ok) return NextResponse.json({ error: "Too many requests" }, { status: 429 }); const { organizationId } = await params; const access = await getEnterpriseFinanceAccess({ session, organizationId, moduleCode: "FINANCE_BUDGETS", action: "write" }); if (!access?.canCreate) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = enterpriseExpenseCreateSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message || "Dépense invalide." }, { status: 400 });
  try { const expense = await createEnterpriseExpense(organizationId, session.userId, parsed.data); await writeAuditLog({ userId: session.userId, action: "ENTERPRISE_EXPENSE_CREATED", entity: "EnterpriseExpense", entityId: expense.id, request: req, metadata: { organizationId, reference: expense.reference, budgetStatus: expense.budgetLineId ? "BUDGETED" : "UNBUDGETED" } }); await writeApiLog({ request: req, statusCode: 201, userId: session.userId, startedAt, metadata: { organizationId, domain: "expenses" } }); return NextResponse.json({ ok: true, expense }, { status: 201 }); }
  catch (error) { const normalized = normalizeEnterpriseCoreV2Error(error); await writeApiLog({ request: req, statusCode: normalized.status, userId: session.userId, startedAt, metadata: { organizationId, domain: "expenses", error: normalized.code } }); return NextResponse.json({ error: normalized.code, message: normalized.message }, { status: normalized.status }); }
}
