import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeAuditLog } from "@/lib/audit";
import { getHealthLaboratoryAccess } from "@/lib/health-laboratory-access";
import { healthLabRequestUpdateSchema } from "@/lib/health-laboratory-validators";
import { maskHealthLabSensitive,updateHealthLabRequest } from "@/lib/health-laboratory";
import { prisma } from "@/lib/prisma";
import { getRateLimitKey,rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";

type Params={params:Promise<{organizationId:string;requestId:string}>};
export async function GET(req:Request,{params}:Params){void req;const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const {organizationId,requestId}=await params,access=await getHealthLaboratoryAccess({session,organizationId,action:"read"});if(!access)return NextResponse.json({error:"Forbidden"},{status:403});const request=await prisma.healthLabRequest.findFirst({where:{id:requestId,organizationId},include:{patient:true,consultation:{include:{professional:{select:{name:true}}}},medicalRecord:{select:{id:true,recordNumber:true}},requestedBy:{select:{name:true}},assignedLabStaff:{select:{name:true}},mainTest:true,sampledBy:{select:{name:true}},resultEnteredBy:{select:{name:true}},validatedBy:{select:{name:true}},cancelledBy:{select:{name:true}},items:{include:{testCatalog:true}},events:{orderBy:{createdAt:"desc"},take:80,include:{actor:{select:{name:true}}}}}});if(!request)return NextResponse.json({error:"Not found"},{status:404});return NextResponse.json({request:maskHealthLabSensitive(request,access.canViewSensitive),permissions:{canUpdate:access.canUpdate,canCancel:access.canCancel,canCollect:access.canCollect,canEnterResult:access.canEnterResult,canValidate:access.canValidate,canCorrect:access.canCorrect,canTransmit:access.canTransmit,canViewSensitive:access.canViewSensitive}})}
export async function PATCH(req:Request,{params}:Params){if(!isSameOriginRequest(req))return NextResponse.json({error:"Forbidden"},{status:403});const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const limited=await rateLimit(getRateLimitKey(req,`health-lab-update:${session.userId}`),100,3600000);if(!limited.ok)return NextResponse.json({error:"Too many requests"},{status:429});const {organizationId,requestId}=await params,access=await getHealthLaboratoryAccess({session,organizationId,action:"write"});if(!access?.canUpdate)return NextResponse.json({error:"Forbidden"},{status:403});const parsed=healthLabRequestUpdateSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid payload",message:"Les modifications de la demande laboratoire sont invalides."},{status:400});try{const request=await updateHealthLabRequest(organizationId,requestId,session.userId,parsed.data);if(!request)return NextResponse.json({error:"Not found"},{status:404});await writeAuditLog({userId:session.userId,action:"HEALTH_LAB_REQUEST_UPDATED",entity:"HealthLabRequest",entityId:requestId,request:req,metadata:{organizationId,reason:parsed.data.reason}});return NextResponse.json({ok:true,request})}catch(error){const code=error instanceof Error?error.message:"UPDATE_FAILED";const message=code==="REQUEST_LOCKED"?"Une demande validée, transmise, annulée ou rejetée ne peut pas être modifiée librement.":code==="RELATION_LOCKED"?"Le patient ou la consultation ne peut plus être changé après prélèvement.":"Modification de la demande laboratoire impossible.";return NextResponse.json({error:code,message},{status:409})}}
