import type { ActivityEntityType } from "@/components/activities/activity-types";

export const ACTIVITY_STATUS_TRANSITIONS: Partial<Record<ActivityEntityType, Record<string, readonly string[]>>> = {
  OPERATION: {
    DRAFT: ["PLANNED", "CANCELED"],
    PLANNED: ["IN_PROGRESS", "CANCELED"],
    IN_PROGRESS: ["WAITING", "BLOCKED", "COMPLETED", "CANCELED"],
    WAITING: ["IN_PROGRESS", "BLOCKED", "CANCELED"],
    BLOCKED: ["IN_PROGRESS", "CANCELED"],
  },
  DEPARTMENT_REQUEST: {
    NEW: ["ACCEPTED", "REJECTED", "CANCELED"],
    ACCEPTED: ["IN_PROGRESS", "REJECTED", "CANCELED"],
    IN_PROGRESS: ["WAITING_INFORMATION", "DONE", "BLOCKED", "CANCELED"],
    WAITING_INFORMATION: ["IN_PROGRESS", "DONE", "CANCELED"],
    BLOCKED: ["IN_PROGRESS", "REJECTED", "CANCELED"],
  },
  BLOCKER: {
    OPEN: ["IN_PROGRESS", "ESCALATED", "CANCELED"],
    IN_PROGRESS: ["RESOLVED", "UNRESOLVED", "ESCALATED", "CANCELED"],
    UNRESOLVED: ["IN_PROGRESS", "ESCALATED", "CANCELED"],
    ESCALATED: ["IN_PROGRESS", "RESOLVED", "CANCELED"],
  },
  MEETING: {
    PLANNED: ["HELD", "POSTPONED", "CANCELED"],
    POSTPONED: ["PLANNED", "CANCELED"],
    HELD: ["MINUTES_PUBLISHED", "CLOSED"],
    MINUTES_PUBLISHED: ["CLOSED"],
  },
  COLLAB_REQUEST: {
    SUBMITTED: ["IN_PROGRESS", "ANSWERED", "REJECTED", "CANCELED"],
    IN_PROGRESS: ["WAITING_RESPONSE", "ANSWERED", "TREATED", "REJECTED", "CANCELED"],
    WAITING_RESPONSE: ["IN_PROGRESS", "ANSWERED", "TREATED", "CANCELED"],
    ANSWERED: ["TREATED", "IN_PROGRESS"],
  },
  CEO_OBJECTIVE: {
    PLANNED: ["IN_PROGRESS", "CANCELED"],
    IN_PROGRESS: ["ACHIEVED", "MISSED", "LATE", "CANCELED"],
    LATE: ["IN_PROGRESS", "ACHIEVED", "MISSED", "CANCELED"],
  },
  CEO_SUPERVISION: {
    OPEN: ["IN_PROGRESS", "CANCELED"],
    IN_PROGRESS: ["DONE", "CANCELED"],
    DONE: ["ARCHIVED"],
  },
  SCO_PURCHASE_REQUEST: {
    DRAFT: ["SUBMITTED", "CANCELED"],
    SUBMITTED: ["SCO_REVIEW", "REJECTED", "CANCELED"],
    SCO_REVIEW: ["WAITING_BUDGET", "WAITING_HR_CFO_VALIDATION", "WAITING_CEO_VALIDATION", "APPROVED", "REJECTED", "CANCELED"],
    WAITING_BUDGET: ["SCO_REVIEW", "WAITING_HR_CFO_VALIDATION", "REJECTED", "CANCELED"],
    WAITING_HR_CFO_VALIDATION: ["WAITING_CEO_VALIDATION", "APPROVED", "REJECTED", "CANCELED"],
    WAITING_CEO_VALIDATION: ["APPROVED", "REJECTED", "CANCELED"],
    APPROVED: ["ORDERED", "CANCELED"],
    ORDERED: ["RECEIVED", "CANCELED"],
  },
  SCO_LOGISTICS: {
    PLANNED: ["PREPARING", "CANCELED"],
    PREPARING: ["WAITING_MATERIAL", "WAITING_BUDGET", "READY", "CANCELED"],
    WAITING_MATERIAL: ["PREPARING", "READY", "CANCELED"],
    WAITING_BUDGET: ["PREPARING", "READY", "CANCELED"],
    READY: ["IN_PROGRESS", "CANCELED"],
    IN_PROGRESS: ["COMPLETED", "CANCELED"],
  },
  MPO_PROJECT: {
    DRAFT: ["SCOPING", "CANCELED"],
    SCOPING: ["INTERNAL_VALIDATION", "BLOCKED", "CANCELED"],
    INTERNAL_VALIDATION: ["WAITING_CTO", "WAITING_BUDGET", "WAITING_SCO_RESOURCES", "DEVELOPMENT", "BLOCKED", "CANCELED"],
    WAITING_CTO: ["DEVELOPMENT", "BLOCKED", "CANCELED"],
    WAITING_BUDGET: ["DEVELOPMENT", "BLOCKED", "CANCELED"],
    WAITING_SCO_RESOURCES: ["DEVELOPMENT", "BLOCKED", "CANCELED"],
    DEVELOPMENT: ["TESTING", "BLOCKED", "CANCELED"],
    TESTING: ["WAITING_CLIENT", "DELIVERED", "DEVELOPMENT", "BLOCKED", "CANCELED"],
    WAITING_CLIENT: ["DELIVERED", "DEVELOPMENT", "BLOCKED", "CANCELED"],
    BLOCKED: ["SCOPING", "DEVELOPMENT", "CANCELED"],
    DELIVERED: ["CLOSED"],
  },
  MPO_RECORD: {
    DRAFT: ["IN_PROGRESS", "CANCELED"],
    IN_PROGRESS: ["SUBMITTED", "WAITING", "BLOCKED", "CANCELED"],
    SUBMITTED: ["WAITING", "VALIDATED", "BLOCKED", "CANCELED"],
    WAITING: ["IN_PROGRESS", "VALIDATED", "BLOCKED", "CANCELED"],
    BLOCKED: ["IN_PROGRESS", "CANCELED"],
    VALIDATED: ["DELIVERED", "ARCHIVED"],
    DELIVERED: ["ARCHIVED"],
  },
  CTO_PROJECT: {
    DRAFT: ["TECH_ANALYSIS", "CANCELED"],
    TECH_ANALYSIS: ["WAITING_MPO", "WAITING_BUDGET", "WAITING_MATERIAL", "DEVELOPMENT", "BLOCKED", "CANCELED"],
    WAITING_MPO: ["TECH_ANALYSIS", "DEVELOPMENT", "BLOCKED", "CANCELED"],
    WAITING_BUDGET: ["TECH_ANALYSIS", "DEVELOPMENT", "BLOCKED", "CANCELED"],
    WAITING_MATERIAL: ["TECH_ANALYSIS", "DEVELOPMENT", "BLOCKED", "CANCELED"],
    DEVELOPMENT: ["REVIEW", "BLOCKED", "CANCELED"],
    REVIEW: ["DEVELOPMENT", "TESTING", "BLOCKED", "CANCELED"],
    TESTING: ["DEVELOPMENT", "PREPRODUCTION", "BLOCKED", "CANCELED"],
    PREPRODUCTION: ["TESTING", "PRODUCTION", "BLOCKED", "CANCELED"],
    PRODUCTION: ["DELIVERED", "BLOCKED"],
    BLOCKED: ["TECH_ANALYSIS", "DEVELOPMENT", "CANCELED"],
    DELIVERED: ["CLOSED"],
  },
  CTO_RECORD: {
    DRAFT: ["OPEN", "CANCELED"],
    OPEN: ["ANALYSIS", "IN_PROGRESS", "BLOCKED", "CANCELED"],
    ANALYSIS: ["IN_PROGRESS", "BLOCKED", "CANCELED"],
    IN_PROGRESS: ["REVIEW", "TESTING", "BLOCKED", "CANCELED"],
    REVIEW: ["IN_PROGRESS", "TESTING", "BLOCKED", "CANCELED"],
    TESTING: ["IN_PROGRESS", "RESOLVED", "VALIDATED", "BLOCKED", "CANCELED"],
    BLOCKED: ["ANALYSIS", "IN_PROGRESS", "CANCELED"],
    RESOLVED: ["VALIDATED", "ARCHIVED"],
    VALIDATED: ["ARCHIVED"],
  },
};

export const ACTIVITY_STATUS_REASON_REQUIRED = new Set([
  "BLOCKED",
  "CANCELED",
  "CANCELLED",
  "REJECTED",
  "MISSED",
  "UNRESOLVED",
  "ESCALATED",
]);

export function normalizeActivityStatus(value: string) {
  return value.trim().toUpperCase().replaceAll(" ", "_").replaceAll("É", "E");
}

export function getActivityStatusTransitions(entityType: ActivityEntityType, currentStatus: string) {
  const normalizedStatus = normalizeActivityStatus(currentStatus);
  return [...(ACTIVITY_STATUS_TRANSITIONS[entityType]?.[normalizedStatus] || [])];
}

export function getQuickActivityStatusTransitions(entityType: ActivityEntityType, currentStatus: string) {
  return getActivityStatusTransitions(entityType, currentStatus)
    .filter((status) => !ACTIVITY_STATUS_REASON_REQUIRED.has(status))
    .slice(0, 2);
}
