import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

const nil=(value?:string)=>value?.trim()||null;
const code=()=>`HP-${new Date().getFullYear()}-${randomUUID().slice(0,6).toUpperCase()}`;
export function healthBatchStatus(batch:{status:string;expiryDate:Date|null;availableQuantity:Prisma.Decimal|number},now=new Date()){if(["BLOCKED","ARCHIVED"].includes(batch.status))return batch.status;if(batch.expiryDate&&batch.expiryDate<now)return"EXPIRED";if(Number(batch.availableQuantity)<=0)return"DEPLETED";if(batch.expiryDate&&batch.expiryDate.getTime()<=now.getTime()+90*86400000)return"NEAR_EXPIRY";return"AVAILABLE";}
export async function createHealthPharmacyProduct(organizationId:string,actorUserId:string,data:Record<string,unknown>){
 const optionalNumber=(value:unknown)=>value===""||value===undefined||value===null?null:Number(value);
 const initial=Number(data.initialStock||0);return prisma.$transaction(async tx=>{const legacy=await tx.enterpriseSectorRecord.create({data:{organizationId,sectorCode:"HEALTH_CARE",moduleCode:"INTERNAL_PHARMACY",recordType:"PHARMACY_ITEM",title:String(data.name),summary:String(data.category),status:String(data.status||"ACTIVE"),createdById:actorUserId,payloadJson:{productCode:"generated"}}});const product=await tx.healthPharmacyProduct.create({data:{organizationId,legacyRecordId:legacy.id,productCode:code(),name:String(data.name),genericName:nil(data.genericName as string),category:String(data.category),pharmaceuticalForm:nil(data.pharmaceuticalForm as string),strength:nil(data.strength as string),unit:String(data.unit),description:nil(data.description as string),currentStock:initial,minimumStock:Number(data.minimumStock||0),criticalStock:optionalNumber(data.criticalStock),maximumStock:optionalNumber(data.maximumStock),trackBatches:Boolean(data.trackBatches),trackExpiry:Boolean(data.trackExpiry),storageLocation:nil(data.storageLocation as string),purchasePrice:optionalNumber(data.purchasePrice),sellingPrice:optionalNumber(data.sellingPrice),billable:Boolean(data.billable),billingCode:nil(data.billingCode as string),supplierReference:nil(data.supplierReference as string),isSensitive:Boolean(data.isSensitive),controlLevel:String(data.controlLevel),prescriptionRequired:Boolean(data.prescriptionRequired),specialAuthorizationRequired:Boolean(data.specialAuthorizationRequired),safetyNotes:nil(data.safetyNotes as string),status:String(data.status),createdById:actorUserId}});if(initial>0)await tx.healthPharmacyStockMovement.create({data:{organizationId,productId:product.id,movementType:"INITIAL_STOCK",quantity:initial,stockBefore:0,stockAfter:initial,reason:"Stock initial du produit",createdById:actorUserId}});return product;});
}
export async function validateHealthPharmacyRelations(organizationId:string,data:{patientId?:string;consultationId?:string;departmentId?:string;prescriberId?:string}){const [patient,consultation,department,prescriber]=await Promise.all([data.patientId?prisma.healthPatient.findFirst({where:{id:data.patientId,organizationId},select:{id:true}}):null,data.consultationId?prisma.healthConsultation.findFirst({where:{id:data.consultationId,organizationId},select:{id:true,patientId:true}}):null,data.departmentId?prisma.enterpriseDepartment.findFirst({where:{id:data.departmentId,organizationId},select:{id:true}}):null,data.prescriberId?prisma.healthStaffAssignment.findFirst({where:{organizationId,userId:data.prescriberId,status:"ACTIVE"},select:{userId:true}}):null]);if(data.patientId&&!patient)throw new Error("INVALID_PATIENT");if(data.consultationId&&!consultation)throw new Error("INVALID_CONSULTATION");if(patient&&consultation&&consultation.patientId!==patient.id)throw new Error("PATIENT_MISMATCH");if(data.departmentId&&!department)throw new Error("INVALID_DEPARTMENT");if(data.prescriberId&&!prescriber)throw new Error("INVALID_PRESCRIBER");}
export async function actionHealthPharmacy(organizationId:string,actorUserId:string,data:{action:string;productId:string;batchId?:string;batchNumber?:string;quantity?:number|"";manufacturingDate?:Date;expiryDate?:Date;purchasePrice?:number|"";supplierReference?:string;source?:string;destination?:string;patientId?:string;consultationId?:string;departmentId?:string;prescriberId?:string;reason?:string;comment?:string;referenceDocument?:string;status?:string},canAuthorizeSensitive:boolean){
 const product=await prisma.healthPharmacyProduct.findFirst({where:{id:data.productId,organizationId}});if(!product)throw new Error("NOT_FOUND");if(["ARCHIVED","BLOCKED"].includes(product.status)&&["stock_exit","dispense"].includes(data.action))throw new Error("PRODUCT_BLOCKED");if(!data.reason?.trim()&&["stock_exit","dispense","adjust","archive","change_status"].includes(data.action))throw new Error("REASON_REQUIRED");if((product.isSensitive||product.specialAuthorizationRequired)&&["stock_exit","dispense","adjust"].includes(data.action)&&!canAuthorizeSensitive)throw new Error("SENSITIVE_FORBIDDEN");await validateHealthPharmacyRelations(organizationId,{patientId:data.patientId,consultationId:data.consultationId,departmentId:data.departmentId,prescriberId:data.prescriberId});
 return prisma.$transaction(async tx=>{if(data.action==="add_batch"){const batchQuantity=Number(data.quantity||0),batchPurchasePrice=data.purchasePrice===""||data.purchasePrice===undefined?undefined:Number(data.purchasePrice);if(!data.batchNumber||batchQuantity<=0)throw new Error("INVALID_QUANTITY");const batch=await tx.healthPharmacyBatch.create({data:{organizationId,productId:product.id,batchNumber:data.batchNumber,initialQuantity:batchQuantity,availableQuantity:batchQuantity,manufacturingDate:data.manufacturingDate,expiryDate:data.expiryDate,supplierReference:nil(data.supplierReference),purchasePrice:batchPurchasePrice,createdById:actorUserId}});const after=Number(product.currentStock)+batchQuantity;await tx.healthPharmacyProduct.update({where:{id:product.id},data:{currentStock:after,updatedById:actorUserId}});await tx.healthPharmacyStockMovement.create({data:{organizationId,productId:product.id,batchId:batch.id,movementType:"ENTRY",quantity:batchQuantity,stockBefore:product.currentStock,stockAfter:after,source:"Nouveau lot",reason:data.reason||"Création du lot",createdById:actorUserId}});return batch;}
 if(data.action==="archive"||data.action==="change_status"){return tx.healthPharmacyProduct.update({where:{id:product.id},data:{status:data.action==="archive"?"ARCHIVED":data.status,archivedAt:data.action==="archive"?new Date():undefined,archivedById:data.action==="archive"?actorUserId:undefined,updatedById:actorUserId}});}
 if(data.action==="block_batch"||data.action==="archive_batch"){if(!data.batchId)throw new Error("INVALID_BATCH");const targetBatch=await tx.healthPharmacyBatch.findFirst({where:{id:data.batchId,organizationId,productId:product.id},select:{id:true}});if(!targetBatch)throw new Error("INVALID_BATCH");return tx.healthPharmacyBatch.update({where:{id:targetBatch.id},data:{status:data.action==="block_batch"?"BLOCKED":"ARCHIVED",notes:nil(data.comment),updatedById:actorUserId}});}
 const quantity=Number(data.quantity||0);if(quantity<=0)throw new Error("INVALID_QUANTITY");const outgoing=["stock_exit","dispense"].includes(data.action)||data.action==="adjust"&&String(data.source)==="NEGATIVE";let batch=data.batchId?await tx.healthPharmacyBatch.findFirst({where:{id:data.batchId,organizationId,productId:product.id}}):null;if(outgoing&&product.trackBatches&&!batch)batch=await tx.healthPharmacyBatch.findFirst({where:{organizationId,productId:product.id,availableQuantity:{gte:quantity},status:"AVAILABLE",OR:[{expiryDate:null},{expiryDate:{gt:new Date()}}]},orderBy:[{expiryDate:"asc"},{createdAt:"asc"}]});if(product.trackBatches&&!batch)throw new Error("NO_SELLABLE_BATCH");if(batch&&healthBatchStatus(batch)==="EXPIRED")throw new Error("BATCH_EXPIRED");if(batch&&["BLOCKED","ARCHIVED"].includes(batch.status))throw new Error("BATCH_BLOCKED");const delta=outgoing?-quantity:quantity,after=Number(product.currentStock)+delta;if(after<0)throw new Error("INSUFFICIENT_STOCK");if(batch){const batchAfter=Number(batch.availableQuantity)+delta;if(batchAfter<0)throw new Error("INSUFFICIENT_BATCH");await tx.healthPharmacyBatch.update({where:{id:batch.id},data:{availableQuantity:batchAfter,updatedById:actorUserId}});}await tx.healthPharmacyProduct.update({where:{id:product.id},data:{currentStock:after,status:after<=0?"OUT_OF_STOCK":product.status==="OUT_OF_STOCK"?"ACTIVE":product.status,updatedById:actorUserId}});const movement=await tx.healthPharmacyStockMovement.create({data:{organizationId,productId:product.id,batchId:batch?.id,movementType:data.action==="dispense"?"DISPENSATION":data.action==="stock_entry"?"ENTRY":data.action==="adjust"?(outgoing?"ADJUSTMENT_NEGATIVE":"ADJUSTMENT_POSITIVE"):"EXIT",quantity,stockBefore:product.currentStock,stockAfter:after,source:nil(data.source),destination:nil(data.destination),patientId:nil(data.patientId),consultationId:nil(data.consultationId),departmentId:nil(data.departmentId),reason:data.reason||"Mouvement de stock",comment:nil(data.comment),referenceDocument:nil(data.referenceDocument),isSensitive:product.isSensitive,requiresAuthorization:product.isSensitive,authorizedById:product.isSensitive?actorUserId:null,authorizedAt:product.isSensitive?new Date():null,createdById:actorUserId}});if(data.action==="dispense"){if(!data.patientId)throw new Error("PATIENT_REQUIRED");await tx.healthPharmacyDispensation.create({data:{organizationId,movementId:movement.id,patientId:data.patientId,consultationId:nil(data.consultationId),productId:product.id,batchId:batch?.id,quantity,dispensedById:actorUserId,prescriberId:nil(data.prescriberId),billable:product.billable,billingStatus:product.billable?"TO_BILL":"NOT_BILLABLE",notes:nil(data.comment)}});}return movement;});
}
