export const roleLabels = {
  ADMIN: "Administrateur",
  MANAGER: "Manager",
  CLIENT: "Client",
  SUPPORT: "Support",
} as const;

export const statusLabels = {
  ACTIVE: "Actif",
  SUSPENDED: "Suspendu",
  PENDING: "En attente",
  OPEN: "Ouvert",
  IN_PROGRESS: "En cours",
  RESOLVED: "Résolu",
  CLOSED: "Clôturé",
  LOW: "Faible",
  MEDIUM: "Moyenne",
  HIGH: "Haute",
  URGENT: "Urgente",
  CRITICAL: "Critique",
  PROCESSING: "Traitement en cours",
  READY: "Prêt",
  FAILED: "Échec",
  ACCEPTED: "Accepté",
  PAID: "Payé",
  CANCELED: "Annulé",
  DRAFT: "Brouillon",
  ISSUED: "Émise",
  PAST_DUE: "En retard",
  EXPIRED: "Expiré",
  PENDING_PAYMENT: "Paiement en attente",
  CANCELED_SUBSCRIPTION: "Abonnement annulé",
  INACTIVE: "Inactif",
  ONBOARDING: "Intégration",
  ON_LEAVE: "En congé",
  EXITED: "Sorti",
  PERMANENT: "Permanent",
  CONSULTANT: "Consultant",
  PART_TIME: "Temps partiel",
  INTERN: "Stagiaire",
  TEMPORARY: "Temporaire",
  COMPLETE: "Complet",
  TO_REVIEW: "À vérifier",
  MISSING_DOCUMENTS: "Documents manquants",
  OPEN_BUDGET: "Budget ouvert",
  MONITORING: "Suivi actif",
  OVER_BUDGET: "Dépassement",
  VALIDATED: "Validé",
  REJECTED: "Rejeté",
  ARCHIVED: "Archivé",
  IN: "Entrée",
  OUT: "Sortie",
  MANUAL: "Manuel",
  SUBSCRIPTION: "Abonnement",
  PAYROLL: "Paie",
  SCO: "SCO",
  CASH: "Caisse",
  BANK: "Banque",
  MOBILE_MONEY: "Mobile Money",
  PROJECT: "Compte projet",
  OPERATIONS: "Compte opérationnel",
  STOCK: "Stock",
  ASSET: "Actif",
  EQUIPMENT: "Équipement",
  CONSUMABLE: "Consommable",
  SERVICE_TOOL: "Outil de service",
  WATCHLIST: "À surveiller",
  AVAILABLE: "Disponible",
  LOW_STOCK: "Stock faible",
  RESERVED: "Réservé",
  OUT_OF_STOCK: "Rupture",
  ASSIGNED: "Assigné",
  MAINTENANCE: "Maintenance",
  LOST: "Perdu",
  RETIRED: "Retiré",
  NEW: "Neuf",
  GOOD: "Bon",
  FAIR: "Moyen",
  DAMAGED: "Endommagé",
  REPAIR: "Réparation",
  PLANNED: "Planifié",
  BLOCKED: "Bloqué",
  SUBMITTED: "Soumis",
  ORDERED: "Commandé",
  RECEIVED: "Reçu",
  PENDING_REVIEW: "Vérification en attente",
  INSUFFICIENT: "Insuffisant",
  APPROVED: "Approuvé",
  NORMAL: "Normale",
  WAITING: "En attente",
  TODO: "À faire",
  PENDING_VALIDATION: "En attente de validation",
  LATE: "En retard",
  ADMINISTRATIVE: "Administrative",
  COMMERCIAL: "Commerciale",
  TECHNICAL: "Technique",
  FINANCIAL: "Financière",
  LEGAL: "Juridique",
  HR: "RH",
  CLIENT_SUPPORT: "Support client",
  MARKETING: "Marketing",
  REPORTING: "Reporting",
  MEETING: "Réunion",
  CLIENT_FOLLOW_UP: "Suivi client",
  DELIVERY: "Livraison",
  OTHER: "Autre",
  DAILY: "Quotidienne",
  WEEKLY: "Hebdomadaire",
  MONTHLY: "Mensuelle",
  CUSTOM: "Personnalisée",
  WAITING_INFORMATION: "En attente d'information",
  DONE: "Traitée",
  TASK: "Tâche",
  OPERATION: "Opération",
  DEPARTMENT_REQUEST: "Demande inter-département",
  FINANCE: "Finance",
  INFORMATION: "Information",
  VALIDATION_DELAY: "Retard de validation",
  UNRESOLVED: "Non résolu",
  ESCALATED: "Escaladé",
  COORDINATION: "Coordination",
  STRATEGIC: "Stratégique",
  OPERATIONAL: "Opérationnelle",
  FOLLOW_UP: "Suivi",
  HELD: "Tenue",
  POSTPONED: "Reportée",
  PUBLISHED: "Publié",
  DEPARTMENT: "Département",
  EMPLOYEE: "Collaborateur",
  CEO: "CEO",
  CEO_OBJECTIVE: "Objectif CEO",
  CEO_SUPERVISION: "Supervision CEO",
  COO: "COO",
  CTO: "CTO",
  HR_CFO: "RH & CFO",
  MPO: "MPO",
  COLLABORATOR: "Collaborateur",
  HR_MANAGER: "Responsable RH",
  FINANCE_MANAGER: "Responsable Finance",
  COMMERCIAL_MANAGER: "Responsable Commercial",
  TECHNICAL_MANAGER: "Responsable Technique",
  MARKETING_MANAGER: "Responsable Marketing",
  SUPPORT_MANAGER: "Responsable Support Client",
  ADMIN_ASSISTANT: "Assistant administratif",
  OPERATIONS_AGENT: "Agent opérationnel",
  ACHIEVED: "Atteint",
  MISSED: "Non atteint",
  OBSERVATION: "Observation",
  DECISION: "Décision",
  INSTRUCTION: "Instruction",
  RISK: "Risque",
  OPPORTUNITY: "Opportunité",
  VALIDATION: "Validation",
  BLACKLISTED: "Blacklisté",
  IT_HARDWARE: "Matériel informatique",
  OFFICE_SUPPLIES: "Fournitures bureau",
  CLOUD_SERVICES: "Services cloud",
  NETWORK_EQUIPMENT: "Équipements réseau",
  LOGISTICS: "Logistique",
  TRANSPORT: "Transport",
  PRINTING: "Impression",
  TECHNICAL_PROVIDER: "Prestataire technique",
  SCO_REVIEW: "En étude SCO",
  WAITING_BUDGET: "En attente budget",
  WAITING_HR_CFO_VALIDATION: "En attente validation HR & CFO",
  WAITING_CEO_VALIDATION: "En attente validation CEO",
  PREPARING: "En préparation",
  WAITING_MATERIAL: "En attente matériel",
  RETURNED: "Retourné",
  STOCK_IN: "Entrée stock",
  STOCK_OUT: "Sortie stock",
  RETURN: "Retour stock",
  LOSS: "Perte",
  DAMAGE: "Détérioration",
  ADJUSTMENT: "Ajustement inventaire",
  CLIENT_MISSION: "Mission client",
  TRAINING: "Formation",
  EVENT: "Événement",
  TECHNICAL_INTERVENTION: "Intervention technique",
  EXTERNAL_MEETING: "Réunion externe",
  INSTALLATION: "Installation",
  FIELD_SUPPORT: "Support terrain",
  PROJECT_PRESENTATION: "Présentation projet",
  WEB_APP: "Application web",
  MOBILE_APP: "Application mobile",
  SAAS_PLATFORM: "Plateforme SaaS",
  BI_DASHBOARD: "Tableau de bord BI",
  DATA_PROJECT: "Projet data",
  AI_PROJECT: "Projet IA",
  AUTOMATION: "Automatisation",
  CHATBOT: "Chatbot",
  ERP: "ERP",
  CRM: "CRM",
  CLIENT_PORTAL: "Portail client",
  DIGITAL_HEALTH: "Santé digitale",
  INTERNAL_DTSC: "Projet interne DTSC",
  CLIENT_PROJECT: "Projet client",
  DIGITAL_TRANSFORMATION: "Transformation numérique",
  SCOPING: "En cadrage",
  INTERNAL_VALIDATION: "En validation interne",
  WAITING_CTO: "En attente CTO",
  WAITING_SCO_RESOURCES: "En attente ressources SCO",
  DEVELOPMENT: "En développement",
  TESTING: "En test",
  WAITING_CLIENT: "En attente client",
  DELIVERED: "Livré",
  NEEDS_ASSESSMENT: "Cadrage des besoins",
  SPECIFICATION: "Cahier des charges",
  DELIVERABLE: "Livrable",
  RISK_BLOCKER: "Risque ou blocage",
  CTO_COLLABORATION: "Collaboration CTO",
  COO_COORDINATION: "Coordination COO",
  BUDGET_REQUEST: "Demande budgétaire",
  SCO_MATERIAL_REQUEST: "Besoin matériel SCO",
  PROJECT_REPORT: "Rapport projet",
  PROJECT_WORKFLOW: "Workflow projet",
  PROJECT_DOCUMENTATION: "Documentation projet",
  DIGITAL_OPPORTUNITY: "Veille et opportunité numérique",
  BACKEND: "Backend",
  FRONTEND: "Frontend",
  API: "API",
  AI_ML: "IA / Machine Learning",
  DATABASE: "Base de données",
  EXTERNAL_INTEGRATION: "Intégration externe",
  INFRASTRUCTURE: "Infrastructure",
  SECURITY: "Sécurité",
  TECH_ANALYSIS: "En analyse technique",
  WAITING_MPO: "En attente MPO",
  PREPRODUCTION: "Préproduction",
  PRODUCTION: "Production",
  ARCHITECTURE: "Architecture",
  TECH_TASK: "Tâche technique",
  API_INTEGRATION: "API et intégration",
  DATABASE_MODEL: "Base et modèle de données",
  DEPLOYMENT: "Déploiement",
  SECURITY_REVIEW: "Sécurité technique",
  BUG_INCIDENT: "Bug ou incident",
  TECH_DOCUMENTATION: "Documentation technique",
  QUALITY_REVIEW: "Qualité et tests",
  MPO_COLLABORATION: "Collaboration MPO",
  BUDGET_NEED: "Besoin budgétaire",
  SCO_MATERIAL_NEED: "Besoin matériel SCO",
  INNOVATION: "Innovation",
  CTO_REPORT: "Rapport CTO",
  MPO_PROJECT: "Projet MPO",
  MPO_RECORD: "Registre MPO",
  CTO_PROJECT: "Projet CTO",
  CTO_RECORD: "Registre CTO",
  SCO_PURCHASE_REQUEST: "Demande d'achat SCO",
  SCO_VENDOR: "Fournisseur SCO",
  SCO_MATERIAL: "Bien matériel SCO",
  SCO_INVENTORY: "Stock SCO",
  SCO_ASSET: "Actif SCO",
  SCO_LOGISTICS: "Mission logistique SCO",
} as const;

export const publicationCategoryLabels = {
  RESSOURCE: "Ressource",
  ARTICLE: "Article",
  GUIDE: "Guide",
  CAS_PRATIQUE: "Cas pratique",
  ANNONCE: "Annonce",
  PROJET: "Projet",
} as const;

export function formatEnumLabel(value: string) {
  const explicit =
    roleLabels[value as keyof typeof roleLabels] ||
    statusLabels[value as keyof typeof statusLabels] ||
    publicationCategoryLabels[value as keyof typeof publicationCategoryLabels];

  if (explicit) {
    return explicit;
  }

  return value
    .toLowerCase()
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
