export const roleLabels = {
  ADMIN: "Administrateur",
  MANAGER: "Manager",
  CLIENT: "Client",
  SUPPORT: "Support",
} as const;

export const statusLabels = {
  ACTIVE: "Actif",
  SUSPENDED: "Suspendu",
  PENDING: "En attente",
  OPEN: "Ouvert",
  IN_PROGRESS: "En cours",
  RESOLVED: "Résolu",
  CLOSED: "Clôturé",
  LOW: "Faible",
  MEDIUM: "Moyenne",
  HIGH: "Haute",
  URGENT: "Urgente",
  CRITICAL: "Critique",
  PROCESSING: "Traitement en cours",
  READY: "Prêt",
  FAILED: "Échec",
  ACCEPTED: "Accepté",
  PAID: "Payé",
  CANCELED: "Annulé",
  DRAFT: "Brouillon",
  ISSUED: "Émise",
  PAST_DUE: "En retard",
  EXPIRED: "Expiré",
  PENDING_PAYMENT: "Paiement en attente",
  CANCELED_SUBSCRIPTION: "Abonnement annulé",
  INACTIVE: "Inactif",
  ONBOARDING: "Intégration",
  ON_LEAVE: "En congé",
  EXITED: "Sorti",
  PERMANENT: "Permanent",
  CONSULTANT: "Consultant",
  PART_TIME: "Temps partiel",
  INTERN: "Stagiaire",
  TEMPORARY: "Temporaire",
  COMPLETE: "Complet",
  TO_REVIEW: "À vérifier",
  MISSING_DOCUMENTS: "Documents manquants",
  OPEN_BUDGET: "Budget ouvert",
  MONITORING: "Suivi actif",
  OVER_BUDGET: "Dépassement",
  VALIDATED: "Validé",
  REJECTED: "Rejeté",
  ARCHIVED: "Archivé",
  IN: "Entrée",
  OUT: "Sortie",
  MANUAL: "Manuel",
  SUBSCRIPTION: "Abonnement",
  PAYROLL: "Paie",
  SCO: "SCO",
  CASH: "Caisse",
  BANK: "Banque",
  MOBILE_MONEY: "Mobile Money",
  PROJECT: "Compte projet",
  OPERATIONS: "Compte opérationnel",
  STOCK: "Stock",
  ASSET: "Actif",
  EQUIPMENT: "Équipement",
  CONSUMABLE: "Consommable",
  SERVICE_TOOL: "Outil de service",
  WATCHLIST: "À surveiller",
  AVAILABLE: "Disponible",
  LOW_STOCK: "Stock faible",
  RESERVED: "Réservé",
  OUT_OF_STOCK: "Rupture",
  ASSIGNED: "Assigné",
  MAINTENANCE: "Maintenance",
  LOST: "Perdu",
  RETIRED: "Retiré",
  NEW: "Neuf",
  GOOD: "Bon",
  FAIR: "Moyen",
  DAMAGED: "Endommagé",
  REPAIR: "Réparation",
  PLANNED: "Planifié",
  BLOCKED: "Bloqué",
  SUBMITTED: "Soumis",
  ORDERED: "Commandé",
  RECEIVED: "Reçu",
  PENDING_REVIEW: "Vérification en attente",
  INSUFFICIENT: "Insuffisant",
  APPROVED: "Approuvé",
  NORMAL: "Normale",
  WAITING: "En attente",
  TODO: "À faire",
  PENDING_VALIDATION: "En attente de validation",
  LATE: "En retard",
  ADMINISTRATIVE: "Administrative",
  COMMERCIAL: "Commerciale",
  TECHNICAL: "Technique",
  FINANCIAL: "Financière",
  LEGAL: "Juridique",
  HR: "RH",
  CLIENT_SUPPORT: "Support client",
  MARKETING: "Marketing",
  REPORTING: "Reporting",
  MEETING: "Réunion",
  CLIENT_FOLLOW_UP: "Suivi client",
  DELIVERY: "Livraison",
  OTHER: "Autre",
  DAILY: "Quotidienne",
  WEEKLY: "Hebdomadaire",
  MONTHLY: "Mensuelle",
  CUSTOM: "Personnalisée",
  WAITING_INFORMATION: "En attente d'information",
  DONE: "Traitée",
  TASK: "Tâche",
  OPERATION: "Opération",
  DEPARTMENT_REQUEST: "Demande inter-département",
  FINANCE: "Finance",
  INFORMATION: "Information",
  VALIDATION_DELAY: "Retard de validation",
  UNRESOLVED: "Non résolu",
  ESCALATED: "Escaladé",
  COORDINATION: "Coordination",
  STRATEGIC: "Stratégique",
  OPERATIONAL: "Opérationnelle",
  FOLLOW_UP: "Suivi",
  HELD: "Tenue",
  POSTPONED: "Reportée",
  PUBLISHED: "Publié",
  DEPARTMENT: "Département",
  EMPLOYEE: "Collaborateur",
} as const;

export const publicationCategoryLabels = {
  RESSOURCE: "Ressource",
  ARTICLE: "Article",
  GUIDE: "Guide",
  CAS_PRATIQUE: "Cas pratique",
  ANNONCE: "Annonce",
  PROJET: "Projet",
} as const;

export function formatEnumLabel(value: string) {
  const explicit =
    roleLabels[value as keyof typeof roleLabels] ||
    statusLabels[value as keyof typeof statusLabels] ||
    publicationCategoryLabels[value as keyof typeof publicationCategoryLabels];

  if (explicit) {
    return explicit;
  }

  return value
    .toLowerCase()
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
