import type { Prisma } from "@prisma/client";
import { criticalPharmacySettingKeys, pharmacyNumberingDefaults, pharmacySettingSections, pharmacySettingsDefaults, type PharmacySettingSection, type SettingValue } from "@/lib/pharmacy-settings-config";
import { prisma } from "@/lib/prisma";

const json = (value: unknown) => value as Prisma.InputJsonValue;
const fieldBySection: Record<PharmacySettingSection, string> = { general: "general", numbering: "numberingSettingsJson", "products-batches": "productSettingsJson", "stock-inventory": "stockSettingsJson", "expiry-fefo": "expiryFefoSettingsJson", sales: "salesSettingsJson", prescriptions: "prescriptionSettingsJson", "receipts-purchases": "receiptPurchaseSettingsJson", "cash-payments": "cashPaymentSettingsJson", "returns-losses": "returnsLossesSettingsJson", "alerts-notifications": "alertsNotificationsSettingsJson", "documents-compliance": "documentsComplianceSettingsJson", quality: "qualitySettingsJson", "reports-exports": "reportsExportsSettingsJson", "privacy-security": "privacySecuritySettingsJson", "erp-integrations": "erpIntegrationsSettingsJson" };
function record(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, SettingValue> : {}; }
function validateValues(section: PharmacySettingSection, values: Record<string, SettingValue>) {
  const defaults = pharmacySettingsDefaults[section]; const unknown = Object.keys(values).find((key) => !(key in defaults)); if (unknown) throw new Error("UNKNOWN_SETTING");
  for (const [key, value] of Object.entries(values)) { const expected = defaults[key]; if (value !== null && expected !== null && typeof value !== typeof expected) throw new Error("INVALID_SETTING_TYPE"); if (typeof value === "number" && (value < 0 || value > 1_000_000)) throw new Error("INVALID_SETTING_VALUE"); }
}
export async function getDefaultPharmacySettingsForOrganization(organizationId: string, actorId: string) {
  const existing = await prisma.pharmacySetting.findUnique({ where: { organizationId } }); if (existing) return existing;
  return prisma.$transaction(async (tx) => {
    const created = await tx.pharmacySetting.create({ data: { organizationId, currency: String(pharmacySettingsDefaults.general.currency), timezone: String(pharmacySettingsDefaults.general.timezone), language: String(pharmacySettingsDefaults.general.language), numberingSettingsJson: json(pharmacySettingsDefaults.numbering), productSettingsJson: json(pharmacySettingsDefaults["products-batches"]), batchSettingsJson: json(pharmacySettingsDefaults["products-batches"]), stockSettingsJson: json(pharmacySettingsDefaults["stock-inventory"]), expiryFefoSettingsJson: json(pharmacySettingsDefaults["expiry-fefo"]), salesSettingsJson: json(pharmacySettingsDefaults.sales), prescriptionSettingsJson: json(pharmacySettingsDefaults.prescriptions), receiptPurchaseSettingsJson: json(pharmacySettingsDefaults["receipts-purchases"]), cashPaymentSettingsJson: json(pharmacySettingsDefaults["cash-payments"]), returnsLossesSettingsJson: json(pharmacySettingsDefaults["returns-losses"]), alertsNotificationsSettingsJson: json(pharmacySettingsDefaults["alerts-notifications"]), documentsComplianceSettingsJson: json(pharmacySettingsDefaults["documents-compliance"]), qualitySettingsJson: json(pharmacySettingsDefaults.quality), reportsExportsSettingsJson: json(pharmacySettingsDefaults["reports-exports"]), privacySecuritySettingsJson: json(pharmacySettingsDefaults["privacy-security"]), erpIntegrationsSettingsJson: json(pharmacySettingsDefaults["erp-integrations"]), createdById: actorId } });
    await tx.pharmacyNumberingSequence.createMany({ data: Object.entries(pharmacyNumberingDefaults).map(([entityType, prefix]) => ({ organizationId, entityType, prefix })) });
    return created;
  });
}
function generalFrom(setting: Awaited<ReturnType<typeof getDefaultPharmacySettingsForOrganization>>) { return { ...pharmacySettingsDefaults.general, pharmacyName: setting.pharmacyName || "", pharmacyType: setting.pharmacyType || "OFFICINE", currency: setting.currency, timezone: setting.timezone, language: setting.language, country: setting.country || "", city: setting.city || "", address: setting.address || "", phone: setting.phone || "", email: setting.email || "", receiptFooterMessage: setting.receiptFooterMessage || "" }; }
export async function getEffectivePharmacySettings(organizationId: string, actorId = "system") {
  const setting = await getDefaultPharmacySettingsForOrganization(organizationId, actorId); const sections = Object.fromEntries(pharmacySettingSections.map((section) => [section, section === "general" ? generalFrom(setting) : { ...pharmacySettingsDefaults[section], ...record(setting[fieldBySection[section] as keyof typeof setting]) }])) as Record<PharmacySettingSection, Record<string, SettingValue>>;
  return { setting, sections };
}
export async function updatePharmacySettingsSection(organizationId: string, section: PharmacySettingSection, values: Record<string, SettingValue>, actorId: string, reason?: string, ip?: string, userAgent?: string) {
  validateValues(section, values); const effective = await getEffectivePharmacySettings(organizationId, actorId); const old = effective.sections[section]; const critical = Object.keys(values).filter((key) => criticalPharmacySettingKeys.has(key)); if (critical.length && !reason?.trim()) throw new Error("REASON_REQUIRED");
  const changed = Object.entries(values).filter(([key, value]) => old[key] !== value); if (!changed.length) return effective.setting;
  return prisma.$transaction(async (tx) => {
    const data: Record<string, unknown> = { updatedById: actorId, settingsVersion: { increment: 1 } };
    if (section === "general") Object.assign(data, { pharmacyName: values.pharmacyName || null, pharmacyType: values.pharmacyType || null, currency: values.currency, timezone: values.timezone, language: values.language, country: values.country || null, city: values.city || null, address: values.address || null, phone: values.phone || null, email: values.email || null, receiptFooterMessage: values.receiptFooterMessage || null });
    else data[fieldBySection[section]] = json({ ...old, ...values });
    const updated = await tx.pharmacySetting.update({ where: { organizationId }, data });
    if (["expiry-fefo", "cash-payments", "returns-losses", "alerts-notifications"].includes(section)) {
      const expiry = section === "expiry-fefo" ? { ...old, ...values } : effective.sections["expiry-fefo"]; const cash = section === "cash-payments" ? { ...old, ...values } : effective.sections["cash-payments"]; const losses = section === "returns-losses" ? { ...old, ...values } : effective.sections["returns-losses"]; const alerts = section === "alerts-notifications" ? { ...old, ...values } : effective.sections["alerts-notifications"];
      await tx.pharmacyAlertSetting.upsert({ where: { organizationId }, create: { organizationId, nearExpiryThresholdDays: Number(expiry.nearExpiryThresholdDays), criticalCashVarianceThreshold: Number(cash.criticalCashVarianceThreshold), criticalLossValueThreshold: Number(losses.criticalLossValueThreshold), maxCashSessionHours: Number(cash.maxCashSessionHours), autoResolveAlertsEnabled: Boolean(alerts.autoResolveAlertsEnabled), criticalAlertNotificationsEnabled: Boolean(alerts.criticalAlertNotificationsEnabled), updatedById: actorId }, update: { nearExpiryThresholdDays: Number(expiry.nearExpiryThresholdDays), criticalCashVarianceThreshold: Number(cash.criticalCashVarianceThreshold), criticalLossValueThreshold: Number(losses.criticalLossValueThreshold), maxCashSessionHours: Number(cash.maxCashSessionHours), autoResolveAlertsEnabled: Boolean(alerts.autoResolveAlertsEnabled), criticalAlertNotificationsEnabled: Boolean(alerts.criticalAlertNotificationsEnabled), updatedById: actorId } });
    }
    await tx.pharmacySettingsAuditLog.createMany({ data: changed.map(([settingKey, newValue]) => ({ organizationId, actorId, section, settingKey, oldValueJson: json({ value: old[settingKey] }), newValueJson: json({ value: newValue }), changeReason: reason || null, criticality: criticalPharmacySettingKeys.has(settingKey) ? "CRITICAL" : "NORMAL", ip, userAgent })) });
    return updated;
  });
}
export async function resetPharmacySettingsToDefaults(organizationId: string, section: PharmacySettingSection, actorId: string, reason: string, ip?: string, userAgent?: string) { return updatePharmacySettingsSection(organizationId, section, pharmacySettingsDefaults[section], actorId, reason, ip, userAgent); }
function formatted(prefix: string, format: string, separator: string, counter: number, length: number, now = new Date()) { const padded = String(counter).padStart(length, "0"); return format.replace("PREFIX", prefix).replace("YYYYMMDD", now.toISOString().slice(0, 10).replaceAll("-", "")).replace("YYYY", String(now.getFullYear())).replace("YYMM", `${String(now.getFullYear()).slice(-2)}${String(now.getMonth() + 1).padStart(2, "0")}`).replace(/0{4,}/, padded).replaceAll("-", separator); }
export async function previewPharmacyEntityNumber(organizationId: string, entityType: string) { const sequence = await prisma.pharmacyNumberingSequence.findUnique({ where: { organizationId_entityType: { organizationId, entityType } } }); if (!sequence) throw new Error("SEQUENCE_NOT_FOUND"); return formatted(sequence.prefix, sequence.format, sequence.separator, sequence.counterValue + 1, sequence.counterLength); }
export async function generatePharmacyEntityNumber(organizationId: string, entityType: string) { return prisma.$transaction(async (tx) => { const sequence = await tx.pharmacyNumberingSequence.update({ where: { organizationId_entityType: { organizationId, entityType } }, data: { counterValue: { increment: 1 } } }); return formatted(sequence.prefix, sequence.format, sequence.separator, sequence.counterValue, sequence.counterLength); }); }
export async function updatePharmacyNumberingSequence(organizationId: string, entityType: string, actorId: string, values: { prefix?: string; format?: string; resetFrequency?: string; counterLength?: number; allowManualOverride?: boolean }, reason?: string, ip?: string, userAgent?: string) { const existing = await prisma.pharmacyNumberingSequence.findUnique({ where: { organizationId_entityType: { organizationId, entityType } } }); if (!existing) throw new Error("SEQUENCE_NOT_FOUND"); const updated = await prisma.$transaction(async (tx) => { const sequence = await tx.pharmacyNumberingSequence.update({ where: { id: existing.id }, data: values }); await tx.pharmacySettingsAuditLog.create({ data: { organizationId, actorId, section: "numbering", settingKey: entityType, oldValueJson: json(existing), newValueJson: json(sequence), changeReason: reason || null, criticality: "CRITICAL", ip, userAgent } }); return sequence; }); return updated; }
export async function getPharmacySettingsDataset(organizationId: string, actorId: string, includeHistory: boolean) { const effective = await getEffectivePharmacySettings(organizationId, actorId); const [sequences, history, locations, members, positions] = await Promise.all([prisma.pharmacyNumberingSequence.findMany({ where: { organizationId }, orderBy: { entityType: "asc" } }), includeHistory ? prisma.pharmacySettingsAuditLog.findMany({ where: { organizationId }, orderBy: { createdAt: "desc" }, take: 500 }) : Promise.resolve([]), prisma.pharmacyStockLocation.findMany({ where: { organizationId, status: "ACTIVE" }, select: { id: true, name: true } }), prisma.organizationMember.findMany({ where: { organizationId, status: "ACTIVE", removedAt: null }, select: { user: { select: { id: true, name: true } } } }), prisma.enterprisePosition.findMany({ where: { organizationId }, select: { id: true, labelFr: true } })]); return { sections: effective.sections, sequences, history, locations, members: members.map((item) => item.user), positions, criticalKeys: [...criticalPharmacySettingKeys] }; }
