import type { Prisma } from "@prisma/client";
import type { PharmacyReportType } from "@/lib/pharmacy-report-validators";
import { prisma } from "@/lib/prisma";

export type PharmacyReportFilters = { start?: string; end?: string; productId?: string; batchId?: string; supplierId?: string; userId?: string; departmentId?: string; status?: string; category?: string; criticality?: string; paymentMethod?: string };
type ReportRow = Record<string, string | number | boolean | null>;
type Metric = { label: string; value: string | number; sensitive?: boolean };
type ReportSection = { title: string; description: string; metrics: Metric[]; rows: ReportRow[] };
const activeAlertStatuses = ["OPEN", "SEEN", "ASSIGNED", "IN_PROGRESS", "WAITING"];
const activeSaleStatuses = ["VALIDATED", "COMPLETED", "PAID", "PARTIALLY_PAID"];
const number = (value: unknown) => Number(value || 0);
const sum = <T>(items: T[], value: (item: T) => number) => items.reduce((total, item) => total + value(item), 0);
const dateText = (value: Date | null | undefined) => value ? value.toISOString().slice(0, 10) : "";
const round = (value: number) => Math.round(value * 100) / 100;
const group = <T>(items: T[], key: (item: T) => string, value: (item: T) => number = () => 1) => Array.from(items.reduce((map, item) => map.set(key(item) || "Non renseigné", (map.get(key(item) || "Non renseigné") || 0) + value(item)), new Map<string, number>())).map(([label, total]) => ({ label, total: round(total) })).sort((a, b) => b.total - a.total);

function period(filters: PharmacyReportFilters) {
  const end = filters.end ? new Date(`${filters.end}T23:59:59.999Z`) : new Date();
  const start = filters.start ? new Date(`${filters.start}T00:00:00.000Z`) : new Date(end.getTime() - 29 * 86400000);
  return { start, end };
}
function metrics(items: Array<[string, string | number, boolean?]>): Metric[] { return items.map(([label, value, sensitive]) => ({ label, value, sensitive })); }
function section(title: string, description: string, sectionMetrics: Metric[], rows: ReportRow[]): ReportSection { return { title, description, metrics: sectionMetrics, rows: rows.slice(0, 250) }; }

export async function getPharmacyReportsDataset(organizationId: string, filters: PharmacyReportFilters, permissions: { financial: boolean; sensitive: boolean }) {
  const { start, end } = period(filters); const now = new Date(); const soon = new Date(now.getTime() + 90 * 86400000);
  const [
    products, batches, movements, inventories, adjustments, suppliers, orders, orderLines, receipts, receiptLines, receiptBatches, receiptDiscrepancies,
    prescriptions, prescriptionLines, sales, saleLines, saleRefunds, payments, cashSessions, cashRefunds, cashDiscrepancies, returnLosses,
    alerts, quality, capa, documents, missingDocuments, documentAccess, members, departments, savedViews, exports, snapshots,
  ] = await Promise.all([
    prisma.pharmacyProduct.findMany({ where: { organizationId, status: { not: "ARCHIVED" } } }),
    prisma.pharmacyBatch.findMany({ where: { organizationId } }), prisma.pharmacyStockMovement.findMany({ where: { organizationId, createdAt: { gte: start, lte: end } }, orderBy: { createdAt: "desc" } }),
    prisma.pharmacyInventorySession.findMany({ where: { organizationId, inventoryDate: { gte: start, lte: end } } }), prisma.pharmacyStockAdjustment.findMany({ where: { organizationId, createdAt: { gte: start, lte: end } } }),
    prisma.pharmacySupplier.findMany({ where: { organizationId } }), prisma.pharmacyPurchaseOrder.findMany({ where: { organizationId, orderDate: { gte: start, lte: end } } }),
    prisma.pharmacyPurchaseOrderLine.findMany({ where: { organizationId } }), prisma.pharmacyReceipt.findMany({ where: { organizationId, receivedAt: { gte: start, lte: end } } }),
    prisma.pharmacyReceiptLine.findMany({ where: { organizationId } }), prisma.pharmacyReceiptBatch.findMany({ where: { organizationId } }), prisma.pharmacyReceiptDiscrepancy.findMany({ where: { organizationId } }),
    prisma.pharmacyPrescription.findMany({ where: { organizationId, receivedAt: { gte: start, lte: end } } }), prisma.pharmacyPrescriptionLine.findMany({ where: { organizationId } }),
    prisma.pharmacySale.findMany({ where: { organizationId, saleDate: { gte: start, lte: end } } }), prisma.pharmacySaleLine.findMany({ where: { organizationId } }),
    prisma.pharmacySaleRefund.findMany({ where: { organizationId, createdAt: { gte: start, lte: end } } }), prisma.pharmacyPayment.findMany({ where: { organizationId, paymentDate: { gte: start, lte: end } } }),
    prisma.pharmacyCashSession.findMany({ where: { organizationId, openedAt: { gte: start, lte: end } } }), prisma.pharmacyRefund.findMany({ where: { organizationId, createdAt: { gte: start, lte: end } } }),
    prisma.pharmacyCashDiscrepancy.findMany({ where: { organizationId, createdAt: { gte: start, lte: end } } }), prisma.pharmacyReturnLossEvent.findMany({ where: { organizationId, createdAt: { gte: start, lte: end } } }),
    prisma.pharmacyAlert.findMany({ where: { organizationId, lastDetectedAt: { gte: start, lte: end } } }), prisma.pharmacyQualityIncident.findMany({ where: { organizationId, reportedAt: { gte: start, lte: end } } }),
    prisma.pharmacyQualityCapaAction.findMany({ where: { organizationId } }), prisma.pharmacyDocument.findMany({ where: { organizationId, status: { not: "DELETED" } } }),
    prisma.pharmacyMissingDocument.findMany({ where: { organizationId } }), permissions.sensitive ? prisma.pharmacyDocumentAccessLog.findMany({ where: { organizationId, createdAt: { gte: start, lte: end } } }) : Promise.resolve([]),
    prisma.organizationMember.findMany({ where: { organizationId, status: "ACTIVE", removedAt: null }, select: { userId: true, role: true, user: { select: { name: true } } } }),
    prisma.enterpriseDepartment.findMany({ where: { organizationId }, select: { id: true, labelFr: true } }),
    prisma.pharmacySavedReportView.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { updatedAt: "desc" } }),
    prisma.pharmacyReportExport.findMany({ where: { organizationId }, orderBy: { exportedAt: "desc" }, take: 100 }),
    prisma.pharmacyReportSnapshot.findMany({ where: { organizationId }, orderBy: { generatedAt: "desc" }, take: 100 }),
  ]);
  const productMap = new Map(products.map((item) => [item.id, item])); const batchMap = new Map(batches.map((item) => [item.id, item])); const supplierMap = new Map(suppliers.map((item) => [item.id, item.name])); const userMap = new Map(members.map((item) => [item.userId, item.user.name]));
  const filteredSales = sales.filter((item) => (!filters.userId || item.cashierId === filters.userId || item.pharmacistId === filters.userId) && (!filters.departmentId || item.departmentId === filters.departmentId) && (!filters.status || item.status === filters.status) && (!filters.paymentMethod || item.paymentMethod === filters.paymentMethod));
  const saleIds = new Set(filteredSales.map((item) => item.id)); const filteredSaleLines = saleLines.filter((item) => saleIds.has(item.saleId) && (!filters.productId || item.productId === filters.productId) && (!filters.batchId || item.batchId === filters.batchId));
  const netSales = filteredSales.filter((item) => activeSaleStatuses.includes(item.status)); const netSaleIds = new Set(netSales.map((item) => item.id)); const netLines = filteredSaleLines.filter((item) => netSaleIds.has(item.saleId));
  const stockBatches = batches.filter((item) => (!filters.productId || item.productId === filters.productId) && (!filters.batchId || item.id === filters.batchId) && (!filters.supplierId || item.supplierId === filters.supplierId) && (!filters.status || item.status === filters.status));
  const stockByProduct = products.filter((item) => !filters.productId || item.id === filters.productId).map((product) => { const productBatches = stockBatches.filter((batch) => batch.productId === product.id); const available = sum(productBatches, (batch) => number(batch.availableQuantity)); return { product: product.name, category: product.category, available: round(available), minimum: number(product.minStock), maximum: product.maxStock === null ? null : number(product.maxStock), status: available <= 0 ? "Rupture" : available <= number(product.minStock) ? "Stock faible" : "Disponible", estimatedValue: round(sum(productBatches, (batch) => number(batch.availableQuantity) * number(batch.purchasePrice || product.referencePurchasePrice))), location: product.defaultLocation || "" }; });
  const financial = (value: number) => permissions.financial ? round(value) : "Accès financier requis";
  const reportSections: Record<string, ReportSection> = {};
  reportSections.overview = section("Tableau de bord rapports", "Synthèse calculée depuis les tables opérationnelles.", metrics([
    ["Ventes nettes", netSales.length], ["Chiffre des ventes", financial(sum(netSales, (item) => number(item.totalAmount))), true], ["Montant encaissé", financial(sum(payments.filter((item) => item.status === "PAID"), (item) => number(item.amount))), true],
    ["Produits en rupture", stockByProduct.filter((item) => item.status === "Rupture").length], ["Stocks faibles", stockByProduct.filter((item) => item.status === "Stock faible").length], ["Lots expirés", stockBatches.filter((item) => item.expiryDate < now).length],
    ["Commandes en retard", orders.filter((item) => item.expectedDeliveryDate && item.expectedDeliveryDate < now && ["VALIDATED", "ORDERED", "PARTIALLY_RECEIVED"].includes(item.status)).length], ["Incidents ouverts", quality.filter((item) => !["CLOSED", "RESOLVED", "ARCHIVED", "CANCELLED"].includes(item.status)).length],
    ["Alertes critiques ouvertes", alerts.filter((item) => item.criticality === "CRITICAL" && activeAlertStatuses.includes(item.status)).length], ["Documents expirés", documents.filter((item) => item.expiryDate && item.expiryDate < now).length], ["Documents manquants", missingDocuments.filter((item) => item.status === "OPEN").length],
  ]), group(netSales, (item) => dateText(item.saleDate), (item) => number(item.totalAmount)).map((item) => ({ date: item.label, ventes: permissions.financial ? item.total : "Protégé" })));
  reportSections.sales = section("Rapports ventes", "Ventes nettes, produits, caissiers et paiements.", metrics([["Nombre de ventes", filteredSales.length], ["Ventes nettes", netSales.length], ["Quantité vendue", round(sum(netLines, (item) => number(item.quantity)))], ["Montant total", financial(sum(netSales, (item) => number(item.totalAmount))), true], ["Montant payé", financial(sum(netSales, (item) => number(item.paidAmount))), true], ["Remboursements", financial(sum(saleRefunds.filter((item) => item.status === "VALIDATED"), (item) => number(item.refundAmount))), true], ["Panier moyen", financial(netSales.length ? sum(netSales, (item) => number(item.totalAmount)) / netSales.length : 0), true], ["Ventes annulées", filteredSales.filter((item) => item.status === "CANCELLED").length]]), filteredSales.map((item) => ({ vente: item.saleNumber, date: dateText(item.saleDate), caissier: userMap.get(item.cashierId) || "Non renseigné", pharmacien: userMap.get(item.pharmacistId || "") || "", montant: permissions.financial ? number(item.totalAmount) : "Protégé", payé: permissions.financial ? number(item.paidAmount) : "Protégé", reste: permissions.financial ? number(item.remainingAmount) : "Protégé", statut: item.status, paiement: item.paymentMethod || "" })));
  reportSections.stock = section("Rapports stock", "Disponibilités calculées depuis les lots.", metrics([["Produits suivis", products.filter((item) => item.stockTrackingEnabled).length], ["Quantité disponible", round(sum(stockBatches, (item) => number(item.availableQuantity)))], ["Quantité réservée", round(sum(stockBatches, (item) => number(item.reservedQuantity)))], ["Quantité endommagée", round(sum(stockBatches, (item) => number(item.damagedQuantity)))], ["Ruptures", stockByProduct.filter((item) => item.status === "Rupture").length], ["Stocks faibles", stockByProduct.filter((item) => item.status === "Stock faible").length], ["Valeur estimée", financial(sum(stockByProduct, (item) => number(item.estimatedValue))), true], ["Mouvements", movements.length], ["Inventaires", inventories.length], ["Ajustements", adjustments.length]]), stockByProduct.map((item) => ({ ...item, estimatedValue: permissions.financial ? item.estimatedValue : "Protégé" })));
  reportSections.batches = section("Rapports lots & péremptions", "Lots actifs, expirés, rappelés et en quarantaine.", metrics([["Nombre de lots", stockBatches.length], ["Lots actifs", stockBatches.filter((item) => item.status === "ACTIVE").length], ["Lots expirés", stockBatches.filter((item) => item.expiryDate < now).length], ["Péremption proche", stockBatches.filter((item) => item.expiryDate >= now && item.expiryDate <= soon).length], ["Lots rappelés", stockBatches.filter((item) => item.recall || item.status === "RECALLED").length], ["Lots en quarantaine", stockBatches.filter((item) => item.quarantine || item.status === "QUARANTINED").length]]), stockBatches.map((item) => ({ produit: productMap.get(item.productId)?.name || "", lot: item.batchNumber, fournisseur: supplierMap.get(item.supplierId || "") || "", péremption: dateText(item.expiryDate), joursRestants: Math.ceil((item.expiryDate.getTime() - now.getTime()) / 86400000), disponible: number(item.availableQuantity), statut: item.status, valeur: permissions.financial ? round(number(item.availableQuantity) * number(item.purchasePrice)) : "Protégé" })));
  reportSections.purchases = section("Rapports achats & fournisseurs", "Commandes, fournisseurs et quantités restantes.", metrics([["Commandes", orders.length], ["Fournisseurs actifs", suppliers.filter((item) => item.status === "ACTIVE").length], ["Montant estimé", financial(sum(orders, (item) => number(item.estimatedTotal))), true], ["Quantité commandée", round(sum(orderLines.filter((item) => orders.some((order) => order.id === item.purchaseOrderId)), (item) => number(item.orderedQuantity)))], ["Quantité reçue", round(sum(orderLines.filter((item) => orders.some((order) => order.id === item.purchaseOrderId)), (item) => number(item.receivedQuantity)))], ["Commandes en retard", orders.filter((item) => item.expectedDeliveryDate && item.expectedDeliveryDate < now && ["VALIDATED", "ORDERED", "PARTIALLY_RECEIVED"].includes(item.status)).length]]), orders.map((item) => ({ commande: item.orderNumber, fournisseur: supplierMap.get(item.supplierId) || "", date: dateText(item.orderDate), livraisonPrévue: dateText(item.expectedDeliveryDate), statut: item.status, montant: permissions.financial ? number(item.estimatedTotal) : "Protégé" })));
  reportSections.receipts = section("Rapports réceptions", "Réceptions, écarts et lots créés.", metrics([["Réceptions", receipts.length], ["Validées", receipts.filter((item) => ["VALIDATED", "PARTIALLY_VALIDATED"].includes(item.status)).length], ["Annulées", receipts.filter((item) => item.status === "CANCELLED").length], ["Quantité reçue", round(sum(receiptLines.filter((line) => receipts.some((receipt) => receipt.id === line.receiptId)), (item) => number(item.receivedQuantity)))], ["Valeur reçue", financial(sum(receipts, (item) => number(item.totalAmount))), true], ["Lots créés", receiptBatches.filter((item) => receipts.some((receipt) => receipt.id === item.receiptId)).length], ["Écarts ouverts", receiptDiscrepancies.filter((item) => !["RESOLVED", "CANCELLED"].includes(item.status)).length]]), receipts.map((item) => ({ réception: item.receiptNumber, fournisseur: supplierMap.get(item.supplierId) || "", date: dateText(item.receivedAt), réceptionnaire: userMap.get(item.receivedById) || "", statut: item.status, valeur: permissions.financial ? number(item.totalAmount) : "Protégé" })));
  reportSections.cash = section("Rapports caisse & paiements", "Encaissements réels, sessions et écarts.", metrics([["Paiements validés", payments.filter((item) => item.status === "PAID").length], ["Total encaissé", financial(sum(payments.filter((item) => item.status === "PAID"), (item) => number(item.amount))), true], ["Remboursements", financial(sum(cashRefunds.filter((item) => ["VALIDATED", "PAID"].includes(item.status)), (item) => number(item.amount))), true], ["Sessions", cashSessions.length], ["Sessions ouvertes", cashSessions.filter((item) => item.status === "OPEN").length], ["Écarts ouverts", cashDiscrepancies.filter((item) => item.status === "OPEN").length]]), group(payments.filter((item) => item.status === "PAID"), (item) => item.paymentMethod, (item) => number(item.amount)).map((item) => ({ modePaiement: item.label, encaissé: permissions.financial ? item.total : "Protégé" })));
  reportSections.prescriptions = section("Rapports ordonnances", "Indicateurs sensibles protégés côté serveur.", metrics([["Ordonnances reçues", prescriptions.length], ["Validées", prescriptions.filter((item) => item.validationStatus === "VALIDATED").length], ["Rejetées", prescriptions.filter((item) => item.validationStatus === "REJECTED").length], ["Liées à une vente", prescriptions.filter((item) => item.linkedSaleId).length], ["Lignes prescrites", prescriptionLines.filter((item) => prescriptions.some((prescription) => prescription.id === item.prescriptionId)).length], ["Substitutions", prescriptionLines.filter((item) => item.substitutionApplied).length]]), permissions.sensitive ? prescriptions.map((item) => ({ ordonnance: item.prescriptionNumber, date: dateText(item.prescriptionDate), pharmacien: userMap.get(item.pharmacistId || "") || "", validation: item.validationStatus, statut: item.status, venteLiée: Boolean(item.linkedSaleId) })) : []);
  reportSections.returns = section("Rapports retours, pertes & destructions", "Impacts et valeurs estimées issus des événements métier.", metrics([["Événements", returnLosses.length], ["Retours clients", returnLosses.filter((item) => item.eventType === "CUSTOMER_RETURN").length], ["Retours fournisseurs", returnLosses.filter((item) => item.eventType === "SUPPLIER_RETURN").length], ["Pertes", returnLosses.filter((item) => item.eventType === "LOSS").length], ["Destructions", returnLosses.filter((item) => item.eventType === "DESTRUCTION").length], ["Quantité", round(sum(returnLosses, (item) => number(item.quantity)))], ["Valeur estimée", financial(sum(returnLosses, (item) => number(item.estimatedValue))), true]]), returnLosses.map((item) => ({ événement: item.eventNumber, type: item.eventType, produit: productMap.get(item.productId)?.name || "", lot: batchMap.get(item.batchId || "")?.batchNumber || "", quantité: number(item.quantity), valeur: permissions.financial ? number(item.estimatedValue) : "Protégé", statut: item.status, date: dateText(item.createdAt) })));
  reportSections.quality = section("Rapports qualité & pharmacovigilance", "Incidents et CAPA, sans données patient dans les tableaux.", metrics([["Incidents", quality.length], ["Incidents ouverts", quality.filter((item) => !["CLOSED", "RESOLVED", "ARCHIVED", "CANCELLED"].includes(item.status)).length], ["Incidents critiques", quality.filter((item) => item.criticality === "CRITICAL").length], ["CAPA ouvertes", capa.filter((item) => !["COMPLETED", "CANCELLED", "ARCHIVED"].includes(item.status)).length], ["CAPA en retard", capa.filter((item) => item.dueAt && item.dueAt < now && !["COMPLETED", "CANCELLED", "ARCHIVED"].includes(item.status)).length]]), permissions.sensitive ? quality.map((item) => ({ incident: item.incidentNumber, type: item.incidentType, criticité: item.criticality, produit: productMap.get(item.productId || "")?.name || "", lot: batchMap.get(item.batchId || "")?.batchNumber || "", responsable: userMap.get(item.assignedToId || "") || "", statut: item.status, date: dateText(item.incidentDate) })) : []);
  reportSections.alerts = section("Rapports alertes", "Alertes réelles, dédupliquées par le moteur d’alertes.", metrics([["Alertes", alerts.length], ["Ouvertes", alerts.filter((item) => activeAlertStatuses.includes(item.status)).length], ["Critiques ouvertes", alerts.filter((item) => item.criticality === "CRITICAL" && activeAlertStatuses.includes(item.status)).length], ["Récurrentes", alerts.filter((item) => item.detectedCount > 1).length], ["Résolues", alerts.filter((item) => item.status === "RESOLVED").length]]), group(alerts, (item) => item.sourceModule || item.category).map((item) => ({ module: item.label, alertes: item.total })));
  reportSections.documents = section("Rapports documents & conformité", "Conformité, expiration, renouvellement et téléchargements sensibles.", metrics([["Documents", documents.length], ["Validés", documents.filter((item) => item.status === "VALIDATED").length], ["Expirés", documents.filter((item) => item.expiryDate && item.expiryDate < now).length], ["À renouveler", documents.filter((item) => item.complianceStatus === "TO_RENEW").length], ["Manquants", missingDocuments.filter((item) => item.status === "OPEN").length], ["Rejetés", documents.filter((item) => item.status === "REJECTED").length], ["Téléchargements sensibles", permissions.sensitive ? documentAccess.filter((item) => item.action === "DOWNLOAD").length : "Accès sensible requis"]]), group(documents, (item) => item.category).map((item) => ({ catégorie: item.label, documents: item.total })));
  const activityRows = group([...sales.map((item) => ({ userId: item.cashierId })), ...receipts.map((item) => ({ userId: item.receivedById })), ...quality.map((item) => ({ userId: item.assignedToId || item.reportedById })), ...documents.map((item) => ({ userId: item.createdById }))], (item) => userMap.get(item.userId) || "Utilisateur non renseigné").map((item) => ({ collaborateur: item.label, actions: item.total }));
  reportSections.collaborators = section("Rapports collaborateurs / activité", "Volume d’activité opérationnelle utile à la gestion.", metrics([["Collaborateurs actifs", members.length], ["Actions agrégées", sum(activityRows, (item) => number(item.actions))]]), activityRows);
  reportSections.custom = section("Rapports personnalisés simples", "Domaines et colonnes contrôlés; aucun SQL libre.", metrics([["Vues sauvegardées", savedViews.length], ["Domaines disponibles", 13]]), savedViews.map((item) => ({ nom: item.name, type: item.reportType, visibilité: item.visibility, crééLe: dateText(item.createdAt) })));
  reportSections.exports = section("Exports & historiques", "Exports CSV audités et snapshots décisionnels.", metrics([["Exports", exports.length], ["Exports sensibles", exports.filter((item) => item.sensitiveExport).length], ["Snapshots", snapshots.length]]), exports.map((item) => ({ rapport: item.reportName, type: item.reportType, format: item.format, statut: item.status, exportéLe: dateText(item.exportedAt), sensible: item.sensitiveExport })));
  return { filters: { start: dateText(start), end: dateText(end), ...filters }, permissions, sections: reportSections, options: { products: products.map((item) => ({ id: item.id, label: item.name })), batches: batches.map((item) => ({ id: item.id, label: item.batchNumber })), suppliers: suppliers.map((item) => ({ id: item.id, label: item.name })), members: members.map((item) => ({ id: item.userId, label: item.user.name })), departments: departments.map((item) => ({ id: item.id, label: item.labelFr })) }, savedViews, exports, snapshots };
}

export async function createSavedReportView(organizationId: string, userId: string, input: { name: string; description?: string; reportType: PharmacyReportType; filters: PharmacyReportFilters; visibility: string }) {
  return prisma.pharmacySavedReportView.create({ data: { organizationId, name: input.name, description: input.description || null, reportType: input.reportType, filtersJson: input.filters as Prisma.InputJsonValue, visibility: input.visibility, createdById: userId } });
}
export async function archiveSavedReportView(organizationId: string, id: string, userId: string) { return prisma.pharmacySavedReportView.updateMany({ where: { id, organizationId }, data: { status: "ARCHIVED", updatedById: userId } }); }
export async function createPharmacyReportSnapshot(organizationId: string, userId: string, reportType: PharmacyReportType, snapshotName: string, filters: PharmacyReportFilters, data: unknown, notes?: string) { const range = period(filters); return prisma.pharmacyReportSnapshot.create({ data: { organizationId, reportType, snapshotName, periodStart: range.start, periodEnd: range.end, dataJson: data as Prisma.InputJsonValue, generatedById: userId, notes } }); }
export async function logReportExport(organizationId: string, userId: string, reportType: PharmacyReportType, filters: PharmacyReportFilters, sensitive: boolean) { return prisma.pharmacyReportExport.create({ data: { organizationId, reportType, reportName: reportType, filtersJson: filters as Prisma.InputJsonValue, format: "CSV", exportedById: userId, sensitiveExport: sensitive } }); }
export function reportTypeToSection(reportType: PharmacyReportType) { return reportType === "PHARMACY_OVERVIEW" ? "overview" : reportType === "SALES" ? "sales" : reportType === "STOCK" ? "stock" : reportType === "BATCH_EXPIRY" ? "batches" : reportType === "PURCHASES" ? "purchases" : reportType === "RECEIPTS" ? "receipts" : reportType === "CASH_PAYMENTS" ? "cash" : reportType === "PRESCRIPTIONS" ? "prescriptions" : reportType === "RETURNS_LOSSES" ? "returns" : reportType === "QUALITY_INCIDENTS" ? "quality" : reportType === "ALERTS" ? "alerts" : reportType === "DOCUMENTS_COMPLIANCE" ? "documents" : reportType === "COLLABORATOR_ACTIVITY" ? "collaborators" : "custom"; }
export function rowsToCsv(rows: ReportRow[]) { if (!rows.length) return "\uFEFFAucune donnée\r\n"; const columns = Array.from(new Set(rows.flatMap((row) => Object.keys(row)))); const escape = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; return `\uFEFF${columns.map(escape).join(",")}\r\n${rows.map((row) => columns.map((column) => escape(row[column])).join(",")).join("\r\n")}`; }
