import { notifyUsers } from "@/lib/notifications";
import { prisma } from "@/lib/prisma";

type Candidate = { alertType: string; category: string; title: string; message: string; criticality: string; sourceModule: string; sourceEntityType: string; sourceEntityId: string; productId?: string | null; batchId?: string | null; supplierId?: string | null; purchaseOrderId?: string | null; receiptId?: string | null; saleId?: string | null; inventorySessionId?: string | null; adjustmentId?: string | null; cashSessionId?: string | null; returnEntityType?: string | null; returnEntityId?: string | null; recommendedAction: string; dueAt?: Date | null };
const activeStatuses = ["OPEN", "SEEN", "ASSIGNED", "IN_PROGRESS", "WAITING"];
const ruleDefinitions = [
  ["PRODUCT_OUT_OF_STOCK", "STOCK", "Produit en rupture", "CRITICAL"], ["PRODUCT_LOW_STOCK", "STOCK", "Produit en stock faible", "HIGH"], ["PRODUCT_OVERSTOCK", "STOCK", "Produit en surstock", "MEDIUM"], ["PRODUCT_WITHOUT_PRICE", "STOCK", "Produit sans prix de vente", "HIGH"], ["PRODUCT_WITHOUT_BATCH", "STOCK", "Produit sans lot disponible", "HIGH"],
  ["BATCH_NEAR_EXPIRY", "EXPIRY", "Lot proche de péremption", "HIGH"], ["BATCH_EXPIRED", "EXPIRY", "Lot expiré", "CRITICAL"], ["BATCH_RECALLED", "RECALL", "Lot rappelé", "CRITICAL"], ["BATCH_QUARANTINED", "RECALL", "Lot en quarantaine", "HIGH"], ["BATCH_BLOCKED", "RECALL", "Lot bloqué", "HIGH"],
  ["PURCHASE_ORDER_OVERDUE", "PURCHASE", "Commande fournisseur en retard", "HIGH"], ["REPLENISHMENT_REQUEST_PENDING", "PURCHASE", "Demande de réapprovisionnement en attente", "MEDIUM"], ["RECEIPT_DISCREPANCY_OPEN", "RECEIPT", "Écart de réception ouvert", "HIGH"],
  ["PHARMACIST_VALIDATION_PENDING", "SALE", "Validation pharmacien en attente", "HIGH"], ["SALE_ANOMALY_OPEN", "SALE", "Anomalie de vente ouverte", "HIGH"], ["INVENTORY_VARIANCE_CRITICAL", "INVENTORY", "Écart d'inventaire critique", "CRITICAL"], ["STOCK_ADJUSTMENT_PENDING", "ADJUSTMENT", "Ajustement stock en attente", "MEDIUM"],
  ["LOSS_CRITICAL", "RETURN_LOSS", "Perte critique", "CRITICAL"], ["DESTRUCTION_PENDING", "RETURN_LOSS", "Destruction en attente", "HIGH"], ["CASH_SESSION_OPEN_TOO_LONG", "CASH", "Session de caisse ouverte trop longtemps", "HIGH"], ["CASH_DISCREPANCY_CRITICAL", "CASH", "Écart caisse critique", "CRITICAL"],
] as const;
export const pharmacyAlertRuleDefinitions = ruleDefinitions;

function key(candidate: Candidate) { return [candidate.alertType, candidate.sourceModule, candidate.sourceEntityType, candidate.sourceEntityId, candidate.productId || "", candidate.batchId || ""].join(":"); }
async function settings(organizationId: string) { return prisma.pharmacyAlertSetting.upsert({ where: { organizationId }, create: { organizationId }, update: {} }); }
async function ensureRules(organizationId: string) {
  await prisma.$transaction(ruleDefinitions.map(([ruleCode, category, label, criticality], sortOrder) => prisma.pharmacyAlertRule.upsert({ where: { organizationId_ruleCode: { organizationId, ruleCode } }, create: { organizationId, ruleCode, category, alertType: ruleCode, label, defaultCriticality: criticality, sortOrder }, update: {} })));
}
async function persist(organizationId: string, candidates: Candidate[], actorId?: string) {
  await ensureRules(organizationId);
  const enabled = new Map((await prisma.pharmacyAlertRule.findMany({ where: { organizationId, enabled: true } })).map((rule) => [rule.alertType, rule]));
  const touched: string[] = [];
  for (const candidate of candidates) {
    const rule = enabled.get(candidate.alertType); if (!rule) continue;
    const deduplicationKey = key(candidate); touched.push(deduplicationKey);
    const existing = await prisma.pharmacyAlert.findUnique({ where: { organizationId_deduplicationKey: { organizationId, deduplicationKey } } });
    const alert = existing
      ? await prisma.pharmacyAlert.update({ where: { id: existing.id }, data: { ...candidate, criticality: rule.defaultCriticality || candidate.criticality, lastDetectedAt: new Date(), detectedCount: { increment: 1 }, status: ["RESOLVED", "IGNORED", "CANCELLED", "ARCHIVED"].includes(existing.status) ? "OPEN" : existing.status, updatedById: actorId } })
      : await prisma.pharmacyAlert.create({ data: { organizationId, alertNumber: `ALT-${new Date().getFullYear()}-${String(await prisma.pharmacyAlert.count({ where: { organizationId } }) + 1).padStart(6, "0")}`, deduplicationKey, ...candidate, criticality: rule.defaultCriticality || candidate.criticality, createdById: actorId, updatedById: actorId } });
    await prisma.pharmacyAlertEvent.create({ data: { organizationId, alertId: alert.id, actorId, eventType: existing ? "DETECTED_AGAIN" : "DETECTED", oldStatus: existing?.status, newStatus: alert.status } });
  }
  const config = await settings(organizationId);
  if (config.autoResolveAlertsEnabled) await prisma.pharmacyAlert.updateMany({ where: { organizationId, deduplicationKey: { notIn: touched.length ? touched : ["__none__"] }, status: { in: activeStatuses } }, data: { status: "RESOLVED", resolvedAt: new Date(), resolutionComment: "Résolution automatique: la condition détectée n'est plus présente." } });
  if (config.criticalAlertNotificationsEnabled) {
    const critical = candidates.filter((item) => item.criticality === "CRITICAL"); if (critical.length) {
      const managers = await prisma.organizationMember.findMany({ where: { organizationId, status: "ACTIVE", removedAt: null, role: { in: ["OWNER", "ADMIN_ENTREPRISE", "ADMIN_ENTERPRISE", "MANAGER"] } }, select: { userId: true } });
      await notifyUsers({ userIds: managers.map((item) => item.userId), organizationId, type: "PHARMACY_ALERT", title: `${critical.length} alerte(s) pharmacie critique(s)`, body: "Ouvrez le module Alertes stock / péremption / rappel pour les traiter.", targetUrl: "/enterprise-admin" });
    }
  }
  return candidates.length;
}

export async function detectAllPharmacyAlerts(organizationId: string, actorId?: string) {
  const config = await settings(organizationId); const now = new Date(); const expiryLimit = new Date(now.getTime() + config.nearExpiryThresholdDays * 86400000); const cashLimit = new Date(now.getTime() - config.maxCashSessionHours * 3600000); const validationLimit = new Date(now.getTime() - config.maxPharmacistValidationHours * 3600000);
  const [products, batches, orders, requests, discrepancies, sales, anomalies, inventoryLines, adjustments, returnLosses, sessions, cashDiscrepancies] = await Promise.all([
    prisma.pharmacyProduct.findMany({ where: { organizationId, status: "ACTIVE" }, include: { batches: true } }), prisma.pharmacyBatch.findMany({ where: { organizationId } }),
    prisma.pharmacyPurchaseOrder.findMany({ where: { organizationId } }), prisma.pharmacyReplenishmentRequest.findMany({ where: { organizationId } }), prisma.pharmacyReceiptDiscrepancy.findMany({ where: { organizationId } }),
    prisma.pharmacySale.findMany({ where: { organizationId } }), prisma.pharmacySaleAnomaly.findMany({ where: { organizationId } }), prisma.pharmacyInventoryLine.findMany({ where: { organizationId } }),
    prisma.pharmacyStockAdjustment.findMany({ where: { organizationId } }), prisma.pharmacyReturnLossEvent.findMany({ where: { organizationId } }), prisma.pharmacyCashSession.findMany({ where: { organizationId } }), prisma.pharmacyCashDiscrepancy.findMany({ where: { organizationId } }),
  ]);
  const candidates: Candidate[] = []; const add = (item: Candidate) => candidates.push(item);
  for (const product of products) { const available = product.batches.reduce((sum, batch) => sum + Number(batch.availableQuantity), 0); const base = { sourceModule: "MEDICINES_PRODUCTS", sourceEntityType: "PharmacyProduct", sourceEntityId: product.id, productId: product.id };
    if (product.stockTrackingEnabled && available <= 0) add({ ...base, alertType: "PRODUCT_OUT_OF_STOCK", category: "STOCK", title: `${product.name} en rupture`, message: "La quantité disponible totale est nulle.", criticality: "CRITICAL", recommendedAction: "Créer une demande de réapprovisionnement." });
    else if (product.stockTrackingEnabled && available <= Number(product.minStock)) add({ ...base, alertType: "PRODUCT_LOW_STOCK", category: "STOCK", title: `${product.name} en stock faible`, message: `Stock disponible: ${available}.`, criticality: "HIGH", recommendedAction: "Créer une demande de réapprovisionnement." });
    if (product.maxStock !== null && available >= Number(product.maxStock)) add({ ...base, alertType: "PRODUCT_OVERSTOCK", category: "STOCK", title: `${product.name} en surstock`, message: `Stock disponible: ${available}.`, criticality: "MEDIUM", recommendedAction: "Contrôler le seuil maximal et les achats." });
    if (!product.referenceSalePrice || Number(product.referenceSalePrice) <= 0) add({ ...base, alertType: "PRODUCT_WITHOUT_PRICE", category: "STOCK", title: `${product.name} sans prix`, message: "Aucun prix de vente de référence valide.", criticality: "HIGH", recommendedAction: "Définir le prix de vente." });
    if (product.stockTrackingEnabled && !product.batches.some((batch) => Number(batch.availableQuantity) > 0)) add({ ...base, alertType: "PRODUCT_WITHOUT_BATCH", category: "STOCK", title: `${product.name} sans lot disponible`, message: "Aucun lot actif ne porte de stock disponible.", criticality: "HIGH", recommendedAction: "Créer ou réceptionner un lot." });
  }
  for (const batch of batches) { const base = { sourceModule: "BATCH_EXPIRY", sourceEntityType: "PharmacyBatch", sourceEntityId: batch.id, productId: batch.productId, batchId: batch.id }; const qty = Number(batch.availableQuantity);
    if (batch.expiryDate < now && qty > 0) add({ ...base, alertType: "BATCH_EXPIRED", category: "EXPIRY", title: `Lot ${batch.batchNumber} expiré`, message: `${qty} unité(s) restent disponibles.`, criticality: "CRITICAL", recommendedAction: "Bloquer le lot et créer un retrait/destruction." });
    else if (batch.expiryDate <= expiryLimit && qty > 0) add({ ...base, alertType: "BATCH_NEAR_EXPIRY", category: "EXPIRY", title: `Lot ${batch.batchNumber} proche péremption`, message: "La date de péremption approche.", criticality: "HIGH", recommendedAction: "Prioriser FEFO et planifier le retrait." });
    if (batch.recall || batch.status === "RECALLED") add({ ...base, alertType: "BATCH_RECALLED", category: "RECALL", title: `Lot ${batch.batchNumber} rappelé`, message: "Ce lot est rappelé.", criticality: "CRITICAL", recommendedAction: "Bloquer et retirer immédiatement le lot." });
    if (batch.quarantine || batch.status === "QUARANTINED") add({ ...base, alertType: "BATCH_QUARANTINED", category: "RECALL", title: `Lot ${batch.batchNumber} en quarantaine`, message: "Une décision qualité reste nécessaire.", criticality: "HIGH", recommendedAction: "Documenter la décision qualité." });
    if (batch.status === "BLOCKED") add({ ...base, alertType: "BATCH_BLOCKED", category: "RECALL", title: `Lot ${batch.batchNumber} bloqué`, message: "Le lot est bloqué.", criticality: "HIGH", recommendedAction: "Contrôler le motif de blocage." });
  }
  for (const order of orders.filter((item) => item.expectedDeliveryDate && item.expectedDeliveryDate < now && ["VALIDATED", "ORDERED", "PARTIALLY_RECEIVED"].includes(item.status))) add({ alertType: "PURCHASE_ORDER_OVERDUE", category: "PURCHASE", title: `Commande ${order.orderNumber} en retard`, message: "La livraison attendue est dépassée.", criticality: "HIGH", sourceModule: "SUPPLIERS_ORDERS", sourceEntityType: "PharmacyPurchaseOrder", sourceEntityId: order.id, supplierId: order.supplierId, purchaseOrderId: order.id, recommendedAction: "Contacter le fournisseur et actualiser la livraison." });
  for (const request of requests.filter((item) => ["SUBMITTED", "IN_VALIDATION", "DRAFT"].includes(item.status))) add({ alertType: "REPLENISHMENT_REQUEST_PENDING", category: "PURCHASE", title: `Réapprovisionnement ${request.requestNumber} en attente`, message: "La demande n'est pas encore convertie ou clôturée.", criticality: "MEDIUM", sourceModule: "SUPPLIERS_ORDERS", sourceEntityType: "PharmacyReplenishmentRequest", sourceEntityId: request.id, productId: request.productId, recommendedAction: "Traiter la demande de réapprovisionnement." });
  for (const item of discrepancies.filter((value) => !["RESOLVED", "CANCELLED"].includes(value.status))) add({ alertType: "RECEIPT_DISCREPANCY_OPEN", category: "RECEIPT", title: "Écart de réception ouvert", message: item.description, criticality: item.criticality, sourceModule: "STOCK_RECEIPTS", sourceEntityType: "PharmacyReceiptDiscrepancy", sourceEntityId: item.id, receiptId: item.receiptId, productId: item.productId, batchId: item.batchId, recommendedAction: item.proposedAction || "Traiter l'écart de réception." });
  for (const sale of sales.filter((item) => item.pharmacistValidationStatus === "PENDING" && item.updatedAt < validationLimit)) add({ alertType: "PHARMACIST_VALIDATION_PENDING", category: "SALE", title: `Validation pharmacien en attente: ${sale.saleNumber}`, message: "Le délai de validation pharmacien est dépassé.", criticality: "HIGH", sourceModule: "SALES_DISPENSATION", sourceEntityType: "PharmacySale", sourceEntityId: sale.id, saleId: sale.id, recommendedAction: "Faire contrôler la vente par le pharmacien." });
  for (const item of anomalies.filter((value) => value.status === "OPEN")) add({ alertType: "SALE_ANOMALY_OPEN", category: "SALE", title: "Anomalie de vente ouverte", message: item.description, criticality: item.criticality, sourceModule: "SALES_DISPENSATION", sourceEntityType: "PharmacySaleAnomaly", sourceEntityId: item.id, saleId: item.saleId, productId: item.productId, batchId: item.batchId, recommendedAction: item.proposedAction || "Contrôler la vente." });
  for (const line of inventoryLines.filter((item) => Math.abs(Number(item.variance || 0)) > Math.max(10, Math.abs(Number(item.systemQuantity)) * 0.25))) add({ alertType: "INVENTORY_VARIANCE_CRITICAL", category: "INVENTORY", title: "Écart d'inventaire critique", message: `Variance détectée: ${line.variance}.`, criticality: "CRITICAL", sourceModule: "STOCK_INVENTORY", sourceEntityType: "PharmacyInventoryLine", sourceEntityId: line.id, inventorySessionId: line.inventorySessionId, productId: line.productId, batchId: line.batchId, recommendedAction: "Contrôler le comptage et créer un ajustement justifié." });
  for (const item of adjustments.filter((value) => ["SUBMITTED", "IN_REVIEW"].includes(value.status))) add({ alertType: "STOCK_ADJUSTMENT_PENDING", category: "ADJUSTMENT", title: "Ajustement stock en attente", message: item.reason, criticality: "MEDIUM", sourceModule: "STOCK_INVENTORY", sourceEntityType: "PharmacyStockAdjustment", sourceEntityId: item.id, adjustmentId: item.id, productId: item.productId, batchId: item.batchId, recommendedAction: "Valider ou rejeter l'ajustement." });
  for (const item of returnLosses.filter((value) => value.eventType === "LOSS" && (value.criticality === "CRITICAL" || Number(value.estimatedValue || 0) >= Number(config.criticalLossValueThreshold)))) add({ alertType: "LOSS_CRITICAL", category: "RETURN_LOSS", title: `Perte critique ${item.eventNumber}`, message: item.reason, criticality: "CRITICAL", sourceModule: "RETURNS_ADJUSTMENTS_LOSSES", sourceEntityType: "PharmacyReturnLossEvent", sourceEntityId: item.id, returnEntityType: item.eventType, returnEntityId: item.id, productId: item.productId, batchId: item.batchId, recommendedAction: "Contrôler, justifier et traiter la perte." });
  for (const item of returnLosses.filter((value) => value.eventType === "DESTRUCTION" && value.status === "SUBMITTED")) add({ alertType: "DESTRUCTION_PENDING", category: "RETURN_LOSS", title: `Destruction en attente ${item.eventNumber}`, message: item.reason, criticality: "HIGH", sourceModule: "RETURNS_ADJUSTMENTS_LOSSES", sourceEntityType: "PharmacyReturnLossEvent", sourceEntityId: item.id, returnEntityType: item.eventType, returnEntityId: item.id, productId: item.productId, batchId: item.batchId, recommendedAction: "Valider et documenter la destruction." });
  for (const item of sessions.filter((value) => value.status === "OPEN" && value.openedAt < cashLimit)) add({ alertType: "CASH_SESSION_OPEN_TOO_LONG", category: "CASH", title: `Caisse ${item.cashSessionNumber} ouverte trop longtemps`, message: "La durée maximale paramétrée est dépassée.", criticality: "HIGH", sourceModule: "CASH_INVOICES_PAYMENTS", sourceEntityType: "PharmacyCashSession", sourceEntityId: item.id, cashSessionId: item.id, recommendedAction: "Clôturer ou justifier la session." });
  for (const item of cashDiscrepancies.filter((value) => !["RESOLVED", "CANCELLED"].includes(value.status) && Math.abs(Number(value.varianceAmount)) >= Number(config.criticalCashVarianceThreshold))) add({ alertType: "CASH_DISCREPANCY_CRITICAL", category: "CASH", title: "Écart caisse critique", message: `Écart détecté: ${item.varianceAmount}.`, criticality: "CRITICAL", sourceModule: "CASH_INVOICES_PAYMENTS", sourceEntityType: "PharmacyCashDiscrepancy", sourceEntityId: item.id, cashSessionId: item.cashSessionId, recommendedAction: "Demander une justification et contrôler la clôture." });
  await persist(organizationId, candidates, actorId); return candidates.length;
}

export async function getPharmacyAlertDataset(organizationId: string, userId: string) {
  await ensureRules(organizationId); const config = await settings(organizationId);
  const [alerts, rules, members, products, batches] = await Promise.all([prisma.pharmacyAlert.findMany({ where: { organizationId }, orderBy: { lastDetectedAt: "desc" }, include: { events: { orderBy: { createdAt: "desc" }, take: 30 } } }), prisma.pharmacyAlertRule.findMany({ where: { organizationId }, orderBy: { sortOrder: "asc" } }), prisma.organizationMember.findMany({ where: { organizationId, status: "ACTIVE", removedAt: null }, select: { user: { select: { id: true, name: true } } } }), prisma.pharmacyProduct.findMany({ where: { organizationId, status: { not: "ARCHIVED" } }, select: { id: true, name: true } }), prisma.pharmacyBatch.findMany({ where: { organizationId }, select: { id: true, productId: true, batchNumber: true } })]);
  const today = new Date().toISOString().slice(0, 10); const count = (test: (item: typeof alerts[number]) => boolean) => alerts.filter(test).length; const metrics = { open: count((a) => activeStatuses.includes(a.status)), critical: count((a) => activeStatuses.includes(a.status) && a.criticality === "CRITICAL"), high: count((a) => activeStatuses.includes(a.status) && a.criticality === "HIGH"), medium: count((a) => activeStatuses.includes(a.status) && a.criticality === "MEDIUM"), low: count((a) => activeStatuses.includes(a.status) && a.criticality === "LOW"), seen: count((a) => a.status === "SEEN"), inProgress: count((a) => a.status === "IN_PROGRESS"), resolvedToday: count((a) => Boolean(a.resolvedAt && a.resolvedAt.toISOString().slice(0, 10) === today)), ignored: count((a) => a.status === "IGNORED"), assignedToMe: count((a) => a.assignedToId === userId && activeStatuses.includes(a.status)), unassigned: count((a) => !a.assignedToId && activeStatuses.includes(a.status)) };
  return { metrics, alerts, rules, settings: config, members: members.map((item) => item.user), products, batches };
}

export async function transitionPharmacyAlert(organizationId: string, alertId: string, userId: string, action: string, comment?: string, assignedToId?: string) {
  const alert = await prisma.pharmacyAlert.findFirst({ where: { id: alertId, organizationId } }); if (!alert) throw new Error("ALERT_NOT_FOUND");
  if (assignedToId && !(await prisma.organizationMember.findFirst({ where: { organizationId, userId: assignedToId, status: "ACTIVE", removedAt: null } }))) throw new Error("ASSIGNEE_INVALID");
  if (["resolve", "ignore", "cancel"].includes(action) && !comment?.trim()) throw new Error("COMMENT_REQUIRED");
  const status = action === "seen" ? "SEEN" : action === "assign" ? "ASSIGNED" : action === "take" ? "IN_PROGRESS" : action === "resolve" ? "RESOLVED" : action === "ignore" ? "IGNORED" : action === "cancel" ? "CANCELLED" : action === "archive" ? "ARCHIVED" : alert.status;
  const data = { status, updatedById: userId, assignedToId: action === "take" ? userId : assignedToId || alert.assignedToId, assignedById: action === "assign" ? userId : alert.assignedById, assignedAt: action === "assign" || action === "take" ? new Date() : alert.assignedAt, seenAt: action === "seen" ? new Date() : alert.seenAt, takenAt: action === "take" ? new Date() : alert.takenAt, resolvedAt: action === "resolve" ? new Date() : alert.resolvedAt, resolvedById: action === "resolve" ? userId : alert.resolvedById, resolutionComment: action === "resolve" ? comment : alert.resolutionComment, ignoredAt: action === "ignore" ? new Date() : alert.ignoredAt, ignoredById: action === "ignore" ? userId : alert.ignoredById, ignoredReason: action === "ignore" ? comment : alert.ignoredReason, cancelledAt: action === "cancel" ? new Date() : alert.cancelledAt, cancelledById: action === "cancel" ? userId : alert.cancelledById, cancellationReason: action === "cancel" ? comment : alert.cancellationReason };
  const updated = await prisma.pharmacyAlert.update({ where: { id: alert.id }, data }); await prisma.pharmacyAlertEvent.create({ data: { organizationId, alertId, actorId: userId, eventType: action.toUpperCase(), oldStatus: alert.status, newStatus: status, comment } }); return updated;
}
