export const pharmacySettingSections = ["general", "numbering", "products-batches", "stock-inventory", "expiry-fefo", "sales", "prescriptions", "receipts-purchases", "cash-payments", "returns-losses", "alerts-notifications", "documents-compliance", "quality", "reports-exports", "privacy-security", "erp-integrations"] as const;
export type PharmacySettingSection = typeof pharmacySettingSections[number];
export type SettingValue = string | number | boolean | null;
export const criticalPharmacySettingKeys = new Set(["allowNegativeStock", "blockExpiredBatchSale", "blockRecalledBatchSale", "enforceFefoSale", "allowSaleWithoutPrescriptionWithPharmacistValidation", "applyStockImpactOnPayment", "refundRequiresValidation", "cashSessionRequiresClosureValidation", "criticalCashVarianceThreshold", "sensitiveDownloadAuditEnabled", "protectPatientData", "allowSensitiveReportExports", "criticalIncidentRequiresCapa", "documentValidationRequired"]);

export const pharmacySettingsDefaults: Record<PharmacySettingSection, Record<string, SettingValue>> = {
  general: { pharmacyName: "", pharmacyType: "OFFICINE", currency: "USD", timezone: "Africa/Kinshasa", language: "fr", country: "", city: "", address: "", phone: "", email: "", receiptFooterMessage: "Merci pour votre confiance.", configurationStatus: "ACTIVE" },
  numbering: { defaultFormat: "PREFIX-YYYY-000001", defaultResetFrequency: "YEARLY", defaultCounterLength: 6, allowManualOverride: false },
  "products-batches": { stockTrackingDefaultEnabled: true, requireBarcodeForProducts: false, requireGenericNameForMedicines: false, requireDosageForMedicines: false, requirePharmaceuticalForm: true, allowProductWithoutPrice: true, allowProductWithoutMinStock: false, requireBatchForStockTrackedProducts: true, requireExpiryDateForBatches: true, allowBatchWithoutSupplier: true, controlledProductsRequireExtraValidation: true },
  "stock-inventory": { allowNegativeStock: false, blockSaleWhenStockUnavailable: true, defaultMinStock: 0, defaultMaxStock: null, lowStockThresholdMode: "PRODUCT", overstockAlertEnabled: true, stockValueCalculationMethod: "BATCH_PRICE", inventoryRequiresValidation: true, inventoryVarianceRequiresReason: true, inventoryVarianceCriticalThresholdQuantity: 10, adjustmentRequiresValidation: true, allowManualStockMovement: false, defaultStockLocationId: null },
  "expiry-fefo": { nearExpiryThresholdDays: 90, criticalExpiryThresholdDays: 30, minimumAcceptableExpiryDaysOnReceipt: 90, blockExpiredBatchSale: true, blockRecalledBatchSale: true, blockQuarantinedBatchSale: true, blockBlockedBatchSale: true, enableFefoSuggestion: true, enforceFefoSale: false, allowOverrideFefoWithReason: false, autoMarkExpiredBatches: true, autoGenerateExpiryAlerts: true, requireReasonForNearExpirySale: false },
  sales: { allowAnonymousSales: true, requireCustomerForCreditSale: true, requireCustomerForRefund: true, allowPriceEditAtSale: false, allowDiscountAtSale: true, maxGlobalDiscountRate: 20, maxLineDiscountRate: 20, requireReasonForDiscount: false, requirePharmacistValidationForSensitiveProducts: true, requirePharmacistValidationForControlledProducts: true, allowSaleDraftWithoutStock: false, applyStockImpactOnPayment: true, applyStockImpactOnValidation: false, generateReceiptAfterPayment: true, allowSaleCancellationAfterPayment: false, saleCancellationRequiresReason: true },
  prescriptions: { prescriptionsModuleEnabled: true, requirePrescriptionForPrescriptionProducts: true, allowSaleWithoutPrescriptionWithPharmacistValidation: false, requirePrescriptionScan: false, allowManualPrescriptionEntry: true, allowGenericSubstitution: true, substitutionRequiresReason: true, substitutionRequiresPharmacistValidation: true, prescriptionValidationRequired: true, prescriptionRejectionRequiresReason: true, allowCreateSaleFromPrescription: true, allowMultipleSalesPerPrescription: false, prescriptionSensitiveDataProtectionEnabled: true, prescriptionDocumentConfidentialityDefault: "CONFIDENTIAL" },
  "receipts-purchases": { allowReceiptWithoutPurchaseOrder: true, receiptRequiresSupplier: true, receiptRequiresInvoiceDocument: false, receiptRequiresDeliveryNoteDocument: false, receiptRequiresValidation: true, allowReceiptValidationByReceiver: false, allowShortExpiryReceipt: false, shortExpiryReceiptRequiresReason: true, allowReceiptCancellationAfterStockImpact: false, purchaseOrderRequiresValidation: true, purchaseOrderRequiresBudget: false, allowOrderToSuspendedSupplier: false, purchaseOrderOverdueAlertDays: 1, autoCreateReplenishmentRequestForLowStock: false },
  "cash-payments": { cashModuleEnabled: true, requireCashSessionForSales: true, allowMultipleOpenCashSessionsPerCashier: false, allowPaymentWithoutCashSession: false, defaultPaymentMethod: "CASH", allowPartialPayment: true, allowCreditSale: true, creditSaleRequiresCustomer: true, refundRequiresValidation: true, refundRequiresReason: true, refundMaxWithoutManagerValidation: 0, cashSessionRequiresOpeningAmount: true, cashSessionRequiresClosureValidation: true, cashierCanValidateOwnClosure: false, maxCashSessionHours: 16, criticalCashVarianceThreshold: 100, cashVarianceRequiresJustification: true, autoGenerateInvoiceAfterSale: false, autoGenerateReceiptAfterPayment: true, invoiceDueDaysDefault: 30 },
  "returns-losses": { customerReturnRequiresSale: true, customerReturnRequiresValidation: true, customerReturnRequiresReason: true, customerReturnRestockRequiresQualityCheck: true, supplierReturnRequiresValidation: true, adjustmentRequiresValidation: true, adjustmentRequiresReason: true, lossRequiresValidation: true, lossRequiresDocument: false, criticalLossValueThreshold: 500, destructionRequiresValidation: true, destructionRequiresDocument: true, destructionRequiresWitness: true, expiredWithdrawalRequiresValidation: true, recallWithdrawalRequiresValidation: true, allowReversalAfterStockImpact: true },
  "alerts-notifications": { alertsEnabled: true, stockAlertsEnabled: true, expiryAlertsEnabled: true, recallAlertsEnabled: true, purchaseAlertsEnabled: true, receiptAlertsEnabled: true, salesAlertsEnabled: true, inventoryAlertsEnabled: true, returnsLossesAlertsEnabled: true, cashAlertsEnabled: true, qualityAlertsEnabled: true, documentAlertsEnabled: true, autoResolveAlertsEnabled: true, criticalAlertNotificationsEnabled: true, alertDeduplicationEnabled: true, notifyManagerOnCriticalAlert: true, alertResolutionRequiresComment: true },
  "documents-compliance": { documentValidationRequired: false, documentExpiryAlertDays: 30, sensitiveDownloadAuditEnabled: true, defaultDocumentConfidentiality: "INTERNAL", supplierComplianceDocumentRequired: true, receiptDeliveryNoteRequired: true, destructionDocumentRequired: true, criticalIncidentDocumentRequired: true },
  quality: { criticalIncidentRequiresImmediateAction: true, criticalIncidentRequiresInvestigation: true, criticalIncidentRequiresCapa: true, highIncidentRequiresInvestigation: true, closureRequiresResolution: true, qualityManagerNotificationEnabled: true, adverseReactionSensitiveDataProtection: true },
  "reports-exports": { defaultReportPeriodDays: 30, allowCsvExport: true, allowSensitiveReportExports: false, auditSensitiveExports: true, showFinancialIndicatorsToManagers: true, maximumReportRows: 250 },
  "privacy-security": { protectPatientData: true, maskSensitiveSettingsHistory: true, requireReasonForCriticalSettingChange: true, auditCriticalSettingChanges: true, restrictSensitiveDocuments: true, restrictFinancialReports: true },
  "erp-integrations": { syncCashToEnterpriseFinance: false, syncPurchaseOrdersToEnterpriseFinance: false, syncDocumentsToEnterpriseDocuments: false, createTasksFromAlerts: false, createInternalRequestsFromAlerts: false, createTasksFromCapa: false, createTasksFromInventoryVariance: false, notifyEnterpriseAdminsOnCriticalEvents: true, useEnterpriseDepartments: true, useEnterpriseDocuments: false, useEnterpriseBudgetModule: false, useEnterpriseAuditLogs: true, useEnterpriseNotifications: true },
};

export const pharmacyNumberingDefaults: Record<string, string> = { PRODUCT: "PRD", BATCH: "LOT", RECEIPT: "REC", SALE: "VTE", PRESCRIPTION: "ORD", SUPPLIER: "FRN", PURCHASE_ORDER: "CMD", REPLENISHMENT_REQUEST: "REA", CASH_SESSION: "CAI", PAYMENT: "PAY", INVOICE: "FAC", CASH_RECEIPT: "RCU", REFUND: "RMB", RETURN_LOSS: "RPL", ALERT: "ALT", QUALITY_INCIDENT: "IQ", DOCUMENT: "DOC", REPORT_EXPORT: "RAP" };
