export const pharmacySettingLabels: Record<string, string> = {
  stockTrackingDefaultEnabled: "Suivi du stock activé par défaut",
  requireBarcodeForProducts: "Code-barres obligatoire pour les produits",
  requireGenericNameForMedicines: "Dénomination commune obligatoire pour les médicaments",
  requireDosageForMedicines: "Dosage obligatoire pour les médicaments",
  requirePharmaceuticalForm: "Forme pharmaceutique obligatoire",
  allowProductWithoutPrice: "Autoriser un produit sans prix",
  allowProductWithoutMinStock: "Autoriser un produit sans seuil minimal",
  requireBatchForStockTrackedProducts: "Lot obligatoire pour les produits suivis en stock",
  requireExpiryDateForBatches: "Date de péremption obligatoire pour les lots",
  allowBatchWithoutSupplier: "Autoriser un lot sans fournisseur",
  controlledProductsRequireExtraValidation: "Validation renforcée des produits contrôlés",
  overstockAlertEnabled: "Alerte de surstock activée",
  inventoryVarianceCriticalThresholdQuantity: "Seuil critique d'écart d'inventaire",
  allowManualStockMovement: "Autoriser les mouvements de stock manuels",
  allowOverrideFefoWithReason: "Autoriser une dérogation FEFO avec motif",
  autoMarkExpiredBatches: "Marquer automatiquement les lots expirés",
  autoGenerateExpiryAlerts: "Créer automatiquement les alertes de péremption",
  requireReasonForNearExpirySale: "Exiger un motif pour vendre un produit proche de la péremption",
  requireCustomerForCreditSale: "Client obligatoire pour une vente à crédit",
  requireCustomerForRefund: "Client obligatoire pour un remboursement",
  requireReasonForDiscount: "Exiger un motif pour une remise",
  requirePharmacistValidationForSensitiveProducts: "Validation pharmacien pour les produits sensibles",
  requirePharmacistValidationForControlledProducts: "Validation pharmacien pour les produits contrôlés",
  allowSaleDraftWithoutStock: "Autoriser un brouillon de vente sans stock",
  applyStockImpactOnPayment: "Déduire le stock au paiement",
  applyStockImpactOnValidation: "Déduire le stock à la validation",
  generateReceiptAfterPayment: "Générer un reçu après paiement",
  allowSaleCancellationAfterPayment: "Autoriser l'annulation après paiement",
  saleCancellationRequiresReason: "Motif obligatoire pour annuler une vente",
  prescriptionsModuleEnabled: "Gestion des ordonnances activée",
  requirePrescriptionForPrescriptionProducts: "Ordonnance obligatoire pour les produits réglementés",
  allowSaleWithoutPrescriptionWithPharmacistValidation: "Autoriser sans ordonnance après validation pharmacien",
  requirePrescriptionScan: "Copie numérique de l'ordonnance obligatoire",
  allowManualPrescriptionEntry: "Autoriser la saisie manuelle d'une ordonnance",
  allowGenericSubstitution: "Autoriser la substitution générique",
  substitutionRequiresReason: "Motif obligatoire pour une substitution",
  substitutionRequiresPharmacistValidation: "Validation pharmacien pour une substitution",
  prescriptionValidationRequired: "Validation obligatoire des ordonnances",
  prescriptionRejectionRequiresReason: "Motif obligatoire pour rejeter une ordonnance",
  allowCreateSaleFromPrescription: "Autoriser la création d'une vente depuis une ordonnance",
  allowMultipleSalesPerPrescription: "Autoriser plusieurs ventes par ordonnance",
  prescriptionSensitiveDataProtectionEnabled: "Protection renforcée des données d'ordonnance",
  prescriptionDocumentConfidentialityDefault: "Confidentialité par défaut des ordonnances",
  allowReceiptWithoutPurchaseOrder: "Autoriser une réception sans commande",
  receiptRequiresSupplier: "Fournisseur obligatoire à la réception",
  receiptRequiresInvoiceDocument: "Facture fournisseur obligatoire",
  receiptRequiresDeliveryNoteDocument: "Bon de livraison obligatoire",
  receiptRequiresValidation: "Validation obligatoire des réceptions",
  allowReceiptValidationByReceiver: "Autoriser le réceptionnaire à valider",
  allowShortExpiryReceipt: "Autoriser les produits à péremption courte",
  shortExpiryReceiptRequiresReason: "Motif obligatoire pour une péremption courte",
  allowReceiptCancellationAfterStockImpact: "Autoriser l'annulation après entrée en stock",
  purchaseOrderRequiresValidation: "Validation obligatoire des commandes",
  purchaseOrderRequiresBudget: "Budget obligatoire pour une commande",
  allowOrderToSuspendedSupplier: "Autoriser une commande à un fournisseur suspendu",
  purchaseOrderOverdueAlertDays: "Délai d'alerte de commande en retard",
  autoCreateReplenishmentRequestForLowStock: "Créer automatiquement une demande de réapprovisionnement",
  cashModuleEnabled: "Gestion de caisse activée",
  requireCashSessionForSales: "Session de caisse obligatoire pour vendre",
  allowMultipleOpenCashSessionsPerCashier: "Autoriser plusieurs sessions ouvertes par caissier",
  allowPaymentWithoutCashSession: "Autoriser un paiement sans session de caisse",
  defaultPaymentMethod: "Mode de paiement par défaut",
  allowPartialPayment: "Autoriser les paiements partiels",
  allowCreditSale: "Autoriser les ventes à crédit",
  creditSaleRequiresCustomer: "Client obligatoire pour une vente à crédit",
  refundRequiresReason: "Motif obligatoire pour un remboursement",
  refundMaxWithoutManagerValidation: "Remboursement maximal sans validation du responsable",
  cashSessionRequiresOpeningAmount: "Montant d'ouverture obligatoire",
  cashSessionRequiresClosureValidation: "Validation obligatoire de la clôture",
  cashierCanValidateOwnClosure: "Autoriser le caissier à valider sa clôture",
  cashVarianceRequiresJustification: "Justification obligatoire pour un écart de caisse",
  autoGenerateInvoiceAfterSale: "Générer automatiquement une facture après vente",
  autoGenerateReceiptAfterPayment: "Générer automatiquement un reçu après paiement",
  invoiceDueDaysDefault: "Délai de paiement par défaut des factures",
  customerReturnRequiresSale: "Vente d'origine obligatoire pour un retour client",
  customerReturnRequiresValidation: "Validation obligatoire des retours clients",
  customerReturnRequiresReason: "Motif obligatoire pour un retour client",
  customerReturnRestockRequiresQualityCheck: "Contrôle qualité avant remise en stock",
  supplierReturnRequiresValidation: "Validation obligatoire des retours fournisseur",
  adjustmentRequiresReason: "Motif obligatoire pour un ajustement",
  lossRequiresValidation: "Validation obligatoire des pertes",
  lossRequiresDocument: "Justificatif obligatoire pour une perte",
  criticalLossValueThreshold: "Valeur critique d'une perte",
  destructionRequiresValidation: "Validation obligatoire des destructions",
  destructionRequiresDocument: "Justificatif obligatoire des destructions",
  destructionRequiresWitness: "Témoin obligatoire pour une destruction",
  expiredWithdrawalRequiresValidation: "Validation obligatoire du retrait des produits expirés",
  recallWithdrawalRequiresValidation: "Validation obligatoire d'un retrait pour rappel",
  allowReversalAfterStockImpact: "Autoriser une contre-passation après impact stock",
  alertsEnabled: "Alertes pharmacie activées",
  stockAlertsEnabled: "Alertes de stock activées",
  expiryAlertsEnabled: "Alertes de péremption activées",
  recallAlertsEnabled: "Alertes de rappel activées",
  purchaseAlertsEnabled: "Alertes d'achats activées",
  receiptAlertsEnabled: "Alertes de réception activées",
  salesAlertsEnabled: "Alertes de vente activées",
  inventoryAlertsEnabled: "Alertes d'inventaire activées",
  returnsLossesAlertsEnabled: "Alertes de retours et pertes activées",
  cashAlertsEnabled: "Alertes de caisse activées",
  qualityAlertsEnabled: "Alertes qualité activées",
  documentAlertsEnabled: "Alertes documentaires activées",
  autoResolveAlertsEnabled: "Résolution automatique des alertes activée",
  criticalAlertNotificationsEnabled: "Notifications des alertes critiques activées",
  alertDeduplicationEnabled: "Regroupement des alertes identiques activé",
  notifyManagerOnCriticalAlert: "Notifier le responsable en cas d'alerte critique",
  alertResolutionRequiresComment: "Commentaire obligatoire pour résoudre une alerte",
  documentValidationRequired: "Validation obligatoire des documents",
  defaultDocumentConfidentiality: "Confidentialité documentaire par défaut",
  supplierComplianceDocumentRequired: "Document de conformité fournisseur obligatoire",
  receiptDeliveryNoteRequired: "Bon de livraison obligatoire à la réception",
  destructionDocumentRequired: "Document de destruction obligatoire",
  criticalIncidentDocumentRequired: "Justificatif obligatoire pour un incident critique",
  criticalIncidentRequiresImmediateAction: "Action immédiate obligatoire pour un incident critique",
  criticalIncidentRequiresInvestigation: "Investigation obligatoire pour un incident critique",
  highIncidentRequiresInvestigation: "Investigation obligatoire pour un incident élevé",
  closureRequiresResolution: "Résolution obligatoire avant clôture",
  qualityManagerNotificationEnabled: "Notifier le responsable qualité",
  adverseReactionSensitiveDataProtection: "Protection renforcée des données d'effets indésirables",
  allowCsvExport: "Autoriser les exports CSV",
  auditSensitiveExports: "Auditer les exports sensibles",
  showFinancialIndicatorsToManagers: "Afficher les indicateurs financiers aux responsables",
  maximumReportRows: "Nombre maximal de lignes par rapport",
  maskSensitiveSettingsHistory: "Masquer les valeurs sensibles dans l'historique",
  requireReasonForCriticalSettingChange: "Motif obligatoire pour un paramètre critique",
  auditCriticalSettingChanges: "Auditer les changements critiques",
  restrictSensitiveDocuments: "Restreindre les documents sensibles",
  restrictFinancialReports: "Restreindre les rapports financiers",
  syncCashToEnterpriseFinance: "Synchroniser la caisse avec les finances de l'entreprise",
  syncPurchaseOrdersToEnterpriseFinance: "Synchroniser les commandes avec les finances de l'entreprise",
  syncDocumentsToEnterpriseDocuments: "Synchroniser avec les documents de l'entreprise",
  createTasksFromAlerts: "Créer des tâches depuis les alertes",
  createInternalRequestsFromAlerts: "Créer des demandes internes depuis les alertes",
  createTasksFromCapa: "Créer des tâches depuis les actions correctives",
  createTasksFromInventoryVariance: "Créer des tâches depuis les écarts d'inventaire",
  notifyEnterpriseAdminsOnCriticalEvents: "Notifier les administrateurs lors d'événements critiques",
  useEnterpriseDocuments: "Utiliser les documents de l'entreprise",
  useEnterpriseBudgetModule: "Utiliser les budgets de l'entreprise",
};

export const pharmacyNumberingEntityLabels: Record<string, string> = {
  PRODUCT: "Produit",
  BATCH: "Lot",
  RECEIPT: "Réception",
  SALE: "Vente",
  PRESCRIPTION: "Ordonnance",
  SUPPLIER: "Fournisseur",
  PURCHASE_ORDER: "Commande fournisseur",
  REPLENISHMENT_REQUEST: "Demande de réapprovisionnement",
  CASH_SESSION: "Session de caisse",
  PAYMENT: "Paiement",
  INVOICE: "Facture",
  CASH_RECEIPT: "Reçu de caisse",
  REFUND: "Remboursement",
  RETURN_LOSS: "Retour, ajustement ou perte",
  ALERT: "Alerte",
  QUALITY_INCIDENT: "Incident qualité",
  DOCUMENT: "Document",
  REPORT_EXPORT: "Export de rapport",
};
