import type { z } from "zod";
import { effectivePharmacyBatchStatus } from "@/lib/pharmacy-batches";
import type { pharmacySaleSchema } from "@/lib/pharmacy-sale-validators";
import { generatePharmacyEntityNumber, getEffectivePharmacySettings } from "@/lib/pharmacy-settings";
import { prisma } from "@/lib/prisma";
type SaleInput = z.infer<typeof pharmacySaleSchema>;
const nil = <T>(value: T | "" | undefined) => value === "" || value === undefined ? null : value;
export async function validateSaleReferences(organizationId: string, data: SaleInput) {
  const settings = (await getEffectivePharmacySettings(organizationId)).sections; const salesSettings = settings.sales; const prescriptionSettings = settings.prescriptions; const stockSettings = settings["stock-inventory"]; const expirySettings = settings["expiry-fefo"];
  const [cashier, department, products, batches, prescription] = await Promise.all([
    prisma.organizationMember.findFirst({ where: { organizationId, userId: data.cashierId, status: "ACTIVE", removedAt: null }, select: { id: true } }),
    data.departmentId ? prisma.enterpriseDepartment.findFirst({ where: { id: data.departmentId, organizationId, isActive: true }, select: { id: true } }) : null,
    prisma.pharmacyProduct.findMany({ where: { organizationId, id: { in: data.lines.map((line) => line.productId) }, status: "ACTIVE" } }),
    prisma.pharmacyBatch.findMany({ where: { organizationId, id: { in: data.lines.map((line) => line.batchId) } } }),
    data.prescriptionId ? prisma.pharmacyPrescription.findFirst({ where: { id: data.prescriptionId, organizationId, status: { notIn: ["REJECTED", "ARCHIVED", "CANCELLED"] } }, select: { id: true } }) : null,
  ]);
  if (!cashier) return "Le caissier n'appartient pas à cette pharmacie.";
  if (data.departmentId && !department) return "Le département n'appartient pas à cette pharmacie.";
  if (data.prescriptionId && !prescription) return "L'ordonnance n'appartient pas à cette pharmacie.";
  if (!salesSettings.allowAnonymousSales && !data.customerName?.trim()) return "Le client est obligatoire selon les paramètres pharmacie.";
  const productMap = new Map(products.map((item) => [item.id, item]));
  const batchMap = new Map(batches.map((item) => [item.id, item]));
  for (const line of data.lines) {
    const product = productMap.get(line.productId); const batch = batchMap.get(line.batchId);
    if (!product) return "Un produit n'appartient pas à cette pharmacie.";
    if (!batch || batch.productId !== line.productId) return "Un lot ne correspond pas au produit ou à cette pharmacie.";
    const batchStatus = effectivePharmacyBatchStatus({ ...batch, expiryAlertDays: Number(expirySettings.nearExpiryThresholdDays) });
    if ((batchStatus === "EXPIRED" && expirySettings.blockExpiredBatchSale) || (batchStatus === "RECALLED" && expirySettings.blockRecalledBatchSale) || (batchStatus === "QUARANTINED" && expirySettings.blockQuarantinedBatchSale) || (batchStatus === "BLOCKED" && expirySettings.blockBlockedBatchSale) || batchStatus === "CANCELLED") return "Un lot sélectionné n'est pas vendable selon les paramètres pharmacie.";
    if (Number(batch.availableQuantity) < line.quantity && (!stockSettings.allowNegativeStock || stockSettings.blockSaleWhenStockUnavailable)) return "La quantité demandée dépasse le stock disponible.";
    if (product.maxQuantityPerSale !== null && line.quantity > Number(product.maxQuantityPerSale)) return "La quantité dépasse la limite autorisée par vente.";
    if ((!salesSettings.allowPriceEditAtSale || !product.priceEditableAtSale) && product.referenceSalePrice !== null && line.unitPrice !== Number(product.referenceSalePrice)) return "Le prix de ce produit ne peut pas être modifié.";
    if ((!salesSettings.allowDiscountAtSale || !product.discountAllowed) && line.lineDiscount > 0) return "Les remises ne sont pas autorisées pour ce produit.";
    if (line.lineDiscount > Number(salesSettings.maxLineDiscountRate)) return "La remise de ligne dépasse le plafond pharmacie.";
    if (product.maxDiscountRate !== null && line.lineDiscount > Number(product.maxDiscountRate)) return "La remise dépasse la limite autorisée.";
    if (product.prescriptionRequired && prescriptionSettings.requirePrescriptionForPrescriptionProducts && !data.prescriptionId && !prescriptionSettings.allowSaleWithoutPrescriptionWithPharmacistValidation) return "Une ordonnance est obligatoire pour un produit du panier.";
  }
  if (data.globalDiscount > Number(salesSettings.maxGlobalDiscountRate)) return "La remise globale dépasse le plafond pharmacie.";
  if (expirySettings.enforceFefoSale) for (const line of data.lines) { const first = await prisma.pharmacyBatch.findFirst({ where: { organizationId, productId: line.productId, availableQuantity: { gt: 0 }, expiryDate: { gt: new Date() }, recall: false, quarantine: false, status: { notIn: ["RECALLED", "QUARANTINED", "BLOCKED", "CANCELLED", "EXPIRED"] } }, orderBy: { expiryDate: "asc" }, select: { id: true } }); if (first && first.id !== line.batchId) return "La règle FEFO impose de sélectionner le lot vendable qui expire le plus tôt."; }
  return null;
}
export async function createSale(organizationId: string, userId: string, data: SaleInput) {
  const products = await prisma.pharmacyProduct.findMany({ where: { organizationId, id: { in: data.lines.map((line) => line.productId) } } });
  const productMap = new Map(products.map((item) => [item.id, item]));
  const lines = data.lines.map((line) => { const product = productMap.get(line.productId)!; const totalLine = line.quantity * line.unitPrice * (1 - line.lineDiscount / 100); return { ...line, totalLine, requiresPrescription: product.prescriptionRequired, requiresPharmacistValidation: product.pharmacistValidationRequired || product.controlledProduct || (product.prescriptionRequired && !data.prescriptionId) }; });
  const subtotal = lines.reduce((sum, line) => sum + line.totalLine, 0); const totalAmount = subtotal * (1 - data.globalDiscount / 100) + data.taxAmount; const validationRequired = lines.some((line) => line.requiresPharmacistValidation);
  const saleNumber = data.saleNumber || await generatePharmacyEntityNumber(organizationId, "SALE");
  return prisma.$transaction(async (tx) => { const sale = await tx.pharmacySale.create({ data: { organizationId, saleNumber, saleType: data.saleType, customerName: nil(data.customerName), customerPhone: nil(data.customerPhone), customerType: nil(data.customerType), prescriptionId: nil(data.prescriptionId), prescriberName: nil(data.prescriberName), cashierId: data.cashierId, departmentId: nil(data.departmentId), saleDate: data.saleDate, subtotal, globalDiscount: data.globalDiscount, taxAmount: data.taxAmount, totalAmount, paidAmount: 0, remainingAmount: totalAmount, paymentMethod: null, paymentReference: null, paymentStatus: "UNPAID", validationRequired, pharmacistValidationStatus: validationRequired ? "PENDING" : "NOT_REQUIRED", status: validationRequired ? "PHARMACIST_VALIDATION" : "DRAFT", notes: nil(data.notes), createdById: userId, updatedById: userId } }); await tx.pharmacySaleLine.createMany({ data: lines.map((line) => ({ organizationId, saleId: sale.id, productId: line.productId, batchId: line.batchId, quantity: line.quantity, unit: line.unit, unitPrice: line.unitPrice, lineDiscount: line.lineDiscount, totalLine: line.totalLine, requiresPrescription: line.requiresPrescription, requiresPharmacistValidation: line.requiresPharmacistValidation, lineStatus: line.requiresPharmacistValidation ? "PENDING_VALIDATION" : "VALID", notes: nil(line.notes) })) }); return sale; });
}
export async function applySaleStockImpact(organizationId: string, saleId: string, userId: string) { const settings = (await getEffectivePharmacySettings(organizationId, userId)).sections; return prisma.$transaction(async (tx) => { const sale = await tx.pharmacySale.findFirst({ where: { id: saleId, organizationId }, include: { lines: true } }); if (!sale) throw new Error("SALE_NOT_FOUND"); if (sale.stockImpactApplied) return sale; if (sale.validationRequired && sale.pharmacistValidationStatus !== "VALIDATED") throw new Error("PHARMACIST_VALIDATION_REQUIRED"); for (const line of sale.lines) { const batch = await tx.pharmacyBatch.findFirst({ where: { id: line.batchId, organizationId, productId: line.productId } }); if (!batch) throw new Error("BATCH_NOT_SELLABLE"); const batchStatus = effectivePharmacyBatchStatus({ ...batch, expiryAlertDays: Number(settings["expiry-fefo"].nearExpiryThresholdDays) }); if ((batchStatus === "EXPIRED" && settings["expiry-fefo"].blockExpiredBatchSale) || (batchStatus === "RECALLED" && settings["expiry-fefo"].blockRecalledBatchSale) || (batchStatus === "QUARANTINED" && settings["expiry-fefo"].blockQuarantinedBatchSale) || (batchStatus === "BLOCKED" && settings["expiry-fefo"].blockBlockedBatchSale)) throw new Error("BATCH_NOT_SELLABLE"); const before = Number(batch.availableQuantity); const quantity = Number(line.quantity); if (before < quantity && (!settings["stock-inventory"].allowNegativeStock || settings["stock-inventory"].blockSaleWhenStockUnavailable)) throw new Error("INSUFFICIENT_STOCK"); await tx.pharmacyBatch.update({ where: { id: batch.id }, data: { availableQuantity: before - quantity, status: before - quantity === 0 ? "DEPLETED" : batch.status, updatedById: userId } }); await tx.pharmacyStockMovement.create({ data: { organizationId, productId: line.productId, batchId: line.batchId, movementType: "SALE", direction: "OUT", quantity, quantityBefore: before, quantityAfter: before - quantity, reason: `Vente ${sale.saleNumber}`, relatedEntityType: "PharmacySale", relatedEntityId: sale.id, createdById: userId } }); } return tx.pharmacySale.update({ where: { id: sale.id }, data: { stockImpactApplied: true, status: Number(sale.paidAmount) >= Number(sale.totalAmount) ? "PAID" : "VALIDATED", updatedById: userId } }); }); }
export async function reverseSaleStockImpact(organizationId: string, saleId: string, userId: string, reason: string) { return prisma.$transaction(async (tx) => { const sale = await tx.pharmacySale.findFirst({ where: { id: saleId, organizationId }, include: { lines: true } }); if (!sale) throw new Error("SALE_NOT_FOUND"); if (sale.stockImpactApplied) for (const line of sale.lines) { const batch = await tx.pharmacyBatch.findFirst({ where: { id: line.batchId, organizationId } }); if (!batch) throw new Error("BATCH_NOT_FOUND"); const before = Number(batch.availableQuantity); const quantity = Number(line.quantity); await tx.pharmacyBatch.update({ where: { id: batch.id }, data: { availableQuantity: before + quantity, status: batch.status === "DEPLETED" ? "ACTIVE" : batch.status, updatedById: userId } }); await tx.pharmacyStockMovement.create({ data: { organizationId, productId: line.productId, batchId: line.batchId, movementType: "SALE_CANCELLATION", direction: "IN", quantity, quantityBefore: before, quantityAfter: before + quantity, reason, relatedEntityType: "PharmacySale", relatedEntityId: sale.id, createdById: userId } }); } return tx.pharmacySale.update({ where: { id: sale.id }, data: { stockImpactApplied: false, status: "CANCELLED", cancellationReason: reason, cancelledById: userId, cancelledAt: new Date(), updatedById: userId } }); }); }
export async function getSalesDataset(organizationId: string) { const [sales, products, batches, members, departments, prescriptions, movements] = await Promise.all([prisma.pharmacySale.findMany({ where: { organizationId }, orderBy: { saleDate: "desc" }, include: { lines: true, refunds: true, anomalies: true } }), prisma.pharmacyProduct.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.pharmacyBatch.findMany({ where: { organizationId, availableQuantity: { gt: 0 } }, orderBy: { expiryDate: "asc" } }), prisma.organizationMember.findMany({ where: { organizationId, status: "ACTIVE", removedAt: null }, select: { user: { select: { id: true, name: true } } } }), prisma.enterpriseDepartment.findMany({ where: { organizationId, isActive: true }, select: { id: true, labelFr: true } }), prisma.pharmacyPrescription.findMany({ where: { organizationId, status: { notIn: ["REJECTED", "ARCHIVED", "CANCELLED"] } }, select: { id: true, prescriptionNumber: true } }), prisma.pharmacyStockMovement.findMany({ where: { organizationId, relatedEntityType: "PharmacySale" }, orderBy: { createdAt: "desc" }, take: 300 })]); const today = new Date().toISOString().slice(0,10); const month = new Date(new Date().getFullYear(), new Date().getMonth(), 1); const metrics = { today: sales.filter((s) => s.saleDate.toISOString().slice(0,10) === today).length, month: sales.filter((s) => s.saleDate >= month).length, todayAmount: sales.filter((s) => s.saleDate.toISOString().slice(0,10) === today).reduce((a,s)=>a+Number(s.totalAmount),0), monthAmount: sales.filter((s)=>s.saleDate>=month).reduce((a,s)=>a+Number(s.totalAmount),0), paid: sales.filter((s)=>s.paymentStatus==="PAID").length, partial: sales.filter((s)=>s.paymentStatus==="PARTIALLY_PAID").length, cancelled: sales.filter((s)=>s.status==="CANCELLED").length, refunds: sales.flatMap((s)=>s.refunds).length, pendingValidation: sales.filter((s)=>s.pharmacistValidationStatus==="PENDING").length, prescriptions: sales.filter((s)=>s.prescriptionId).length, anomalies: sales.flatMap((s)=>s.anomalies).filter((a)=>a.status==="OPEN").length, stockImpacted: sales.filter((s)=>s.stockImpactApplied && s.saleDate.toISOString().slice(0,10)===today).length }; return { metrics, sales, products, batches: batches.filter((b)=>["ACTIVE","NEAR_EXPIRY"].includes(effectivePharmacyBatchStatus(b))), members: members.map((m)=>m.user), departments, prescriptions: prescriptions.map((prescription) => ({ id: prescription.id, title: prescription.prescriptionNumber })), movements }; }
