"use client";

import { Archive, Eye, PauseCircle, Pencil, Plus, UserPlus } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { BusinessList, BusinessListItem } from "@/components/workspace/business-list";
import { ContextActions, type BusinessContextAction } from "@/components/workspace/context-actions";
import { EmptyState } from "@/components/workspace/empty-state";
import { ModuleMetric, ModuleMetrics } from "@/components/workspace/module-metrics";
import { ModuleSection } from "@/components/workspace/module-workspace";
import { StatusBadge } from "@/components/workspace/status-badge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useToastMessage } from "@/components/ui/use-toast-message";
import { Field, NativeSelect, statusLabel } from "@/components/enterprise/core-v2/erp-v2-ui";
import { enterpriseV2Mutation, useEnterpriseV2Collection } from "@/components/enterprise/core-v2/use-enterprise-v2-collection";

type SupplierItem = { id: string; legalName: string; displayName: string | null; category: string | null; status: string; email: string | null; phone: string | null; country: string | null; revision: number; contacts: Array<{ id: string; name: string; title: string | null; email: string | null; phone: string | null; isPrimary: boolean }>; _count: { purchases: number } };
type LegacyRecord = { id: string; title: string; description: string | null; status: string; updatedAt: string };
const supplierStatuses = ["PROSPECT", "ACTIVE", "SUSPENDED", "INACTIVE"];
function supplierStatusLabel(locale: string | null | undefined, value: string) { const fr: Record<string, string> = { PROSPECT: "Prospect", ACTIVE: "Actif", SUSPENDED: "Suspendu", INACTIVE: "Inactif" }; const en: Record<string, string> = { PROSPECT: "Prospect", ACTIVE: "Active", SUSPENDED: "Suspended", INACTIVE: "Inactive" }; return (locale === "en" ? en : fr)[value] || value; }

export function EnterpriseSuppliersWorkspace({ organizationId, canManage, locale, legacyRecords = [] }: { organizationId: string; canManage: boolean; locale?: string | null; legacyRecords?: LegacyRecord[] }) {
  const en = locale === "en"; const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [country, setCountry] = useState(""); const [refreshKey, setRefreshKey] = useState(0); const [createOpen, setCreateOpen] = useState(false); const [detail, setDetail] = useState<SupplierItem | null>(null); const [contactTarget, setContactTarget] = useState<SupplierItem | null>(null); const [message, setMessage] = useState(""); useToastMessage(message);
  const params = useMemo(() => { const value = new URLSearchParams({ page: String(page), pageSize: "20" }); if (search.trim()) value.set("search", search.trim()); if (status) value.set("status", status); if (country.trim()) value.set("country", country.trim()); return value; }, [page, search, status, country]);
  const collection = useEnterpriseV2Collection<SupplierItem>({ endpoint: `/api/enterprise/${organizationId}/suppliers`, params, refreshKey }); const metrics = collection.meta.metrics || {};
  async function createSupplier(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/suppliers`, "POST", Object.fromEntries(new FormData(event.currentTarget).entries())); setCreateOpen(false); setRefreshKey((v) => v + 1); setMessage(en ? "Supplier created." : "Fournisseur créé."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  async function addContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!contactTarget) return; const form = new FormData(event.currentTarget); try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/suppliers/${contactTarget.id}/contacts`, "POST", { ...Object.fromEntries(form.entries()), isPrimary: form.get("isPrimary") === "on" }); setContactTarget(null); setRefreshKey((v) => v + 1); setMessage(en ? "Contact added." : "Contact ajouté."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  async function action(item: SupplierItem, actionName: string) { const reason = actionName === "SUSPEND" ? (window.prompt(en ? "Suspension reason" : "Motif de suspension") || "") : ""; if (actionName === "SUSPEND" && !reason) return; try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/suppliers/${item.id}/actions`, "POST", { action: actionName, revision: item.revision, reason }); setRefreshKey((v) => v + 1); setMessage(en ? "Supplier updated." : "Fournisseur mis à jour."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  const actionsFor = (item: SupplierItem): BusinessContextAction[] => [{ id: "open", label: en ? "Open" : "Ouvrir", icon: Eye, onSelect: () => setDetail(item) }, ...(canManage ? [{ id: "contact", label: en ? "Add contact" : "Ajouter contact", icon: UserPlus, onSelect: () => setContactTarget(item) }, ...(item.status === "ACTIVE" ? [{ id: "suspend", label: en ? "Suspend" : "Suspendre", icon: PauseCircle, onSelect: () => void action(item, "SUSPEND") }] : [{ id: "activate", label: en ? "Activate" : "Activer", icon: Pencil, onSelect: () => void action(item, "ACTIVATE") }]), { id: "archive", label: en ? "Archive" : "Archiver", icon: Archive, destructive: true, separatorBefore: true, onSelect: () => void action(item, "ARCHIVE") }] : [])];
  return <div className="grid min-w-0 gap-5">
    <ModuleMetrics label={en ? "Supplier indicators" : "Indicateurs fournisseurs"}><ModuleMetric label={en ? "Active" : "Actifs"} value={metrics.active || 0} /><ModuleMetric label={en ? "Suspended" : "Suspendus"} value={metrics.suspended || 0} /><ModuleMetric label={en ? "New (30 days)" : "Nouveaux (30 jours)"} value={metrics.recent || 0} /></ModuleMetrics>
    <ModuleSection title={en ? "Suppliers" : "Fournisseurs"} description={en ? "Third-party supplier registry, independent from DTSC users." : "Référentiel de tiers fournisseurs, indépendant des comptes utilisateurs DTSC."} count={`${collection.pagination.total}`} action={canManage ? <Button onClick={() => setCreateOpen(true)} className="bg-dtsc-blue text-white"><Plus className="h-4 w-4" />{en ? "New supplier" : "Nouveau fournisseur"}</Button> : undefined}>
      <div className="grid gap-2 border-y border-dtsc-border py-3 md:grid-cols-3"><Input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder={en ? "Search suppliers…" : "Rechercher un fournisseur…"} /><NativeSelect value={status} onChange={setStatus} items={supplierStatuses.map((id) => ({ id, label: supplierStatusLabel(locale, id) }))} /><Input value={country} onChange={(e) => setCountry(e.target.value)} placeholder={en ? "Country" : "Pays"} /></div>
      {collection.loading ? <p className="py-8 text-center text-sm text-dtsc-muted">{en ? "Loading…" : "Chargement…"}</p> : collection.items.length ? <BusinessList ariaLabel={en ? "Suppliers" : "Fournisseurs"}>{collection.items.map((item) => <BusinessListItem key={item.id} title={item.displayName || item.legalName} status={<StatusBadge>{supplierStatusLabel(locale, item.status)}</StatusBadge>} meta={`${item.category || (en ? "Uncategorized" : "Sans catégorie")} · ${item.country || "—"} · ${item._count.purchases} ${en ? "purchases" : "achats"}`} description={item.contacts[0] ? `${item.contacts[0].name}${item.contacts[0].title ? ` · ${item.contacts[0].title}` : ""}` : item.email || item.phone || ""} onOpen={() => setDetail(item)} openLabel={`${en ? "Open" : "Ouvrir"} ${item.legalName}`} actions={<ContextActions label={en ? "Supplier actions" : "Actions fournisseur"} actions={actionsFor(item)} />} />)}</BusinessList> : <EmptyState compact title={en ? "No suppliers" : "Aucun fournisseur"} description={collection.error || (en ? "No supplier matches the filters." : "Aucun fournisseur ne correspond aux filtres.")} />}
      <div className="mt-3 flex justify-between border-t border-dtsc-border pt-3 text-sm text-dtsc-muted"><span>Page {collection.pagination.page}/{collection.pagination.pageCount}</span><div className="flex gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => setPage((v) => Math.max(1, v - 1))}>{en ? "Previous" : "Précédent"}</Button><Button variant="outline" disabled={page >= collection.pagination.pageCount} onClick={() => setPage((v) => v + 1)}>{en ? "Next" : "Suivant"}</Button></div></div>
    </ModuleSection>
    {legacyRecords.length ? <ModuleSection title={en ? "Historical suppliers" : "Fournisseurs historiques"} description={en ? "Legacy supplier records are read-only." : "Les anciens fournisseurs restent en lecture seule."}><BusinessList ariaLabel="legacy suppliers">{legacyRecords.map((item) => <BusinessListItem key={item.id} title={item.title} status={<StatusBadge>{en ? "History" : "Historique"}</StatusBadge>} description={item.description || statusLabel(locale, item.status)} />)}</BusinessList></ModuleSection> : null}
    <Dialog open={createOpen} onClose={() => setCreateOpen(false)} title={en ? "New supplier" : "Nouveau fournisseur"} className="h-[94dvh] max-w-3xl"><form onSubmit={createSupplier} className="grid gap-4"><Field label={en ? "Legal name" : "Raison sociale"}><Input name="legalName" required /></Field><div className="grid gap-3 md:grid-cols-2"><Field label={en ? "Display name" : "Nom usuel"}><Input name="displayName" /></Field><Field label={en ? "Category" : "Catégorie"}><Input name="category" /></Field><Field label="Email"><Input name="email" type="email" /></Field><Field label={en ? "Phone" : "Téléphone"}><Input name="phone" /></Field><Field label={en ? "Country" : "Pays"}><Input name="country" /></Field><Field label={en ? "Status" : "Statut"}><NativeSelect name="status" defaultValue="PROSPECT" items={supplierStatuses.map((id) => ({ id, label: supplierStatusLabel(locale, id) }))} /></Field></div><Button className="bg-dtsc-blue text-white">{en ? "Create supplier" : "Créer le fournisseur"}</Button></form></Dialog>
    <Dialog open={Boolean(contactTarget)} onClose={() => setContactTarget(null)} title={en ? "Add supplier contact" : "Ajouter un contact fournisseur"} description={contactTarget?.legalName}><form onSubmit={addContact} className="grid gap-4"><Field label={en ? "Name" : "Nom"}><Input name="name" required /></Field><Field label={en ? "Role / title" : "Fonction"}><Input name="title" /></Field><div className="grid gap-3 md:grid-cols-2"><Field label="Email"><Input name="email" type="email" /></Field><Field label={en ? "Phone" : "Téléphone"}><Input name="phone" /></Field></div><label className="flex items-center gap-2 text-sm"><input name="isPrimary" type="checkbox" />{en ? "Primary contact" : "Contact principal"}</label><Button className="bg-dtsc-blue text-white">{en ? "Add" : "Ajouter"}</Button></form></Dialog>
    <Dialog open={Boolean(detail)} onClose={() => setDetail(null)} title={detail?.displayName || detail?.legalName || ""}>{detail ? <div className="grid gap-3 text-sm"><StatusBadge>{supplierStatusLabel(locale, detail.status)}</StatusBadge><p>{detail.legalName}</p><p className="text-dtsc-muted">{detail.email || "—"} · {detail.phone || "—"}</p><p>{en ? "Country" : "Pays"}: {detail.country || "—"}</p><p>{en ? "Active purchases" : "Achats liés"}: {detail._count.purchases}</p>{detail.contacts.length ? <div className="border-t border-dtsc-border pt-3"><strong>{en ? "Contacts" : "Contacts"}</strong>{detail.contacts.map((contact) => <p key={contact.id} className="mt-1 text-dtsc-muted">{contact.name}{contact.isPrimary ? ` · ${en ? "Primary" : "Principal"}` : ""}</p>)}</div> : null}</div> : null}</Dialog>
  </div>;
}
