"use client";

import { Eye, FilePlus2, Plus, Send, XCircle, CheckCircle2, RotateCcw } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { BusinessList, BusinessListItem } from "@/components/workspace/business-list";
import { ContextActions, type BusinessContextAction } from "@/components/workspace/context-actions";
import { EmptyState } from "@/components/workspace/empty-state";
import { ModuleMetric, ModuleMetrics } from "@/components/workspace/module-metrics";
import { ModuleSection } from "@/components/workspace/module-workspace";
import { StatusBadge } from "@/components/workspace/status-badge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useToastMessage } from "@/components/ui/use-toast-message";
import { Field, NativeSelect, formatEnterpriseDate, type EnterpriseChoice } from "@/components/enterprise/core-v2/erp-v2-ui";
import { enterpriseV2Mutation, useEnterpriseV2Collection } from "@/components/enterprise/core-v2/use-enterprise-v2-collection";

type LegacyRecord = { id: string; recordType?: string; title: string; description: string | null; status: string; updatedAt: string };
type BudgetItem = { id: string; reference: string; title: string; description: string | null; status: string; periodStart: string; periodEnd: string; currency: string; departmentId: string | null; revision: number; plannedAmount: string | number; committedAmount: string | number; actualAmount: string | number; availableAmount: string | number; lineCount: number };
type ExpenseItem = { id: string; reference: string; title: string; description: string | null; status: string; expenseDate: string; category: string | null; currency: string; amount: string | number; supplierId: string | null; purchaseId: string | null; budgetLineId: string | null; revision: number; budgetStatus: string; supplier: { id: string; legalName: string; displayName: string | null } | null; purchase: { id: string; reference: string; title: string; totalAmount: string | number } | null; budgetLine: { id: string; name: string; budget: { id: string; reference: string; title: string; currency: string; status: string } } | null };
type BudgetDetail = { budget: BudgetItem; lines: Array<{ id: string; code: string | null; name: string; category: string | null; plannedAmount: string | number; committedAmount: string | number; actualAmount: string | number; availableAmount: string | number }>; totals: { plannedAmount: string | number; committedAmount: string | number; actualAmount: string | number; availableAmount: string | number }; purchases: Array<{ id: string; reference: string; title: string; status: string; totalAmount: string | number; currency: string }>; expenses: Array<{ id: string; reference: string; title: string; status: string; amount: string | number; currency: string }>; events: Array<{ id: string; summary: string; createdAt: string }> };
type ExpenseDetail = { expense: ExpenseItem & { amountVarianceReason?: string | null }; documents: Array<{ id: string; title: string; documentType: string }>; events: Array<{ id: string; summary: string; createdAt: string }>; approval: { id: string; status: string; approverUserId: string; decisionComment: string | null } | null };
type SummaryBucket = { currency: string; activeBudgets: number; plannedAmount: string; committedAmount: string; actualAmount: string; availableAmount: string; unbudgetedExpenseAmount: string; unbudgetedExpenseCount: number };
type BudgetLineDraft = { name: string; code: string; category: string; plannedAmount: string; departmentId: string };

const budgetStatuses = ["DRAFT", "PENDING_APPROVAL", "ACTIVE", "REJECTED", "CLOSED", "CANCELLED"];
const expenseStatuses = ["DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED", "CANCELLED"];
const labelsFr: Record<string, string> = { DRAFT: "Brouillon", PENDING_APPROVAL: "En validation", ACTIVE: "Actif", APPROVED: "Approuvée", REJECTED: "Rejeté", CLOSED: "Clôturé", CANCELLED: "Annulé", UNBUDGETED: "Non budgétée", BUDGETED: "Budgétée" };
const labelsEn: Record<string, string> = { DRAFT: "Draft", PENDING_APPROVAL: "Pending approval", ACTIVE: "Active", APPROVED: "Approved", REJECTED: "Rejected", CLOSED: "Closed", CANCELLED: "Cancelled", UNBUDGETED: "Unbudgeted", BUDGETED: "Budgeted" };
function label(en: boolean, value: string) { return (en ? labelsEn : labelsFr)[value] || value.replaceAll("_", " "); }
function tone(status: string) { return status === "ACTIVE" || status === "APPROVED" ? "success" : status === "PENDING_APPROVAL" ? "warning" : status === "REJECTED" || status === "CANCELLED" ? "danger" : "neutral"; }
function amount(value: string | number, currency: string, en: boolean) { const n = Number(value || 0); try { return new Intl.NumberFormat(en ? "en-US" : "fr-FR", { style: "currency", currency }).format(n); } catch { return `${n.toFixed(2)} ${currency}`; } }

export function EnterpriseFinanceWorkspace({ organizationId, members, departments, canCreate, canManage, locale, legacyRecords = [] }: { organizationId: string; members: EnterpriseChoice[]; departments: EnterpriseChoice[]; canCreate: boolean; canManage: boolean; locale?: string | null; legacyRecords?: LegacyRecord[] }) {
  void canManage;
  const en = locale === "en"; const [pageBudget, setPageBudget] = useState(1); const [pageExpense, setPageExpense] = useState(1); const [budgetSearch, setBudgetSearch] = useState(""); const [expenseSearch, setExpenseSearch] = useState(""); const [budgetStatus, setBudgetStatus] = useState(""); const [expenseStatus, setExpenseStatus] = useState(""); const [refreshKey, setRefreshKey] = useState(0); const [summary, setSummary] = useState<SummaryBucket[]>([]); const [createBudgetOpen, setCreateBudgetOpen] = useState(false); const [createExpenseOpen, setCreateExpenseOpen] = useState(false); const [budgetDetail, setBudgetDetail] = useState<BudgetDetail | null>(null); const [expenseDetail, setExpenseDetail] = useState<ExpenseDetail | null>(null); const [approvalBudget, setApprovalBudget] = useState<BudgetItem | null>(null); const [approvalExpense, setApprovalExpense] = useState<ExpenseItem | null>(null); const [lines, setLines] = useState<BudgetLineDraft[]>([{ name: "", code: "", category: "", plannedAmount: "0", departmentId: "" }]); const [budgetLines, setBudgetLines] = useState<EnterpriseChoice[]>([]); const [suppliers, setSuppliers] = useState<EnterpriseChoice[]>([]); const [purchases, setPurchases] = useState<EnterpriseChoice[]>([]); const [documents, setDocuments] = useState<EnterpriseChoice[]>([]); const [message, setMessage] = useState(""); useToastMessage(message);
  const budgetParams = useMemo(() => { const p = new URLSearchParams({ page: String(pageBudget), pageSize: "20" }); if (budgetSearch.trim()) p.set("search", budgetSearch.trim()); if (budgetStatus) p.set("status", budgetStatus); return p; }, [pageBudget, budgetSearch, budgetStatus]);
  const expenseParams = useMemo(() => { const p = new URLSearchParams({ page: String(pageExpense), pageSize: "20" }); if (expenseSearch.trim()) p.set("search", expenseSearch.trim()); if (expenseStatus) p.set("status", expenseStatus); return p; }, [pageExpense, expenseSearch, expenseStatus]);
  const budgets = useEnterpriseV2Collection<BudgetItem>({ endpoint: `/api/enterprise/${organizationId}/budgets`, params: budgetParams, refreshKey }); const expenses = useEnterpriseV2Collection<ExpenseItem>({ endpoint: `/api/enterprise/${organizationId}/expenses`, params: expenseParams, refreshKey });
  useEffect(() => { void Promise.all([fetch(`/api/enterprise/${organizationId}/finance-summary`, { cache: "no-store" }).then((r) => r.ok ? r.json() : Promise.reject()), fetch(`/api/enterprise/${organizationId}/budget-lines?page=1&pageSize=100&status=ACTIVE`, { cache: "no-store" }).then((r) => r.ok ? r.json() : ({ items: [] })), fetch(`/api/enterprise/${organizationId}/suppliers?page=1&pageSize=100&status=ACTIVE`, { cache: "no-store" }).then((r) => r.ok ? r.json() : ({ items: [] })), fetch(`/api/enterprise/${organizationId}/purchases?page=1&pageSize=100`, { cache: "no-store" }).then((r) => r.ok ? r.json() : ({ items: [] })), fetch(`/api/enterprise/${organizationId}/documents?page=1&pageSize=100&status=ACTIVE`, { cache: "no-store" }).then((r) => r.ok ? r.json() : ({ items: [] }))]).then(([summaryBody, lineBody, supplierBody, purchaseBody, documentBody]) => { setSummary((summaryBody as { currencies?: SummaryBucket[] }).currencies || []); setBudgetLines(((lineBody as { items?: Array<{ id: string; name: string; budget: { reference: string; currency: string } }> }).items || []).map((item) => ({ id: item.id, label: `${item.budget.reference} · ${item.name} · ${item.budget.currency}` }))); setSuppliers(((supplierBody as { items?: Array<{ id: string; legalName: string; displayName: string | null }> }).items || []).map((item) => ({ id: item.id, label: item.displayName || item.legalName }))); setPurchases(((purchaseBody as { items?: Array<{ id: string; reference: string; title: string; status: string }> }).items || []).filter((item) => !["REJECTED", "CANCELLED"].includes(item.status)).map((item) => ({ id: item.id, label: `${item.reference} · ${item.title}` }))); setDocuments(((documentBody as { items?: Array<{ id: string; title: string }> }).items || []).map((item) => ({ id: item.id, label: item.title }))); }).catch(() => setSummary([])); }, [organizationId, refreshKey]);
  async function createBudget(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/budgets`, "POST", { ...form, lines: lines.map((line) => ({ ...line, plannedAmount: Number(line.plannedAmount) })) }); setCreateBudgetOpen(false); setLines([{ name: "", code: "", category: "", plannedAmount: "0", departmentId: "" }]); setRefreshKey((v) => v + 1); setMessage(en ? "Budget draft created." : "Brouillon budgétaire créé."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  async function createExpense(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); const amountValue = String(form.amount || "").trim(); const currencyValue = String(form.currency || "").trim(); const documentId = String(form.documentId || "").trim(); const payload = { ...form, amount: amountValue ? Number(amountValue) : undefined, currency: currencyValue || undefined, documentIds: documentId ? [documentId] : [] }; delete (payload as Record<string, unknown>).documentId; try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/expenses`, "POST", payload); setCreateExpenseOpen(false); setRefreshKey((v) => v + 1); setMessage(en ? "Expense draft created." : "Brouillon de dépense créé."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  async function action(kind: "budgets" | "expenses", item: BudgetItem | ExpenseItem, actionName: string, approverUserId?: string) { try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/${kind}/${item.id}/actions`, "POST", { action: actionName, revision: item.revision, approverUserId: approverUserId || "" }); setApprovalBudget(null); setApprovalExpense(null); setBudgetDetail(null); setExpenseDetail(null); setRefreshKey((v) => v + 1); setMessage(en ? "Workflow updated." : "Workflow mis à jour."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  async function openBudget(item: BudgetItem) { const response = await fetch(`/api/enterprise/${organizationId}/budgets/${item.id}`, { cache: "no-store" }); const body = await response.json() as BudgetDetail & { message?: string }; if (!response.ok) return setMessage(body.message || "LOAD_FAILED"); setBudgetDetail(body); }
  async function openExpense(item: ExpenseItem) { const response = await fetch(`/api/enterprise/${organizationId}/expenses/${item.id}`, { cache: "no-store" }); const body = await response.json() as ExpenseDetail & { message?: string }; if (!response.ok) return setMessage(body.message || "LOAD_FAILED"); setExpenseDetail(body); }
  const budgetActions = (item: BudgetItem): BusinessContextAction[] => [{ id: "open", label: en ? "Open" : "Ouvrir", icon: Eye, onSelect: () => void openBudget(item) }, ...(item.status === "DRAFT" ? [{ id: "submit", label: en ? "Submit" : "Soumettre", icon: Send, onSelect: () => setApprovalBudget(item) }, { id: "cancel", label: en ? "Cancel" : "Annuler", icon: XCircle, destructive: true, onSelect: () => void action("budgets", item, "CANCEL") }] : []), ...(item.status === "REJECTED" ? [{ id: "reopen", label: en ? "Reopen" : "Rouvrir", icon: RotateCcw, onSelect: () => void action("budgets", item, "REOPEN") }] : []), ...(item.status === "ACTIVE" ? [{ id: "close", label: en ? "Close" : "Clôturer", icon: CheckCircle2, onSelect: () => void action("budgets", item, "CLOSE") }] : [])];
  const expenseActions = (item: ExpenseItem): BusinessContextAction[] => [{ id: "open", label: en ? "Open" : "Ouvrir", icon: Eye, onSelect: () => void openExpense(item) }, ...(item.status === "DRAFT" ? [{ id: "submit", label: en ? "Submit" : "Soumettre", icon: Send, onSelect: () => setApprovalExpense(item) }, { id: "cancel", label: en ? "Cancel" : "Annuler", icon: XCircle, destructive: true, onSelect: () => void action("expenses", item, "CANCEL") }] : []), ...(item.status === "REJECTED" ? [{ id: "reopen", label: en ? "Reopen" : "Rouvrir", icon: RotateCcw, onSelect: () => void action("expenses", item, "REOPEN") }] : [])];
  return <div className="grid min-w-0 gap-8">
    {summary.map((item) => <ModuleMetrics key={item.currency} label={`${en ? "Finance indicators" : "Indicateurs financiers"} · ${item.currency}`}><ModuleMetric label={en ? "Active budgets" : "Budgets actifs"} value={item.activeBudgets} /><ModuleMetric label={en ? "Planned" : "Planifié"} value={amount(item.plannedAmount, item.currency, en)} /><ModuleMetric label={en ? "Committed" : "Engagé"} value={amount(item.committedAmount, item.currency, en)} /><ModuleMetric label={en ? "Actual" : "Réalisé"} value={amount(item.actualAmount, item.currency, en)} /><ModuleMetric label={en ? "Available" : "Disponible"} value={amount(item.availableAmount, item.currency, en)} /><ModuleMetric label={en ? "Unbudgeted expenses" : "Dépenses non budgétées"} value={amount(item.unbudgetedExpenseAmount, item.currency, en)} hint={`${item.unbudgetedExpenseCount}`} /></ModuleMetrics>)}
    <ModuleSection title={en ? "Budgets" : "Budgets"} description={en ? "Financial plans, commitments and actual consumption." : "Plans financiers, engagements et consommation réelle."} count={`${budgets.pagination.total}`} action={canCreate ? <Button onClick={() => setCreateBudgetOpen(true)}><Plus className="h-4 w-4" />{en ? "New budget" : "Nouveau budget"}</Button> : undefined}><div className="grid gap-2 border-y border-dtsc-border py-3 md:grid-cols-2"><Input value={budgetSearch} onChange={(e) => { setBudgetSearch(e.target.value); setPageBudget(1); }} placeholder={en ? "Search budgets…" : "Rechercher un budget…"} /><NativeSelect value={budgetStatus} onChange={setBudgetStatus} items={budgetStatuses.map((id) => ({ id, label: label(en, id) }))} /></div>{budgets.loading ? <p className="py-8 text-center text-sm text-dtsc-muted">{en ? "Loading…" : "Chargement…"}</p> : budgets.items.length ? <BusinessList ariaLabel="budgets">{budgets.items.map((item) => <BusinessListItem key={item.id} title={`${item.reference} · ${item.title}`} status={<StatusBadge tone={tone(item.status)}>{label(en, item.status)}</StatusBadge>} meta={`${item.currency} · ${en ? "Planned" : "Planifié"} ${amount(item.plannedAmount, item.currency, en)} · ${en ? "Available" : "Disponible"} ${amount(item.availableAmount, item.currency, en)}`} description={`${formatEnterpriseDate(item.periodStart, locale)} → ${formatEnterpriseDate(item.periodEnd, locale)} · ${item.lineCount} ${en ? "lines" : "lignes"}`} onOpen={() => void openBudget(item)} actions={<ContextActions label={en ? "Budget actions" : "Actions budget"} actions={budgetActions(item)} />} />)}</BusinessList> : <EmptyState compact title={en ? "No budgets" : "Aucun budget"} description={budgets.error || (en ? "No budget matches the filters." : "Aucun budget ne correspond aux filtres.")} />}<Pager page={pageBudget} pageCount={budgets.pagination.pageCount} setPage={setPageBudget} en={en} /></ModuleSection>
    <ModuleSection title={en ? "Expenses" : "Dépenses"} description={en ? "ERP expenses are budget consumption, not bank payments." : "Les dépenses ERP représentent une consommation budgétaire, pas un paiement bancaire."} count={`${expenses.pagination.total}`} action={canCreate ? <Button onClick={() => setCreateExpenseOpen(true)}><FilePlus2 className="h-4 w-4" />{en ? "New expense" : "Nouvelle dépense"}</Button> : undefined}><div className="grid gap-2 border-y border-dtsc-border py-3 md:grid-cols-2"><Input value={expenseSearch} onChange={(e) => { setExpenseSearch(e.target.value); setPageExpense(1); }} placeholder={en ? "Search expenses…" : "Rechercher une dépense…"} /><NativeSelect value={expenseStatus} onChange={setExpenseStatus} items={expenseStatuses.map((id) => ({ id, label: label(en, id) }))} /></div>{expenses.loading ? <p className="py-8 text-center text-sm text-dtsc-muted">{en ? "Loading…" : "Chargement…"}</p> : expenses.items.length ? <BusinessList ariaLabel="expenses">{expenses.items.map((item) => <BusinessListItem key={item.id} title={`${item.reference} · ${item.title}`} status={<StatusBadge tone={tone(item.status)}>{label(en, item.status)}</StatusBadge>} meta={`${amount(item.amount, item.currency, en)} · ${label(en, item.budgetStatus)}`} description={`${formatEnterpriseDate(item.expenseDate, locale)} · ${item.supplier?.displayName || item.supplier?.legalName || (en ? "No supplier" : "Sans fournisseur")}${item.purchase ? ` · ${item.purchase.reference}` : ""}`} onOpen={() => void openExpense(item)} actions={<ContextActions label={en ? "Expense actions" : "Actions dépense"} actions={expenseActions(item)} />} />)}</BusinessList> : <EmptyState compact title={en ? "No expenses" : "Aucune dépense"} description={expenses.error || (en ? "No expense matches the filters." : "Aucune dépense ne correspond aux filtres.")} />}<Pager page={pageExpense} pageCount={expenses.pagination.pageCount} setPage={setPageExpense} en={en} /></ModuleSection>
    {legacyRecords.length ? <ModuleSection title={en ? "Historical finance records" : "Historique financier"} description={en ? "Legacy BUDGET/EXPENSE records are read-only." : "Les anciens BUDGET/EXPENSE restent en lecture seule."}><BusinessList ariaLabel="legacy finance">{legacyRecords.map((item) => <BusinessListItem key={item.id} title={item.title} status={<StatusBadge>{en ? "History" : "Historique"}</StatusBadge>} description={item.description || label(en, item.status)} />)}</BusinessList></ModuleSection> : null}
    <Dialog open={createBudgetOpen} onClose={() => setCreateBudgetOpen(false)} title={en ? "New budget" : "Nouveau budget"} className="h-[96dvh] max-w-5xl"><form onSubmit={createBudget} className="grid gap-4"><Field label={en ? "Title" : "Intitulé"}><Input name="title" required /></Field><div className="grid gap-3 md:grid-cols-2"><Field label={en ? "Start" : "Début"}><Input name="periodStart" type="date" required /></Field><Field label={en ? "End" : "Fin"}><Input name="periodEnd" type="date" required /></Field><Field label={en ? "Currency" : "Devise"}><Input name="currency" defaultValue="USD" maxLength={3} required /></Field><Field label={en ? "Department" : "Département"}><NativeSelect name="departmentId" items={departments} /></Field></div><Field label="Description"><textarea name="description" className="min-h-20 rounded-xl border border-dtsc-border bg-dtsc-surface p-3 text-sm" /></Field><div className="grid gap-3 border-y border-dtsc-border py-3"><div className="flex items-center justify-between"><strong>{en ? "Budget lines" : "Lignes budgétaires"}</strong><Button type="button" variant="outline" onClick={() => setLines((items) => [...items, { name: "", code: "", category: "", plannedAmount: "0", departmentId: "" }])}><Plus className="h-4 w-4" />{en ? "Add line" : "Ajouter"}</Button></div>{lines.map((line, index) => <div key={index} className="grid gap-2 border-b border-dtsc-border pb-3 md:grid-cols-5"><Input value={line.name} onChange={(e) => setLines((items) => items.map((item, i) => i === index ? { ...item, name: e.target.value } : item))} placeholder={en ? "Line name" : "Nom de ligne"} required /><Input value={line.code} onChange={(e) => setLines((items) => items.map((item, i) => i === index ? { ...item, code: e.target.value } : item))} placeholder="Code" /><Input value={line.category} onChange={(e) => setLines((items) => items.map((item, i) => i === index ? { ...item, category: e.target.value } : item))} placeholder={en ? "Category" : "Catégorie"} /><Input value={line.plannedAmount} onChange={(e) => setLines((items) => items.map((item, i) => i === index ? { ...item, plannedAmount: e.target.value } : item))} type="number" min="0" step="0.01" required /><NativeSelect value={line.departmentId} onChange={(value) => setLines((items) => items.map((item, i) => i === index ? { ...item, departmentId: value } : item))} items={departments} /></div>)}</div><Button type="submit">{en ? "Create draft" : "Créer le brouillon"}</Button></form></Dialog>
    <Dialog open={createExpenseOpen} onClose={() => setCreateExpenseOpen(false)} title={en ? "New expense" : "Nouvelle dépense"} className="h-[96dvh] max-w-4xl"><form onSubmit={createExpense} className="grid gap-4"><Field label={en ? "Title" : "Dépense"}><Input name="title" required /></Field><div className="grid gap-3 md:grid-cols-2"><Field label={en ? "Expense date" : "Date"}><Input name="expenseDate" type="date" required /></Field><Field label={en ? "Category" : "Catégorie"}><Input name="category" /></Field><Field label={en ? "Purchase source" : "Achat source"}><NativeSelect name="purchaseId" items={purchases} /></Field><Field label={en ? "Supplier" : "Fournisseur"}><NativeSelect name="supplierId" items={suppliers} /></Field><Field label={en ? "Budget line" : "Ligne budgétaire"}><NativeSelect name="budgetLineId" items={budgetLines} /></Field><Field label={en ? "Supporting document" : "Justificatif"}><NativeSelect name="documentId" items={documents} /></Field><Field label={en ? "Amount" : "Montant"}><Input name="amount" type="number" min="0" step="0.01" placeholder={en ? "Defaults to purchase total" : "Par défaut : total achat"} /></Field><Field label={en ? "Currency" : "Devise"}><Input name="currency" maxLength={3} placeholder={en ? "Defaults from purchase/budget" : "Reprise achat/budget"} /></Field><Field label={en ? "Department" : "Département"}><NativeSelect name="departmentId" items={departments} /></Field><Field label={en ? "Variance reason" : "Motif d’écart"}><Input name="amountVarianceReason" /></Field></div><Field label="Description"><textarea name="description" className="min-h-20 rounded-xl border border-dtsc-border bg-dtsc-surface p-3 text-sm" /></Field><Button type="submit">{en ? "Create draft" : "Créer le brouillon"}</Button></form></Dialog>
    <ApprovalDialog open={Boolean(approvalBudget)} onClose={() => setApprovalBudget(null)} title={en ? "Submit budget" : "Soumettre le budget"} members={members} en={en} onSubmit={(approver) => approvalBudget ? void action("budgets", approvalBudget, "SUBMIT", approver) : undefined} />
    <ApprovalDialog open={Boolean(approvalExpense)} onClose={() => setApprovalExpense(null)} title={en ? "Submit expense" : "Soumettre la dépense"} members={members} en={en} onSubmit={(approver) => approvalExpense ? void action("expenses", approvalExpense, "SUBMIT", approver) : undefined} />
    <Dialog open={Boolean(budgetDetail)} onClose={() => setBudgetDetail(null)} title={budgetDetail ? `${budgetDetail.budget.reference} · ${budgetDetail.budget.title}` : ""} className="h-[96dvh] max-w-5xl">{budgetDetail ? <div className="grid gap-5"><ModuleMetrics label={en ? "Budget position" : "Position budgétaire"}><ModuleMetric label={en ? "Planned" : "Planifié"} value={amount(budgetDetail.totals.plannedAmount, budgetDetail.budget.currency, en)} /><ModuleMetric label={en ? "Committed" : "Engagé"} value={amount(budgetDetail.totals.committedAmount, budgetDetail.budget.currency, en)} /><ModuleMetric label={en ? "Actual" : "Réalisé"} value={amount(budgetDetail.totals.actualAmount, budgetDetail.budget.currency, en)} /><ModuleMetric label={en ? "Available" : "Disponible"} value={amount(budgetDetail.totals.availableAmount, budgetDetail.budget.currency, en)} /></ModuleMetrics><BusinessList ariaLabel="budget lines">{budgetDetail.lines.map((line) => <BusinessListItem key={line.id} title={`${line.code || "—"} · ${line.name}`} meta={`${en ? "Planned" : "Planifié"} ${amount(line.plannedAmount, budgetDetail.budget.currency, en)} · ${en ? "Available" : "Disponible"} ${amount(line.availableAmount, budgetDetail.budget.currency, en)}`} description={`${en ? "Committed" : "Engagé"} ${amount(line.committedAmount, budgetDetail.budget.currency, en)} · ${en ? "Actual" : "Réalisé"} ${amount(line.actualAmount, budgetDetail.budget.currency, en)}`} />)}</BusinessList>{budgetDetail.events.length ? <div className="border-y border-dtsc-border py-3 text-sm text-dtsc-muted">{budgetDetail.events.slice(0, 10).map((event) => <p key={event.id}>{formatEnterpriseDate(event.createdAt, locale)} · {event.summary}</p>)}</div> : null}</div> : null}</Dialog>
    <Dialog open={Boolean(expenseDetail)} onClose={() => setExpenseDetail(null)} title={expenseDetail ? `${expenseDetail.expense.reference} · ${expenseDetail.expense.title}` : ""} className="h-[96dvh] max-w-4xl">{expenseDetail ? <div className="grid gap-4 text-sm"><div className="grid gap-2 border-y border-dtsc-border py-3 md:grid-cols-2"><p><strong>{en ? "Amount" : "Montant"}</strong><br />{amount(expenseDetail.expense.amount, expenseDetail.expense.currency, en)}</p><p><strong>{en ? "Budget" : "Budget"}</strong><br />{expenseDetail.expense.budgetLine ? `${expenseDetail.expense.budgetLine.budget.reference} · ${expenseDetail.expense.budgetLine.name}` : label(en, "UNBUDGETED")}</p><p><strong>{en ? "Purchase" : "Achat"}</strong><br />{expenseDetail.expense.purchase?.reference || "—"}</p><p><strong>{en ? "Supplier" : "Fournisseur"}</strong><br />{expenseDetail.expense.supplier?.displayName || expenseDetail.expense.supplier?.legalName || "—"}</p></div>{expenseDetail.expense.amountVarianceReason ? <p><strong>{en ? "Amount variance" : "Écart de montant"}</strong><br />{expenseDetail.expense.amountVarianceReason}</p> : null}{expenseDetail.documents.length ? <BusinessList ariaLabel="expense documents">{expenseDetail.documents.map((doc) => <BusinessListItem key={doc.id} title={doc.title} meta={doc.documentType} />)}</BusinessList> : null}</div> : null}</Dialog>
  </div>;
}

function Pager({ page, pageCount, setPage, en }: { page: number; pageCount: number; setPage: (value: number | ((value: number) => number)) => void; en: boolean }) { return <div className="mt-3 flex justify-between border-t border-dtsc-border pt-3 text-sm text-dtsc-muted"><span>Page {page}/{pageCount}</span><div className="flex gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>{en ? "Previous" : "Précédent"}</Button><Button variant="outline" disabled={page >= pageCount} onClick={() => setPage((value) => value + 1)}>{en ? "Next" : "Suivant"}</Button></div></div>; }
function ApprovalDialog({ open, onClose, title, members, en, onSubmit }: { open: boolean; onClose: () => void; title: string; members: EnterpriseChoice[]; en: boolean; onSubmit: (approver: string) => void }) { const [approver, setApprover] = useState(""); useEffect(() => { if (!open) setApprover(""); }, [open]); return <Dialog open={open} onClose={onClose} title={title}><div className="grid gap-4"><Field label={en ? "Approver" : "Approbateur"}><NativeSelect value={approver} onChange={setApprover} items={members} required /></Field><Button disabled={!approver} onClick={() => onSubmit(approver)}><Send className="h-4 w-4" />{en ? "Submit" : "Soumettre"}</Button></div></Dialog>; }
