"use client";

import { Archive, Download, Eye, FileBarChart2, Plus, Send } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { BusinessList, BusinessListItem } from "@/components/workspace/business-list";
import { ContextActions, type BusinessContextAction } from "@/components/workspace/context-actions";
import { EmptyState } from "@/components/workspace/empty-state";
import { ModuleMetric, ModuleMetrics } from "@/components/workspace/module-metrics";
import { ModuleSection } from "@/components/workspace/module-workspace";
import { StatusBadge } from "@/components/workspace/status-badge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useToastMessage } from "@/components/ui/use-toast-message";
import { Field, NativeSelect, formatEnterpriseDate } from "@/components/enterprise/core-v2/erp-v2-ui";
import { enterpriseV2Mutation, useEnterpriseV2Collection } from "@/components/enterprise/core-v2/use-enterprise-v2-collection";

type LegacyRecord = { id: string; title: string; description: string | null; status: string; updatedAt: string };
type ReportItem = { id: string; reference: string; title: string; description: string | null; reportType: string; status: string; periodStart: string | null; periodEnd: string | null; currency: string | null; generatedByUserId: string; generatedAt: string; schemaVersion: number; revision: number };
type ReportDetail = { report: ReportItem & { filtersJson: unknown; snapshotJson: unknown; sourceModule?: string | null; sourceEntityType?: string | null; sourceEntityId?: string | null }; links: Array<{ id: string; sourceEntityType: string; sourceEntityId: string; targetEntityType: string; targetEntityId: string }>; events: Array<{ id: string; summary: string; createdAt: string }> };
const reportTypes = ["BUDGET_VS_ACTUAL", "EXPENSE_SUMMARY", "PROCUREMENT_SUMMARY", "FINANCE_OVERVIEW"];
const statuses = ["GENERATED", "PUBLISHED", "ARCHIVED"];
const fr: Record<string, string> = { BUDGET_VS_ACTUAL: "Budget vs réalisé", EXPENSE_SUMMARY: "Synthèse des dépenses", PROCUREMENT_SUMMARY: "Synthèse des achats", FINANCE_OVERVIEW: "Vue financière", GENERATED: "Généré", PUBLISHED: "Publié", ARCHIVED: "Archivé" };
const enLabels: Record<string, string> = { BUDGET_VS_ACTUAL: "Budget vs actual", EXPENSE_SUMMARY: "Expense summary", PROCUREMENT_SUMMARY: "Procurement summary", FINANCE_OVERVIEW: "Finance overview", GENERATED: "Generated", PUBLISHED: "Published", ARCHIVED: "Archived" };
function label(en: boolean, value: string) { return (en ? enLabels : fr)[value] || value.replaceAll("_", " "); }
function tone(status: string) { return status === "PUBLISHED" ? "success" : status === "GENERATED" ? "info" : "neutral"; }

export function EnterpriseReportsWorkspace({ organizationId, canCreate, canManage, locale, legacyRecords = [] }: { organizationId: string; canCreate: boolean; canManage: boolean; locale?: string | null; legacyRecords?: LegacyRecord[] }) {
  const en = locale === "en"; const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [refreshKey, setRefreshKey] = useState(0); const [createOpen, setCreateOpen] = useState(false); const [detail, setDetail] = useState<ReportDetail | null>(null); const [message, setMessage] = useState(""); useToastMessage(message);
  const params = useMemo(() => { const p = new URLSearchParams({ page: String(page), pageSize: "20" }); if (search.trim()) p.set("search", search.trim()); if (type) p.set("type", type); if (status) p.set("status", status); return p; }, [page, search, type, status]); const reports = useEnterpriseV2Collection<ReportItem>({ endpoint: `/api/enterprise/${organizationId}/reports`, params, refreshKey });
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/reports/generate`, "POST", form); setCreateOpen(false); setRefreshKey((v) => v + 1); setMessage(en ? "Report generated from current ERP data." : "Rapport généré à partir des données ERP actuelles."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  async function runAction(item: ReportItem, action: "PUBLISH" | "ARCHIVE") { try { await enterpriseV2Mutation(`/api/enterprise/${organizationId}/reports/${item.id}/actions`, "POST", { action, revision: item.revision }); setDetail(null); setRefreshKey((v) => v + 1); setMessage(en ? "Report updated." : "Rapport mis à jour."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACTION_FAILED"); } }
  async function open(item: ReportItem) { const response = await fetch(`/api/enterprise/${organizationId}/reports/${item.id}`, { cache: "no-store" }); const body = await response.json() as ReportDetail & { message?: string }; if (!response.ok) return setMessage(body.message || "LOAD_FAILED"); setDetail(body); }
  const actions = (item: ReportItem): BusinessContextAction[] => [{ id: "open", label: en ? "Open" : "Ouvrir", icon: Eye, onSelect: () => void open(item) }, { id: "export", label: en ? "Export CSV" : "Exporter CSV", icon: Download, onSelect: () => { window.location.href = `/api/enterprise/${organizationId}/reports/${item.id}/export`; } }, ...(canManage && item.status === "GENERATED" ? [{ id: "publish", label: en ? "Publish" : "Publier", icon: Send, onSelect: () => void runAction(item, "PUBLISH") }] : []), ...(canManage && item.status !== "ARCHIVED" ? [{ id: "archive", label: en ? "Archive" : "Archiver", icon: Archive, destructive: true, separatorBefore: true, onSelect: () => void runAction(item, "ARCHIVE") }] : [])];
  return <div className="grid min-w-0 gap-6">
    <ModuleMetrics label={en ? "Reporting indicators" : "Indicateurs reporting"}><ModuleMetric label={en ? "Reports" : "Rapports"} value={reports.pagination.total} /><ModuleMetric label={en ? "Published on page" : "Publiés sur la page"} value={reports.items.filter((item) => item.status === "PUBLISHED").length} /><ModuleMetric label={en ? "Latest generation" : "Dernière génération"} value={reports.items[0] ? formatEnterpriseDate(reports.items[0].generatedAt, locale) : "—"} /></ModuleMetrics>
    <ModuleSection title={en ? "Reports" : "Rapports"} description={en ? "Immutable snapshots generated from real ERP aggregates. Currencies remain separated without FX." : "Snapshots immuables générés depuis les vrais agrégats ERP. Les devises restent séparées sans FX."} count={`${reports.pagination.total}`} action={canCreate ? <Button onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4" />{en ? "Generate report" : "Générer un rapport"}</Button> : undefined}><div className="grid gap-2 border-y border-dtsc-border py-3 md:grid-cols-3"><Input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder={en ? "Search reports…" : "Rechercher un rapport…"} /><NativeSelect value={type} onChange={setType} items={reportTypes.map((id) => ({ id, label: label(en, id) }))} /><NativeSelect value={status} onChange={setStatus} items={statuses.map((id) => ({ id, label: label(en, id) }))} /></div>{reports.loading ? <p className="py-8 text-center text-sm text-dtsc-muted">{en ? "Loading…" : "Chargement…"}</p> : reports.items.length ? <BusinessList ariaLabel="reports">{reports.items.map((item) => <BusinessListItem key={item.id} title={`${item.reference} · ${item.title}`} status={<StatusBadge tone={tone(item.status)}>{label(en, item.status)}</StatusBadge>} meta={`${label(en, item.reportType)}${item.currency ? ` · ${item.currency}` : ""}`} description={`${formatEnterpriseDate(item.generatedAt, locale)}${item.periodStart ? ` · ${formatEnterpriseDate(item.periodStart, locale)} → ${formatEnterpriseDate(item.periodEnd, locale)}` : ""}`} onOpen={() => void open(item)} actions={<ContextActions label={en ? "Report actions" : "Actions rapport"} actions={actions(item)} />} />)}</BusinessList> : <EmptyState compact title={en ? "No reports" : "Aucun rapport"} description={reports.error || (en ? "Generate the first report from ERP data." : "Générez le premier rapport à partir des données ERP.")} />}<div className="mt-3 flex justify-between border-t border-dtsc-border pt-3 text-sm text-dtsc-muted"><span>Page {reports.pagination.page}/{reports.pagination.pageCount}</span><div className="flex gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => setPage((v) => Math.max(1, v - 1))}>{en ? "Previous" : "Précédent"}</Button><Button variant="outline" disabled={page >= reports.pagination.pageCount} onClick={() => setPage((v) => v + 1)}>{en ? "Next" : "Suivant"}</Button></div></div></ModuleSection>
    {legacyRecords.length ? <ModuleSection title={en ? "Historical reports" : "Rapports historiques"} description={en ? "Legacy REPORT records remain read-only." : "Les anciens REPORT restent en lecture seule."}><BusinessList ariaLabel="legacy reports">{legacyRecords.map((item) => <BusinessListItem key={item.id} title={item.title} status={<StatusBadge>{en ? "History" : "Historique"}</StatusBadge>} description={item.description || item.status} />)}</BusinessList></ModuleSection> : null}
    <Dialog open={createOpen} onClose={() => setCreateOpen(false)} title={en ? "Generate report" : "Générer un rapport"} className="h-[96dvh] max-w-3xl"><form onSubmit={generate} className="grid gap-4"><Field label={en ? "Title" : "Titre"}><Input name="title" required /></Field><Field label={en ? "Report type" : "Type de rapport"}><NativeSelect name="reportType" required defaultValue="BUDGET_VS_ACTUAL" items={reportTypes.map((id) => ({ id, label: label(en, id) }))} /></Field><div className="grid gap-3 md:grid-cols-2"><Field label={en ? "Period start" : "Début période"}><Input name="periodStart" type="date" /></Field><Field label={en ? "Period end" : "Fin période"}><Input name="periodEnd" type="date" /></Field><Field label={en ? "Currency filter" : "Filtre devise"}><Input name="currency" maxLength={3} placeholder={en ? "Optional; otherwise separated" : "Optionnel ; sinon séparées"} /></Field><Field label={en ? "Category" : "Catégorie"}><Input name="category" /></Field></div><Field label="Description"><textarea name="description" className="min-h-20 rounded-xl border border-dtsc-border bg-dtsc-surface p-3 text-sm" /></Field><Button type="submit"><FileBarChart2 className="h-4 w-4" />{en ? "Generate snapshot" : "Générer le snapshot"}</Button></form></Dialog>
    <Dialog open={Boolean(detail)} onClose={() => setDetail(null)} title={detail ? `${detail.report.reference} · ${detail.report.title}` : ""} className="h-[96dvh] max-w-5xl">{detail ? <div className="grid gap-5"><div className="grid gap-2 border-y border-dtsc-border py-3 text-sm md:grid-cols-3"><p><strong>{en ? "Type" : "Type"}</strong><br />{label(en, detail.report.reportType)}</p><p><strong>{en ? "Generated" : "Généré"}</strong><br />{formatEnterpriseDate(detail.report.generatedAt, locale)}</p><p><strong>{en ? "Status" : "Statut"}</strong><br />{label(en, detail.report.status)}</p></div><SnapshotView value={detail.report.snapshotJson} /><div className="border-y border-dtsc-border py-3 text-sm text-dtsc-muted"><strong>{en ? "Filters" : "Filtres"}</strong><pre className="mt-2 whitespace-pre-wrap break-words font-sans">{JSON.stringify(detail.report.filtersJson, null, 2)}</pre></div>{detail.events.length ? <div className="text-sm text-dtsc-muted">{detail.events.slice(0, 10).map((event) => <p key={event.id}>{formatEnterpriseDate(event.createdAt, locale)} · {event.summary}</p>)}</div> : null}</div> : null}</Dialog>
  </div>;
}

function SnapshotView({ value }: { value: unknown }) { const data = value as Record<string, unknown> | null; if (!data) return null; const currencies = Array.isArray(data.currencies) ? data.currencies as Array<Record<string, unknown>> : []; const lines = Array.isArray(data.lines) ? data.lines as Array<Record<string, unknown>> : []; return <div className="grid gap-4">{currencies.length ? <BusinessList ariaLabel="currency summaries">{currencies.map((item, index) => <BusinessListItem key={`${String(item.currency)}-${index}`} title={String(item.currency || "—")} meta={`Planned ${String(item.planned || "0")} · Committed ${String(item.committed || "0")} · Actual ${String(item.actual || "0")} · Available ${String(item.available || "0")}`} />)}</BusinessList> : null}{lines.length ? <BusinessList ariaLabel="report details">{lines.slice(0, 100).map((item, index) => <BusinessListItem key={`${String(item.budgetLineId || index)}`} title={String(item.name || item.budgetTitle || "Line")} meta={`${String(item.currency || "")} · Planned ${String(item.planned || "0")} · Actual ${String(item.actual || "0")}`} description={`Committed ${String(item.committed || "0")} · Available ${String(item.available || "0")}`} />)}</BusinessList> : <pre className="max-h-[55dvh] overflow-auto whitespace-pre-wrap break-words rounded-xl border border-dtsc-border p-3 text-xs">{JSON.stringify(value, null, 2)}</pre>}</div>; }
