import { NextResponse } from "next/server";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { authorizeFinanceRequest, financeErrorResponse, financeListParams } from "@/lib/enterprise/accounting/http";
import { createAccountTransfer } from "@/lib/enterprise/accounting/treasury-service";
import { accountTransferSchema } from "@/lib/enterprise/accounting/treasury-schemas";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ organizationId: string }> };
export async function GET(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_TREASURY", "view"); if (!auth.ok) return auth.response; const { page, pageSize, status } = financeListParams(req); const where = { organizationId, ...(status ? { status } : {}) }; const [items, total] = await Promise.all([prisma.enterpriseAccountTransfer.findMany({ where, orderBy: [{ transferDate: "desc" }, { createdAt: "desc" }], skip: (page - 1) * pageSize, take: pageSize, include: { sourceFinancialAccount: { select: { id: true, code: true, name: true, currencyCode: true } }, targetFinancialAccount: { select: { id: true, code: true, name: true, currencyCode: true } } } }), prisma.enterpriseAccountTransfer.count({ where })]); await writeApiLog({ request: req, statusCode: 200, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "account-transfers" } }); return NextResponse.json({ items, pagination: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) } }); }
export async function POST(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_TREASURY", "create", { mutation: true, limit: 60 }); if (!auth.ok) return auth.response; const parsed = accountTransferSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message }, { status: 400 }); try { const transfer = await createAccountTransfer(organizationId, auth.session.userId, parsed.data); await writeAuditLog({ userId: auth.session.userId, action: "ENTERPRISE_ACCOUNT_TRANSFER_CREATED", entity: "EnterpriseAccountTransfer", entityId: transfer.id, request: req, metadata: { organizationId, sourceFinancialAccountId: transfer.sourceFinancialAccountId, targetFinancialAccountId: transfer.targetFinancialAccountId, sourceAmount: transfer.sourceAmount.toFixed(), sourceCurrency: transfer.sourceCurrencyCode } }); await writeApiLog({ request: req, statusCode: 201, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "account-transfers" } }); return NextResponse.json({ ok: true, transfer }, { status: 201 }); } catch (error) { return financeErrorResponse(error, "ACCOUNT_TRANSFER_CREATE_FAILED"); } }
