import { NextResponse } from "next/server";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { authorizeFinanceRequest, financeErrorResponse, financeListParams } from "@/lib/enterprise/accounting/http";
import { importBankStatement } from "@/lib/enterprise/accounting/treasury-service";
import { bankStatementSchema } from "@/lib/enterprise/accounting/treasury-schemas";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ organizationId: string }> };
export async function GET(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_BANK", "view"); if (!auth.ok) return auth.response; const { page, pageSize, status } = financeListParams(req); const where = { organizationId, ...(status ? { status } : {}) }; const [items, total] = await Promise.all([prisma.enterpriseBankStatement.findMany({ where, orderBy: { statementDate: "desc" }, skip: (page - 1) * pageSize, take: pageSize, include: { financialAccount: { select: { id: true, code: true, name: true, currencyCode: true } }, _count: { select: { lines: true, reconciliationSessions: true } } } }), prisma.enterpriseBankStatement.count({ where })]); await writeApiLog({ request: req, statusCode: 200, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "bank-statements" } }); return NextResponse.json({ items, pagination: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) } }); }
export async function POST(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_BANK", "create", { mutation: true, limit: 20 }); if (!auth.ok) return auth.response; const parsed = bankStatementSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message }, { status: 400 }); try { const statement = await importBankStatement(organizationId, auth.session.userId, parsed.data); await writeAuditLog({ userId: auth.session.userId, action: "ENTERPRISE_BANK_STATEMENT_IMPORTED", entity: "EnterpriseBankStatement", entityId: statement.id, request: req, metadata: { organizationId, financialAccountId: statement.financialAccountId, reference: statement.reference, currency: statement.currencyCode, lineCount: statement.lines.length } }); await writeApiLog({ request: req, statusCode: 201, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "bank-statements" } }); return NextResponse.json({ ok: true, statement }, { status: 201 }); } catch (error) { return financeErrorResponse(error, "BANK_STATEMENT_IMPORT_FAILED"); } }
