ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "targetUrl" TEXT;

ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "announcementEditWindowMinutes" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "commentEditWindowMinutes" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "AppSetting" ADD COLUMN IF NOT EXISTS "notificationRetentionDays" INTEGER NOT NULL DEFAULT 60;
