import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeApiLog } from "@/lib/audit";
import { enterpriseReportVisibilityWhere, getEnterpriseFinanceAccess } from "@/lib/enterprise/finance/access";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ organizationId: string }> };

export async function GET(req: Request, { params }: Params) {
  const startedAt = Date.now(); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { organizationId } = await params; const access = await getEnterpriseFinanceAccess({ session, organizationId, moduleCode: "REPORTS", action: "read" }); if (!access) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const url = new URL(req.url); const page = Math.max(1, Number(url.searchParams.get("page") || 1) || 1); const pageSize = Math.min(50, Math.max(5, Number(url.searchParams.get("pageSize") || 20) || 20)); const reportType = url.searchParams.get("type")?.trim(); const status = url.searchParams.get("status")?.trim(); const creator = url.searchParams.get("creator")?.trim(); const search = url.searchParams.get("search")?.trim(); const from = url.searchParams.get("from"); const to = url.searchParams.get("to");
  const filters: Prisma.EnterpriseReportWhereInput[] = [enterpriseReportVisibilityWhere({ organizationId, userId: session.userId, canSeeAll: access.canSeeAll })]; if (reportType) filters.push({ reportType }); if (status) filters.push({ status }); if (creator) filters.push({ generatedByUserId: creator }); if (search) filters.push({ OR: [{ reference: { contains: search, mode: "insensitive" } }, { title: { contains: search, mode: "insensitive" } }, { description: { contains: search, mode: "insensitive" } }] }); if (from || to) filters.push({ generatedAt: { ...(from ? { gte: new Date(from) } : {}), ...(to ? { lte: new Date(to) } : {}) } });
  const where: Prisma.EnterpriseReportWhereInput = { AND: filters }; const [items, total, publishedCount, latest] = await Promise.all([prisma.enterpriseReport.findMany({ where, select: { id: true, reference: true, title: true, description: true, reportType: true, status: true, periodStart: true, periodEnd: true, currency: true, generatedByUserId: true, generatedAt: true, schemaVersion: true, revision: true }, orderBy: { generatedAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), prisma.enterpriseReport.count({ where }), prisma.enterpriseReport.count({ where: { ...enterpriseReportVisibilityWhere({ organizationId, userId: session.userId, canSeeAll: access.canSeeAll }), status: "PUBLISHED" } }), prisma.enterpriseReport.findFirst({ where: enterpriseReportVisibilityWhere({ organizationId, userId: session.userId, canSeeAll: access.canSeeAll }), orderBy: { generatedAt: "desc" }, select: { generatedAt: true } })]);
  await writeApiLog({ request: req, statusCode: 200, userId: session.userId, startedAt, metadata: { organizationId, domain: "reports", page, pageSize } }); return NextResponse.json({ items, metrics: { generated: total, published: publishedCount, latestGeneratedAt: latest?.generatedAt || null }, pagination: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) }, canManage: access.canManage, canCreate: access.canCreate });
}
