-- Additive schema parity corrections generated by Prisma migrate diff.
CREATE UNIQUE INDEX "EnterpriseSupplierCreditNoteItem_organizationId_supplierCreditNoteId_id_key"
ON "EnterpriseSupplierCreditNoteItem"("organizationId", "supplierCreditNoteId", "id");

ALTER TABLE "EnterpriseAccountMapping"
ADD CONSTRAINT "EnterpriseAccountMapping_organizationId_ledgerAccountId_fkey"
FOREIGN KEY ("organizationId", "ledgerAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseAccountGroup"
ADD CONSTRAINT "EnterpriseAccountGroup_organizationId_parentGroupId_fkey"
FOREIGN KEY ("organizationId", "parentGroupId")
REFERENCES "EnterpriseAccountGroup"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseJournalEntry"
ADD CONSTRAINT "EnterpriseJournalEntry_organizationId_reversalOfEntryId_fkey"
FOREIGN KEY ("organizationId", "reversalOfEntryId")
REFERENCES "EnterpriseJournalEntry"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseJournalReversal"
ADD CONSTRAINT "EnterpriseJournalReversal_organizationId_originalEntryId_fkey"
FOREIGN KEY ("organizationId", "originalEntryId")
REFERENCES "EnterpriseJournalEntry"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseJournalReversal"
ADD CONSTRAINT "EnterpriseJournalReversal_organizationId_reversalEntryId_fkey"
FOREIGN KEY ("organizationId", "reversalEntryId")
REFERENCES "EnterpriseJournalEntry"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseOpeningBalanceImport"
ADD CONSTRAINT "EnterpriseOpeningBalanceImport_organizationId_fiscalPeriodId_fkey"
FOREIGN KEY ("organizationId", "fiscalPeriodId")
REFERENCES "EnterpriseFiscalPeriod"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseOpeningBalanceLine"
ADD CONSTRAINT "EnterpriseOpeningBalanceLine_organizationId_ledgerAccountId_fkey"
FOREIGN KEY ("organizationId", "ledgerAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseSalesInvoiceItem"
ADD CONSTRAINT "EnterpriseSalesInvoiceItem_organizationId_salesInvoiceId_id_fkey"
FOREIGN KEY ("organizationId", "salesInvoiceId", "id")
REFERENCES "EnterpriseSalesInvoice"("organizationId", "id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "EnterpriseSupplierInvoiceItem"
ADD CONSTRAINT "EnterpriseSupplierInvoiceItem_organizationId_supplierInvoiceId_id_fkey"
FOREIGN KEY ("organizationId", "supplierInvoiceId", "id")
REFERENCES "EnterpriseSupplierInvoice"("organizationId", "id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "EnterpriseSupplierCreditNoteItem"
ADD CONSTRAINT "EnterpriseSupplierCreditNoteItem_organizationId_supplierCreditNoteId_id_fkey"
FOREIGN KEY ("organizationId", "supplierCreditNoteId", "id")
REFERENCES "EnterpriseSupplierCreditNote"("organizationId", "id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxCode"
ADD CONSTRAINT "EnterpriseTaxCode_organizationId_payableAccountId_fkey"
FOREIGN KEY ("organizationId", "payableAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxCode"
ADD CONSTRAINT "EnterpriseTaxCode_organizationId_recoverableAccountId_fkey"
FOREIGN KEY ("organizationId", "recoverableAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxLine"
ADD CONSTRAINT "EnterpriseTaxLine_organizationId_taxCodeId_fkey"
FOREIGN KEY ("organizationId", "taxCodeId")
REFERENCES "EnterpriseTaxCode"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxSummary"
ADD CONSTRAINT "EnterpriseTaxSummary_organizationId_taxPeriodId_fkey"
FOREIGN KEY ("organizationId", "taxPeriodId")
REFERENCES "EnterpriseTaxPeriod"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxSummary"
ADD CONSTRAINT "EnterpriseTaxSummary_organizationId_taxCodeId_fkey"
FOREIGN KEY ("organizationId", "taxCodeId")
REFERENCES "EnterpriseTaxCode"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
