-- Additive schema parity corrections generated by Prisma migrate diff.
-- The three invoice-item relations already exist in migration 09 with their
-- canonical tenant-aware (organizationId, documentId) foreign keys.

ALTER TABLE "EnterpriseAccountMapping"
ADD CONSTRAINT "EnterpriseAccountMapping_organizationId_ledgerAccountId_fkey"
FOREIGN KEY ("organizationId", "ledgerAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseAccountGroup"
ADD CONSTRAINT "EnterpriseAccountGroup_organizationId_parentGroupId_fkey"
FOREIGN KEY ("organizationId", "parentGroupId")
REFERENCES "EnterpriseAccountGroup"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseJournalEntry"
ADD CONSTRAINT "EnterpriseJournalEntry_organizationId_reversalOfEntryId_fkey"
FOREIGN KEY ("organizationId", "reversalOfEntryId")
REFERENCES "EnterpriseJournalEntry"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseJournalReversal"
ADD CONSTRAINT "EnterpriseJournalReversal_organizationId_originalEntryId_fkey"
FOREIGN KEY ("organizationId", "originalEntryId")
REFERENCES "EnterpriseJournalEntry"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseJournalReversal"
ADD CONSTRAINT "EnterpriseJournalReversal_organizationId_reversalEntryId_fkey"
FOREIGN KEY ("organizationId", "reversalEntryId")
REFERENCES "EnterpriseJournalEntry"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseOpeningBalanceImport"
ADD CONSTRAINT "EnterpriseOpeningBalanceImport_organizationId_fiscalPeriodId_fkey"
FOREIGN KEY ("organizationId", "fiscalPeriodId")
REFERENCES "EnterpriseFiscalPeriod"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseOpeningBalanceLine"
ADD CONSTRAINT "EnterpriseOpeningBalanceLine_organizationId_ledgerAccountId_fkey"
FOREIGN KEY ("organizationId", "ledgerAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxCode"
ADD CONSTRAINT "EnterpriseTaxCode_organizationId_payableAccountId_fkey"
FOREIGN KEY ("organizationId", "payableAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxCode"
ADD CONSTRAINT "EnterpriseTaxCode_organizationId_recoverableAccountId_fkey"
FOREIGN KEY ("organizationId", "recoverableAccountId")
REFERENCES "EnterpriseLedgerAccount"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxLine"
ADD CONSTRAINT "EnterpriseTaxLine_organizationId_taxCodeId_fkey"
FOREIGN KEY ("organizationId", "taxCodeId")
REFERENCES "EnterpriseTaxCode"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxSummary"
ADD CONSTRAINT "EnterpriseTaxSummary_organizationId_taxPeriodId_fkey"
FOREIGN KEY ("organizationId", "taxPeriodId")
REFERENCES "EnterpriseTaxPeriod"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EnterpriseTaxSummary"
ADD CONSTRAINT "EnterpriseTaxSummary_organizationId_taxCodeId_fkey"
FOREIGN KEY ("organizationId", "taxCodeId")
REFERENCES "EnterpriseTaxCode"("organizationId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
