import {
  Activity,
  Archive,
  BadgeCheck,
  BadgePercent,
  BarChart3,
  BellRing,
  BookOpen,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Bug,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Code2,
  ConciergeBell,
  Factory,
  FileBadge,
  FileCheck,
  FileHeart,
  FilePlus,
  FileSignature,
  FileText,
  FileWarning,
  Folder,
  FolderKanban,
  Fuel,
  GitBranch,
  GraduationCap,
  HandCoins,
  HandHeart,
  HardHat,
  Headphones,
  HeartPulse,
  History,
  Hourglass,
  Image,
  Inbox,
  Landmark,
  Layers3,
  LayoutDashboard,
  ListChecks,
  LockKeyhole,
  Mail,
  Map,
  MessageSquare,
  Microscope,
  Network,
  Package,
  PackageCheck,
  Paperclip,
  PartyPopper,
  Pill,
  Plug,
  Receipt,
  Repeat2,
  Rocket,
  RotateCcw,
  Route,
  Scale,
  ScanLine,
  School,
  SearchCheck,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sprout,
  Stethoscope,
  Ticket,
  TriangleAlert,
  Truck,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  Wallet,
  WalletCards,
  Wheat,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const enterpriseModuleIcons: Record<string, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  "badge-check": BadgeCheck,
  "badge-percent": BadgePercent,
  "bell-ring": BellRing,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  "briefcase-business": BriefcaseBusiness,
  bug: Bug,
  "building-2": Building2,
  calculator: Calculator,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock3,
  "code-2": Code2,
  "concierge-bell": ConciergeBell,
  factory: Factory,
  "file-badge": FileBadge,
  "file-bar-chart": BarChart3,
  "file-check": FileCheck,
  "file-heart": FileHeart,
  "file-plus": FilePlus,
  "file-signature": FileSignature,
  "file-text": FileText,
  "file-warning": FileWarning,
  folder: Folder,
  "folder-kanban": FolderKanban,
  fuel: Fuel,
  "git-branch": GitBranch,
  "graduation-cap": GraduationCap,
  "hand-coins": HandCoins,
  "hand-heart": HandHeart,
  "hard-hat": HardHat,
  headphones: Headphones,
  "heart-pulse": HeartPulse,
  history: History,
  hourglass: Hourglass,
  image: Image,
  inbox: Inbox,
  landmark: Landmark,
  layers: Layers3,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  "lock-keyhole": LockKeyhole,
  mail: Mail,
  map: Map,
  "message-square": MessageSquare,
  microscope: Microscope,
  network: Network,
  package: Package,
  "package-check": PackageCheck,
  paperclip: Paperclip,
  "party-popper": PartyPopper,
  pill: Pill,
  plug: Plug,
  receipt: Receipt,
  repeat: Repeat2,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  route: Route,
  scale: Scale,
  "scan-line": ScanLine,
  school: School,
  "search-check": SearchCheck,
  settings: Settings,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  sprout: Sprout,
  stethoscope: Stethoscope,
  ticket: Ticket,
  "triangle-alert": TriangleAlert,
  truck: Truck,
  "user-round": UserRound,
  users: Users,
  "users-round": UsersRound,
  utensils: Utensils,
  wallet: Wallet,
  "wallet-cards": WalletCards,
  wheat: Wheat,
  workflow: Workflow,
  wrench: Wrench,
};

const iconByModuleCode: Record<string, LucideIcon> = {
  ADMIN_DASHBOARD: LayoutDashboard,
  COLLABORATORS_POSITIONS: UsersRound,
  DEPARTMENTS: Building2,
  PERMISSIONS: ShieldCheck,
  TASKS_OPERATIONS: ListChecks,
  MEETINGS: CalendarDays,
  INTERNAL_REQUESTS: Inbox,
  REPORTS: FileText,
  DOCUMENTS: Folder,
  FINANCE_BUDGETS: Wallet,
  SUPPLIERS_PURCHASES: PackageCheck,
  WORKFLOWS: Workflow,
  AUDIT_LOGS: History,
  SETTINGS: Settings,
  AI_ASSISTANT: Bot,
  PATIENTS: HeartPulse,
  APPOINTMENTS: CalendarCheck,
  CONSULTATIONS: Stethoscope,
  MEDICAL_RECORDS: FileHeart,
  CARE_TEAM: UsersRound,
  LABORATORY: Microscope,
  INTERNAL_PHARMACY: Pill,
  MEDICAL_BILLING: Receipt,
  MEDICINES_PRODUCTS: Pill,
  BATCH_EXPIRY: Hourglass,
  STOCK_INVENTORY: Boxes,
  STOCK_RECEIPTS: PackageCheck,
  SALES_DISPENSATION: Receipt,
  PRESCRIPTIONS: ClipboardList,
  SUPPLIERS_ORDERS: ShoppingCart,
  CASH_INVOICES_PAYMENTS: Wallet,
  PHARMACY_REPORTS: BarChart3,
  PHARMACY_SETTINGS: Settings,
};

export function resolveEnterpriseModuleIcon({
  icon,
  code,
  category,
}: {
  icon?: string | null;
  code: string;
  category?: string | null;
}): LucideIcon {
  const normalizedIcon = icon?.trim().toLowerCase();
  if (normalizedIcon && enterpriseModuleIcons[normalizedIcon]) {
    return enterpriseModuleIcons[normalizedIcon];
  }
  return iconByModuleCode[code] || (category === "CORE" ? Layers3 : BriefcaseBusiness);
}
