-- DTSC ERP consolidation iteration 02: customer HR core.
-- These tables are separate from internal DTSC Hrcfo* tables.

CREATE TABLE "EnterpriseEmployee" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "employeeNumber" TEXT NOT NULL,
  "organizationMemberId" TEXT,
  "businessPartyId" TEXT,
  "firstName" TEXT NOT NULL,
  "lastName" TEXT NOT NULL,
  "displayName" TEXT NOT NULL,
  "workEmail" TEXT,
  "workPhone" TEXT,
  "positionId" TEXT,
  "positionCode" TEXT,
  "departmentId" TEXT,
  "managerEmployeeId" TEXT,
  "siteId" TEXT,
  "hireDate" TIMESTAMP(3) NOT NULL,
  "terminationDate" TIMESTAMP(3),
  "employmentStatus" TEXT NOT NULL DEFAULT 'ACTIVE',
  "employmentType" TEXT,
  "baseCompensation" DECIMAL(18,2),
  "compensationCurrency" TEXT,
  "professionalInfoJson" JSONB,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseEmployee_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseEmploymentContract" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "contractType" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "versionNumber" INTEGER NOT NULL DEFAULT 1,
  "supersedesContractId" TEXT,
  "startDate" TIMESTAMP(3) NOT NULL,
  "endDate" TIMESTAMP(3),
  "probationEndDate" TIMESTAMP(3),
  "jobTitle" TEXT,
  "departmentId" TEXT,
  "siteId" TEXT,
  "baseCompensation" DECIMAL(18,2) NOT NULL,
  "compensationCurrency" TEXT NOT NULL,
  "payFrequency" TEXT NOT NULL DEFAULT 'MONTHLY',
  "standardHoursPerWeek" DECIMAL(8,2),
  "terms" TEXT,
  "approvedAt" TIMESTAMP(3),
  "activatedAt" TIMESTAMP(3),
  "suspendedAt" TIMESTAMP(3),
  "endedAt" TIMESTAMP(3),
  "endReason" TEXT,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseEmploymentContract_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseEmployeeAssignment" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "assignmentType" TEXT NOT NULL DEFAULT 'PRIMARY',
  "positionId" TEXT,
  "positionCode" TEXT,
  "departmentId" TEXT,
  "siteId" TEXT,
  "managerEmployeeId" TEXT,
  "startsAt" TIMESTAMP(3) NOT NULL,
  "endsAt" TIMESTAMP(3),
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "createdByUserId" TEXT NOT NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseEmployeeAssignment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseWorkSchedule" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "scheduleType" TEXT NOT NULL DEFAULT 'WEEKLY',
  "dayOfWeek" INTEGER,
  "scheduleDate" TIMESTAMP(3),
  "startMinute" INTEGER NOT NULL,
  "endMinute" INTEGER NOT NULL,
  "breakMinutes" INTEGER NOT NULL DEFAULT 0,
  "timezone" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "effectiveFrom" TIMESTAMP(3) NOT NULL,
  "effectiveUntil" TIMESTAMP(3),
  "createdByUserId" TEXT NOT NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseWorkSchedule_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseAttendance" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "attendanceDate" TIMESTAMP(3) NOT NULL,
  "observedStartAt" TIMESTAMP(3),
  "observedEndAt" TIMESTAMP(3),
  "status" TEXT NOT NULL DEFAULT 'PRESENT',
  "source" TEXT NOT NULL DEFAULT 'MANUAL',
  "siteId" TEXT,
  "notes" TEXT,
  "recordedByUserId" TEXT NOT NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseAttendance_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseLeaveRequest" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "leaveType" TEXT NOT NULL,
  "startDate" TIMESTAMP(3) NOT NULL,
  "endDate" TIMESTAMP(3) NOT NULL,
  "partialDay" BOOLEAN NOT NULL DEFAULT false,
  "startMinute" INTEGER,
  "endMinute" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "reason" TEXT,
  "requestedByUserId" TEXT NOT NULL,
  "approverUserId" TEXT,
  "submittedAt" TIMESTAMP(3),
  "decidedAt" TIMESTAMP(3),
  "decisionComment" TEXT,
  "cancelledAt" TIMESTAMP(3),
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseLeaveRequest_pkey" PRIMARY KEY ("id")
);
