import { NextResponse } from "next/server";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { authorizeFinanceRequest, financeErrorResponse, financeListParams } from "@/lib/enterprise/accounting/http";
import { creditNoteCreateSchema } from "@/lib/enterprise/accounting/schemas";
import { createSupplierCreditNote } from "@/lib/enterprise/accounting/supplier-credit-notes-service";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ organizationId: string }> };
export async function GET(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_PAYABLES", "view"); if (!auth.ok) return auth.response; const { page, pageSize, status } = financeListParams(req); const where = { organizationId, ...(status ? { status } : {}) }; const [items, total] = await Promise.all([prisma.enterpriseSupplierCreditNote.findMany({ where, orderBy: [{ creditDate: "desc" }, { createdAt: "desc" }], skip: (page - 1) * pageSize, take: pageSize, include: { supplierInvoice: true } }), prisma.enterpriseSupplierCreditNote.count({ where })]); await writeApiLog({ request: req, statusCode: 200, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "supplier-credit-notes" } }); return NextResponse.json({ items, pagination: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) } }); }
export async function POST(req: Request, { params }: Params) { const startedAt = Date.now(); const { organizationId } = await params; const auth = await authorizeFinanceRequest(req, organizationId, "FINANCE_PAYABLES", "create", { mutation: true }); if (!auth.ok) return auth.response; const parsed = creditNoteCreateSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message }, { status: 400 }); try { const creditNote = await createSupplierCreditNote(organizationId, auth.session.userId, parsed.data); await writeAuditLog({ userId: auth.session.userId, action: "ENTERPRISE_SUPPLIER_CREDIT_NOTE_CREATED", entity: "EnterpriseSupplierCreditNote", entityId: creditNote.id, request: req, metadata: { organizationId, number: creditNote.number, total: creditNote.grandTotal.toFixed(), currency: creditNote.currencyCode } }); await writeApiLog({ request: req, statusCode: 201, userId: auth.session.userId, startedAt, metadata: { organizationId, domain: "supplier-credit-notes" } }); return NextResponse.json({ ok: true, creditNote }, { status: 201 }); } catch (error) { return financeErrorResponse(error, "SUPPLIER_CREDIT_NOTE_CREATE_FAILED"); } }
