-- DTSC ERP consolidation iteration 02: CRM, quotes and contracts.

CREATE TABLE "EnterpriseLead" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "partyType" TEXT NOT NULL DEFAULT 'PERSON',
  "legalName" TEXT NOT NULL,
  "displayName" TEXT,
  "normalizedName" TEXT NOT NULL,
  "email" TEXT,
  "phone" TEXT,
  "companyName" TEXT,
  "source" TEXT,
  "status" TEXT NOT NULL DEFAULT 'NEW',
  "ownerUserId" TEXT,
  "departmentId" TEXT,
  "expectedValue" DECIMAL(18,2),
  "currency" TEXT,
  "notes" TEXT,
  "convertedPartyId" TEXT,
  "convertedOpportunityId" TEXT,
  "lostReason" TEXT,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "contactedAt" TIMESTAMP(3),
  "qualifiedAt" TIMESTAMP(3),
  "convertedAt" TIMESTAMP(3),
  "lostAt" TIMESTAMP(3),
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseLead_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseOpportunity" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "leadId" TEXT,
  "businessPartyId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'OPEN',
  "ownerUserId" TEXT,
  "departmentId" TEXT,
  "estimatedValue" DECIMAL(18,2),
  "currency" TEXT,
  "probabilityPercent" INTEGER NOT NULL DEFAULT 0,
  "expectedCloseDate" TIMESTAMP(3),
  "source" TEXT,
  "wonAt" TIMESTAMP(3),
  "lostAt" TIMESTAMP(3),
  "lostReason" TEXT,
  "closedAt" TIMESTAMP(3),
  "notes" TEXT,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseOpportunity_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseQuote" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "opportunityId" TEXT,
  "businessPartyId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "currency" TEXT NOT NULL,
  "subtotalAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "discountAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "taxAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "totalAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "validUntil" TIMESTAMP(3),
  "ownerUserId" TEXT,
  "terms" TEXT,
  "sentAt" TIMESTAMP(3),
  "acceptedAt" TIMESTAMP(3),
  "rejectedAt" TIMESTAMP(3),
  "expiredAt" TIMESTAMP(3),
  "cancelledAt" TIMESTAMP(3),
  "convertedAt" TIMESTAMP(3),
  "convertedOrderId" TEXT,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseQuote_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseQuoteItem" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "quoteId" TEXT NOT NULL,
  "catalogItemId" TEXT,
  "description" TEXT NOT NULL,
  "quantity" DECIMAL(18,3) NOT NULL,
  "unitOfMeasureId" TEXT,
  "unitPrice" DECIMAL(18,2) NOT NULL,
  "discountRate" DECIMAL(8,4) NOT NULL DEFAULT 0,
  "discountAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "taxRate" DECIMAL(8,4) NOT NULL DEFAULT 0,
  "taxAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
  "lineSubtotal" DECIMAL(18,2) NOT NULL,
  "lineTotal" DECIMAL(18,2) NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EnterpriseQuoteItem_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "EnterpriseContract" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  "businessPartyId" TEXT NOT NULL,
  "opportunityId" TEXT,
  "quoteId" TEXT,
  "projectId" TEXT,
  "contractType" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "ownerUserId" TEXT,
  "departmentId" TEXT,
  "startDate" TIMESTAMP(3),
  "endDate" TIMESTAMP(3),
  "indicativeAmount" DECIMAL(18,2),
  "currency" TEXT,
  "renewalMode" TEXT DEFAULT 'NONE',
  "renewalNoticeDays" INTEGER,
  "terms" TEXT,
  "approvedAt" TIMESTAMP(3),
  "activatedAt" TIMESTAMP(3),
  "suspendedAt" TIMESTAMP(3),
  "terminatedAt" TIMESTAMP(3),
  "terminationReason" TEXT,
  "createdByUserId" TEXT NOT NULL,
  "updatedByUserId" TEXT,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "archivedAt" TIMESTAMP(3),
  CONSTRAINT "EnterpriseContract_pkey" PRIMARY KEY ("id")
);
