import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeAuditLog } from "@/lib/audit";
import { getHealthStaffAccess } from "@/lib/health-staff-access";
import { healthStaffActionSchema, healthStaffUpdateSchema } from "@/lib/health-staff-validators";
import { transitionHealthStaffAssignment, updateHealthStaffAssignment } from "@/lib/health-staff";
import { prisma } from "@/lib/prisma";
import { getRateLimitKey, rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";
type Params={params:Promise<{organizationId:string;staffId:string}>};

export async function GET(req:Request,{params}:Params){void req;const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const {organizationId,staffId}=await params,access=await getHealthStaffAccess({session,organizationId,action:"read"});if(!access)return NextResponse.json({error:"Forbidden"},{status:403});const assignment=await prisma.healthStaffAssignment.findFirst({where:{id:staffId,organizationId},include:{organizationMember:{include:{user:{select:{id:true,name:true,email:true,phone:true}}}},enterprisePosition:true,enterpriseDepartment:true,healthSpecialty:true,supervisorStaff:{include:{user:{select:{name:true}}}},createdBy:{select:{name:true}},updatedBy:{select:{name:true}},events:{orderBy:{createdAt:"desc"},take:50,include:{actor:{select:{name:true}}}}}});if(!assignment)return NextResponse.json({error:"Not found"},{status:404});const [appointments,consultations]=access.canViewActivity?await Promise.all([prisma.healthAppointment.findMany({where:{organizationId,professionalId:assignment.userId},orderBy:{appointmentDate:"desc"},take:20,select:{id:true,appointmentNumber:true,appointmentDate:true,status:true,reason:true}}),prisma.healthConsultation.findMany({where:{organizationId,professionalId:assignment.userId},orderBy:{consultationDate:"desc"},take:20,select:{id:true,consultationNumber:true,consultationDate:true,status:true,chiefComplaint:true}})]) : [[],[]];return NextResponse.json({assignment:{...assignment,permissionsJson:access.canViewPermissions?assignment.permissionsJson:[]},appointments,consultations})}
export async function PATCH(req:Request,{params}:Params){if(!isSameOriginRequest(req))return NextResponse.json({error:"Forbidden"},{status:403});const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const limited=await rateLimit(getRateLimitKey(req,`health-staff-update:${session.userId}`),120,3600000);if(!limited.ok)return NextResponse.json({error:"Too many requests"},{status:429});const {organizationId,staffId}=await params,access=await getHealthStaffAccess({session,organizationId,action:"write"});if(!access)return NextResponse.json({error:"Forbidden"},{status:403});const payload=await req.json().catch(()=>null),actionParsed=healthStaffActionSchema.safeParse(payload);try{if(actionParsed.success){if(actionParsed.data.action==="suspend"&&!access.canSuspend||actionParsed.data.action==="archive"&&!access.canArchive||actionParsed.data.action==="reactivate"&&!access.canUpdate)return NextResponse.json({error:"Forbidden"},{status:403});const assignment=await transitionHealthStaffAssignment(organizationId,staffId,session.userId,actionParsed.data.action,actionParsed.data.reason);await writeAuditLog({userId:session.userId,action:`HEALTH_STAFF_${actionParsed.data.action.toUpperCase()}`,entity:"HealthStaffAssignment",entityId:staffId,request:req,metadata:{organizationId,reason:actionParsed.data.reason}});return NextResponse.json({ok:true,assignment})}if(!access.canUpdate)return NextResponse.json({error:"Forbidden"},{status:403});const parsed=healthStaffUpdateSchema.safeParse(payload);if(!parsed.success)return NextResponse.json({error:"Invalid payload",message:"Les modifications de l’affectation sont invalides."},{status:400});if(parsed.data.availabilityStatus!==undefined&&!access.canManageAvailability)return NextResponse.json({error:"Forbidden",message:"Vous n’avez pas la permission de modifier la disponibilité."},{status:403});const assignment=await updateHealthStaffAssignment(organizationId,staffId,session.userId,parsed.data,access.canManagePermissions);if(!assignment)return NextResponse.json({error:"Not found"},{status:404});await writeAuditLog({userId:session.userId,action:parsed.data.permissions?"HEALTH_STAFF_PERMISSIONS_UPDATED":"HEALTH_STAFF_UPDATED",entity:"HealthStaffAssignment",entityId:staffId,request:req,metadata:{organizationId}});return NextResponse.json({ok:true,assignment})}catch(error){const code=error instanceof Error?error.message:"UPDATE_FAILED";const message=code==="PERMISSIONS_FORBIDDEN"?"Vous n’avez pas la permission de modifier les permissions Santé.":code==="MEMBER_IMMUTABLE"?"Le membre lié à une affectation ne peut pas être remplacé.":code==="INVALID_SUPERVISOR"?"Un professionnel ne peut pas être son propre responsable.":"Modification impossible.";return NextResponse.json({error:code,message},{status:409})}}
