import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { canAccessPharmacySettings } from "@/lib/pharmacy-setting-access";
import { criticalPharmacySettingKeys } from "@/lib/pharmacy-settings-config";
import { pharmacySettingsUpdateSchema } from "@/lib/pharmacy-settings-validators";
import { getPharmacySettingsDataset, updatePharmacySettingsSection } from "@/lib/pharmacy-settings";
import { getRateLimitKey, rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";

type Params = { params: Promise<{ organizationId: string }> };
export async function GET(request: Request, { params }: Params) { const startedAt = Date.now(); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { organizationId } = await params; if (!(await canAccessPharmacySettings(session.userId, organizationId, "view"))) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const history = await canAccessPharmacySettings(session.userId, organizationId, "view_history"); const dataset = await getPharmacySettingsDataset(organizationId, session.userId, history); await writeApiLog({ request, statusCode: 200, userId: session.userId, startedAt }); return NextResponse.json({ ...dataset, permissions: { canUpdate: await canAccessPharmacySettings(session.userId, organizationId, "update"), canUpdateCritical: await canAccessPharmacySettings(session.userId, organizationId, "update_critical"), canReset: await canAccessPharmacySettings(session.userId, organizationId, "reset"), canViewHistory: history } }); }
export async function PATCH(request: Request, { params }: Params) { const startedAt = Date.now(); if (!isSameOriginRequest(request)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const limited = await rateLimit(getRateLimitKey(request, `pharmacy-settings:${session.userId}`), 50, 3600000); if (!limited.ok) return NextResponse.json({ error: "Too many requests" }, { status: 429 }); const { organizationId } = await params; const parsed = pharmacySettingsUpdateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: "Paramètres invalides." }, { status: 400 }); const critical = Object.keys(parsed.data.values).some((key) => criticalPharmacySettingKeys.has(key)); if (!(await canAccessPharmacySettings(session.userId, organizationId, critical ? "update_critical" : "update"))) return NextResponse.json({ error: "Forbidden", message: "Permission insuffisante pour modifier ces paramètres." }, { status: 403 }); try { await updatePharmacySettingsSection(organizationId, parsed.data.section, parsed.data.values, session.userId, parsed.data.reason, request.headers.get("x-forwarded-for") || undefined, request.headers.get("user-agent") || undefined); await writeAuditLog({ userId: session.userId, action: "PHARMACY_SETTINGS_UPDATED", entity: "PharmacySetting", request, metadata: { organizationId, section: parsed.data.section, keys: Object.keys(parsed.data.values) } }); await writeApiLog({ request, statusCode: 200, userId: session.userId, startedAt }); return NextResponse.json({ ok: true }); } catch (error) { const code = error instanceof Error ? error.message : "UNKNOWN"; return NextResponse.json({ error: code, message: code === "REASON_REQUIRED" ? "Un motif est obligatoire pour ce changement critique." : "Mise à jour des paramètres impossible." }, { status: 400 }); } }
