ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "callSoundsEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "callNotificationsEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "floatingCallAlertsEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "participantEventAlertsEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "callAlertSoundEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "incomingCallBannerEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "connectionIssueSoundsEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "startMutedByDefault" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "startCameraOffByDefault" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "callSoundVolume" INTEGER NOT NULL DEFAULT 45,
  ADD COLUMN IF NOT EXISTS "callAlertDisplayDuration" INTEGER NOT NULL DEFAULT 6000,
  ADD COLUMN IF NOT EXISTS "preferredAudioInputId" TEXT,
  ADD COLUMN IF NOT EXISTS "preferredVideoInputId" TEXT,
  ADD COLUMN IF NOT EXISTS "preferredAudioOutputId" TEXT;

ALTER TABLE "CollaborationGroupCall"
  ADD COLUMN IF NOT EXISTS "durationSeconds" INTEGER;
