import type { ProfessionalErpLocale } from "@/components/enterprise/professional/professional-erp-i18n";

const copy = {
  fr: {
    savedParty: "La fiche métier a été enregistrée.",
    savedPartyInvitationPending: "La fiche métier est enregistrée, mais l’invitation DTSC n’a pas pu être envoyée. Vous pouvez réessayer sans recréer la fiche.",
    savedCatalogItem: "Le produit ou service a été enregistré.",
    updatedCatalogItem: "Le produit ou service a été mis à jour.",
    savedCategory: "La catégorie a été enregistrée.",
    savedUnit: "L’unité de mesure a été enregistrée.",
    savedLead: "Le prospect a été enregistré.",
    savedOpportunity: "L’opportunité a été enregistrée.",
    leadLostReason: "Expliquez pourquoi ce prospect est perdu.",
    leadLostTitle: "Marquer le prospect comme perdu",
    pipelinePageNotice: "Le pipeline affiche la page courante. Utilisez les pages suivantes pour parcourir toutes les opportunités.",
    existingPartyCanonical: "Les coordonnées viennent de la fiche métier sélectionnée et ne sont pas ressaisies ici.",
    savedQuote: "Le devis a été enregistré en brouillon.",
    quoteUpdated: "Le devis a été mis à jour.",
    quoteConverted: "Le devis a été converti en commande.",
    fulfillmentSaved: "La livraison a été enregistrée.",
    salesSelectorsUnavailable: "Les clients, dépôts ou devises de cette entreprise sont indisponibles. Actualisez avant de continuer.",
    catalogUnavailable: "Le catalogue actif est indisponible. Réessayez avant d’ajouter une ligne.",
    catalogSearch: "Rechercher un produit ou service du catalogue…",
    catalogSearchHelp: "La recherche interroge le catalogue réel de l’entreprise par pages de 50 éléments.",
    selectCurrency: "Sélectionnez une devise autorisée.",
    selectParty: "Sélectionnez un client ou prospect.",
    quoteTitleRequired: "Renseignez le titre du devis.",
    quoteLineRequired: "Chaque ligne doit avoir une description, une quantité positive et un prix valide.",
    quoteCurrencyMismatch: "La devise de cet article diffère de celle du devis. Choisissez une devise cohérente ou un autre article.",
    confirmQuoteAction: "Confirmer l’action sur ce devis",
    confirmQuoteActionHelp: "Cette transition modifie l’état commercial du devis et sera historisée.",
    deliveryQuantityRequired: "Renseignez au moins une quantité réellement livrée.",
    deliveryQuantityTooHigh: "Une quantité livrée dépasse le reliquat de la commande.",
    deliveryRetrySafe: "La même référence d’idempotence est conservée jusqu’au succès afin d’éviter une double livraison après une erreur réseau.",
    savedContract: "Le contrat a été enregistré.",
    updatedContract: "Le contrat a été mis à jour.",
    contractActionDone: "L’action contractuelle a été enregistrée.",
    contractTerminationInfo: "Motif de résiliation",
    confirmArchiveTitle: "Archiver le contrat",
    confirmArchiveHelp: "L’archivage conserve l’historique et retire le contrat des parcours actifs.",
    actionErrorHelp: "Corrigez les informations dans cette fenêtre puis réessayez.",
    noTaxCode: "Aucun code taxe",
    taxConfigurationHelp: "Seuls les codes taxe actifs de cette entreprise sont proposés.",
    currencyConfigurationHelp: "Les devises configurées dans Finance sont proposées en priorité. À défaut, la liste monétaire contrôlée DTSC est utilisée.",
    unitCategoryHelp: "Choisissez une famille déjà utilisée dans cette entreprise ou créez-en une nouvelle. Cette classification reste propre à votre organisation.",
    selectUnitCategory: "Famille d’unité",
    newUnitCategoryOption: "Créer une nouvelle famille…",
    newUnitCategoryLabel: "Nouvelle famille d’unité",
    newUnitCategoryHelp: "Saisissez une famille métier courte et stable. Elle pourra ensuite être réutilisée pour les prochaines unités de cette entreprise.",
    unitCategoryRequired: "Sélectionnez une famille existante ou renseignez une nouvelle famille d’unité.",
    busy: "Traitement en cours…",
    closeDetailBeforeEdit: "Le détail est fermé avant l’ouverture du formulaire d’édition afin d’éviter les fenêtres superposées.",
  },
  en: {
    savedParty: "The business record was saved.",
    savedPartyInvitationPending: "The business record is saved, but the DTSC invitation could not be sent. You can retry without creating the record again.",
    savedCatalogItem: "The product or service was saved.",
    updatedCatalogItem: "The product or service was updated.",
    savedCategory: "The category was saved.",
    savedUnit: "The unit of measure was saved.",
    savedLead: "The lead was saved.",
    savedOpportunity: "The opportunity was saved.",
    leadLostReason: "Explain why this lead was lost.",
    leadLostTitle: "Mark lead as lost",
    pipelinePageNotice: "The pipeline shows the current page. Use the next pages to browse all opportunities.",
    existingPartyCanonical: "Contact details come from the selected business record and are not re-entered here.",
    savedQuote: "The quote was saved as a draft.",
    quoteUpdated: "The quote was updated.",
    quoteConverted: "The quote was converted into an order.",
    fulfillmentSaved: "The fulfillment was saved.",
    salesSelectorsUnavailable: "Customers, warehouses or currencies for this organization are unavailable. Refresh before continuing.",
    catalogUnavailable: "The active catalog is unavailable. Try again before adding a line.",
    catalogSearch: "Search the product and service catalog…",
    catalogSearchHelp: "Search queries the organization’s real catalog in pages of 50 items.",
    selectCurrency: "Select an allowed currency.",
    selectParty: "Select a customer or prospect.",
    quoteTitleRequired: "Enter a quote title.",
    quoteLineRequired: "Each line needs a description, a positive quantity and a valid price.",
    quoteCurrencyMismatch: "This item uses a different currency from the quote. Select a matching currency or another item.",
    confirmQuoteAction: "Confirm quote action",
    confirmQuoteActionHelp: "This transition changes the quote’s commercial status and will be audited.",
    deliveryQuantityRequired: "Enter at least one quantity actually fulfilled.",
    deliveryQuantityTooHigh: "A fulfilled quantity exceeds the remaining quantity on the order.",
    deliveryRetrySafe: "The same idempotency reference is kept until success to prevent duplicate fulfillment after a network error.",
    savedContract: "The contract was saved.",
    updatedContract: "The contract was updated.",
    contractActionDone: "The contract action was saved.",
    contractTerminationInfo: "Termination reason",
    confirmArchiveTitle: "Archive contract",
    confirmArchiveHelp: "Archiving preserves history and removes the contract from active workflows.",
    actionErrorHelp: "Correct the information in this window and try again.",
    noTaxCode: "No tax code",
    taxConfigurationHelp: "Only active tax codes from this organization are offered.",
    currencyConfigurationHelp: "Currencies configured in Finance are offered first. Otherwise DTSC’s controlled currency list is used.",
    unitCategoryHelp: "Choose a family already used by this organization or create a new one. This classification remains organization-specific.",
    selectUnitCategory: "Unit family",
    newUnitCategoryOption: "Create a new family…",
    newUnitCategoryLabel: "New unit family",
    newUnitCategoryHelp: "Enter a short, stable business family. It can then be reused for future units in this organization.",
    unitCategoryRequired: "Select an existing family or enter a new unit family.",
    busy: "Processing…",
    closeDetailBeforeEdit: "The detail view is closed before the editor opens to avoid stacked dialogs.",
  },
} as const;

export function commercialHotfixCopy(locale: ProfessionalErpLocale) {
  return copy[locale];
}
