import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { writeApiLog, writeAuditLog } from "@/lib/audit";
import { enterprisePurchaseVisibilityWhere, getEnterpriseProcurementAccess } from "@/lib/enterprise/procurement/access";
import { createEnterprisePurchase } from "@/lib/enterprise/procurement/purchase-service";
import { enterprisePurchaseCreateSchema } from "@/lib/enterprise/procurement/validators";
import { prisma } from "@/lib/prisma";
import { getRateLimitKey, rateLimit } from "@/lib/rate-limit";
import { isSameOriginRequest } from "@/lib/request-security";

type Params = { params: Promise<{ organizationId: string }> };

export async function GET(req: Request, { params }: Params) {
  const startedAt = Date.now(); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { organizationId } = await params; const access = await getEnterpriseProcurementAccess({ session, organizationId, moduleCode: "SUPPLIERS_PURCHASES", action: "read" }); if (!access) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const url = new URL(req.url); const page = Math.max(1, Number(url.searchParams.get("page") || 1) || 1); const pageSize = Math.min(100, Math.max(5, Number(url.searchParams.get("pageSize") || 20) || 20));
  const search = url.searchParams.get("search")?.trim() || ""; const status = url.searchParams.get("status")?.trim() || ""; const supplier = url.searchParams.get("supplier")?.trim() || ""; const department = url.searchParams.get("department")?.trim() || ""; const requester = url.searchParams.get("requester")?.trim() || ""; const buyer = url.searchParams.get("buyer")?.trim() || ""; const budgetLineId = url.searchParams.get("budgetLineId")?.trim() || ""; const from = url.searchParams.get("from")?.trim() || ""; const to = url.searchParams.get("to")?.trim() || ""; const expectedBefore = url.searchParams.get("expectedBefore")?.trim() || "";
  const base = enterprisePurchaseVisibilityWhere({ organizationId, userId: session.userId, canSeeAll: access.canSeeAll }); const filters: Prisma.EnterprisePurchaseWhereInput[] = [];
  if (search) filters.push({ OR: [{ reference: { contains: search, mode: "insensitive" } }, { title: { contains: search, mode: "insensitive" } }, { description: { contains: search, mode: "insensitive" } }] }); if (status) filters.push({ status }); if (supplier) filters.push({ supplierId: supplier }); if (department) filters.push({ departmentId: department }); if (requester) filters.push({ requestedByUserId: requester }); if (buyer) filters.push({ buyerUserId: buyer }); if (budgetLineId) filters.push({ budgetLineId });
  if (from || to) { const createdAt: { gte?: Date; lte?: Date } = {}; if (from) createdAt.gte = new Date(from); if (to) createdAt.lte = new Date(to); filters.push({ createdAt }); } if (expectedBefore) filters.push({ expectedAt: { lte: new Date(expectedBefore) } });
  const where: Prisma.EnterprisePurchaseWhereInput = { AND: [base, ...filters] }; const [items, total, drafts, pending, ordered, receiving, received] = await Promise.all([prisma.enterprisePurchase.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize, include: { supplier: { select: { id: true, legalName: true, displayName: true, status: true } }, budgetLine: { select: { id: true, name: true, budget: { select: { id: true, reference: true, title: true, currency: true, status: true } } } }, _count: { select: { items: true, receipts: true } } } }), prisma.enterprisePurchase.count({ where }), prisma.enterprisePurchase.count({ where: { AND: [base, { status: "DRAFT" }] } }), prisma.enterprisePurchase.count({ where: { AND: [base, { status: "PENDING_APPROVAL" }] } }), prisma.enterprisePurchase.count({ where: { AND: [base, { status: "ORDERED" }] } }), prisma.enterprisePurchase.count({ where: { AND: [base, { status: "PARTIALLY_RECEIVED" }] } }), prisma.enterprisePurchase.count({ where: { AND: [base, { status: "RECEIVED", receivedAt: { gte: new Date(Date.now() - 30 * 86400000) } }] } })]);
  await writeApiLog({ request: req, statusCode: 200, userId: session.userId, startedAt, metadata: { organizationId, domain: "purchases", page } }); return NextResponse.json({ items, pagination: { page, pageSize, total, pageCount: Math.max(1, Math.ceil(total / pageSize)) }, metrics: { drafts, pending, ordered, receiving, received }, canManage: access.canManage, currentUserId: session.userId });
}

export async function POST(req: Request, { params }: Params) {
  const startedAt = Date.now(); if (!isSameOriginRequest(req)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const session = await getSession(); if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const limited = await rateLimit(getRateLimitKey(req, `enterprise-purchase-create:${session.userId}`), 80, 60 * 60 * 1000); if (!limited.ok) return NextResponse.json({ error: "Too many requests" }, { status: 429 }); const { organizationId } = await params; const access = await getEnterpriseProcurementAccess({ session, organizationId, moduleCode: "SUPPLIERS_PURCHASES", action: "write" }); if (!access) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = enterprisePurchaseCreateSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid payload", message: parsed.error.issues[0]?.message || "Achat invalide." }, { status: 400 });
  try { const purchase = await createEnterprisePurchase(organizationId, session.userId, parsed.data); await writeAuditLog({ userId: session.userId, action: "ENTERPRISE_PURCHASE_CREATED", entity: "EnterprisePurchase", entityId: purchase.id, request: req, metadata: { organizationId, reference: purchase.reference, totalAmount: purchase.totalAmount.toString(), currency: purchase.currency, budgetLineId: purchase.budgetLineId } }); await writeApiLog({ request: req, statusCode: 201, userId: session.userId, startedAt, metadata: { organizationId, domain: "purchases" } }); return NextResponse.json({ ok: true, purchase }, { status: 201 }); }
  catch (error) { const duplicate = error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002"; return NextResponse.json({ error: duplicate ? "PURCHASE_DUPLICATE" : "PURCHASE_CREATE_FAILED", message: duplicate ? "La référence d’achat existe déjà." : error instanceof Error ? error.message : "Création de l’achat impossible." }, { status: duplicate ? 409 : 400 }); }
}
