export const MANUFACTURING_SECTOR_CODE = "MANUFACTURING" as const;

export const MANUFACTURING_MODULE_CODES = [
  "MANUFACTURING_OVERVIEW",
  "BILL_OF_MATERIALS",
  "PRODUCTION_ORDERS",
  "PRODUCTION_ROUTINGS",
  "WORK_CENTERS",
  "MATERIAL_REQUIREMENTS",
  "PRODUCTION_EXECUTION",
  "QUALITY_CONTROL",
  "SCRAP_WASTE",
  "PRODUCTION_REPORTS",
] as const;

export type ManufacturingModuleCode = (typeof MANUFACTURING_MODULE_CODES)[number];

export const MANUFACTURING_WORK_CENTER_STATUSES = ["ACTIVE", "INACTIVE", "MAINTENANCE"] as const;
export const MANUFACTURING_DEFINITION_STATUSES = ["DRAFT", "ACTIVE", "RETIRED"] as const;
export const PRODUCTION_ORDER_STATUSES = ["DRAFT", "SUBMITTED", "RELEASED", "IN_PROGRESS", "COMPLETED", "REJECTED", "CANCELLED"] as const;
export const PRODUCTION_ORDER_PRIORITIES = ["LOW", "NORMAL", "HIGH", "CRITICAL"] as const;
export const MATERIAL_REQUIREMENT_STATUSES = ["PLANNED", "AVAILABLE", "SHORTAGE", "PARTIALLY_CONSUMED", "CONSUMED"] as const;
export const PRODUCTION_EXECUTION_TYPES = ["OPERATION_START", "OPERATION_COMPLETE", "LABOR", "MATERIAL_CONSUMPTION", "OUTPUT_RECEIPT"] as const;
export const PRODUCTION_QUALITY_RESULTS = ["PASS", "FAIL", "HOLD"] as const;
export const BOM_ISSUE_METHODS = ["MANUAL", "BACKFLUSH"] as const;

export const MANUFACTURING_ORDER_TRANSITIONS: Record<string, readonly string[]> = {
  DRAFT: ["SUBMITTED", "CANCELLED"],
  SUBMITTED: ["RELEASED", "REJECTED", "CANCELLED"],
  RELEASED: ["IN_PROGRESS", "CANCELLED"],
  IN_PROGRESS: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  REJECTED: [],
  CANCELLED: [],
};
